### ISSUE TITLE
Bug/ High  CPU usage when using cloudwatch acquistion

### ISSUE THREAD

**Issue by sbs2001** [crowdsecurity/crowdsec#1002]
To reproduce  just use the cloudwatch acq to read logs. After crowdsec starts to read multiple cloudwatch streams, the CPU usage goe up.

**Comment by prohand** [comment]
Hello,

Same problem with crowdsec 1.2.2
Do you have a solution ?

Thank you

**Comment by buixor** [comment]
Hello,

it was related to excessive short polling from cloudwatch or reading too many streams at once.
For reading AWS logs with decent throughput, [Kinesis](https://doc.crowdsec.net/docs/next/data_sources/kinesis) source is recommended.

**Comment by prohand** [comment]
Hello,

So what is the solution when reading logs locally?

Thank you
