### ISSUE TITLE
Improvement/plugins/notification: Add email notification plugin

### ISSUE THREAD

**Issue by pdf** [crowdsecurity/crowdsec#1003]
**Is your feature request related to a problem? Please describe.**
The documentation uses writing an email notification plugin as an example. As a user, I don't want to write, build, maintain, and deploy this plugin.

**Describe the solution you'd like**
Publish an email notification plugin, rather than leaving it as an exercise for the user to copy-pasta. The code already exists in the documentation, though it probably needs an option to send unauthenticated email (or just default to `AuthNone` if username/password are empty). Probably should also include an option to set subject from config.

**Comment by sbs2001** [comment]
@pdf  Thanks for the feature request. Expect the plugin in the next release.
