### ISSUE TITLE
Improvement/cscli decisions import

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1027]
For users that wish to import decisions (blocklists) from 3rd party sources, a `cscli` helper would be useful to save people the hassle of interacting directly with the API.

How it would look like ?

`cscli decisions import file.csv`

Each line would be equivalent to one individual decision, and we would allow to share flags of `cscli decisions add` to overload/fill the missing fields

**Comment by AlteredCoder** [comment]
This has been done in https://github.com/crowdsecurity/crowdsec/pull/1038
