### ISSUE TITLE
Improvement/crowdsec: switch to pgx

### ISSUE THREAD

**Issue by umglurf** [crowdsecurity/crowdsec#1042]
**Is your feature request related to a problem? Please describe.**
pq is no longer in active development and the project recommends to move to pgx. Many features are not available in pq, for instance support for [multi-host](https://paquier.xyz/postgresql-2/postgres-10-multi-host-connstr/), which can simplify failover solutions for postgresql.

**Describe the solution you'd like**
Use pgx instead of pq for postgresql connectivity.

**Describe alternatives you've considered** (Optional) 

**Example of what you imagine**
Able to use advanced connection parameters such as multi-host

**Additional context**
 The ent doc describes [how to use pgx](https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql)

**Comment by buixor** [comment]
solved, coming up in 1.3 :)
