### ISSUE TITLE
Bug/ Systemctl called by wizard in docker mode

### ISSUE THREAD

**Issue by sbs2001** [crowdsecurity/crowdsec#1043]
https://github.com/crowdsecurity/crowdsec/blob/7ca3625706c5e1a7934aa1dc640510f033800de7/wizard.sh#L463 is being ran when the wizard is called with `--docker-mode`. systemctl does not exist on docker. This is also caused during building the docker image. 

The image and build process continue and function properly even after this error.

**Comment by mmetc** [comment]
fixed in https://github.com/crowdsecurity/crowdsec/pull/1044

**Comment by sbs2001** [comment]
Fixed by https://github.com/crowdsecurity/crowdsec/pull/1044
