### ISSUE TITLE
Bug/ On RPM-based Linux distros, wizard.sh fails to get API key and register bouncer

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1047]
**Describe the bug**
On RPM-based Linux distros, wizard.sh fails to get API key for registering the firewall bouncer (I tried with the iptables bouncer). As a result, no bouncers are registered after installing the bouncer.

**To Reproduce**
Follow install instructions for CentOS 8 and install on CentOS 8 or AlmaLinux 8. Install both agent and bouncer simultaneously like this: 
sudo yum install crowdsec crowdsec-firewall-bouncer-iptables
Afterwards do 'cscli bouncers list'. No bouncers registered.

**Expected behavior**
I would expect firewall bouncer to be registered automatically. 

**Screenshots**
This is the install log with the error that I suspect triggers this:
Installing    : libnfnetlink-1.0.1-13.el8.x86_64                                  1/8 
 Running scriptlet: libnfnetlink-1.0.1-13.el8.x86_64                                  1/8 
 Installing    : libnetfilter_conntrack-1.0.6-5.el8.x86_64                              2/8 
 Running scriptlet: libnetfilter_conntrack-1.0.6-5.el8.x86_64                              2/8 
 Installing    : libnftnl-1.1.5-4.el8.x86_64                                     3/8 
 Running scriptlet: libnftnl-1.1.5-4.el8.x86_64                                     3/8 
 Running scriptlet: iptables-1.8.4-17.el8_4.1.x86_64                                  4/8 
 Installing    : iptables-1.8.4-17.el8_4.1.x86_64                                  4/8 
 Running scriptlet: iptables-1.8.4-17.el8_4.1.x86_64                                  4/8 
 Installing    : ipset-libs-7.1-1.el8.x86_64                                     5/8 
 Running scriptlet: ipset-libs-7.1-1.el8.x86_64                                     5/8 
 Installing    : ipset-7.1-1.el8.x86_64                                       6/8 
 Installing    : crowdsec-firewall-bouncer-iptables-0.0.16-1.el8.x86_64                       7/8 
 Running scriptlet: crowdsec-firewall-bouncer-iptables-0.0.16-1.el8.x86_64                       7/8 
/var/tmp/rpm-tmp.6ralBP: line 7: type: cscli: not found
no api key was generated, won't start service

 Running scriptlet: crowdsec-1.2.0-1.el8.x86_64                                     8/8 
 Installing    : crowdsec-1.2.0-1.el8.x86_64                                     8/8 
 Running scriptlet: crowdsec-1.2.0-1.el8.x86_64                                     8/8 
/bin/bash
Creating acquisition configuration
INFO[11/08/21:08:58:13] crowdsec_wizard: service 'sshd': /var/log/secure
INFO[11/08/21:08:58:13] crowdsec_wizard: service 'linux': /var/log/messages
time="08-11-2021 08:58:13 AM" level=warning msg="can't load CAPI credentials from '/etc/crowdsec/online_api_credentials.yaml' (missing field)"
time="08-11-2021 08:58:13 AM" level=info msg="push and pull to Central API disabled"
time="08-11-2021 08:58:14 AM" level=info msg="Successfully registered to Central API (CAPI)"
time="08-11-2021 08:58:14 AM" level=info msg="Central API credentials dumped to '/etc/crowdsec/online_api_credentials.yaml'"
time="08-11-2021 08:58:14 AM" level=warning msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
time="08-11-2021 08:58:15 AM" level=info msg="Machine '480da73215c141f48894bdb362e0ef6b3J8Y1fThN7zRijqo' successfully added to the local API"
time="08-11-2021 08:58:15 AM" level=info msg="API credentials dumped to '/etc/crowdsec/local_api_credentials.yaml'"
time="08-11-2021 08:58:15 AM" level=info msg="Wrote new 159206 bytes index to /etc/crowdsec/hub/.index.json"
INFO[11/08/21:08:58:15] crowdsec_wizard: Installing collection 'crowdsecurity/sshd'
INFO[11/08/21:08:58:16] crowdsec_wizard: Installing collection 'crowdsecurity/linux'

 Verifying    : ipset-7.1-1.el8.x86_64                                       1/8 
 Verifying    : ipset-libs-7.1-1.el8.x86_64                                     2/8 
 Verifying    : iptables-1.8.4-17.el8_4.1.x86_64                                  3/8 
 Verifying    : libnetfilter_conntrack-1.0.6-5.el8.x86_64                              4/8 
 Verifying    : libnfnetlink-1.0.1-13.el8.x86_64                                  5/8 
 Verifying    : libnftnl-1.1.5-4.el8.x86_64                                     6/8 
 Verifying    : crowdsec-1.2.0-1.el8.x86_64                                     7/8 
 Verifying    : crowdsec-firewall-bouncer-iptables-0.0.16-1.el8.x86_64                       8/8 

Installed:
 crowdsec-1.2.0-1.el8.x86_64            crowdsec-firewall-bouncer-iptables-0.0.16-1.el8.x86_64          
 ipset-7.1-1.el8.x86_64               ipset-libs-7.1-1.el8.x86_64                       
 iptables-1.8.4-17.el8_4.1.x86_64          libnetfilter_conntrack-1.0.6-5.el8.x86_64                
 libnfnetlink-1.0.1-13.el8.x86_64          libnftnl-1.1.5-4.el8.x86_64                       

Complete!
[klaus@defender ~]$ sudo cscli bouncers list
-------------------------------------------------------
 NAME IP ADDRESS VALID LAST API PULL TYPE VERSION 
-------------------------------------------------------
-------------------------------------------------------

**Technical Information (please complete the following information):**
CentOS 8, AlmaLinux 8

es.

**Comment by blotus** [comment]
Hello,

As discussed with you, this is not an issue with crowdsec, but rather an issue with the way yum/dnf handles the order of package installation.

It tries to install the bouncer before installing crowdsec, so `cscli` is not available yet.

I don't think we can handle that on our end, the workaround would be to install first crowdsec, then the bouncer  (in 2 different commands).
