### ISSUE TITLE
Bug/cscli decisions fails to limit output correctly

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1057]
**Describe the bug**
cscli decisions works unreliably. Using '-l' parameter it should be possible to limit results. When using it, it doesn't consistently limit results. 

Here are examples. In the last two cases the number of listed decisions are not consistent with the expected number of results.
```
admin@ip-172-31-11-235:~$ sudo cscli decisions list -l 1
+--------+----------+-------------------+---------------------------+--------+---------+---------------------------+--------+--------------------+----------+
|   ID   |  SOURCE  |    SCOPE:VALUE    |          REASON           | ACTION | COUNTRY |            AS             | EVENTS |     EXPIRATION     | ALERT ID |
+--------+----------+-------------------+---------------------------+--------+---------+---------------------------+--------+--------------------+----------+
| 479327 | crowdsec | Ip:116.105.24.126 | crowdsecurity/ssh-slow-bf | ban    | VN      | 24086 Viettel Corporation |     11 | 3h56m43.899496209s |     2265 |
+--------+----------+-------------------+---------------------------+--------+---------+---------------------------+--------+--------------------+----------+
admin@ip-172-31-11-235:~$ sudo cscli decisions list -l 2
+--------+----------+-------------------+----------------------+--------+---------+---------------------------+--------+--------------------+----------+
|   ID   |  SOURCE  |    SCOPE:VALUE    |        REASON        | ACTION | COUNTRY |            AS             | EVENTS |     EXPIRATION     | ALERT ID |
+--------+----------+-------------------+----------------------+--------+---------+---------------------------+--------+--------------------+----------+
| 479326 | crowdsec | Ip:116.105.24.126 | crowdsecurity/ssh-bf | ban    | VN      | 24086 Viettel Corporation |      8 | 3h56m37.149076048s |     2264 |
+--------+----------+-------------------+----------------------+--------+---------+---------------------------+--------+--------------------+----------+
admin@ip-172-31-11-235:~$ sudo cscli decisions list -l 3
+--------+----------+-------------------+----------------------+--------+---------+---------------------------+--------+--------------------+----------+
|   ID   |  SOURCE  |    SCOPE:VALUE    |        REASON        | ACTION | COUNTRY |            AS             | EVENTS |     EXPIRATION     | ALERT ID |
+--------+----------+-------------------+----------------------+--------+---------+---------------------------+--------+--------------------+----------+
| 479326 | crowdsec | Ip:116.105.24.126 | crowdsecurity/ssh-bf | ban    | VN      | 24086 Viettel Corporation |      8 | 3h56m28.231169902s |     2264 |
| 479325 | crowdsec | Ip:116.98.166.43  | crowdsecurity/ssh-bf | ban    | VN      | 24086 Viettel Corporation |      6 | 3h56m7.514429356s  |     2263 |
+--------+----------+-------------------+----------------------+--------+---------+---------------------------+--------+--------------------+----------+

```
**To Reproduce**
1. Login to your host with a functioning, up to date CrowdSec agent.
2. Type sudo cscli decisions list to see how many active decisions are in the database. Verify that there are more than three. 
3. Type sudo cscli decicions list -l 1
4. Type sudo cscli decicions list -l 2
5. Type sudo cscli decicions list -l 3
6. Verify that each output is consistent with what is expected, e.g. 1, 2 and 3 results.

**Expected behavior**
I would expect output to be 1,2 or 3 results.

**Technical Information (please complete the following information):**
 - OS: Debian Bullseye
 - Version: 1.2.1

**Comment by Lamera** [comment]
The interesting thing is that it's not every time happening. Sometimes the output seems correct.

**Comment by AlteredCoder** [comment]
Hello @klausagnoletti,

Does the third decisions has the same ip address than the second one ?
If you have multiple decisions that apply on the same IP, `cscli decisions list` will only show the decisions one time.

**Comment by klausagnoletti** [comment]
That's a good question :-) I tried to re-run the commands:
`admin@ip-172-31-11-235:~$ sudo cscli decisions list -l 1
+--------+----------+-----------------+----------------------+--------+---------+------------------+--------+--------------------+----------+
|   ID   |  SOURCE  |   SCOPE:VALUE   |        REASON        | ACTION | COUNTRY |        AS        | EVENTS |     EXPIRATION     | ALERT ID |
+--------+----------+-----------------+----------------------+--------+---------+------------------+--------+--------------------+----------+
| 947053 | crowdsec | Ip:92.255.85.37 | crowdsecurity/ssh-bf | ban    | RU      | 42097 SOVTEL LTD |      6 | 3h55m16.239620628s |     3104 |
+--------+----------+-----------------+----------------------+--------+---------+------------------+--------+--------------------+----------+
admin@ip-172-31-11-235:~$ sudo cscli decisions list -l 2
+--------+----------+------------------+----------------------+--------+---------+------------------+--------+--------------------+----------+
|   ID   |  SOURCE  |   SCOPE:VALUE    |        REASON        | ACTION | COUNTRY |        AS        | EVENTS |     EXPIRATION     | ALERT ID |
+--------+----------+------------------+----------------------+--------+---------+------------------+--------+--------------------+----------+
| 947053 | crowdsec | Ip:92.255.85.37  | crowdsecurity/ssh-bf | ban    | RU      | 42097 SOVTEL LTD |      6 | 3h55m12.871056162s |     3104 |
| 947052 | crowdsec | Ip:92.255.85.237 | crowdsecurity/ssh-bf | ban    | RU      | 42097 SOVTEL LTD |      6 | 3h6m11.292304647s  |     3103 |
+--------+----------+------------------+----------------------+--------+---------+------------------+--------+--------------------+----------+
admin@ip-172-31-11-235:~$ sudo cscli decisions list -l 3
+--------+----------+------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+
|   ID   |  SOURCE  |   SCOPE:VALUE    |          REASON           | ACTION | COUNTRY |               AS               | EVENTS |     EXPIRATION     | ALERT ID |
+--------+----------+------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+
| 947053 | crowdsec | Ip:92.255.85.37  | crowdsecurity/ssh-bf      | ban    | RU      | 42097 SOVTEL LTD               |      6 | 3h55m10.159245856s |     3104 |
| 947052 | crowdsec | Ip:92.255.85.237 | crowdsecurity/ssh-bf      | ban    | RU      | 42097 SOVTEL LTD               |      6 | 3h6m8.580492507s   |     3103 |
| 944747 | crowdsec | Ip:186.33.254.20 | crowdsecurity/ssh-slow-bf | ban    | AR      | 52361 Empresa Argentina de     |     11 | 1h1m25.790591615s  |     3101 |
|        |          |                  |                           |        |         | Soluciones Satelitales S.A.    |        |                    |          |
+--------+----------+------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+`

As you can see, there's nothing redundant within the same output so I can't rule it out. 
If it's a feature (as opposed to a bug) it should be documented. And maybe with an option to enable redundancy if, for some reason, one would want that.

**Comment by buixor** [comment]
Hello,

I took a look at it and it's more like an unwanted side effect : `cscli decisions list` at the back queries the `alert` endpoint (to be able to display Geoloc information) and deduplicates the entries by IP to keep output more concise.

Hence, you might see a number of decisions inferior to what you asked for if you have more than one decision targeting the same IP.

I'm going to do a cosmetic fix for that

**Comment by buixor** [comment]
https://github.com/crowdsecurity/crowdsec/pull/1120
