### ISSUE TITLE
Bug/journald source example is wrong

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#1062]
**Describe the bug**
Copying the example from [the docs](https://docs.crowdsec.net/docs/data_sources/journald) causes crowdsec to fail init.
Two things are wrong:
1. `labels` is missing
2. `journalctl_filters` isn't parsed correctly, the filter needs to be quoted: ` - "_SYSTEMD_UNIT=ssh.service"`

Also side-note: when I copy the code manually from the docs I get no newlines, but when I use the copy button I do. This might be browser related but I'd rather mention it too.

**Technical Information (please complete the following information):**
 - OS: `Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`
 - Version: `v1.2.1-debian-pragmatic-linux-dd03d073558e380c283afe66942f537c3da647ff`

**Comment by mmetc** [comment]
Fixed the page, thank you!

The copy-paste issue has been fixed upstream, we will have it in the next release: https://github.com/facebook/docusaurus/pull/5668
