### ISSUE TITLE
Bug/Implement RAW output for cscli ban list

### ISSUE THREAD

**Issue by ThomasLohner** [crowdsecurity/crowdsec#107]
**Describe the bug**
It seems that the raw output is not implemented yet as described in command help.

**To Reproduce**
`cscli ban list -o raw --debug` 
There is no output at all, not even the debug headers. Exit code is 0 as expected.

**Expected behavior**
Fetch all current bans from database and output them in raw format.

**Technical Information (please complete the following information):**
 - OS: Ubuntu 18.04 / Docker
 - Version v0.2.2

**Comment by AlteredCoder** [comment]
Hello Thomas,

We have this [pending MR](https://github.com/crowdsecurity/crowdsec/pull/108) to fix your issue. 
Is the proposed output is ok for you ?
