### ISSUE TITLE
Bug/Ubuntu repo for impish is missing Release file

### ISSUE THREAD

**Issue by jarppiko** [crowdsecurity/crowdsec#1073]
**Describe the bug**

Crowsec ubuntu repo in packagecloud.io is missing Release file for Ubuntu 21.10/impish causing the repo to get disabled by default (see `man 8 apt-secure`)

**To Reproduce**

1. Follow the official installation instructions for Ubuntu: 

```$ curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash```

2. Run `apt update`

3. See error

```
> apt update
Ign:9 https://packagecloud.io/crowdsec/crowdsec/ubuntu impish InRelease
Err:10 https://packagecloud.io/crowdsec/crowdsec/ubuntu impish Release
  404  Not Found [IP: 52.52.239.191 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/crowdsec/crowdsec/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
>
```

**Expected behavior**

The default installation instructions to work for the latest Ubuntu release without need to configure apt's security settings. 

**Technical Information (please complete the following information):**

 - OS: Ubuntu 
 - Version 21.10/impish amd64

**Additional context**
This might be related to the fact that crowdsec does not have version for Ubuntu 21.10 yet :-(

**Comment by Utopiah** [comment]
Indeed, makes me think I should be using Debian stable on my server instead, especially now that I migrated all services to containers.

**Comment by mmetc** [comment]
Thanks for the bug report - the non-LTS ubuntu versions were added after the 1.2.1 release so the build had to be triggered manually, which we did today: https://packagecloud.io/app/crowdsec/crowdsec/search?q=&filter=debs&filter=debs&dist=impish

We will be more proactive for the next releases. The firewall package is still building, it should be available any minute now.

**Comment by Xyaren** [comment]
@mmetc Ubuntu kinetic (22.10) is out for a while now, but the repository returns 404.
