### ISSUE TITLE
Bug/fail to reinstall crowdsec

### ISSUE THREAD

**Issue by 1iver** [crowdsecurity/crowdsec#1075]
**Describe the bug**
I have installed crowdsec as tutorial do using "apt install crowdsec" successfully.
For some reason, I uninstall crowdsec and totally removed /etc/crowdsec dir.
When I tried to reinstall crowdsec, some annoying errors happens.
First, because I have deleted /etc/crowdsec,  **/etc/crowdsec/config.yaml file does not auto recreate** when I exec "apt install crowdsec"，which is really unreasonable. So the wizard.sh failed to exec.
Second, after I create a config.yaml manually from the default file,  the another error 
**no credentials or URL found in api client configuration '/etc/crowdsec/local_api_credentials.yaml'，‘missing local API credentials for crowdsec agent, abort’** appears. 
I cannot figure out any way to fix these problem.
These are just some default config problem. I am not able to understand why these kind problem happens when i just reinstall the program.

additional information:
I uninstall crowdsec directly without using wizard.sh --uninstall, but i stoped crowdsec.service firstly
 
**To Reproduce**
stop crowdsec directly
rm -rf /etc/crowdsec
apt remove crowdsec

**Expected behavior**
success to reinstall
**Screenshots**

**Technical Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version v1.2.1

**Additional context**
Add any other context about the problem here, for example `/var/log/crowdsec.log` or error messages.

**Comment by 1iver** [comment]
solved by manually installing all components.

But it is strange that apt install failed to extract config.yaml to the /etc/crowdsec.
Maybe some controll exec before the extract process finishs.

**Comment by sabban** [comment]
Thank you for reporting this issue.

I can reproduce this. I'll look into it.

**Comment by prohand** [comment]
Hello, same problem for me :(.

Thank you

**Comment by prohand** [comment]
I have found a solution : 

```
rm /var/lib/dpkg/info/crowdsec*
rm -r /var/lib/crowdsec
```
I reinstall crowdsec properly

**Comment by sabban** [comment]
`apt purge crowdsec` should achieve the same. When removing a package, its configuration is left untouched, and so is its dpkg information.
