### ISSUE TITLE
Bug/No logrotate configuration in crowdsec 1.2.1 rpm

### ISSUE THREAD

**Issue by SignFinder** [crowdsecurity/crowdsec#1077]
After crowdsec 1.2.1 and crowdsec-bouncer-iptables installation to Centos 7 (el7 repository) logrotate configuration file was not created in /etc/logrotate.d/
In result crowdsec_api.log is 90 megabytes already.
Please add logrotate configuration file. It is not a good idea to have unlimited log files on the servers.

**Comment by buixor** [comment]
Hello @SignFinder !

Crowdsec doesn't rely on `/etc/logrotate.d/`, but performs logrotate using lumberjack : https://github.com/crowdsecurity/crowdsec/blob/c188d401a3e37ead07351544c4ceaa2a080c9f6d/pkg/types/utils.go#L29

However, it is not configurable : https://github.com/crowdsecurity/crowdsec/issues/1084
