### ISSUE TITLE
Improvement/CAPI: Ability to override 

### ISSUE THREAD

**Issue by wehde92** [crowdsecurity/crowdsec#1078]
Maybe this has been talked about and I just couldn't find it. Is there a way to disable the CAPI or cache it locally? We are currently evaluating Crowdsec as a potential solution and really like the idea of having one bad IP trigger a black hole action across all of our endpoints and maybe even our firewall. The issue that we potentially see is what if we have a user forget their password and trigger multiple login attempts by accident and then their IP for their organization gets pushed to the CAPI. Then when they call us to reset their password, we would have to submit a request to Crowdsec to remove that offender.

Obviously we would like to keep the CAPI enabled to be able to prevent known attackers, but we will inevitably have to deal with the false positives. Possible solutions would be:

1) Have the ability via LAPI to push to the endpoint a whitelist that overrides the rules from the CAPI. 
2) Be able to disable CAPI at the endpoints and then at the LAPI server cache a list from the CAPI that you can manualy override.

We could disable the CAPI and only use the LAPI to trigger a response upon first detection of an attacker IP address, but that is more of a reactive approach than being proactive and blocking that attack before it gets to your network.

Again, not sure if maybe there is a solution to this that we just haven't found in the documentation.

Keep up the fantastic work!

**Comment by sabban** [comment]
Thanks for your report, and sorry to be this long to answer.

There're two things to take into account:
* capi side generated list is consolidated among all our users, there's almost  no chance that only one of your user leads to its IP being listed
* you can set up whitelist at parser level

Feel free to reopen the issue if this doesn't answer your issue
