### ISSUE TITLE
Improvement/cscli ban list: Add filter for reason / scenario

### ISSUE THREAD

**Issue by ThomasLohner** [crowdsecurity/crowdsec#109]
**Is your feature request related to a problem? Please describe.**
When having hundreds of bans it is complicated to find only bans from a specific reason / scenario. For example if you need to debug a scenario or for checking false positives.

**Describe the solution you'd like**
`cscli ban list --scenario crowdsecurity/http-bad-user-agent`

**Describe alternatives you've considered** (Optional) 
`cscli ban list --raw | grep 'crowdsecurity/http-bad-user-agent`

**Comment by buixor** [comment]
https://github.com/crowdsecurity/crowdsec/pull/115
