### ISSUE TITLE
Bug/bouncer: Debian Repository install crowdsec-firewall-bouncer-iptables

### ISSUE THREAD

**Issue by prohand** [crowdsecurity/crowdsec#1093]
**Describe the bug**
Hello, I have install crowdsec-firewall-bouncer-iptables with repository and i have an error.

**To Reproduce**
```
curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash 
sudo apt-get install crowdsec -y
/usr/share/crowdsec/wizard.sh -c 
sudo apt install  crowdsec-firewall-bouncer-iptables
```

**Expected behavior**
` sudo apt install crowdsec-firewall-bouncer-iptables
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  ipset libipset11
The following NEW packages will be installed:
  crowdsec-firewall-bouncer-iptables ipset libipset11
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/2,626 kB of archives.
After this operation, 9,176 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Selecting previously unselected package libipset11:amd64.
(Reading database ... 62967 files and directories currently installed.)
Preparing to unpack .../libipset11_6.38-1.2_amd64.deb ...
Unpacking libipset11:amd64 (6.38-1.2) ...
Selecting previously unselected package ipset.
Preparing to unpack .../ipset_6.38-1.2_amd64.deb ...
Unpacking ipset (6.38-1.2) ...
Selecting previously unselected package crowdsec-firewall-bouncer-iptables.
Preparing to unpack .../crowdsec-firewall-bouncer-iptables_0.0.16_amd64.deb ...
Unpacking crowdsec-firewall-bouncer-iptables (0.0.16) ...
Setting up libipset11:amd64 (6.38-1.2) ...
Setting up ipset (6.38-1.2) ...
Setting up crowdsec-firewall-bouncer-iptables (0.0.16) ...
cscli/crowdsec is present, generating API key
API Key : xxxxxx
Job for crowdsec-firewall-bouncer.service failed because the control process exited with error code.
See "systemctl status crowdsec-firewall-bouncer.service" and "journalctl -xe" for details.
dpkg: error processing package crowdsec-firewall-bouncer-iptables (--configure):
 installed crowdsec-firewall-bouncer-iptables package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 crowdsec-firewall-bouncer-iptables
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
The journalctl -xe :

`- The job identifier is 5180.
Dec 13 21:17:23 vault crowdsec-firewall-bouncer[9005]: time="2021-12-13T21:17:23+01:00" level=info msg="crowdsec-firewall-bouncer v0.0.16-debian-pragmatic-ea64223d4e41c28b5d6324e82ab07625874ce507"
Dec 13 21:17:23 vault crowdsec-firewall-bouncer[9011]: time="2021-12-13T21:17:23+01:00" level=info msg="crowdsec-firewall-bouncer v0.0.16-debian-pragmatic-ea64223d4e41c28b5d6324e82ab07625874ce507"
Dec 13 21:17:23 vault crowdsec-firewall-bouncer[9011]: time="13-12-2021 21:17:23" level=fatal msg="http code 404, invalid body: invalid character '<' looking for beginning of value"
Dec 13 21:17:23 vault systemd[1]: crowdsec-firewall-bouncer.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
`

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version 10

Thank you

**Comment by buixor** [comment]
Hello @prohand 

By default, the bouncer is going to assume that you have the local api running on the same machine on port 8080.
Given the error message `msg="http code 404, invalid body: invalid character '<' looking for beginning of value"` it is likely that you have another web server listening on localhost 8080 and that the `<` is from the 404 html page !

You should edit the bouncer configuration to point it to the right endpoint for local api !


Please let me know,

**Comment by prohand** [comment]
Thank you for the answer.
How can I change this port on the bouncer?

**Comment by prohand** [comment]
I have reinstall completely crowdsec
I have change the port of crowdsec in config.yaml to 9090.
I have restart crowdsec
I have an another error : 

`crowdsec-firewall-bouncer[15101]: time="13-12-2021 21:56:35" level=fatal msg="firewall '${BACKEND}' is not supported"`

**Comment by prohand** [comment]
I have change the mode to iptables in config of the bouncer put i have this error : 

`="Get \"http://localhost:9191/v1/decisions/stream?startup=true\": dial tcp 127.0.0.1:9191: connect: connection refused"`

**Comment by prohand** [comment]
I have modify port to local_api_credentials.yaml and is ok.

Thank you
