### ISSUE TITLE
Сan't repeat CrowdSec multi-server installation

### ISSUE THREAD

**Issue by ibsteklodom** [crowdsecurity/crowdsec#1095]
Can't repeat CrowdSec multi-server installation (https://crowdsec.net/blog/multi-server-setup/)
After step 2 on registering the local machine again in the database I have error:
_pq: SSL is not enabled on the server_
If to add string "sslmode: disable" in config "/etc/crowdsec/config.yaml" I have error again:
_pq: password authentication failed for user "crowdsec"_

/var/lib/pgsql/12/data/pg_hba.conf:
local   all             all                                     password
host    all             all             127.0.0.1/32            password
host    all             all             ::1/128                 password

**Comment by ibsteklodom** [comment]
I think troubles was with special characters in password.(have special characters #,$,etc.).
What should be config in /var/lib/pgsql/12/data/pg_hba.conf?
My config now:
local all all peer
host all all 127.0.0.1/32 password
host all all ::1/128 password

**Comment by sabban** [comment]
For special characters in crowdsec configuration, you can use the yaml `|-` stuff, like it is explained here https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines/21699210

You pg_hba.conf seems good to me.
