### ISSUE TITLE
systemd: crowdsec-firewall-bouncer.service unit not enabled on install

### ISSUE THREAD

**Issue by Mist-Hunter** [crowdsecurity/crowdsec#1099]
After a fresh install of crowdsec-firewall-bouncer-iptables in debian 11.1
```bash
apt install crowdsec-firewall-bouncer-iptables
```
crowdsec-firewall-bouncer.service will start, but after reboot systemctl reports 'dead; disabled'.
```bash
root@mistDockerDev 12:58:17 ~ →  systemctl status crowdsec-firewall-bouncer
● crowdsec-firewall-bouncer.service - The firewall bouncer for CrowdSec
     Loaded: loaded (/etc/systemd/system/crowdsec-firewall-bouncer.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
lines 1-3/3 (END)
```

I don't know if that is intended, but in order to get it to start on reboot I had to add the following to my install script.
```bash
systemctl enable crowdsec-firewall-bouncer
``` 
I hope this isn't user error (again :P)

**Comment by AlteredCoder** [comment]
The PR has been merged. We will release a new version of the bouncer soon :)
