### ISSUE TITLE
Improvement/Packages for OpenSUS

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1101]
**Is your feature request related to a problem? Please describe.**
Yes. I hear from OpenSUSE users who'd like to use CrowdSec but can't due to the lack of officially supported packages

**Describe the solution you'd like**
Packages for OpenSUS :-)

**Describe alternatives you've considered** (Optional) 
There are none if you don't want to hack the excisting packages.

**Example of what you imagine**
Binary packages for OpenSUSE :-)

**Additional context**
See post from user on Reddit: https://www.reddit.com/r/selfhosted/comments/rem2vf/comment/hon2vw8/

**Comment by LaurenceJJones** [comment]
> Why is opensuse listed as supported distro when in reality it is not ??
> https://packagecloud.io/docs#anchor-opensuse

You might be mistaken. You linked to the package cloud docs, not our documentation.

**Comment by GreatBigWhiteWorld** [comment]
Was lead to that link from your [doc](https://docs.crowdsec.net/docs/next/getting_started/install_crowdsec/)
[manually install crowdsec](https://docs.crowdsec.net/docs/next/user_guides/building)
[public repository](https://packagecloud.io/crowdsec/crowdsec)
But after reading your reply above I guess "it still has nothing to do with you". So never mind.

**Comment by LaurenceJJones** [comment]
We have implemented packages for opensuse please follow instructions on https://docs.crowdsec.net/u/getting_started/installation/linux
