### ISSUE TITLE
Bug/"cscli bouncers -o json" does not report "ip_address", "revoked", "type", "version" keys when empty or false

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/crowdsec#1102]
When asking for the json list of bouncers, if ip_address is empty or null, it is not included in the response. Payload should always have the same keys for a given object.
The same goes for "revoked" when equal to 0 (boolean, not nullable) and for "type", "version".

**Comment by cronlabspl** [comment]
Additionally, php dims out error code 490.

Whatever it is.
