### ISSUE TITLE
false positive postfix-spam

### ISSUE THREAD

**Issue by celevra** [crowdsecurity/crowdsec#1106]
hi,

i'm using crowdsec/postfix-spam version 0.2 on 3 Servers
These servers are watched by our monitoring system, the systems tries to connect and then disconnects, the Logs in mail.log look like these:

```
Dec 16 14:56:40 mx02 postfix/submission/smtpd[5116]: connect from host.name.de[1.1.1.1]
Dec 16 14:56:40 mx02 postfix/submission/smtpd[5116]: disconnect from host.name.de[1.1.1.1] ehlo=2 starttls=1 quit=1 commands=4
Dec 16 14:56:53 mx02 postfix/smtpd[4673]: connect from host.name.de[1.1.1.1]
Dec 16 14:56:53 mx02 postfix/smtpd[4673]: disconnect from host.name.de[1.1.1.1] ehlo=2 starttls=1 quit=1 commands=4
Dec 16 14:57:18 mx02 postfix/anvil[1411]: statistics: max connection rate 1/60s for (submission:1.1.1.1) at Dec 16 14:47:40
Dec 16 14:57:18 mx02 postfix/anvil[1411]: statistics: max connection count 1 for (submission:1.1.1.1) at Dec 16 14:47:40
Dec 16 14:57:40 mx02 postfix/submission/smtpd[5116]: connect from host.name.de[1.1.1.1]
Dec 16 14:57:40 mx02 postfix/submission/smtpd[5116]: disconnect from host.name.de[1.1.1.1] ehlo=2 starttls=1 quit=1 commands=4
Dec 16 14:57:53 mx02 postfix/smtpd[4673]: connect from host.name.de[1.1.1.1]
Dec 16 14:57:53 mx02 postfix/smtpd[4673]: disconnect from host.name.de[1.1.1.1] ehlo=2 starttls=1 quit=1 commands=4
Dec 16 14:58:40 mx02 postfix/submission/smtpd[5116]: connect from host.name.de[1.1.1.1]
Dec 16 14:58:40 mx02 postfix/submission/smtpd[5116]: disconnect from host.name.de[1.1.1.1] ehlo=2 starttls=1 quit=1 commands=4
Dec 16 14:58:53 mx02 postfix/smtpd[4673]: connect from host.name.de[1.1.1.1]
Dec 16 14:58:53 mx02 postfix/smtpd[4673]: disconnect from host.name.de[1.1.1.1] ehlo=2 starttls=1 quit=1 commands=4
```

after a few hours the system gets blocked by crowdsec:
```
hosting ~ # cscli decisions list | grep 1.1.1.1
| 870691 | crowdsec | Ip:1.1.1.1 | crowdsecurity/postfix-spam                | ban    | IN      |                             0  |      9 | 2h53m3.182969248s   |    52784 |
```

is there anything that i can provide to dig deeper?

regards

Celevra

**Comment by buixor** [comment]
Thanks, I'll try to have a look at this asap and come back to you !

**Comment by cronlabspl** [comment]
@celevra & @buixor
looks like postfix issue rather than CS........

**Comment by cronlabspl** [comment]
> how does postfix talks to crowdsec?

via API

**Comment by buixor** [comment]
@celevra : postfix doesn't talk to crowdsec, crowdsec only read its logs, and I do believe it's a false positive in the postfix scenario. I'll keep you posted

**Comment by cronlabspl** [comment]
@buixor 
> crowdsec only read its logs

True; It equals `talking` ( in **this** case )

**Comment by celevra** [comment]
@cronlabspl 
because it is missleading, there can't be a postfix issue if crowdsec only parses the log files
and there is no API Communication

**Comment by celevra** [comment]
@cronlabspl  and you commented this thread but I asked the crowdsec team ;-)

**Comment by buixor** [comment]
Hello @celevra !

Sorry for the delay, I pinged you on gitter in the meanwhile.
If I'm not mistaken, the logs you pasted above are not parsed by the postifx parser, so I don't think there are the one triggering the false positive :

![image](https://user-images.githubusercontent.com/990714/147125251-e0f9e803-20d2-47c6-83fb-5f8890c04834.png)

Can you let me know which collection you are using or try to find the logs that triggered the false positive ?

Please le me know if I can help,
