### ISSUE TITLE
Bug/Install script

### ISSUE THREAD

**Issue by thib3113** [crowdsecurity/crowdsec#1112]
(not sure if it's the correct repository, I doesn't found the script in all repos)

**Describe the bug**

When running script on ubuntu 20.04, it will produce a warning : 
`[: 20.04: integer expression expected`

( and because I try, if the "if" match, it will not go in the if, but will continue => so maybe doesn't works on 16.04 ? )

The error is on line 201 : `
  { [ "${os,,}" = "ubuntu" ] && [ "${version_id}" -lt 18 ]; } ||`
And in fact, $version_id === "20.04", and -lt doesn't support float .

**To Reproduce**
1. Start the install script on an ubuntu 20.04 (and all versions where $VERSION_ID in `/etc/os-release`/ or `/usr/lib/os-release` is a float)

**Expected behavior**
No warnings (in fact, not really important if it works on ubundu < 18, just it show a warning, and skip a part) .

**Technical Information (please complete the following information):**
 - OS: ubuntu 20.04
 - Version : 1.2.1, script : https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh

**Comment by blotus** [comment]
Hello,

This is unfortunately an issue with the install script provided by packagecloud.

We already reported the issue to them.

In the meantime, you have 2 workarounds:
 - Download the script, and execute it with the `os` and `dist` env vars, so in your case `os=ubuntu dist=focal ./script.sh` 
 - Follow the manual repository setup installation: https://packagecloud.io/crowdsec/crowdsec/install#manual-deb
