### ISSUE TITLE
Bug/cscli: fragile collection dependencies

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/crowdsec#1118]
**Describe the bug**

If two collections have common elements, uninstalling one collection taints the other.

**To Reproduce**

Note: The `crowdsecurity/freebsd` and `crowdsecurity/linux` collections have, today, the exact same elements, one of which is the `crowdsecurity/sshd` collection.

```
# cscli collections list
--------------------------------------------------------------------------------
 NAME                 📦 STATUS   VERSION  LOCAL PATH                           
--------------------------------------------------------------------------------
 crowdsecurity/sshd   ✔️  enabled  0.2      /etc/crowdsec/collections/sshd.yaml  
 crowdsecurity/linux  ✔️  enabled  0.2      /etc/crowdsec/collections/linux.yaml 
--------------------------------------------------------------------------------
# cscli install crowdsecurity/freebsd
[...]
# cscli collections list
[...]
 crowdsecurity/sshd   ✔️  enabled  0.2      /etc/crowdsec/collections/sshd.yaml  
 crowdsecurity/freebsd  ✔️  enabled  0.1      /etc/crowdsec/collections/freebsd.yaml 
 crowdsecurity/linux  ✔️  enabled  0.2      /etc/crowdsec/collections/linux.yaml 
# cscli collections remove crowdsecurity/freebsd
[...]
# cscli collections list
----------------------------------------------------------------------------------------
 NAME                 📦 STATUS           VERSION  LOCAL PATH                           
----------------------------------------------------------------------------------------
 crowdsecurity/linux  ⚠️  enabled,tainted  0.2      /etc/crowdsec/collections/linux.yaml 

```

Reinstalling `crowdsecurity/linux` removes the taint (and reinstalls `crowdsecurity/sshd`) although the command shows a fatal error (_error while enabling  crowdsecurity/linux : crowdsecurity/linux is tainted, won't enable unless --force_).

**Expected behavior**

Installing and immediately uninstalling any collection should not impact other objects. Removing `crowdsecurity/freebsd` should not automatically remove `crowdsecurity/sshd` if the latter was installed by hand or by another collection.
At least, reinstalling the tainted collection should not return the message "error... won't enable unless --force" because the collections is correctly installed, untainted and enabled.

**Comment by ze42** [comment]
Came here to report that. Found the problem with apache/nginx.

If you `crowdsecurity/apache2` and `crowdsecurity/nginx`, removing either would remove `crowdsecurity/base-http-scenarios`.

An update after that gives:
```
# cscli hub update 
INFO[30-12-2021 08:55:46 AM] Wrote new 204553 bytes index to /etc/crowdsec/hub/.index.json 
INFO[30-12-2021 08:55:46 AM] dependency of crowdsecurity/apache2 : missing collections crowdsecurity/base-http-scenarios, tainted. 
```
