### ISSUE TITLE
Parser ModSecurity unused

### ISSUE THREAD

**Issue by cmiscloni** [crowdsecurity/crowdsec#1121]
Version:
```
2021/12/22 15:39:45 version: v1.2.2-el7-rpm-f86e0c0a5aae3e8f83941023f4e75d0ec877fbc9
2021/12/22 15:39:45 Codename: alphaga
2021/12/22 15:39:45 BuildDate: 2021-12-22_09:12:33
2021/12/22 15:39:45 GoVersion: 1.17.5
2021/12/22 15:39:45 Constraint_parser: >= 1.0, <= 2.0
2021/12/22 15:39:45 Constraint_scenario: >= 1.0, < 3.0
2021/12/22 15:39:45 Constraint_api: v1
2021/12/22 15:39:45 Constraint_acquis: >= 1.0, < 2.
```

It seems that parser ModSecurity is not bind to the log file associated with it, current metrics still empty

![image](https://user-images.githubusercontent.com/4446733/147109812-e7d87fc5-bc4c-48c1-95c5-726a2e1300c4.png)

**It is enable in configuration:**
crowdsecurity/modsecurity       ✔️  enabled          0.8      /etc/crowdsec/parsers/s01-parse/modsecurity.yaml

Source file (modsec_audit) is present in metrics output  but modsecurity is not present in parsers list .

It seems that the parser is not used in my config.

**Comment by cmiscloni** [comment]
I tried to uninstall manually the parser and install it again with the wizard, it let me choose the parser but doesn't provide a list of file to monitor like the other parsers, and finally it return an error:

`ERR[22/12/2021:16:08:38] crowdsec_wizard: fail to install collection crowdsecurity/modsecurity`

**Comment by cmiscloni** [comment]
Maybe the reason:

`find: ‘/var/log/apache2’: Aucun fichier ou dossier de ce type`

In Centos, it's httpd folder and not apache

**Comment by blotus** [comment]
Hello,

Currently the wizard does detect modsecurity automatically.

You will need to manually edit your `acquis.yaml` file to point crowdsec to the correct log file, for example:
```yaml
---
filenames:
 - /var/log/httpd/error.log
labels:
 type: modsecurity
```
You will also need to install the collection yourself:
```
cscli hub update && cscli collections install crowdsecurity/modsecurity
```

Something else to note, the modsecurity parser does not support modsec audit logs (the logs that contains the full details of a blocked requests).

It only supports the modsec logs saying that a request has triggered a rule (they should be in your apache error logs).

**Comment by cmiscloni** [comment]
Hello,

Thanks, I do what you said, but I don't see the parser enabled on metrics:


```
INFO[22-12-2021 05:43:38 PM] Parser Metrics:
+----------------------------------+-------+--------+----------+
|             PARSERS              | HITS  | PARSED | UNPARSED |
+----------------------------------+-------+--------+----------+
| child-crowdsecurity/apache2-logs |  3882 |   2980 |      902 |
| child-crowdsecurity/http-logs    | 18795 |  12300 |     6495 |
| child-crowdsecurity/nginx-logs   |  3285 |   3285 | -        |
| child-crowdsecurity/sshd-logs    |    96 | -      |       96 |
| crowdsecurity/apache2-logs       |  3431 |   2980 |      451 |
| crowdsecurity/cdn-whitelist      |     1 |      1 | -        |
| crowdsecurity/dateparse-enrich   |  6265 |   6265 | -        |
| crowdsecurity/geoip-enrich       |  6265 |   6265 | -        |
| crowdsecurity/http-logs          |  6265 |   5925 |      340 |
| crowdsecurity/nginx-logs         |  3285 |   3285 | -        |
| crowdsecurity/non-syslog         |  6716 |   6716 | -        |
| crowdsecurity/rdns               |     1 |      1 | -        |
| crowdsecurity/seo-bots-whitelist |     1 |      1 | -        |
| crowdsecurity/sshd-logs          |    12 | -      |       12 |
| crowdsecurity/syslog-logs        |   803 |    803 | -        |
| crowdsecurity/whitelists         | 12530 |  12530 | -       
```


**acquis file: content:**

#Generated acquisition file - wizard.sh (service: sshd) / files : /var/log/secure
filenames:
  - /var/log/secure
labels:
  type: syslog
---
filenames:
  - /var/log/httpd/filename.error_log
  - /var/log/httpd/xxxx.error_log
  - /var/log/httpd/error_log
labels:
  type: modsecurity
---

**Comment by cmiscloni** [comment]
It's ok now, it appeared when something has hitted it seems.
Many thanks for the guideline.
