### ISSUE TITLE
Bug/cloudflare-bouncer: issue after changing actions from challenge to block in config file

### ISSUE THREAD

**Issue by MUBI06** [crowdsecurity/crowdsec#1122]
Hello, 

We have an urgent issue with our cloudflare bouncer attached to crowdsec. After editing the the cloudflare bouncer config file to change actions from challenge to block. We noticed an error in our container log (see the pictures). 

According to someone of the crowdsec team, it is an internal cash issue. Because after changing the actions in the config file it created a new list in cloudflare so perhaps it is still referencinf an old list that has been romoved.

Please could we have some help on that because it is blocking our production environment ?

We tried **/usr/local/bin/crowdsec -d -c cloudflare.yaml** and **/usr/local/bin/crowdsec -s -c cloudflare.yaml** its deleting the list then recreated it but still isuues in the container logs.

![image](https://user-images.githubusercontent.com/65021626/147235905-ace34f19-ad9b-4b07-b64e-f9044e1ee76d.png)

![image](https://user-images.githubusercontent.com/65021626/147248660-67f6eb29-dad2-487a-96ee-d9e8e254e3e4.png)

Best Regards,
Santiane

**Comment by buixor** [comment]
solved via discord, user/cache issue.
