### ISSUE TITLE
Date format with Logstash

### ISSUE THREAD

**Issue by cmiscloni** [crowdsecurity/crowdsec#1128]
Since the latest build of crowdsec (1.2.2), i'm facing to problem with logstash with date format.
It works very well before so I suppose that there is maybe some changes at your side ?

Actually http_plugin from crowdsec send json message to logstash http plugin.

```
"status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"fai
led to parse field [timestamp] of type [date] in document with id 'eQ80AH4Bd6Olf9ouAiFF'. Preview of field's value: '2021/12/28 09:41:52'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [2021/1
2/28 09:41:52] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}}}}
```

**Comment by sbs2001** [comment]
@cmiscloni  I didn't find any difference in date format between 1.2.0 and 1.2.2 using the defaults.  Could you paste your plugin's config from /etc/crowdsec/notifications/http.yaml ?  And also please let us know which version of CrowdSec you were using previously & now and any specific db config etc.

**Comment by cmiscloni** [comment]
@sbs2001, yes this is my config:

```
type: http

name: http_default # this must match with the registered plugin in the profile
log_level: info # Options include: trace, debug, info, warn, error, off

format: |
  {{.|toJson}}

url: http://127.0.0.1:5050 # plugin will make requests to this url. Eg value https://www.example.com/
skip_tls_verification: true
method: POST
headers:
 Content-Type: "application/json
```
version: v1.2.2-el7-rpm

I didn't find any errors with the previous version 1.2.1

It stop working of the middle of the night without any modifications of my side, I supposed that it was maybe a cron job (cscli hub update && upgrade)

**Comment by buixor** [comment]
Hello, I do not believe there is any change on our side in the date format. Do you believe it's related to crowdsec's version upgrade, or parser/scenario upgrade ?

**Comment by cmiscloni** [comment]
I was asking to be sure that no changes have been made, if this is not the case then the problem must come from elsewhere.
Thanks for your time.

**Comment by buixor** [comment]
Hello @cmiscloni : any news on your side ? Please let me know if bug is confirmed or if we should close :+1:
