### ISSUE TITLE
Bug/cscli collections install wrongfuly report tainted for missing dependencies

### ISSUE THREAD

**Issue by ze42** [crowdsecurity/crowdsec#1140]
**Describe the bug**

When we have missing dependencies, installing a collection again states it is tainted, and `--force` would be required. But it still reinstall missing dependencies.

**To Reproduce**

```
# Install apache2, remove one of the scenarios
cscli collections install crowdsecurity/apache2
cscli scenarios remove crowdsecurity/http-probing

# Re-install apache2 (fatal message, --force required)
cscli collections install crowdsecurity/apache2   2>&1 | cat
[...] level=fatal msg="error while enabling  crowdsecurity/apache2 : while installing crowdsecurity/base-http-scenarios: crowdsecurity/base-http-scenarios is tainted, won't enable unless --force."
# Re-install apache2 would not get any error, as everything was ok the first time around
cscli collections install crowdsecurity/apache2
```

**Expected behavior**
Properly stating it re-enables dependencies, but clearly not some misleading error messages.

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version 1.2.2

**Additional context**
Found while checking workaround for https://github.com/crowdsecurity/crowdsec/issues/1118

**Comment by mmetc** [comment]
This is fixed since the error message now tells exactly what's happening and the --force flag is indeed required. I'm leaving the other bug open because it's a different/larger issue.
