### ISSUE TITLE
Improvement/cscli: Support for time zones

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/crowdsec#1151]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I look up alerts and the time for the alerts is not matching my timezone.

**Describe the solution you'd like**
I wish that CrowdSec supports time zones. The timestamp for the alerts would be in sync with the configured time zone.

**Example of what you imagine**
You can configure the time zone in /etc/crowdsec/ and the alerts in the database would match that time zone.

**Comment by mikkel1156** [comment]
Would be nice to have ths extended to Docker as well with a environment variable TZ

**Comment by buixor** [comment]
We took the decision to enforce UTC everywhere : https://github.com/crowdsecurity/crowdsec/pull/1167 (people having issues with daylight saving timezones).

Please open an issue if you still think that TZ support (for `cscli` only) would make sense !
