### ISSUE TITLE
Bug/installer Error when adding crowdsec repository on Ubuntu 18.04 

### ISSUE THREAD

**Issue by SimonVanacco** [crowdsecurity/crowdsec#1163]
**Describe the bug**
I'm trying to get crowdsec installed on a Ubuntu 18.04 vm, and i'm adding the repository with the script given in the docs. 
When running apt update after that i get an error. 
This has been a real head-scratcher so if you have any idea what could cause this issue that would be great ! 

**To Reproduce**
1. Run curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
2. Run apt update
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/5305627/149336377-fca1c69d-52a8-4d8b-aaa1-d9b28b91a97c.png)

**Technical Information:**
 - OS: Ubuntu 18.04.6 / Linux 4.15.0-166-generic

**Additional context**
On the screenshot we get a certificate error but **after** apt ignores  "Ign:8 https://packagecloud.io/crowdsec/crowdsec/ubuntu bionic InRelease" for some reason. I think finding why apt ignores this line is the key but I don't gave technical knowledge to understand why it's happening.

**Comment by buixor** [comment]
@SimonVanacco As seen on discord, seems to be an issue w/ your setup. I'll close but feel free to reopen if you get more info on this :)
