### ISSUE TITLE
Bug/grok pattern HTTPD24_ERRORLOG: issue with Apache non-MPM modules.

### ISSUE THREAD

**Issue by NoelProf** [crowdsecurity/crowdsec#1164]
The default grok pattern HTTPD24_ERRORLOG, used by grok pattern HTTPD_ERRORLOG in the parsers/apache2-logs.yaml  doesn't handle the absence of a thread id(tid) in the error log.  As a result, the http-generic-bf scenario is not parsed if auth_basic is not an MPM module. As it is in RHEL7, Amazon Linux 2

https://httpd.apache.org/docs/2.4/mod/core.html#errorlogformat

**Steps to reproduce the behavior**
1. On a system with Apache HTTPD 2.4, trigger an error with auth_basic
Example line:
```
[Tue Jan 11 13:57:46.740590 2022] [auth_basic:error] [pid 31363] [client 32.8.74.123:6977] AH01618: user hacker not found: /special/docs/secure, referer: https://wikipedia.org/search?query=thetruth

```
2. cscli parsers inspect crowdsecurity/apache2-logs
3. Note non parsed error log rows.

**Expected behavior**
error log line would be parsed.

 - OS: Amazon Linux 2, RHEL 7.x

**Comment by NoelProf** [comment]
Pattern is defined in grokky module.

https://github.com/crowdsecurity/grokky/pull/2

**Comment by buixor** [comment]
thank you very much, let's update grokky dependency as well, it's going to be in upcoming 1.3 :  https://github.com/crowdsecurity/crowdsec/pull/1187
