### ISSUE TITLE
Bug/ TrueNas - Local API is disabled please run this command on the local API Machine

### ISSUE THREAD

**Issue by filol** [crowdsecurity/crowdsec#1166]
Please, start your issue name (after `Bug`) with the component name impacted by this feature request and a small description of the Bug. Example: `Bug/cscli: issue with ....` and remove this line :)

**Describe the bug**
I was trying to install your tool on TrueNas but i can't start the service and the message error is really obscur to me.

<img width="686" alt="Capture d’écran 2022-01-15 à 16 58 07" src="https://user-images.githubusercontent.com/9217516/149628540-b25b58e9-72b1-497a-9a09-3705fa2f0333.png">

Also, not part of the bug but your pkg in not available freebsd 12 on the amd64 architecture (but it is for freebsd 11 ,13, 14. Can you add it ? There is a table here : https://www.freshports.org/security/crowdsec/

**To Reproduce**
1. Create Jail : Clone Jail / 11.4-RELEASE-p13
2. `pkg install crowdsec`
3. `sysrc crowdsec_enable="YES"`
4. `service crowdsec start`

**Expected behavior**
Service start

**Technical Information (please complete the following information):**
 - OS: TrueNAS-12.0-U7 (Core edition)

**Comment by buixor** [comment]
Sorry for the delay, not cool :sweat: 
However, some users reported running crowdsec successfully on TrueNAS : https://discord.com/channels/921520481163673640/963373475827941416/963373478705238016 (sorry, it's on discord).

If you're still facing the issue, can you include logs of crowdsec in debug mode so we can investigate ? (None of the dev team is running TrueNAS)
