### ISSUE TITLE
Bug/crowdsec: file reader will claim it can't access files when it actually can

### ISSUE THREAD

**Issue by capnspacehook** [crowdsecurity/crowdsec#1168]
**Describe the bug**
`crowdsec` will ignore any capabilities set when checking if it can access files for reading while doing file acquisition. This is because `unix.Access` is used to check if the current user has permission to read the file, instead of just opening it and checking for an error. It seems `access(2)` does not respect capabilities, while `open(2)` does. The man page for `access(2)` even recommends it should not be used in this way: https://linux.die.net/man/2/access (see 'Notes' section).

The `unix.Access` calls occur here:
https://github.com/crowdsecurity/crowdsec/blob/master/pkg/acquisition/modules/file/file.go#L233
https://github.com/crowdsecurity/crowdsec/blob/master/pkg/acquisition/modules/file/file.go#L303

This isn't an issue if `crowdsec` is running as the `root` user, which it does by default. In the interest of removing unneeded privileges from `crowdsec`, I tried modifying the systemd service to run it as a non-root user, and gave it the `cap_dac_read_search` ambient capability. This in theory should allow `crowdsec` to function properly.

**To Reproduce**

- Create crowdsec user: 
```
useradd crowdsec
```
- Give ownership of crowdsec directories to the crowdsec user: 
```
chown -R crowdsec:crowdsec /etc/crowdsec /var/lib/crowdsec /var/log/crowdsec*.log
```
- Add these lines to the crowdsec systemd service file (after `[Service]`) : `/lib/systemd/system/crowdsec.service`
```
User=crowdsec
AmbientCapabilities=CAP_DAC_READ_SEARCH
```
- Restart systemd daemon and crowdsec service
```
systemctl daemon-reload
systemctl restart crowdsec
```
- View errors in crowdsec logs

**Expected behavior**
I expected `crowdsec` to succeed reading log files when I gave it the appropriate capability.

**Technical Information:**
 - OS: Debian 11
 - Version v1.2.3-debian-pragmatic-a6e405422c732e9b6c46ae1004a2b80297df8336

**Additional context**
Log entries:
```
time="16-01-2022 20:38:02" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"                                                                            
time="16-01-2022 20:38:02" level=info msg="Adding file /var/log/auth.log to datasources" type=file                                                                          
time="16-01-2022 20:38:02" level=info msg="Adding file /var/log/syslog to datasources" type=file                                                                            
time="16-01-2022 20:38:02" level=info msg="Adding file /var/log/kern.log to datasources" type=file                                                                          
time="16-01-2022 20:38:02" level=info msg="Adding file /var/log/messages to datasources" type=file                                                                          
time="16-01-2022 20:38:02" level=warning msg="Starting processing data"
time="16-01-2022 20:38:02" level=error msg="unable to read /var/log/syslog : permission denied" type=file                                                                   
time="16-01-2022 20:38:02" level=error msg="unable to read /var/log/kern.log : permission denied" type=file                                                                 
time="16-01-2022 20:38:02" level=error msg="unable to read /var/log/messages : permission denied" type=file                                                                 
time="16-01-2022 20:38:02" level=error msg="unable to read /var/log/auth.log : permission denied" type=file 
```

**Comment by buixor** [comment]
Thanks for the report, looking into it :)
