### ISSUE TITLE
Improvement/Dockerhub: container for linux/arm

### ISSUE THREAD

**Issue by r3dpan** [crowdsecurity/crowdsec#1178]
Any chance that you guys will add a container for linux/arm on dockerhub in the near future?

**Comment by sabban** [comment]
Hi,

When you write `linux/arm` do you really mean `linux/arm`and not `linux/arm64` ?

If it's the case, what would be your use case for this ? 

Thanks your for your issue

**Comment by maxi017** [comment]
Uhr sry for not beeing specific enough. I actually mean linux/armhf or Linux/armv7. I'm currently trying to run the crowdsec docker container on a raspberry pi 4 which sadly doesn't work because your provided container only supports arm64.
