### ISSUE TITLE
Bug/cscli ban list is *suboptimal*

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#119]
**Describe the bug**
`cscli ban list` gets slow when the database grows, and looking at the code, it makes sense.

**To Reproduce**
 - Have a big (>100Mo) sqlite database.
 - Run `cscli ban list`
 - ???
 - Wait

**Expected behavior**
`cscli ban list` should be fast.

**Technical Information (please complete the following information):**
 - OS: Ubuntu
 - Version: v0.2.2

**Comment by ThomasLohner** [comment]
If you refactor this it would also be nice to have a param `--count` instead of hardcoded 20 items in `human` output format:

https://github.com/crowdsecurity/crowdsec/blob/master/cmd/crowdsec-cli/ban.go#L141

**Comment by buixor** [comment]
now that we switched orm *and* including pagination support, it should be a lot better.
