### ISSUE TITLE
Improvement/adding files in forensics mode with wildcard

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1207]
**Is your feature request related to a problem? Please describe.**
Sort of. More of an inconvenience.

**Describe the solution you'd like**
When adding cold log to CrowdSec using forensics mode I would like to be able to add multiple files by using wildcards (same possibilities as in acquis.yaml)

**Describe alternatives you've considered** (Optional) 
Adding files one by one manually or using a script.

**Example of what you imagine**
sudo crowdsec -dsn file:///home/klaus/containers/npm/data/logs/*.log -type nginx-proxy-manager

**Comment by blotus** [comment]
As discussed, this is already supported, you just need to quote the path to prevent your shell from interpreting the glob pattern.
