### ISSUE TITLE
Improvement/cscli: add 'machines status' command

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1210]
User TipTopf on Discord suggested this

**Is your feature request related to a problem? Please describe.**
It's related to debugging

**Describe the solution you'd like**
Add a "cscli machines status" to get information about the agents deployed in distributed setup

**Example of what you imagine**
for example it would be helpful to get a list of the simulation status of each scenario on each node.

**Comment by buixor** [comment]
It has been added in the 1.4.X versions and the `cscli machines list` command
