### ISSUE TITLE
Bug/failed to parse ingress-nginx logs in kubernetes

### ISSUE THREAD

**Issue by rlex** [crowdsecurity/crowdsec#1213]
**Describe the bug**
Crowdsec can't parse ingress-nginx logs

**To Reproduce**
Official guide on how to install crowdsec to k8s

**Expected behavior**
Logs should be parsed

**Screenshots**
```
/ # cscli metrics
INFO[28-01-2022 10:53:23 AM] Acquisition Metrics:                         
+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+----------------+------------------------+
|                                                                        SOURCE                                                                         | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+----------------+------------------------+
| file:/var/log/containers/ingress-nginx-controller-79pmx_ingress-nginx_controller-dcb11eee7ff5827ada9d1d174383acb9608d529681410b71f586a3dc7626832c.log |        309 | -            |            309 | -                      |
+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+----------------+------------------------+
INFO[28-01-2022 10:53:23 AM] Parser Metrics:                              
+--------------------------------+------+--------+----------+
|            PARSERS             | HITS | PARSED | UNPARSED |
+--------------------------------+------+--------+----------+
| child-crowdsecurity/nginx-logs |  618 | -      |      618 |
| crowdsecurity/docker-logs      |  309 |    309 | -        |
| crowdsecurity/nginx-logs       |  309 | -      |      309 |
+--------------------------------+------+--------+----------+
```

**Technical Information (please complete the following information):**
k3s 1.23.1
crowdsec helm chart 0.2.1
ingress-nginx 1.1.1

**Additional context**
Sample log line from ingress-nginx:
2022-01-28T13:47:49.354767118+03:00 stdout F 69.162.124.232 - - [28/Jan/2022:10:47:49 +0000] "HEAD / HTTP/1.1" 308 0 "https://example.org" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)" 402 0.000 [example-wikijs-3000] [] - - - - 36dc88f75402b20189f5506c338d06c6

**Comment by he2ss** [comment]
Hi @rlex,

The log sample your pasted is one from the node log file ?
If the answer is yes, I think it's because of the log format. the helm chart and the official guide show of to handle logs from k8s cluster that use docker as containers engine, and it seems in k3s the containers logs aren't in json format.

**Comment by rlex** [comment]
It's directly from logfile crowdsec-agent is watching, yes.
Also yes, k3s uses containerd instead of docker. 

There seems to be support for json in containerd, but PR is pretty recent: https://github.com/containerd/containerd/issues/3955

Plus dockershim is deprecated in kubernetes and they seem to recommend containerd by default now.

**Comment by rlex** [comment]
Also, cri-o seems to be write in different format too.

**Comment by he2ss** [comment]
So I just merged the [cri log format parser](https://github.com/crowdsecurity/hub/pull/362) in the hub. 
And also [improved the helm chart](https://github.com/crowdsecurity/helm-charts/pull/22) so user can specify if the k8s cluster is using docker or containerd so it can parsed properly your logs.

So to make it work you need to specify in your `values.yaml`:

```yaml
container_runtime: containerd

agent:
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
```

Could you please tell us if it's working.

**Comment by rlex** [comment]
seems to be working, but no mention of nginx:
```
INFO[28-01-2022 05:43:35 PM] Parser Metrics:                              
+--------------------------+------+--------+----------+
|         PARSERS          | HITS | PARSED | UNPARSED |
+--------------------------+------+--------+----------+
| crowdsecurity/non-syslog |   26 |     26 | -        |
+--------------------------+------+--------+----------+
```

That's expected?

**Comment by rlex** [comment]
yea, it seems like nginx parser is not used. No hits while running scan with ie nikto and no output from cscli alerts. 
But it seems to parse logs now, since there is nothing in "unparsed" column.

**Comment by he2ss** [comment]
Did you add the `crowdsecurity/cri-logs` and change `container_runtime` value ?

You can join [crowdsec discord](https://discord.gg/Dse9tXd3) for better exchange.
Otherwise, we can continue here, if you can paste your `cscli metrics` and `cscli parsers list` results here please

**Comment by rlex** [comment]
Found the reason - crowdsec was still at 1.2.x.
It's better to bind helm chart image version to specific release, not "latest".
Since i installed it some time ago, combination of "IfNotPresent" policy and "latest" tag used some old version:
https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/values.yaml#L10-L14

```
INFO[31-01-2022 10:10:54 AM] Parser Metrics:                              
+--------------------------------+------+--------+----------+
|            PARSERS             | HITS | PARSED | UNPARSED |
+--------------------------------+------+--------+----------+
| child-crowdsecurity/cri-logs   |   89 |     89 | -        |
| child-crowdsecurity/http-logs  |  198 |    146 |       52 |
| child-crowdsecurity/nginx-logs |  135 |     66 |       69 |
| crowdsecurity/cri-logs         |   89 |     89 | -        |
| crowdsecurity/dateparse-enrich |   66 |     66 | -        |
| crowdsecurity/geoip-enrich     |   66 |     66 | -        |
| crowdsecurity/http-logs        |   66 |     63 |        3 |
| crowdsecurity/nginx-logs       |   89 |     66 |       23 |
| crowdsecurity/whitelists       |   66 |     66 | -        |
+--------------------------------+------+--------+----------+
```

Looks like it's working?

**Comment by he2ss** [comment]
Yep, I think you can close this issue as it's now fixed.
