### ISSUE TITLE
Bug/ Handle  decisions with varying expiry for same IP

### ISSUE THREAD

**Issue by sbs2001** [crowdsecurity/crowdsec#1244]
Consider the following case:

Pull 1 (at t=0): {"new":[{"ip": 1.2.3.4, "duration":4h}, {"ip": 1.2.3.4, "duration":2h}]} -> Bouncer inserts 1.2.3.4

Pull 2(at t=2h + 1): {"deleted": [{"ip":"1.2.3.4"}]} -> Bouncer deletes 1.2.3.4

`cscli decisions list` would show that `1.2.3.4` is still banned due to the 4h decision, but it won't be present in ipset, nftables or whatever the bouncer is managing.

Here duration is irrelevant because ip would be deleted when the first decision expires.

I haven't thought this thoroughly, but one way to solve this would be to add a boolean column `deleted` for decisions table and then have unique constraint on `(decision.deleted, decision.value)`.

**Comment by buixor** [comment]
if we're ok that LAPI deduplicates the decisions :
 - in step 1. it's going to return only one {ip,decision_type,duration} (favoring the longest one)
 - in step 2. it's only going to return the delete if no other decisions for the same {ip,decision_type} is active ?

**Comment by sbs2001** [comment]
@buixor  could you clarify few scenarios, assuming we're using your suggested approach:

Pull 1 (at t=0): {"new":[{"ip": 1.2.3.4, "duration":4h}  

Then at t=1h I create another decsion for same ip `1.2.3.4`
```
cscli decisions add --ip 1.2.3.4 --duration 6h
```
Will I receive  Pull 1 (at t=1h): {"new":[{"ip": 1.2.3.4, "duration":6h}   ?
What would be the decision pull stream look like at (t=4h) (time at which first decision expired) ?

**Comment by sbs2001** [comment]
Recapping our discussion, the approach we agreed upon is to be "greedy" and provide minimal updates. 

In general, only single  {decision_value,decision_type}  would be present in either `new` or `expired` decisions. 

For a decision to be present in `new` following conditions must be met:
1. It should have max duration compared to all other decisions with same {decision_value,decision_type} . max duration in the sense , that this decision should live longest compared to others assuming current time. 
```
# decision 1
cscli decisions add --ip 1.2.3.4 --duration 6h # at t=0 ; 

# decision 2
cscli decisions add --ip 1.2.3.4 --duration 2h # at t=5h ; 
```

From above eg, at t=5h the decision 2 would be returned.

2. It should not be expired, obviously. 

For a decision to be present in `expired` , all decisions with same {decision_value,decision_type} must be expired too. 

In the above case we will get `1.2.3.4` deleted at t=7h only.
