### ISSUE TITLE
Bug/crowdsec raspberrypi install & wizzard

### ISSUE THREAD

**Issue by nitescuc** [crowdsecurity/crowdsec#1245]
**Describe the bug**
1. Running the wizzard from command line complains about envsubst binary is needed ...
2. Not attempting to start crowdsec, port 8080 is already used or lapi was disabled message even though the ports have been changed into config files

**To Reproduce**
Port 8080 is in use on the system
1. sudo apt update && sudo apt install crowdsec
2. got message "Not attempting to start ..." (correct)
3. Change config.yaml + local_api_credentials.yaml to move to 8042
4. sudo apt remove crowdsec
5. Check that configuration files are not removed (ok)
6. sudo apt install crowdsec
7. got message "Not attempting to start ..." (wrong as configuration has been modified to listen on 8042)
8. Attempt to run /usr/share/crowdsec/wizard.sh -c
9. got "FATA[08/02/2022:10:27:46] crowdsec_wizard: envsubst binary is needed to use do a full install with the wizard, exiting ..."

**Expected behavior**
Installing crowdsec when the configuration has been modified to listen on a free port shouldn't warn about port 8080 being already used and installation should continue
Should be able to launch the wizard without error

**Screenshots**

**Technical Information (please complete the following information):**
 - OS: Raspbian Buster
 - Version 1.3.0

**Additional context**
Crowdsec does start normally with sudo service crowdsec start

**Comment by sabban** [comment]
Hi,

I tried but didn't manage to reproduce step7.

Concerning step 9, it's not bug it was meant to be a feature to choose not add gettext dependency.

**Comment by sabban** [comment]
This should be fixed by https://github.com/crowdsecurity/crowdsec/pull/1258
