### ISSUE TITLE
[CrowdSec HAProxy] haproxy-logs parser and bad-user-agent scenario won't work together

### ISSUE THREAD

**Issue by DiiSteR** [crowdsecurity/crowdsec#1268]
Hello ! 

I'm having trouble using the http-bad-user-agent feature with HAProxy-logs parser. 

I do not know why, but it wont trigger the scenario, but it look like the parser is correctly parsing HAProxy logs : 

Example : 

`cscli exlain -f /var/log/haproxy.log --type haproxy `

line: Feb 15 14:33:31 crowdsec haproxy[21421]: 192.168.1.43:47278 [15/Feb/2022:14:33:31.440] tomcat_srv tomcat_srv/tomcat01 0/0/0/4/4 404 825 - - ---- 1/1/0/0/0 0/0 {360Spider} "GET /test HTTP/1.1"
        ├ s00-raw
        |       ├ 🟢 crowdsecurity/non-syslog (first_parser)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       └ 🟢 crowdsecurity/haproxy-logs (+46 ~2)
        ├ s02-enrich
        |       ├ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
        |       ├ 🟢 crowdsecurity/geoip-enrich (+9)
        |       ├ 🟢 crowdsecurity/http-logs (+7)
        |       └ 🟢 crowdsecurity/whitelists (unchanged)
        ├-------- parser success 🟢
        ├ Scenarios
                ├ 🟢 crowdsecurity/http-crawl-non_statics
                └ 🟢 crowdsecurity/http-probing

As u can see, there is no "http-bad-user-agent triggered.

But if I try the same thing, with Nginx, or Apache2. it works great, the scenarii is triggered and then the decision is taken.

I tried many things, but nothing is working atm.

I have already unmarked these lines on /etc/crowdsec/patterns/haproxy :  

- HAPROXYCAPTUREDREQUESTHEADERS %{DATA:captured_request_headers}
- HAPROXYCAPTUREDRESPONSEHEADERS %{DATA:captured_response_headers}
- capture request header X-Forwarded-For len 50
- capture request header User-Agent len 200

And my parser is on default value.

If u have any tip to help me, It would be really appreciated!

**Comment by AlteredCoder** [comment]
Hello @DiiSteR,

Can you run the `cscli explain` command with a `--verbose` arguments and paste it in the issue please so we can see what the haproxy parser is capturing.

**Comment by DiiSteR** [comment]
Hi @AlteredCoder, you are very fast thanks a lot ! here it is :

line: Feb 15 14:33:31 crowdsec haproxy[21421]: 192.168.1.43:47282 [15/Feb/2022:14:33:31.864] tomcat_srv tomcat_srv/tomcat01 0/0/0/5/5 404 825 - - ---- 1/1/0/0/0 0/0 {360Spider} "GET /test HTTP/1.1"
        ├ s00-raw
        |       ├ 🟢 crowdsecurity/non-syslog (first_parser)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       └ 🟢 crowdsecurity/haproxy-logs (+46 ~2)
        |               └ update evt.Stage : s01-parse -> s02-enrich
        |               └ create evt.Parsed.backend_queue : 0
        |               └ create evt.Parsed.captured_response_cookie : -
        |               └ create evt.Parsed.feconn : 1
        |               └ create evt.Parsed.http_request : /test
        |               └ create evt.Parsed.request : /test
        |               └ create evt.Parsed.captured_request_cookie : -
        |               └ create evt.Parsed.captured_response_headers :
        |               └ create evt.Parsed.haproxy_second : 31.8
        |               └ create evt.Parsed.http_host :
        |               └ create evt.Parsed.http_user :
        |               └ create evt.Parsed.http_version : 1.1
        |               └ create evt.Parsed.retries : 0
        |               └ create evt.Parsed.actconn : 1
        |               └ create evt.Parsed.haproxy_month : Feb
        |               └ create evt.Parsed.termination_state : ----
        |               └ create evt.Parsed.time_backend_connect : 0
        |               └ create evt.Parsed.time_backend_response : 5
        |               └ create evt.Parsed.time_request : 0
        |               └ create evt.Parsed.captured_request_headers : 360Spider
        |               └ create evt.Parsed.haproxy_milliseconds : 4
        |               └ create evt.Parsed.haproxy_minute : 33
        |               └ create evt.Parsed.http_proto :
        |               └ create evt.Parsed.srv_queue : 0
        |               └ create evt.Parsed.accept_date : 15/Feb/2022:14:33:31.864
        |               └ create evt.Parsed.client_ip : 192.168.1.43
        |               └ create evt.Parsed.client_port : 47282
        |               └ create evt.Parsed.frontend_name : tomcat_srv
        |               └ create evt.Parsed.http_verb : GET
        |               └ create evt.Parsed.server_name : tomcat01
        |               └ create evt.Parsed.haproxy_year : 2022
        |               └ create evt.Parsed.http_status_code : 404
        |               └ create evt.Parsed.srvconn : 0
        |               └ create evt.Parsed.bytes_read : 825
        |               └ create evt.Parsed.haproxy_hour : 14
        |               └ create evt.Parsed.time_duration : 5
        |               └ create evt.Parsed.time_queue : 0
        |               └ create evt.Parsed.backend_name : tomcat_srv
        |               └ create evt.Parsed.beconn : 0
        |               └ create evt.Parsed.haproxy_monthday : 15
        |               └ create evt.Parsed.haproxy_time : 14:33:31.8
        |               └ create evt.Parsed.port :
        |               └ update evt.StrTime :  -> 15/Feb/2022:14:33:31 -0000
        |               └ create evt.Meta.http_path : /test
        |               └ create evt.Meta.http_status : 404
        |               └ create evt.Meta.log_type : http_access-log
        |               └ create evt.Meta.service : http
        |               └ create evt.Meta.source_ip : 192.168.1.43
        ├ s02-enrich
        |       ├ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
        |               ├ create evt.Enriched.MarshaledTime : 2022-02-15T14:33:31Z
        |               ├ update evt.MarshaledTime :  -> 2022-02-15T14:33:31Z
        |               ├ create evt.Meta.timestamp : 2022-02-15T14:33:31Z
        |       ├ 🟢 crowdsecurity/geoip-enrich (+9)
        |               ├ create evt.Enriched.ASNOrg :
        |               ├ create evt.Enriched.ASNumber : 0
        |               ├ create evt.Enriched.IsInEU : false
        |               ├ create evt.Enriched.IsoCode :
        |               ├ create evt.Enriched.Latitude : 0.000000
        |               ├ create evt.Enriched.Longitude : 0.000000
        |               ├ create evt.Enriched.ASNNumber : 0
        |               ├ create evt.Meta.ASNNumber : 0
        |               ├ create evt.Meta.IsInEU : false
        |       ├ 🟢 crowdsecurity/http-logs (+7)
        |               ├ create evt.Parsed.file_ext :
        |               ├ create evt.Parsed.static_ressource : false
        |               ├ create evt.Parsed.file_dir : /
        |               ├ create evt.Parsed.file_name : test
        |               ├ create evt.Parsed.impact_completion : false
        |               ├ create evt.Parsed.file_frag : test
        |               ├ create evt.Meta.http_args_len : 0
        |       └ 🟢 crowdsecurity/whitelists (unchanged)
        ├-------- parser success 🟢
        ├ Scenarios
                ├ 🟢 crowdsecurity/http-crawl-non_statics
                └ 🟢 crowdsecurity/http-probing

It finds the bad user agent : create evt.Parsed.captured_request_headers : **360Spider**

But I guess that this is not considered as an User-Agent ?

**Comment by AlteredCoder** [comment]
It appears that some configuration need to be added in order to logs headers so we can't capture the user agent in the upstream parser.

For your case, if only the user agent is logged in your haproxy logs, you can add this static in your haproxy parser to have the bad user agent scenario works:

```yaml
  - parsed: http_user_agent
    expression: evt.Parsed.captured_request_headers
```

Since the `http-bad-user-agent` use the `evt.Parsed.http_user_agent` field to check the user agent, using this static should works :)

**Comment by DiiSteR** [comment]
Ok great, now this is parsing correctly the user-agent : 

`create evt.Parsed.http_user_agent : 360Spider`

Then the good scenarii is triggered, but the decision is not taken...

├ Scenarios
                ├ 🟢 crowdsecurity/http-bad-user-agent

I'm working on. Thank's a lot !

**Comment by AlteredCoder** [comment]
For your information, the decision will not be taken if your run `cscli explain` . You need to trigger the scenario with real logs

**Comment by DiiSteR** [comment]
Issue resolved and I'm closing ! Thanks again.
