### ISSUE TITLE
Your discord link seems to be broken

### ISSUE THREAD

**Issue by ovizii** [crowdsecurity/crowdsec#1271]
Sorry for posting this here but I wasn't sure where else to raise this issue :-(

Visiting your website, I clicked the link to your discord channel: 

![image](https://user-images.githubusercontent.com/837902/154114208-6849aea6-ffeb-4dbd-ab44-38d4c6b58e8b.png)

I end up on discord with this error:

![image](https://user-images.githubusercontent.com/837902/154114383-f0b77a84-50b8-41a3-ab96-cd1368bc6f26.png)

**Comment by buixor** [comment]
thank you ! it has been fixed !
