### ISSUE TITLE
Bug/Crowdsec docker Environment Variable CUSTOM_HOSTNAME has no affect

### ISSUE THREAD

**Issue by LePresidente** [crowdsecurity/crowdsec#1278]
**Describe the bug**
When running the crowdsec docker container, the environment variable CUSTOM_HOSTNAME doesn't work and the agent is always called localhost

**To Reproduce**
1. docker run -e CUSTOM_HOSTNAME="test" crowdsecurity/crowdsec

**Expected behavior**
The agent on the docker container should be called the CUSTOM_HOSTNAME variable, not localhost

**Technical Information (please complete the following information):**
 - OS: Docker
 - Version: latest

**Additional context**
Output of command:
```
docker run -e CUSTOM_HOSTNAME="test" crowdsecurity/crowdsec
Regenerate local agent credentials
time="18-02-2022 08:06:28 AM" level=info msg="push and pull to Central API disabled"
time="18-02-2022 08:06:28 AM" level=info msg="machine 'localhost' deleted successfully"
time="18-02-2022 08:06:28 AM" level=info msg="push and pull to Central API disabled"
time="18-02-2022 08:06:28 AM" level=info msg="Machine 'localhost' successfully added to the local API"
time="18-02-2022 08:06:28 AM" level=info msg="API credentials dumped to '/etc/crowdsec/local_api_credentials.yaml'"
Check if lapi need to register automatically an agent
```

**Comment by woopstar** [comment]
It is currently not in the released version of crowdsec in docker. Unfortunately the docker readme is updated without the release to docker hub for image. So this is a regression and will be fixed when a new release is published.

**Comment by woopstar** [comment]
Tagging @he2ss as we talked about this on Discord.
