### ISSUE TITLE
Improvement/Add number of found items with cscli <item> list

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1280]
This is a feature request from the Discord from martin.scahible

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add the number of found (scenarios|collections|bouncers), if i run cscli (scenarios|collections|bouncers) list

This would make a quick compare e.g. between servers much more easier instead of counting.

**Example of what you imagine**
At the first line after the list command you write in uppercase eg. COLLECTIONS, so extend this by (found: 6) or sometimes else which makes sense.

**Comment by LaurenceJJones** [comment]
Closing issue as not planned, if you wish to find something like this then you can use bash syntax

```
cscli -oraw decisions list | grep -v ^name | wc -l
```
