### ISSUE TITLE
Improvement/crowdsec Install script and Oracle Linux

### ISSUE THREAD

**Issue by SignFinder** [crowdsecurity/crowdsec#1282]
Crowdsec repository installation script https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh correctly detects Oracle Linux (fully binary compatible with RHEL\Centos) as ol8 instead of el8. 
But there is not repository for ol8 and after installation is necessary to change "ol8" to "el8" in crowdsec.repo manually.
Might it will be better to make changes of script to provide correct url for Oracle Linux automatically.

**Comment by sabban** [comment]
oracle linux 7 and 8 packages will be available when 1.3.3 is out.
