### ISSUE TITLE
Improvement/docker: allow to enroll LAPI to app.crowdsec.net on startup

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#1286]
- Add an env var that will contain the enroll key
 - Add a `cscli console status` command to be able to check if the instance is already enrolled or not in the console.

**Comment by woopstar** [comment]
@blotus can you provide an outfrom the `cscli console status` from when it's not enrolled and when its enrolled. Then I'll look into it.

**Comment by blotus** [comment]
@woopstar This command does not exist yet, we need to add a new CAPI endpoint on our side before we can implement it in crowdsec (this is needed because if you try to enroll an already enrolled instance, the console will ask you to re-confirm the enrollment, so we want to check if the instance is already enrolled or not)

**Comment by woopstar** [comment]
> @woopstar This command does not exist yet, we need to add a new CAPI endpoint on our side before we can implement it in crowdsec (this is needed because if you try to enroll an already enrolled instance, the console will ask you to re-confirm the enrollment, so we want to check if the instance is already enrolled or not)

You're right. We need to add a status endpoint on app.crowdsec.net. Do we want to use the enrollment key or the machine id to do the lookup?

**Comment by he2ss** [comment]
@blotus is [this](https://github.com/crowdsecurity/crowdsec/pull/1430/files#diff-d2e9469a98eb27c1f57744d40fb6f541a9ff1897597a84309fe2289ad7af242cR110) can be used to replace the `cscli console status` ?

**Comment by he2ss** [comment]
Done, it will be available in the next release.
