### ISSUE TITLE
Bug/cscli: dashboard not being created with podman

### ISSUE THREAD

**Issue by rbqbjyur** [crowdsecurity/crowdsec#1292]
**Technical Information:**
 - OS: CentOS Stream 8
 - Podman v3.4.1
 - CrowdSec v1.3.0

**Describe the bug**
Just trying to setup the dashboard, main thing to consider is I am using podman rather than docker.
I note, that separate to the `cscli dashboard setup` command, podman has no problem pulling and running the `docker.io/metabase/metabase:v0.41.5` image, so doesn't seem to be an issue with actually running it. Most likely with the setup. But am happy to play around and try any suggestions you have, as I recognise it could just be oddities with interacting with podman.

**To Reproduce**
Steps to reproduce the behaviour:
1. On system running podman, as opposed to docker
2. Run command: `sudo ln -s /var/run/podman/podman.sock /var/run/docker.sock`
3. Run command: `sudo cscli dashboard setup`

**Expected behaviour**
The metabase container should be successfully created, and confirmed by output

**Screenshots**
No screenshots, but this is the output:
```
$ sudo cscli dashboard setup
INFO[24-02-2022 05:06:47 PM] Pulling docker image metabase/metabase:v0.41.5
........
INFO[24-02-2022 05:06:49 PM] creating container 'crowdsec-metabase'
FATA[24-02-2022 05:06:49 PM] container create: failed to create container : Error response from daemon: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                       
$
```

Thanks for all your hard work on this project.

**Comment by sbs2001** [comment]
Can reproduce this issue without `sudo ln -s /var/run/podman/podman.sock /var/run/docker.sock` too. This is most likely because crowdsec has docker specific stuff https://github.com/crowdsecurity/crowdsec/blob/1928d385b0d66aa03faabef0f212e7d1ee695bb7/pkg/metabase/metabase.go#L17 .

**Comment by buixor** [comment]
then the doc is misleading : https://doc.crowdsec.net/docs/next/observability/dashboard/ :

```
If you use podman instead of docker and want to install the crowdsec dashboard, you need to run:

sudo ln -s /var/run/podman/podman.sock /var/run/docker.sock

Then you can setup the dashboard with sudo cscli dashboard setup.
```

**Comment by ne20002** [comment]
Hi
I want to setup crowdsec with dashboard in a pod using podman, means: create a crowdsec lapi container and a dashboard container (and probably a mariadb or postgresql container). But I can't use cscli dashboard setup as crowdsec is not installed on the host.
Both containers in the pod share the same mounted directory so access to the crowdsec database shall be possible from metabase container.

How do I set up the dashboard container manually?
