### ISSUE TITLE
Bug/cscli: cant generate completion without `/etc/crowdsec/config.yaml` or override with `--config`

### ISSUE THREAD

**Issue by 06kellyjac** [crowdsecurity/crowdsec#1301]
**Describe the bug**

can't generate completion without `/etc/crowdsec/config.yaml` or override with `--config`

**To Reproduce**
1. Don't have `/etc/crowdsec/config.yaml`
2. `cscli completion bash`
3. See error

```
λ cscli completion bash
FATA[02-03-2022 08:13:42 PM] failed to read config file: open /etc/crowdsec/config.yaml: no such file or directory
```

**Expected behavior**

Completion shouldn't depend on config file existing

**Comment by mmetc** [comment]
fixed in https://github.com/crowdsecurity/crowdsec/pull/1340

thanks
