### ISSUE TITLE
Bug/notification-email from address name component is literal `From`

### ISSUE THREAD

**Issue by pdf** [crowdsecurity/crowdsec#1304]
**Describe the bug**
When sending email, the `notification-email` plugin sends email with the name component of the from address hard-coded to `From`, here: https://github.com/crowdsecurity/crowdsec/blob/383eebf2b6009d0c1963b4c5be9770a16807c305/plugins/notifications/email/main.go#L91

This looks very strange for the mail receiver.

**To Reproduce**
1. Enable email notification plugin
2. Set `sender_email` to e.g. `configured@email.address`
3. Trigger email notification
4. Observe that from address is `From <configured@email.address>`

**Expected behavior**
The `sender_email` field should probably just be passed verbatim to the mailer library, allowing users to set the full from address, e.g.:
```yaml
sender_email: CrowdSec Alerts <configured@email.address>
```
This change should remain valid for existing users that have specified a bare email address, since the from address does not require a name component.

Alternatively, if it's preferred for some reason that `sender_email` be retained as an email-only field, an additional field `sender_name` could be introduced, and should default to something that's not `From`.

**Technical Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: v1.3.0

**Comment by buixor** [comment]
Hello, there is an ongoing PR for that : https://github.com/crowdsecurity/crowdsec/pull/1297

**Comment by pdf** [comment]
Ah so there is, I did not search PRs. That should work, feel free to close this now, or when that's merged.

**Comment by pdf** [comment]
Closing, as #1297 is merged.
