### ISSUE TITLE
Bug/ Debian 11 Bullseye crowdsec no longer installs on a Proxmox node

### ISSUE THREAD

**Issue by RvLDSDM** [crowdsecurity/crowdsec#1313]
**Describe the bug**
root@internet02:/etc/apt/sources.list.d# curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
Detected operating system as /11.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
**Installing /etc/apt/sources.list.d/crowdsec_crowdsec.list...curl: (22) The requested URL returned error: 404** 

Unable to download repo config from: https://packagecloud.io/install/repositories/crowdsec/crowdsec/config_file.list?os=&dist=11&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this

**To Reproduce**
1. install proxmox
2. enter shell
3. execute as root

**Expected behavior**
Installation of the software

**Technical Information (please complete the following information):**
 - OS: Debian 11  Bullseye]
 - Version [Running a Proxmox node , NO VM !!, the node itself]

.

**Comment by OcelotNat** [comment]
Can you re-ping packagecloud ? Still not working (Proxmox VE 7 / Debian 11)
