### ISSUE TITLE
Bug/ query error in dashboard when using MariaDB

### ISSUE THREAD

**Issue by ne20002** [crowdsecurity/crowdsec#1318]
I changed my setup to use CrowdSec with a MariaDB instead of sqlite.
I also chnaged the Crowdsec database entry in dashboard to connect to the Crowdsec Mariadb.

Most tiles in Dashboard are working correctly but for decisions I get:

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(strftime('%Y-%m-%d %H:%M:%S',"decisions"."until")) > datetime('now')' at line 2 

This is caused by this query:
SELECT count(distinct(simulated||value||scope||type)) from decisions WHERE datetime(strftime('%Y-%m-%d %H:%M:%S',"decisions"."until")) > datetime('now');

Any ideas how to fix this?

**Comment by sbs2001** [comment]
@ne20002  currently for dashboard only sqlite is supported https://docs.crowdsec.net/docs/next/observability/dashboard . 

The `cscli dashboard setup` should fail if you're using anything other. Any chance you started dashboard with sqlite and then changed the db from UI settings of metabase ?

**Comment by buixor** [comment]
@ne20002 : unfortunately, we tried in the past to industrialize dashboard deploys on non-sqlite backend and it was a nightmare.

closing as it's out of scope for now.
