### ISSUE TITLE
Improvement/profile: ban duration format (and config validation)

### ISSUE THREAD

**Issue by Athanasius** [crowdsecurity/crowdsec#1321]
**Is your feature request related to a problem? Please describe.**
I decided to change my bantime from 4 hours to 3 days (to match my fail2ban config).  Seeing '4h' already there I assumed that '3d' would be valid.  It turns out it isn't.  However no error was triggered or logged *until a ban was attempted*.

**Describe the solution you'd like**
At the very least https://docs.crowdsec.net/docs/profiles/format should be updated to list/link to other doc that does, what the valid formats are here.  Ideally the could would support all of:

- Xm (minutes)
- Xh (hours, as it already does)
- Xd (days)
- Xw (weeks)
- XM (months)
- XY (years)

Yes, I know, banning for weeks, months or years seems unwise, but if this is going to be addresses then it should be done so comprehensively.

But also, some method of being informed that this bit of configuration is invalid at start/restart/reload would go a long way to catching such errors as soon as possible, instead of only being aware when:

1. You check the crowdsec.log and see a spam of `time="08-03-2022 00:30:06" level=error msg="while pushing to api : failed sending alert to LAPI: API error: unable to create alerts: decision duration '0xc000ba3d60' : time: unknown unit \"d\" in duration \"3d\": unable to parse duration"`, which continues until you fix it.
2. You get repeated email notifications about banning the same IP.  **I ended up with these every 1-2 seconds**.  I think it only stopped when fail2ban applied its own ban on the IP in question.

For instance the monitoring software icinga2 has `icinga2 daemon -c <config file> -C` to check the syntax of all of the configuration, so you can catch errors even before a reload/restart.  If `cscli` has something similar I'm not finding it in the help.

**Describe alternatives you've considered** (Optional) 
For now I'm trying '72h' on the assumption there's not also a "only 1 digit of hours" limitation....

**Comment by Athanasius** [comment]
I've just come across `/usr/bin/crowdsec -c /etc/crowdsec/config.yaml -t` in the supplied systemd unit file.  But that results in exit code of `0` with '72h' or '3d' in the profile.yaml file.

**Comment by Athanasius** [comment]
OK, if you search in general for `duration` you can hit https://doc.crowdsec.net/docs/scenarios/format/#duration which then refers to the [golang ParseDuration format](https://golang.org/pkg/time/#ParseDuration).  I'd suggest adding that also to the profile format documentation.  It's not in the 'next' version of https://doc.crowdsec.net/docs/next/profiles/format either.

**Comment by buixor** [comment]
Hello,

Thanks for the issue and feedback. I opened a PR to fix the issue (https://github.com/crowdsecurity/crowdsec/pull/1326) and another one to complete the documentation : https://github.com/crowdsecurity/crowdsec-docs/pull/189
