### ISSUE TITLE
Improvement/debian: Add logrotate file

### ISSUE THREAD

**Issue by Athanasius** [crowdsecurity/crowdsec#1322]
In getting crowdsec up and running, and checking logs for consequences of configuration errors I noticed that the start of `/var/log/crowdsec.log` is still way back last year when I first installed crowdsec.

This is less than ideal.

At least on Debian you can reasonably assume someone will be employing `logrotate`, and supplying a configuration file this will be harmless if the user doesn't have it installed.  It might also be relevant to other OSes.

So, something like this should be added as `/etc/logrotate.d/crowdsec`:

```
/var/log/crowdsec.log {

    daily
    rotate 31
    compress

    delaycompress
    missingok
    postrotate
        systemctl reload crowdsec.service
    endscript
}
```
I'll now be running with this file in place locally and will try to remember to report back on if it works without issues.

I've no relevant experience with Debian packaging, there are probably guidelines and standards for exactly how the file should be supplied by a .deb file / its scripts.

**Comment by buixor** [comment]
Hello,

unless I'm mistaken, crowdsec already supports this : https://doc.crowdsec.net/docs/next/configuration/crowdsec_configuration/#log_max_size

Logrotate features are provided by [lumberjack](https://github.com/natefinch/lumberjack/)

**Comment by Athanasius** [comment]
Interesting, although that then begs the question as to why the default is to just not rotate or limit the log file size at all.  I even did a full purge and reinstall to crowdsec 1.3.1 recently due to another issue, so the defaults I have are recent.

Sure, a default log file size could lead to a user losing relevant stuff when first setting up, but potentially filling the disk space is also a problem.

Still, `logrotate` is a standard Debian thing, so the Debian packaging of crowdsec could benefit from this.

**Comment by Athanasius** [comment]
Adding in the other two log files ....
```
/var/log/crowdsec.log /var/log/crowdsec_api.log /var/log/crowdsec-firewall-bouncer.log {

    daily
    rotate 31
    compress

    delaycompress
    missingok
    postrotate
        systemctl reload crowdsec.service
    endscript
}
```
> I'll now be running with this file in place locally and will try to remember to report back on if it works without issues.
And I've now tested this, it definitely works.
