### ISSUE TITLE
Improvement/docker: swap removal and adding

### ISSUE THREAD

**Issue by zerkms** [crowdsecurity/crowdsec#1331]
At the moment the dockerfile entrypoint script looks like

```bash
## Install collections, parsers, scenarios & postoverflows
cscli -c "$CS_CONFIG_FILE" hub update
cscli -c "$CS_CONFIG_FILE" collections upgrade crowdsecurity/linux || true
cscli -c "$CS_CONFIG_FILE" parsers upgrade crowdsecurity/whitelists || true
cscli -c "$CS_CONFIG_FILE" parsers install crowdsecurity/docker-logs || true
if [ "$COLLECTIONS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" collections install $COLLECTIONS
fi
if [ "$PARSERS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" parsers install $PARSERS
fi
if [ "$SCENARIOS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" scenarios install $SCENARIOS
fi
if [ "$POSTOVERFLOWS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" postoverflows install $POSTOVERFLOWS
fi

## Remove collections, parsers, scenarios & postoverflows
if [ "$DISABLE_COLLECTIONS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" collections remove $DISABLE_COLLECTIONS
fi
if [ "$DISABLE_PARSERS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" parsers remove $DISABLE_PARSERS
fi
if [ "$DISABLE_SCENARIOS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" scenarios remove $DISABLE_SCENARIOS
fi
if [ "$DISABLE_POSTOVERFLOWS" != "" ]; then
    cscli -c "$CS_CONFIG_FILE" postoverflows remove $DISABLE_POSTOVERFLOWS
fi
```
So things first installed, then removed.

It makes a weird situation when you cannot remove `crowdsecurity/linux` collection and install `crowdsecurity/sshd` - because `sshd` will be installed first, and then removal will clean everything up.

So I suggest that default collections/parsers are installed first, followed by a block of removals, followed by a block of custom installs.

**Comment by LaurenceJJones** [comment]
Sorry for no reply in a while,

This has been refactored and changed in such a way that startup should be optimized to compute differences between the defined installs and defined disabled ones.

https://github.com/crowdsecurity/crowdsec/blob/0fb64682fd17452784b81a42f6909bd322afcacb/docker/docker_start.sh#L367-L368

If this is still not optimal please reopen this issue stating why.
