### ISSUE TITLE
Improvement/Allow .local config file

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/crowdsec#1385]
Hi,

It could be usefull to allow usage of config file with .local to allow to override some value in the config file without touching the "official" file...
Because when crowdsec config file (or the bouncer) is updated this can cause issue.
Or you keep your current config file and you may loose some new value.
Or you overwrite with the maintainer version and then you loose your custom change...

The idea is to thave a file like config.yaml.local (or config.local.yaml as you wish) where you can place custom value.
Like changing the log dir or the backend. The same apply for the bouncer ofc.

**Comment by mmetc** [comment]
This is pretty much ready, missing only final approval and some doc.

https://github.com/crowdsecurity/crowdsec/pull/1497
