### ISSUE TITLE
Bug/ sshd logs not parsing

### ISSUE THREAD

**Issue by amithiel** [crowdsecurity/crowdsec#1391]
Hi!

I'm not sure why some logs are not parsed! i have crowdsec on 2 servers. Ubuntu 20.04 and debian 11. I'm trying to understand the metrics, specifically the "unparsed" section.

### **Here's some samples of the debian 11 server:**

![1](https://user-images.githubusercontent.com/848214/160018152-b9edd754-cf1a-40f7-950c-fa17c0d6ab81.png)
![2](https://user-images.githubusercontent.com/848214/160018201-168d80a2-f0a8-412c-96df-058f5f93b9f3.png)

### **and the collections list:** 

![3](https://user-images.githubusercontent.com/848214/160018300-37982459-daa5-4b53-b11f-33b15b4fb0d5.png)

**### And also the config file (maybe something i did wrong here?)**

![4](https://user-images.githubusercontent.com/848214/160018555-c9c41c32-298f-416b-aad0-5e616a3d1dde.png)

### **Now for the ubuntu 20.04 server:**

![1](https://user-images.githubusercontent.com/848214/160018855-5ef378d6-d12a-4ad3-8b40-cc0b27abf686.png)

### **and the collections list:** 

![2](https://user-images.githubusercontent.com/848214/160018961-ab9bf23d-cca9-4b2a-8976-6517098ef7a8.png)

### **The config file:**

![3](https://user-images.githubusercontent.com/848214/160019137-efa8fd72-5229-46c9-9841-f6ac28b61917.png)

**Comment by buixor** [comment]
Please look at : https://doc.crowdsec.net/docs/next/faq#how-to-know-if-my-setup-is-working-correctly--some-of-my-logs-are-unparsed-is-it-normal-

As well if you believe some lines should be parsed, have a go at : https://doc.crowdsec.net/docs/next/user_guides/cscli_explain

**Comment by amithiel** [comment]
Thank you, i should have searched the obvious. cheers!
