### ISSUE TITLE
Bug/compilation issue on armhf platform

### ISSUE THREAD

**Issue by sabban** [crowdsecurity/crowdsec#1407]
Compilation on all rmhf platform is affected. I suspect that all 32 bits platforms are affected as well.

**Describe the bug**
Current build on armhf platform is currently broken on master.

**To Reproduce**
1. go build on a armhf platform

**Expected behavior**
Current build on armhf platform should work.

**Technical Information (please complete the following information):**
- architecture: armhf

**Additional context**
The build is broken due to the use of too large constant in `./cmd/crowdsec-cli/utils.go`:

```
var ranges = []unit{
    {
        value:  1e18,
        symbol: "E",
    },
    {
        value:  1e15,
        symbol: "P",
    },
    {
        value:  1e12,
        symbol: "T",
    },
    {
        value:  1e6,
        symbol: "M",
    },
    {
        value:  1e3,
        symbol: "k",
    },
    {
        value:  1,
        symbol: "",
    },
}
```
seems to be the culprit piece of code.

**Comment by mmetc** [comment]
should be fixed by https://github.com/crowdsecurity/crowdsec/pull/1419
