### ISSUE TITLE
Improvement/Add regular agent ping to LAPI

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#1411]
An agent will only contact LAPI if it needs to send an alert, but this means that the `Last update` field in `cscli machines` cannot be used reliably to check if an agent is down or not.

Add a new endpoint (available only for agents) that will record the last ping time from an agent, and have the agent query this endpoint at an interval (every minute ? longer ?).

In `cscli machines list`, display a warning if an agent ping is more than $INTERVAL+$DELTA, meaning the agent is likely dead.

**Comment by Lamera** [comment]
I like this enhancement. Probably it would be great, if it would send an alert through the configured notification channel when an agent doesn't respond.
