### ISSUE TITLE
Bug/Docker datasource does not get any logs if the container runs with `tty: true`

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#1417]
To reproduce: have a container outputting data, and point crowdsec to it.

If the container is started with `tty: true` (`-t` with `docker run`), crowdsec won't see any logs.

If the containers is started without it, crowdsec can read the logs correctly.

**Comment by vacumet** [comment]
I can verify it on my mailcow-installation. 
I removed the tty: true line from the dovecot container and after I ran **docker-compose up -d** the container appeared in the source list:
**docker:mailcowdockerized_dovecot-mailcow_1**

To bad the container doesn't work without that parameter. I had to add the parameter again for the container to work.
