### ISSUE TITLE
Bug/pfSense - APU Board

### ISSUE THREAD

**Issue by rc042** [crowdsecurity/crowdsec#1427]
Hello! 

I have a problem and I hope finding a solution with your feedbacks!

**Describe the bug**
I tried to install Crowdsec on an appliance (APU) with pfSense 2.6.0  and I have some errors.

**To Reproduce**
1. Install pfSense 2.6.0 on a APU board (eg. https://www.pcengines.ch/apu.htm)
2. Enable the FreeBSD repos
3. Install Crowdsec
4. Start the service

**Expected behavior**
Service must start

**Logs**

After enable the FreeBSD repos, the package seems to be installed correctely, however, when I start the service, I have the following errors:

```
[2.6.0-RELEASE][root@pfSense.home.arpa.jon]/root: service crowdsec onestart
Registering LAPI
WARN[06-04-2022 06:31:31 PM] can't load CAPI credentials from '/usr/local/etc/crowdsec/online_api_credentials.yaml' (missing field)
INFO[06-04-2022 06:31:31 PM] push and pull to Central API disabled
FATA[06-04-2022 06:31:31 PM] unable to generate machine id : generating machine id: open /proc/sys/kernel/random/uuid: no such file or directory
Registering CAPI
WARN[06-04-2022 06:31:31 PM] can't load CAPI credentials from '/usr/local/etc/crowdsec/online_api_credentials.yaml' (missing field)
INFO[06-04-2022 06:31:31 PM] push and pull to Central API disabled
FATA[06-04-2022 06:31:31 PM] unable to generate machine id: generating machine id: open /proc/sys/kernel/random/uuid: no such file or directory
[2.6.0-RELEASE][root@pfSense.home.arpa.jon]/root:
```

**Technical Information (please complete the following information):**
 - OS: pfSense 2.6.0
 - Hardware: APU Board

Many thanks for your support!

**Comment by AlteredCoder** [comment]
Hello, thanks for your issue. We are trying to reproduce the bug and will fix it in the next crowdsec version

**Comment by rc042** [comment]
Hello @AlteredCoder !

I did the same test on a VM and it works. The problem seems the installation on an APU board (https://pcengines.ch/apu.htm).

I ran `sysrc crowdsec_enable="YES"` for an easy service starting (`start`versus `onestart`).

`/usr/local/bin/cscli capi register` gave me the same previous error:

```
[2.6.0-RELEASE][root@pfSense.home.arpa.jon]/root: /usr/local/bin/cscli capi register
WARN[07-04-2022 08:14:43 PM] can't load CAPI credentials from '/usr/local/etc/crowdsec/online_api_credentials.yaml' (missing field)
INFO[07-04-2022 08:14:43 PM] push and pull to Central API disabled
FATA[07-04-2022 08:14:43 PM] unable to generate machine id: generating machine id: open /proc/sys/kernel/random/uuid: no such file or directory
[2.6.0-RELEASE][root@pfSense.home.arpa.jon]/root:
```

If I put valid data in `online_api_credentials.yaml`, the problem still persist (machine id issue).

Version seems fine compare to my VM:

```
[2.6.0-RELEASE][root@pfSense.home.arpa.jon]/root: cscli version
2022/04/07 20:22:01 version: v1.3.2-716251323da59f1ce04fb1fc38af0a72629b5d78
2022/04/07 20:22:01 Codename: alphaga
2022/04/07 20:22:01 BuildDate: 2022-03-28_20:20:27
2022/04/07 20:22:01 GoVersion: 1.18
2022/04/07 20:22:01 Platform: freebsd
2022/04/07 20:22:01 Constraint_parser: >= 1.0, <= 2.0
2022/04/07 20:22:01 Constraint_scenario: >= 1.0, < 3.0
2022/04/07 20:22:01 Constraint_api: v1
2022/04/07 20:22:01 Constraint_acquis: >= 1.0, < 2.0
[2.6.0-RELEASE][root@pfSense.home.arpa.jon]/root:
```

**Comment by mmetc** [comment]
Hi @rc042 

Crowdsec assumes that one of the following commands is working:

`$ cat /etc/hostid
`
`$ kenv -q smbios.system.uuid
`

The first is a regular file that even you can write; the second is an EFI hardware thingy so it may be missing on your board.

In your case, both are failing so it falls back to /proc, but it looks for a file that exists only on Linux.
I don't know the cause, but the effect is the same as this issue on opnsense: https://forum.opnsense.org/index.php?topic=7787.0

You should try `/etc/rc.d/hostid start; /etc/rc.d/hostid_save start` then register again.

Let us know, thanks

**Comment by rc042** [comment]
Hi @mmetc !

You are absolutely right!

I did `/etc/rc.d/hostid start` and `/etc/rc.d/hostid_save start` then start Crowdsec and everything works fine! I have no error anymore and `online_api_credentials.yaml` is fine.

Thanks a lot for your support!
