### ISSUE TITLE
Bug/No `warn` log level

### ISSUE THREAD

**Issue by thespad** [crowdsecurity/crowdsec#1450]
**Describe the bug**
As per https://docs.crowdsec.net/docs/configuration/crowdsec_configuration the available log levels are only `(error|info|debug|trace)`. `info` is much too noisy for normal use as it includes every remote API hit, but `error` excludes a lot of useful information that's logged with the `warning` level.

Attempting to run with a log level of `warn` or `warning` results in `trace` level logging being enabled.

**To Reproduce**
1. Set `log_level: warn` in config.yaml
2. Restart crowdsec
3. Observe logs

**Expected behavior**
If logs are being generated lagged with the `warning` level then it should be possible to configure logging to expose `warning` level events.

**Technical Information (please complete the following information):**
 - OS: Docker
 - Version v1.3.2

**Comment by buixor** [comment]
solved in 1.4.0, RC dans les bacs
