### ISSUE TITLE
Bug/FalsePositive on Nextcloud Contacts

### ISSUE THREAD

**Issue by LarsBel** [crowdsecurity/crowdsec#1451]
**Describe the bug**
When managing or downloading Nextcloud contacts(I have 100+) via Nextcloud WebGUI my IP gets banned

**To Reproduce**
Login to Nextcloud Webinterface and edit a few contacts or try to download them all

**Expected behavior**
first download succeeds, but then my IP is banned

**Screenshots/Logs**
`time="17-04-2022 01:21:16" level=info msg="(xxx/crowdsec) crowdsecurity/http-probing by ip 1.2.3.4 (Country/1234) : 4h ban on Ip 1.2.3.4"`
`time="17-04-2022 01:21:16" level=info msg="(xxx/crowdsec) crowdsecurity/http-crawl-non_statics by ip 1.2.3.4 (Country/1234) : 4h ban on Ip 1.2.3.4"`

NGINX Logs have lots of these line, so it is banned:
`1.2.3.4 - - [17/Apr/2022:20:33:59 +0200] "PROPFIND /remote.php/dav/addressbooks/users/myuser/mycontacts/F3BB1234-F3D6-3A6B44-666C-77DDCC45FG7254.vcf HTTP/2.0" 207 274270 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"`

**Technical Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version v1.3.2

**Additional context**

I created a whitelist:

`name: crowdsecurity/nextcloudcontactswhitelist`
`description: "Whitelist events from nextcloud contact access"`
`whitelist:`
`  reason: "ignore remote.php/dav/addressbooks/users/"`
`  expression:`
`    - evt.Parsed.request contains "'/remote.php/dav/addressbooks/users/'"`
``
  
which seems to solve the problem
*edit* **no, its not, I'm still get banned** */edit*

**Comment by buixor** [comment]
Hello,

Can you please provide some sample logs of the http requests that trigger the scenarios ?

Thanks !

**Comment by LaurenceJJones** [comment]
We have implemented nextcloud whitelist in the hub closing as completed
