### ISSUE TITLE
Bug/Dashboard does not keep filters

### ISSUE THREAD

**Issue by ToeiRei** [crowdsecurity/crowdsec#1452]
**Describe the bug**
As far as I know, the dashboard should have persistent filters to make our life easier. Everytime I log on I have to define my filters again as I am mostly interested what happened the last 7 days instead of the last 2 years.

**To Reproduce**
1. Go to 'app.crowdsec.net' and log in
2. Apply some filters
3. Close the browser window and reopen
4. Log back into the dashboard

**Expected behavior**
I'd expect the filters to be saved somewhere or 

**Technical Information (please complete the following information):**
 - OS: doesn't matter - tried on Windows 10, 11, Gentoo, Debian 11 in Google Chrome

**Comment by mobula9** [comment]
Hello and thank you for your feedback.

Can you tell me what filter you are talking about? (Those on the instance page or those on the alerts list?)

You would like to be able to save a filter to keep it even after closing and reopening a session. We had planned to develop this feature one day, but others are higher priority in our roadmap today. We cannot indicate a date yet, but we will let you know when this feature becomes available.

**Comment by ToeiRei** [comment]
I am talking about the ones on top of the alerts list (https://app.crowdsec.net/alerts)

Over time the alert chart grows and it just tells me the complete history of the attacks happening whereas only the recent ones are really interesting to me. On my daily checkup I usually do not care about the stuff that happened ages ago.

**Comment by mobula9** [comment]
Ah yes I see, while waiting to develop a filter registration system, what we could easily do without embarking on something too long will be to pass the default period (when we arrive on the alerts page) to last 48 hours.

**Comment by ToeiRei** [comment]
That would really help.

**Comment by LaurenceJJones** [comment]
This feedback has been moved to the internal ticketing system. Closing this ticket and will track internally
