### ISSUE TITLE
Improvement/Add more expr JSON helpers

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#1459]
We only provide a `JsonExtract` expr helper to parse JSON which returns a string, which is perfect to parse simple JSON.

But if we need to parse more complex JSON objects (for example, https://github.com/crowdsecurity/hub/pull/444), this becomes either almost impossible or incredibly complex to read the parser.

We should add more JSON helpers:
 - `JsonExtractSlice`: returns `[]interface{}`
 - `JsonExtractMap`: returns `map[interface{}]interface{}`
 - `JsonExtractObject`: returns `interface{}`

This would also require some changes on our assumption for the type of `statics`, as we currently `Fatal` if the returned value is not a string or an int (which is likely a bug as we try to return an error just after the Fatal call :)).

Alternatively, we could also support [JsonPath](https://goessner.net/articles/JsonPath/) which would enable users to precisely target a specific value with an XPath-like expression (a bit like what is done with `XMLGetNodeValue` in the windows branch)

**Comment by buixor** [comment]
I think adding the helpers, and having explicit serialization for people that want to carry non-string objects over parsing steps. (Explicit because we don't want users to abuse this feature without understanding the performance impact).

**Comment by blotus** [comment]
Done in #1576
