### ISSUE TITLE
Improvment/metrics: Rename prometheus metrics follwing prometheus best practices

### ISSUE THREAD

**Issue by erenJag** [crowdsecurity/crowdsec#147]
**Is your feature request related to a problem? Please describe.**
The current metrics name on crowdsec aren't prometheus best practices compliant ([link](https://prometheus.io/docs/practices/naming/)).

**Describe the solution you'd like**
Follow prometheus best practices to have better metrics names.

**Comment by buixor** [comment]
+ review/improve documentation
