### ISSUE TITLE
Improvement/Allow Notification System to log alert to flat file or journald

### ISSUE THREAD

**Issue by Sachiru** [crowdsecurity/crowdsec#1471]
**Is your feature request related to a problem? Please describe.**
This feature request allows for historical logging and log aggregation of actions taken by Crowdsec.

**Describe the solution you'd like**
Allow notification system to log alerts to flat files on local storage or to journald. Actions logged to flat files can then be picked up by logging agents (Fluentd/Zabbix agent/Logstash) and forwarded to log aggregators for historical analysis.

**Comment by LaurenceJJones** [comment]
User has created https://github.com/zbalkan/notification-file for logging to flat file.

**Comment by LaurenceJJones** [comment]
Please note that file plugin is now included as a standard plugin, classing the issue as resolved.
