### ISSUE TITLE
Bug/ Write i/o stats are way too high (13 GB in 5 days for only a few calls per day)

### ISSUE THREAD

**Issue by grasshide** [crowdsecurity/crowdsec#1476]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4366857/164913040-8e2aea84-564b-4e95-98da-b61810e97331.png)
Im worried about my SSD.

**To Reproduce**
Install crowdsec on debian bullseye via docker and watch the stats.
I use the following bouncer cotainer with traefik: fbonalair/traefik-crowdsec-bouncer.

**Expected behavior**
much less i/o.

**Screenshots**
see above.

**Technical Information (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Docker version 20.10.14, build a224086

**Additional context**
The i/o grows even as I write this article for about 500 MB.

**Comment by buixor** [comment]
Hello,

Thanks for the issue ! Would you be able to provide more context so we can look into this ?

 - is the I/O caused by crowdsec or the bouncer ?
 - what are the log file size ?
 - how big is crowdsec's database ?
 - can you share your config.yaml if it's not a stock config
 - what tool did you use to collect the stats ?

Please let us know :)

**Comment by grasshide** [comment]
Sure :)

> * is the I/O caused by crowdsec or the bouncer ?
It is caused by crowdsec. The screenshot is from the crowdsec docker container.
Yesterday I disabled the bouncer completely and already got another 1 GB i/o since then.

> * what are the log file size ?
I don't parse any logs/ no logs are mounted in the container.
I just started using crowdsec and wanted to leverage the crowd-collected malicious IP's in a first attempt.

> * how big is crowdsec's database ?
5,4M crowdsec.db

> * can you share your config.yaml if it's not a stock config
It is the stock config

> * what tool did you use to collect the stats ?
None. I currently use the cli to see how crowdsec is doing.

**Comment by blotus** [comment]
Hello,

That's really weird, if you haven't configured anything, the only writes crowdsec should perform are when the IPs are pulled from CAPI (to update the database) or when the bouncer queries LAPI (for the access logs mostly).

Regarding the metrics, we meant which tool provided you with the graphs ? (cscli does not know how to graph anything, and it would definitely not be that pretty :) and the metrics endpoint does not give anything related to the I/O as far as I can tell).

Do you see anything in crowdsec logs ? (so in your case `docker logs ....`)

**Comment by LaurenceJJones** [comment]
Hey! Going through open issues, how are you getting along with this? on the latest version are you seeing the same figures?

**Comment by grasshide** [comment]
Ran another test. It's still the same with the most current docker image.
With over 5 GB I/O for almost no traffic (not even 4MB total on the network side of the container), there is certainly something very wrong.

![image](https://user-images.githubusercontent.com/4366857/199953909-90d2086b-9c5d-4697-bd0c-a448f14f8373.png)

![image](https://user-images.githubusercontent.com/4366857/199954025-f3513288-289c-4953-90ce-be03c3339344.png)

docker-compose:
`  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors
      - GID=1000
    depends_on:
      - traefik
    volumes:
      - ./crowdsec/db:/var/lib/crowdsec/data
      - ./crowdsec/config:/etc/crowdsec/
      - ./traefik/logs:/var/log/traefik/:ro
    security_opt:
      - no-new-privileges=true
    networks:
      - traefik

  crowdsec-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer
    container_name: crowdsec-bouncer
    environment:
      CROWDSEC_BOUNCER_API_KEY: e5e6...1463
      CROWDSEC_AGENT_HOST: crowdsec:8080
      GIN_MODE: release
    networks:
      - traefik`

**Comment by LaurenceJJones** [comment]
Even though you only see 4mb on eth0, the bouncer communication wont happen on this network. What are the stats within the docker network? cause the traefik bouncer queries per request and there is no cache from what I know.

**Comment by LaurenceJJones** [comment]
So tried to get a test environment up and running without portainer, then going to try a stack within portainer.
10 min nikto scanning
![image](https://user-images.githubusercontent.com/23139695/199973358-d611205c-cd99-4021-9ce0-811f2a458ab7.png)

**Comment by grasshide** [comment]
Let it run for a day. It did not immediately go up for me either.

Am Fr., 4. Nov. 2022 um 13:32 Uhr schrieb Laurence Jones <
***@***.***>:

**Comment by LaurenceJJones** [comment]
👍🏻 Okay, I am leaving my environment to run with a scan every 5 mins to make it more like a live environment

**Comment by LaurenceJJones** [comment]
So ran it since last spoke.
Browser crashed but here the stats
![image](https://user-images.githubusercontent.com/23139695/200088586-c5c84776-9ce3-471e-a9ff-0d9961573cd1.png)
![image](https://user-images.githubusercontent.com/23139695/200088602-dc8329c7-0697-481b-bcf6-04020165a47c.png)
However I can explain the read operations on the latter picture. I was running `watch -n 15 docker exec <id> cscli decisions list`. Running this makes cscli read all configuration files so running this every 15 seconds would make it climb.

**Comment by grasshide** [comment]
So I ran it again. This time only for one hour. I did not even start the bouncer container. So the crowdsec container got no requests at all.

![image](https://user-images.githubusercontent.com/4366857/200116460-fa7a3c2a-5b4c-4371-9b33-c815ee17ba20.png)

`cat acquis.yaml
filenames:
  - /var/log/traefik/*
labels:
  type: traefik
---
filenames:
 - /var/log/auth.log
 - /var/log/syslog
labels:
  type: syslog`


`cat config.yaml  
common:
  daemonize: false
  pid_dir: /var/run/
  log_media: stdout
  log_level: info
  log_dir: /var/log/
  working_dir: .
config_paths:
  config_dir: /etc/crowdsec/
  data_dir: /var/lib/crowdsec/data/
  simulation_path: /etc/crowdsec/simulation.yaml
  hub_dir: /etc/crowdsec/hub/
  index_path: /etc/crowdsec/hub/.index.json
  notification_dir: /etc/crowdsec/notifications/
  plugin_dir: /usr/local/lib/crowdsec/plugins/
crowdsec_service:
  acquisition_path: /etc/crowdsec/acquis.yaml
  parser_routines: 1
plugin_config:
  user: nobody
  group: nobody
cscli:
  output: human
db_config:
  log_level: info
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db
  #user:
  #password:
  #db_name:
  #host:
  #port:
  flush:
    max_items: 5000
    max_age: 7d
api:
  client:
    insecure_skip_verify: false
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 0.0.0.0:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    online_client: # Central API credentials (to push signals and receive bad IPs)
      credentials_path: /etc/crowdsec/online_api_credentials.yaml
    #credentials_path: /etc/crowdsec/online_api_credentials.yaml
#    tls:
#      cert_file: /etc/crowdsec/ssl/cert.pem
#      key_file: /etc/crowdsec/ssl/key.pem
prometheus:
  enabled: true
  level: full
  listen_addr: 0.0.0.0
  listen_port: 6060`

The only thing strange to me is the prometheus config. I don't runn any prometheus on my system. That came with the default config.

**Comment by grasshide** [comment]
Just saw this spike while leaving the monitor running:

![image](https://user-images.githubusercontent.com/4366857/200119606-51159e4a-a5a8-4d1d-8eef-8b23c5675482.png)

Currently still nothing connected. No bouncer, no monitoring, nothing.

**Comment by LaurenceJJones** [comment]
So with the timestamps, it is the community blocklist. However it list shouldn't be this big. How many scenarios do you have installed?
```
cscli scenarios list
```

**Comment by LaurenceJJones** [comment]
Closing due to stale, in version 1.5 we have some IO improvements in the form of file acquisition. Re reading over the issue this should have no effect.
