### ISSUE TITLE
Bug Crowsec does not block IP with IPTABLES

### ISSUE THREAD

**Issue by bartounet16** [crowdsecurity/crowdsec#1479]
Hello.
I have installed crowdsec in Debian
It detect SSH attach and says ban but does not create ipables rules ...

`# cscli bouncers list
------------------------------------------------------------------------------------
 NAME                        IP ADDRESS  VALID  LAST API PULL         TYPE  VERSION 
------------------------------------------------------------------------------------
 FirewallBouncer-1650891152              ✔️      2022-04-25T12:52:32Z                
------------------------------------------------------------------------------------
`
`# cscli decisions list
+-------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+
|  ID   |  SOURCE  |    SCOPE:VALUE     |          REASON           | ACTION | COUNTRY |               AS               | EVENTS |     EXPIRATION     | ALERT ID |
+-------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+
| 13301 | crowdsec | Ip:153.34.238.67   | crowdsecurity/ssh-bf      | ban    | CN      | 4837 CHINA UNICOM China169     |      6 | 3h58m38.32836517s  |       11 |
|       |          |                    |                           |        |         | Backbone                       |        |                    |          |
|     9 | crowdsec | Ip:195.122.226.164 | crowdsecurity/ssh-slow-bf | ban    | RU      | 8580 MTS PJSC                  |     19 | 3h47m8.780944499s  |        9 |
|     8 | crowdsec | Ip:157.230.98.148  | crowdsecurity/ssh-slow-bf | ban    | DE      | 14061 DIGITALOCEAN-ASN         |     17 | 3h43m6.992929346s  |        8 |
|     4 | crowdsec | Ip:176.111.173.242 | crowdsecurity/ssh-slow-bf | ban    | EE      | 213010 GigaHostingServices OU  |     11 | 3h29m24.845633943s |        4 |
+-------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+

`

`root@pror:~#  iptables -L             
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
 `

**Comment by bartounet16** [comment]
`time="25-04-2022 14:52:36" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="25-04-2022 15:10:56" level=info msg="backend type : iptables"
time="25-04-2022 15:10:56" level=info msg="iptables for ipv4 initiated"
time="25-04-2022 15:10:56" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:10:56" level=info msg="ipset 'crowdsec-blacklists' doesn't exist, skip"
time="25-04-2022 15:10:56" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="25-04-2022 15:10:56" level=info msg="Checking existing set"
time="25-04-2022 15:10:56" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec-blacklists nethash timeout 300"
time="25-04-2022 15:10:57" level=info msg="Rule doesn't exist (/usr/sbin/iptables -C INPUT -m set --match-set crowdsec-blacklists src -j DROP)"
time="25-04-2022 15:10:57" level=info msg="iptables set-up : /usr/sbin/iptables -I INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:10:57" level=info msg="iptables for ipv6 initiated"
time="25-04-2022 15:10:57" level=info msg="iptables clean-up : /usr/sbin/ip6tables -D INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:10:57" level=info msg="ipset 'crowdsec6-blacklists' doesn't exist, skip"
time="25-04-2022 15:10:57" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="25-04-2022 15:10:57" level=info msg="Checking existing set"
time="25-04-2022 15:10:57" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec6-blacklists nethash timeout 300 family inet6"
time="25-04-2022 15:10:58" level=warning msg="iptables check command (/usr/sbin/ip6tables -C INPUT -m set --match-set crowdsec6-blacklists src -j DROP) failed : exit status 1"
time="25-04-2022 15:10:58" level=info msg="iptables set-up : /usr/sbin/ip6tables -I INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:10:58" level=info msg="Processing new and deleted decisions . . ."
time="25-04-2022 15:10:58" level=error msg="API error: access forbidden"
time="25-04-2022 15:10:58" level=error msg="terminating bouncer process"
time="25-04-2022 15:10:58" level=error msg="process return with error: stream api init failed"
time="25-04-2022 15:10:58" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:10:58" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="25-04-2022 15:10:58" level=info msg="iptables clean-up : /usr/sbin/ip6tables -D INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:10:58" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="25-04-2022 15:11:38" level=info msg="backend type : iptables"
time="25-04-2022 15:11:38" level=info msg="iptables for ipv4 initiated"
time="25-04-2022 15:11:38" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:11:38" level=info msg="ipset 'crowdsec-blacklists' doesn't exist, skip"
time="25-04-2022 15:11:38" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="25-04-2022 15:11:38" level=info msg="Checking existing set"
time="25-04-2022 15:11:38" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec-blacklists nethash timeout 300"
time="25-04-2022 15:11:39" level=info msg="Rule doesn't exist (/usr/sbin/iptables -C INPUT -m set --match-set crowdsec-blacklists src -j DROP)"
time="25-04-2022 15:11:39" level=info msg="iptables set-up : /usr/sbin/iptables -I INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:11:39" level=info msg="iptables for ipv6 initiated"
time="25-04-2022 15:11:39" level=info msg="iptables clean-up : /usr/sbin/ip6tables -D INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:11:39" level=info msg="ipset 'crowdsec6-blacklists' doesn't exist, skip"
time="25-04-2022 15:11:39" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="25-04-2022 15:11:39" level=info msg="Checking existing set"
time="25-04-2022 15:11:39" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec6-blacklists nethash timeout 300 family inet6"
time="25-04-2022 15:11:40" level=warning msg="iptables check command (/usr/sbin/ip6tables -C INPUT -m set --match-set crowdsec6-blacklists src -j DROP) failed : exit status 1"
time="25-04-2022 15:11:40" level=info msg="iptables set-up : /usr/sbin/ip6tables -I INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:11:40" level=info msg="Processing new and deleted decisions . . ."
time="25-04-2022 15:11:40" level=error msg="API error: access forbidden"
time="25-04-2022 15:11:40" level=error msg="terminating bouncer process"
time="25-04-2022 15:11:40" level=error msg="process return with error: stream api init failed"
time="25-04-2022 15:11:40" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:11:40" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="25-04-2022 15:11:40" level=info msg="iptables clean-up : /usr/sbin/ip6tables -D INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:11:40" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="25-04-2022 15:25:31" level=info msg="backend type : iptables"
time="25-04-2022 15:25:31" level=info msg="iptables for ipv4 initiated"
time="25-04-2022 15:25:31" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:25:31" level=info msg="ipset 'crowdsec-blacklists' doesn't exist, skip"
time="25-04-2022 15:25:31" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="25-04-2022 15:25:31" level=info msg="Checking existing set"
time="25-04-2022 15:25:31" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec-blacklists nethash timeout 300"
time="25-04-2022 15:25:32" level=info msg="Rule doesn't exist (/usr/sbin/iptables -C INPUT -m set --match-set crowdsec-blacklists src -j DROP)"
time="25-04-2022 15:25:32" level=info msg="iptables set-up : /usr/sbin/iptables -I INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:25:32" level=info msg="iptables for ipv6 initiated"
time="25-04-2022 15:25:32" level=info msg="iptables clean-up : /usr/sbin/ip6tables -D INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:25:32" level=info msg="ipset 'crowdsec6-blacklists' doesn't exist, skip"
time="25-04-2022 15:25:32" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="25-04-2022 15:25:33" level=info msg="Checking existing set"
time="25-04-2022 15:25:33" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec6-blacklists nethash timeout 300 family inet6"
time="25-04-2022 15:25:34" level=warning msg="iptables check command (/usr/sbin/ip6tables -C INPUT -m set --match-set crowdsec6-blacklists src -j DROP) failed : exit status 1"
time="25-04-2022 15:25:34" level=info msg="iptables set-up : /usr/sbin/ip6tables -I INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:25:34" level=info msg="Processing new and deleted decisions . . ."
time="25-04-2022 15:25:34" level=error msg="API error: access forbidden"
time="25-04-2022 15:25:34" level=error msg="terminating bouncer process"
time="25-04-2022 15:25:34" level=error msg="process return with error: stream api init failed"
time="25-04-2022 15:25:34" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="25-04-2022 15:25:34" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="25-04-2022 15:25:34" level=info msg="iptables clean-up : /usr/sbin/ip6tables -D INPUT -m set --match-set crowdsec6-blacklists src -j DROP"
time="25-04-2022 15:25:34" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
`

**Comment by bartounet16** [comment]
if i grep on errors
`tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:22" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:22" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=false\": dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:32" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:32" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=false\": dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:42" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:42" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=false\": dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:52" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:48:52" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=false\": dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:49:02" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:49:02" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=false\": dial tcp 127.0.0.1:8080: connect: connection refused"
time="25-04-2022 14:49:12" level=error msg="API error: access forbidden"
time="25-04-2022 14:49:22" level=error msg="API error: access forbidden"
time="25-04-2022 14:49:32" level=error msg="API error: access forbidden"
time="25-04-2022 14:49:42" level=error msg="API error: access forbidden"
time="25-04-2022 14:49:52" level=error msg="API error: access forbidden"
time="25-04-2022 14:50:02" level=error msg="API error: access forbidden"
time="25-04-2022 14:50:12" level=error msg="API error: access forbidden"
time="25-04-2022 14:50:22" level=error msg="API error: access forbidden"
time="25-04-2022 14:50:32" level=error msg="API error: access forbidden"
time="25-04-2022 14:50:42" level=error msg="API error: access forbidden"
time="25-04-2022 14:50:52" level=error msg="API error: access forbidden"
time="25-04-2022 14:51:02" level=error msg="API error: access forbidden"
time="25-04-2022 14:51:12" level=error msg="API error: access forbidden"
time="25-04-2022 14:51:22" level=error msg="API error: access forbidden"
time="25-04-2022 14:51:32" level=error msg="API error: access forbidden"
time="25-04-2022 14:51:42" level=error msg="API error: access forbidden"
time="25-04-2022 14:51:52" level=error msg="API error: access forbidden"
time="25-04-2022 14:52:02" level=error msg="API error: access forbidden"
time="25-04-2022 14:52:12" level=error msg="API error: access forbidden"
time="25-04-2022 14:52:36" level=error msg="API error: access forbidden"
time="25-04-2022 14:52:36" level=error msg="terminating bouncer process"
time="25-04-2022 14:52:36" level=error msg="process return with error: stream api init failed"
time="25-04-2022 15:10:58" level=error msg="API error: access forbidden"
time="25-04-2022 15:10:58" level=error msg="terminating bouncer process"
time="25-04-2022 15:10:58" level=error msg="process return with error: stream api init failed"
time="25-04-2022 15:11:40" level=error msg="API error: access forbidden"
time="25-04-2022 15:11:40" level=error msg="terminating bouncer process"
time="25-04-2022 15:11:40" level=error msg="process return with error: stream api init failed"
time="25-04-2022 15:25:34" level=error msg="API error: access forbidden"
time="25-04-2022 15:25:34" level=error msg="terminating bouncer process"
time="25-04-2022 15:25:34" level=error msg="process return with error: stream api init failed"
`

**Comment by AlteredCoder** [comment]
Hello, from the logs, it seems that the bouncer receive a `403` reponse code from the local API (`API error: access forbidden`).

After registering your bouncer, did you set the API key in the bouncer configuration file ?

**Comment by bartounet16** [comment]
Hello.
No i have follow install tutorial, there was no API advise ...
how can i do this ?

**Comment by AlteredCoder** [comment]
during the installation of the bouncer, it should have generated the api key automatically.
Here are the step
- run `cscli bouncers add <your_bouncer_name>` on the crowdsec machine and keep the api key.
- in `/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml`, set the API key.
- restart the bouncer: `sudo systemctl restart crowdsec-firewall-bouncer`

**Comment by bartounet16** [comment]
i don't understand
bouncer is already activate ..

root@promox-info16-fr:~# cscli bouncers list
------------------------------------------------------------------------------------
 NAME                        IP ADDRESS  VALID  LAST API PULL         TYPE  VERSION
------------------------------------------------------------------------------------
 FirewallBouncer-1650891152              ✔️      2022-04-25T12:52:32Z
------------------------------------------------------------------------------------

**Comment by bartounet16** [comment]
now i have 
`time="25-04-2022 17:54:43" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=true\": dial tcp 127.0.0.1:8080: connect: connection refused"
`

**Comment by AlteredCoder** [comment]
Does the crowdsec local API run in the same host ? and does it listen on the port `8080` ?

**Comment by bartounet16** [comment]
I have uninstall and réinstall crowdsec

apt remove crowdsec-firewall-bouncer-iptables --purge
apt remove crowdsec --purge
apt install crowdsec
apt install crowdsec-firewall-bouncer-iptables

Seems to work
`# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             match-set crowdsec-blacklists src

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
`

**Comment by bartounet16** [comment]
yes it is surprising...
after uninstall et reinstall crowdsec + bouncer (the bouncer is activated by default whith API after réinstall)
I see the rule in IPTABLE 

`# cscli decisions list     
+------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+
|  ID  |  SOURCE  |    SCOPE:VALUE     |          REASON           | ACTION | COUNTRY |               AS               | EVENTS |     EXPIRATION     | ALERT ID |
+------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+--------------------+----------+
| 8665 | crowdsec | Ip:51.250.96.113   | crowdsecurity/ssh-slow-bf | ban    | RU      | 200350 Yandex.Cloud LLC        |     19 | 3h18m49.539495212s |       26 |
|   24 | crowdsec | Ip:120.48.6.169    | crowdsecurity/ssh-slow-bf | ban    | CN      | 38365 Beijing Baidu Netcom     |     18 | 2h56m36.281517711s |       24 |
|      |          |                    |                           |        |         | Science and Technology Co.,    |        |                    |          |
|      |          |                    |                           |        |         | Ltd.                           |        |                    |          |
|   23 | crowdsec | Ip:209.97.163.142  | crowdsecurity/ssh-slow-bf | ban    | SG      | 14061 DIGITALOCEAN-ASN         |     19 | 2h53m13.580287319s |       23 |
|   22 | crowdsec | Ip:117.50.88.114   | crowdsecurity/ssh-slow-bf | ban    | CN      | 9808 China Mobile              |     17 | 2h48m25.463019356s |       22 |
|      |          |                    |                           |        |         | Communications Group Co., Ltd. |        |                    |          |
|   21 | crowdsec | Ip:52.172.168.56   | crowdsecurity/ssh-slow-bf | ban    | IN      |                           8075 |     15 | 2h44m54.095628804s |       21 |
|      |          |                    |                           |        |         | MICROSOFT-CORP-MSN-AS-BLOCK    |        |                    |          |
|   20 | crowdsec | Ip:43.134.208.132  | crowdsecurity/ssh-slow-bf | ban    | HK      | 132203 Tencent Building,       |     21 | 2h24m59.856956238s |       20 |
|      |          |                    |                           |        |         | Kejizhongyi Avenue             |        |                    |          |
|   19 | crowdsec | Ip:163.172.61.214  | crowdsecurity/ssh-slow-bf | ban    | FR      | 12876 Online S.a.s.            |     23 | 2h17m19.750064609s |       19 |
|   18 | crowdsec | Ip:45.9.20.25      | crowdsecurity/ssh-bf      | ban    | RU      | 60930 Intem LLC                |      7 | 2h13m49.879721009s |       18 |
|   17 | crowdsec | Ip:159.203.177.45  | crowdsecurity/ssh-slow-bf | ban    | US      | 14061 DIGITALOCEAN-ASN         |     17 | 2h12m9.329648831s  |       17 |
|   16 | crowdsec | Ip:180.76.156.234  | crowdsecurity/ssh-slow-bf | ban    | CN      | 38365 Beijing Baidu Netcom     |     22 | 2h11m34.475748233s |       16 |
|      |          |                    |                           |        |         | Science and Technology Co.,    |        |                    |          |
|      |          |                    |                           |        |         | Ltd.                           |        |                    |          |
|   15 | crowdsec | Ip:43.154.51.166   | crowdsecurity/ssh-slow-bf | ban    | HK      | 132203 Tencent Building,       |     21 | 2h8m59.521077139s  |       15 |
|      |          |                    |                           |        |         | Kejizhongyi Avenue             |        |                    |          |
|   14 | crowdsec | Ip:111.220.139.23  | crowdsecurity/ssh-slow-bf | ban    | AU      | 9443 Vocus Retail              |     13 | 2h2m0.023521538s   |       14 |
|   13 | crowdsec | Ip:104.154.33.7    | crowdsecurity/ssh-slow-bf | ban    | US      | 15169 GOOGLE                   |     13 | 2h1m51.997900138s  |       13 |
|   12 | crowdsec | Ip:103.133.36.2    | crowdsecurity/ssh-slow-bf | ban    | ID      | 45325 PT PC24 Telekomunikasi   |     22 | 1h54m25.42055455s  |       12 |
|      |          |                    |                           |        |         | Indonesia                      |        |                    |          |
|   11 | crowdsec | Ip:43.134.81.66    | crowdsecurity/ssh-slow-bf | ban    | SG      | 132203 Tencent Building,       |     19 | 1h53m36.52333539s  |       11 |
|      |          |                    |                           |        |         | Kejizhongyi Avenue             |        |                    |          |
|   10 | crowdsec | Ip:125.212.203.113 | crowdsecurity/ssh-slow-bf | ban    | VN      | 38731 CHT Compamy Ltd          |     16 | 1h47m10.372810024s |       10 |
|    9 | crowdsec | Ip:138.68.230.183  | crowdsecurity/ssh-slow-bf | ban    | US      | 14061 DIGITALOCEAN-ASN         |     13 | 1h45m36.338635621s |        9 |
|    8 | crowdsec | Ip:115.77.187.194  | crowdsecurity/ssh-slow-bf | ban    | VN      | 7552 Viettel Group             |     23 | 1h45m5.49625572s   |        8 |
|    7 | crowdsec | Ip:43.154.177.238  | crowdsecurity/ssh-slow-bf | ban    | HK      | 132203 Tencent Building,       |     21 | 1h44m26.126369115s |        7 |
|      |          |                    |                           |        |         | Kejizhongyi Avenue             |        |                    |          |
|    6 | crowdsec | Ip:84.57.195.134   | crowdsecurity/ssh-slow-bf | ban    | DE      | 3209 Vodafone GmbH             |     50 | 1h44m1.552247105s  |        6 |
|    5 | crowdsec | Ip:143.198.53.72   | crowdsecurity/ssh-slow-bf | ban    | US      | 14061 DIGITALOCEAN-ASN         |     16 | 1h40m45.713202173s |        5 |
|    4 | crowdsec | Ip:93.151.156.231  | crowdsecurity/ssh-bf      | ban    | IT      | 30722 Vodafone Italia S.p.A.   |      6 | 1h40m16.373820964s |        4 |
|    3 | crowdsec | Ip:103.136.40.17   | crowdsecurity/ssh-slow-bf | ban    | NL      | 139884 Apeiron Global Pvt.     |     19 | 1h11m52.749163959s |        3 |
|      |          |                    |                           |        |         | Ltd.                           |        |                    |          |
|    2 | crowdsec | Ip:161.35.196.203  | crowdsecurity/ssh-slow-bf | ban    | DE      | 14061 DIGITALOCEAN-ASN         |     18 | 1h11m9.17075217s   |        2 |
|    1 | crowdsec | Ip:143.198.105.150 | crowdsecurity/ssh-slow-bf | ban    | US      | 14061 DIGITALOCEAN-ASN         |     16 | 1h9m28.741931785s  |        1 |
`

`# iptables -L              
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             match-set crowdsec-blacklists src

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination`

**Comment by AlteredCoder** [comment]
Maybe something went wrong during the installation. I close this since its solved.
