### ISSUE TITLE
Bug/cscli Simulated decisions

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/crowdsec#1480]
**Describe the bug**
When displaying decisions with the flag "--no-simu" there are sometimes also simulated decisions being displayed.

**To Reproduce**
1. cscli decisions list --no-simu

**Expected behavior**
There should be only actively banned decisions.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19840658/165275668-3a719409-916f-4d77-8e29-adbc59b8e318.png)

**Technical Information (please complete the following information):**
 - OS: Debian 10 (Buster)
 - Version: v1.3.3-debian-pragmatic-1bd8cc79c891bd5a3e343d01dd807b58b85936ce

**Comment by AlteredCoder** [comment]
Hello, i don't manage to reproduce the bug.
Can you show me your `cscli alerts list` when this problem occur please?
Also: 
- is it a multi server setup ? 
- Can you paste your profiles.yaml file if you have customized it please

**Comment by Lamera** [comment]
@AlteredCoder Can I reach out to you on discord? What's your name on discord?
