### ISSUE TITLE
Why there is not  `crowdsec-release-static.tgz` for the latest(v1.3.4)

### ISSUE THREAD

**Issue by CberYellowstone** [crowdsecurity/crowdsec#1498]
I'm using Centos7.9, and when I came across with this:
```
/root/Temp/crowdsec-v1.3.4/tests/cscli: /lib64/libc.so.6: version GLIBC_2.28' not found (required by /root/Temp/crowdsec-v1.3.4/tests/cscli)
```
I found this issue #733, from that, it told me to use the package `crowdsec-release-static.tgz` 
but the only I could find is there is no a `crowdsec-release-static.tgz` for `v1.3.4`, while the `v1.3.4-rc2` has it.
how should i do?

**Comment by CberYellowstone** [comment]
by the way, `crowdsec-release-static.tgz` of `v1.3.4-rc2` also not suit for me.
```
[root@localhost crowdsec-v1.3.4-rc2]# /usr/local/bin/cscli
/usr/local/bin/cscli: /lib64/libc.so.6: version GLIBC_2.28' not found (required by /usr/local/bin/cscli)
```

**Comment by sabban** [comment]
The crowdsec-release-static.tgz is there again for 1.3.4. Is this a fit for you ?

By the way there're some packages available at packagecloud.io (https://docs.crowdsec.net/docs/getting_started/install_crowdsec)

**Comment by CberYellowstone** [comment]
> The crowdsec-release-static.tgz is there again for 1.3.4. Is this a fit for you ?
> 
> By the way there're some packages available at packagecloud.io (https://docs.crowdsec.net/docs/getting_started/install_crowdsec)

now I use the crowdsec-release-static.tgz and it works.
by the way, I think the package on packagecloud.io were also not suitable for me.

**Comment by sabban** [comment]
> now I use the crowdsec-release-static.tgz and it works. by the way, I think the package on packagecloud.io were also not suitable for me.

Can you be a bit more specific about this ? We want to make this way the easiest way to install crowdsec so, we want to deal with all issue that would prevent users to use this.
