### ISSUE TITLE
Bug/cscli - yaml: unmarshal errors

### ISSUE THREAD

**Issue by zorions** [crowdsecurity/crowdsec#1499]
Hello,

**Describe the bug**

After upgrading from 1.3.2 to 1.3.4 my "cscsli" commands no longer work. I get the following error on every launch. I looked in the github or the documentation but didn't find a similar bug.

No log is present in the crowdsec file in the "var" folder. Crowdsec's operation doesn't seem to be disrupted as I'm still getting bans. It's quite strange.

_`"FATA[01-05-2022 06:38:51 PM] yaml: unmarshal errors: line 51: field trusted_ips not found in type csconfig.LocalApiServerCfg"`_

Are you aware of this issue please? It may be an error on my part.

**To Reproduce**
1. Upgrade version 1.3.2 to 1.3.4 with package debian

**Technical Information (please complete the following information):**
 - OS: Debian 11
 - Version : 1.3.4

![image](https://user-images.githubusercontent.com/104729783/166155765-733c0ed9-b587-4c01-9c04-e85f63055a12.png)

**Comment by AlteredCoder** [comment]
Hello @zorions ,

It looks like your cscli has not the latest version.
Can you please paste the output of `crowdsec -version` and `cscli version` please?

**Comment by zorions** [comment]
Hello @AlteredCoder,

here is the requested screenshot.

![image](https://user-images.githubusercontent.com/104729783/166234758-8c329ce7-5c67-4d83-9889-63671f54344d.png)

**Comment by zorions** [comment]
Hi,

Here is the requested screenshot. Is it this ?

![image](https://user-images.githubusercontent.com/104729783/166518505-6bceb3df-0ca9-4cc3-99d2-be648165543a.png)

**Comment by AlteredCoder** [comment]
Hello,

First this is an issue that cscli need to load the configuration to print the version.
To debug the problem, can you remove the `trusted_ips` option in your configuration and rerun `cscli version` please?

**Comment by zorions** [comment]
Hi,
I reinstalled version 1.3.4 and everything works correctly again. If the problem will come back to you. Thanks for the help provided.
