### ISSUE TITLE
Improvement/Escalating Bans

### ISSUE THREAD

**Issue by thespad** [crowdsecurity/crowdsec#1500]
**Is your feature request related to a problem? Please describe.**
Having a fixed ban time means that persistently malicious hosts fall into a (by default 4 hour) cycle of getting banned, ban expiring, host gets banned again, etc.

**Describe the solution you'd like**
Similar to fail2ban, crowdsec should support escalating bans, where if an address triggers a decision within X time of a previous one, the duration is increased, cumulatively up to a configurable maximum. For each Y time after a ban expires that the host doesn't trigger another decision the potential duration is reduced, down to the default.

**Describe alternatives you've considered** (Optional) 
I've attempted to create this via creative use of profiles but without success - it may just be my limited ability with go filter syntax.

**Example of what you imagine**
Host 1.1.1.1 is compromised and starts attacking my network. Crowdsec triggers a ban decision for 4 hours. After 4 hours the host immediately resumes its attacks and crowdsec this time bans it for 8 hours, then 16 hours. During this ban the host ceases its malicious activity. 12 hours after the ban expires the potential ban duration for that host drops back to 8 hours. After a further 12 hours it returns to the default 4 hours 

**Additional context**

**Comment by rwjack** [comment]
I'm looking for a way to just straight up ban IP's forever if they're suspect, but I can't understand how to get the --duration parameter to accept a format other than 1h, 2h, 999h (hours)

**Comment by thespad** [comment]
It's something I've mentioned to the devs but as it stands you can only ban for discrete amounts of time and not indefinitely.

**Comment by rwjack** [comment]
I mean this is a level of control we absolutely need. Crowdsec isn't and shouldn't be an iPhone, in a way that it's limited so a user "can't break" it. 

If a person (well a sysadmin basically) decides to use an application such as crowdsec, they probably know what they're doing, and a time format limitation shouldn't really be a thing.

**Comment by rwjack** [comment]
Wow, an even stupider thing happened today. So after I banned an IP for a year. The IP still kept probing my server ignoring the 403's, and then crowdsec decided to overwrite my manual ban with an automatic 4 hour one.

I mean it's not like I have an alternative, this is a pretty cool piece of software but god damn this is a dumb issue.

**Comment by buixor** [comment]
@rwjack Hello,

Yes there is currently no way to do an infinite ban, while we're looking into it, it's not our highest priority unfortunately.
However, this :

> and then crowdsec decided to overwrite my manual ban with an automatic 4 hour one.

is not something likely to happen, as there is no "overwriting" of decisions afaik. However, `cscli decisions lists` output might be misleading, because it's always going to show you the "latest" decisions, not necessarily the "longest" one !

I'll keep the issue open until we find a proper way to solve this,

**Comment by legiorange** [comment]
mypc:~# cscli decisions list
+---------+--------+--------------------+----------------+--------+---------+----+--------+-------------------------+----------+
|   ID    | SOURCE |    SCOPE:VALUE     |     REASON     | ACTION | COUNTRY | AS | EVENTS |       EXPIRATION        | ALERT ID |
+---------+--------+--------------------+----------------+--------+---------+----+--------+-------------------------+----------+
| 7191006 | cscli  | Ip:?.?.?.89  | web bruteforce | ban    |         |    |      1 | 999998h59m49.416657586s |    94811 |


when ?.?.?.89 attack again,this happened:

+---------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+-------------------------+----------+
|   ID    |  SOURCE  |    SCOPE:VALUE     |          REASON           | ACTION | COUNTRY |               AS               | EVENTS |       EXPIRATION        | ALERT ID |
+---------+----------+--------------------+---------------------------+--------+---------+--------------------------------+--------+-------------------------+----------+
| 7191007 | crowdsec | Ip:?.?.?.89  | crowdsecurity/ssh-slow-bf | ban    | HK      | 132203 Tencent Building,       |     13 | 3h59m33.92221427s       |    94812 |
|

It look like ban again.

**Comment by LaurenceJJones** [comment]
The original issue was solve with [this](https://docs.crowdsec.net/docs/next/profiles/format#duration_expr). Closing due to this, if other thread is outstanding please open a new issue.
