### ISSUE TITLE
Bug/cscli: cscli version need to unmarshall configuration

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#1504]
`cscli` should not need to unmarshall configuration to print its version.
If a user has a problem with its configuration, he can't get the cscli version.

cf. https://github.com/crowdsecurity/crowdsec/issues/1499

**Comment by AlteredCoder** [comment]
I didn't manage to reproduce and i don't think it is a bug in the latest version.

**Comment by LaurenceJJones** [comment]
Context line 156 protects against this https://github.com/crowdsecurity/crowdsec/blob/5f2797c83ccec84368b03abe32c2aa0449aff9c3/cmd/crowdsec-cli/main.go#L156
