### ISSUE TITLE
Crowdsec crashed because syslog was likely not in correct format

### ISSUE THREAD

**Issue by priyankub** [crowdsecurity/crowdsec#1505]
Please, start your issue name (after `Bug`) with the component name impacted by this feature request and a small description of the Bug. Example: `Bug/cscli: issue with ....` and remove this line :)

**Describe the bug**
I just enabled my syslog server, and started streaming logs from my UDM Pro - Unifi Gateway.
**To Reproduce**
1. acquis.yaml:
`
source: syslog
listen_addr: 0.0.0.0
listen_port: 4242
labels:
  type: syslog
`
2. 
**Expected behavior**
Syslog module errors out, but entire crowdsec should not crash

**Screenshots**
Output from crashdump:
`
error : interface conversion: syslog.Message is nil, not *rfc3164.SyslogMessage
version: v1.3.4-ddfe95e45d98d1e7a6496d2499e2e44a023135be
Codename: alphaga
BuildDate: 2022-04-29_09:33:00
GoVersion: 1.17.9
Platform: linux
goroutine 250 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/crowdsecurity/crowdsec/pkg/types.WriteStackTrace({0x1546e60, 0xc000ef8d20})
        /go/src/crowdsec/pkg/types/utils.go:115 +0x254
github.com/crowdsecurity/crowdsec/pkg/types.CatchPanic({0x17147e9, 0x1b})
        /go/src/crowdsec/pkg/types/utils.go:130 +0xfa
panic({0x1546e60, 0xc000ef8d20})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/syslog.(*SyslogSource).handleSyslogMsg(0xc0008194d0, 0xc0000b9c20, 0x25637e0, 0xc0005ee420)
        /go/src/crowdsec/pkg/acquisition/modules/syslog/syslog.go:213 +0xd6c
github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/syslog.(*SyslogSource).StreamingAcquisition.func1()
        /go/src/crowdsec/pkg/acquisition/modules/syslog/syslog.go:131 +0x85
gopkg.in/tomb%2ev2.(*Tomb).run(0x25637e0, 0x2594f20)
        /go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x36
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xf3
 `

Crowdsec is running in docker with the syslog UDP port exposed through the host.

**Comment by buixor** [comment]
Hello,

 One of our colleagues has a  Unifi Gateway at home and is going to reproduce it, however he's currently on travel and should be back in a week or so.

We do know that currently the syslog parser is too strict and might crash on poorly formatted messages, so please bear with us, we'll keep you posted !

**Comment by blotus** [comment]
Hello,

I was able to reproduce the issue.

This come from our syslog parser which is both too strict and too lenient :( 

I've started to rewrite it in #1554, should be done in a few days.

**Comment by blotus** [comment]
Fixed in #1554
