### ISSUE TITLE
Bug/LAPI doesn't report connected host stats for their host

### ISSUE THREAD

**Issue by ToeiRei** [crowdsecurity/crowdsec#1506]
**Describe the bug**
I run crowdsec in LAPI mode and I had them all report to the central API. 

**To Reproduce**
1. Add some hosts (agents)
2. Activate LAPI on one host
3. Link the other (local) hosts to the LAP

**Expected behavior**
I'd expect to have the alerts all on their hosts in app.crowdsec.net instead of all just being added to the host running the LAPI.

... nearly had a heart attack seeing alerts for ssh-bf on my webserver which didn't even had an sshd exposed....

**Comment by buixor** [comment]
Hello,

Currently the metrics exposed by LAPI are only for LAPI, and each agent expose their own prometheus metrics.
It is not in our plans to change it in close term, sorry :)
