### ISSUE TITLE
Improvement/cscli: Add HTTP method in `cscli alerts inspect -d`

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/crowdsec#1508]
**Is your feature request related to a problem? Please describe.**
To investigate an alert it would be helpful to have also the http method (GET, POST, PUT, etc.).

**Describe the solution you'd like**
Display `evt.Parsed.verb` in `cscli alerts inspect -d`.

**Comment by AlteredCoder** [comment]
Hello, this depend more on the parser that you have installed. What parser do you use for your web server ?
Elements displayed with `cscli alerts inspect -d` are the one inside the `evt.Meta` object,

**Comment by Lamera** [comment]
I use this one: https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/crowdsecurity/apache2-logs.yaml.
So can we change that?
