### ISSUE TITLE
Improvement/Download package and install from source

### ISSUE THREAD

**Issue by autokilla47** [crowdsecurity/crowdsec#1510]
The documentation says that I can only download the package without enable using "`--download-only`" key. 
Is it possible to copy the downloaded package to another host, place it in a special directory and install it ? Or, using Docker, similarly place the package in a special directory, add it in the environment ("`COLLECTIONS`")  and run the container to get the installed package.

**Comment by buixor** [comment]
Hello,

Can you let me know what you try to achieve ? 

Otherwise, you can download packages from https://packagecloud.io/crowdsec/crowdsec and install them manually with your distribution's package management tool (ie. `dpkg -i` on debian).

**Comment by autokilla47** [comment]
I mean a situation where, for example, download several packages from collections on one host (with `--download-only`), copy to another host and install.
