### ISSUE TITLE
Bug/crowdsec6-blacklists not populating on OPNsense 22.1

### ISSUE THREAD

**Issue by Christophe999s** [crowdsecurity/crowdsec#1512]
**Describe the bug**
crowdsec6-blacklists not populating on OPNsense 22.1
Installed v0.1 following https://github.com/crowdsecurity/opnsense-plugin-crowdsec
Reinstall did not solve the issue

crowdsec-blacklists is population without any issues, but crowdsec6 stays empty
Manually adding IPv6 address using cscli decisions add is working as intended

**Screenshots**
https://imgur.com/a/WGuNNfu

**Technical Information (please complete the following information):**
OPNsense 22.1.6-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Additional context**
https://pastebin.com/j0XiQVNg
https://pastebin.com/U36ET3dd

**Comment by mmetc** [comment]
Hi @Christophe999s !

I think the ipv6 blacklist for the scenarios you have installed may actually be empty at the moment. You can try running, for example, `cscli collections install crowdsecurity/http-cve` and see if it gets populated over time.

**Comment by Christophe999s** [comment]
I think you're right. I ran the command, and now there's a single address in the crowdsec6-blacklists.
