### ISSUE TITLE
Bug/leakybucket: poor design causing excessive & unnecessary load, stuck sending event

### ISSUE THREAD

**Issue by casesolved-co-uk** [crowdsecurity/crowdsec#1519]
**Describe the bug**
I was looking into an ssh attack and noticed many log lines like below in crowdsec. On looking at the code producing the log lines (for [this blog post](https://discourse.crowdsec.net/t/ssh-attack-causing-crowdsec-memory-leak/767)) it seems a poor design in [PourItemToBucket](https://github.com/crowdsecurity/crowdsec/blob/ad28a979e98436b468dd35101baa16335ad720a8/pkg/leakybucket/manager_run.go#L157).

There is a tight loop (no sleeps) that will repeat until an event is sent. This sometimes takes 300,000 attempts and more than a second.

It appears the intention was that the loop would block on a select call waiting for an event to happen. But this doesn't appear to be working. It seems there shouldn't be multiple select calls because you can [wait on several events](https://stackoverflow.com/questions/68436941/what-is-the-back-arrow-in-golang) with a single select.

Either that or the loop needs a 100msec sleep to eliminate the unnecessary load.

`time="03-05-2022 07:47:52" level=warning msg="stuck for 1.2835585s sending event to ff28ee5fb2ff72db65d783775f08425420084ca5 (sigclosed:0 keymiss:1 failed_sent:299998 attempts:300000)" cfg=crimson-paper file=/etc/crowdsec/scenarios/ssh-bf.yaml name=crowdsecurity/ssh-bf_user-enum`

**To Reproduce**
1. Launch brute-force ssh attack on crowdsec on resource constrained server

**Expected behavior**
One or two failed loop attempts at most

**Technical Information (please complete the following information):**
 - Debian 10
 - v1.2.1

**Comment by AlteredCoder** [comment]
Hello, can you try to upgrade to the latest version and see if this behavior still happen ?

**Comment by casesolved-co-uk** [comment]
Makes no difference, the `PourItemToBucket` code hasn't changed

**Comment by buixor** [comment]
Hello,

While adding buffered channel or waiting on time might seem a good idea at first, it is going to have a lot of undesirable side effects.
Can you provide some context in the discourse post you made as well so we can try to reproduce ? This part might be optimized, but not in this way :slightly_smiling_face:

**Comment by casesolved-co-uk** [comment]
What are the side effects and what context do you want?

**Comment by casesolved-co-uk** [comment]
I have posted the auth.log to the [discourse post](https://discourse.crowdsec.net/t/ssh-attack-causing-crowdsec-memory-leak/767/5)

**Comment by ryantig** [comment]
Was the cause of the problem identified? If not why was the issue closed?

**Comment by casesolved-co-uk** [comment]
Apparently making 300,000 attempts to do something simple is a non-issue according to @buixor 😱
Let's hope they've simulated it using my uploaded auth.log
