### ISSUE TITLE
Bug/Service failed ‘address already in use’ DirectAdmin server

### ISSUE THREAD

**Issue by germanosbh** [crowdsecurity/crowdsec#1525]
I have the following scenario:
CentOS 7 Server
NGINX with Apache reverse proxy.
Apache uses ports 8080 and 8081
The crowdsec service failed to start because the port is already used by Apache ( tcp 127.0.0.1:8080: bind: address already in use" )

I looked what configuration files have port 8080 .
./config.yaml: listen_uri: 127.0.0.1:8080
./local_api_credentials.yaml:url: http://127.0.0.1:8080/
./bouncers/crowdsec-firewall-bouncer.yaml:api_url: http://127.0.0.1:8080/

I did a replace for port 8888.  After that I was able to start the crowdsec service but I found another error when trying to install the wordpress bouncer, this time " tcp 127.0.0.1:8888: bind: address already in use"
crowdsec cscli bouncers add wordpress-bouncer

**Comment by germanosbh** [comment]
> Hello @germanosbh I see a user with a similar issue open comment on the Linux thread on discord? @blotus responded to you with: the command is just `cscli bouncers add wordpress-bouncer` no need to prefix with crowdsec (this will attempt to start crowdsec again, which will fail because another instance is already running)

Hello !! Wow, this time I was even embarrassed hahaha, I was very distracted. Thanks a lot, now it's working.

**Comment by LaurenceJJones** [comment]
Great, that is good to hear it is now working! Don't forget to close the issue once you get the chance :) If you ever need help please reach out!
