### ISSUE TITLE
Improvement/Allow whitelist on top of community blocklists

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1545]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have whitelists that would apply on incoming community blocklists from CAPI.

**Describe the solution you'd like**
Given the amount of IPs that we're receiving from CAPI (10k+), I guess we cannot really allow too expensive whitelisting process (ie. reverse-dns etc.). However, being able to at least apply simple static whitelists based on IP / Ranges and such would be nice.

If - in the future - community blocklists contain more information about the IPs in the blocklist (ie. geoloc info, tags), it will allow for even finer grained whitelists :+1:

**Comment by LaurenceJJones** [comment]
Fixed via #2132

**Comment by thespad** [comment]
Is there documentation for applying this or will it simply apply existing whitelists to CAPI/3rd party sources?

**Comment by celevra** [comment]
Same question
How to use?
Applying in /etc/crowdsec/parsers/s02-enrich/whitelists.yaml is not enough

**Comment by LaurenceJJones** [comment]
@thespad @celevra Does this help https://docs.crowdsec.net/docs/next/whitelist/create#whitelists-from-capi-central-api-community-blocklist-or-third-party-blocklist

**Comment by celevra** [comment]
@LaurenceJJones this looks promising, thank you
