### ISSUE TITLE
Improvement/Syslog parser

### ISSUE THREAD

**Issue by bennet-esyoil** [crowdsecurity/crowdsec#1557]
We've discussed the current implementation of the syslog parser and why it probably does not work correctly in our use-case.
I've attached some logs that show 
[7i1j.txt](https://github.com/crowdsecurity/crowdsec/files/8761161/7i1j.txt)

**Comment by buixor** [comment]
related to #1554

**Comment by blotus** [comment]
Closing as #1505 already tracks the same issue.
