### ISSUE TITLE
Bug/Crowdsec 1.3.3 -> 1.3.4 : Bug with stream mode if refresh > 60s

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1565]
Because of the changes induced by https://github.com/crowdsecurity/crowdsec/pull/1445 :
 - if the refresh frequency of a stream mode bouncer is > to 60 seconds, its last_pull will be updated during the authentication process
 - it cause to the bouncer to miss a full 60s of decisions

**Comment by AlteredCoder** [comment]
Fixed in https://github.com/crowdsecurity/crowdsec/pull/1517
