### ISSUE TITLE
Improvement/  Static profiles.yaml file that does not get changes after ever update

### ISSUE THREAD

**Issue by JoshWho** [crowdsecurity/crowdsec#1578]
Every time there is a update my profiles.yaml file always goes back to the default ban time.

Is there a way to prevent this from changing after every update?

I preferer my bans to last for 7 days  and lately I come back and I will see it set to 4 hours after a update.

**Comment by blotus** [comment]
Hello,

The next release will include support for `.local.yaml` files that will allow you to override settings without touching the files coming from the package (see https://github.com/crowdsecurity/crowdsec/pull/1497)
