### ISSUE TITLE
Improvement/add Zorin in install script

### ISSUE THREAD

**Issue by Idlefase** [crowdsecurity/crowdsec#1579]
Zorin 16 is based on Ubuntu focal and this is confirmed by uname -a, but the install script will query Zorin in the parameters 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
 
The install script querys Zorin while its confirmed to be Ubuntu focal. 2 different vars in Zorin OS 16

**Describe the solution you'd like**

I would like a elseif statement in the function os_detect. Just as it happends for the  rasberry pi

**Describe alternatives you've considered** (Optional) 

Ive considerd to use Ubuntu focal directly but this would not add much a difference to the core of the os. Zorin is a port of Ubuntu and therefor shares lots of code. 

**Example of what you imagine**
If applicable, add an example of what you would expect from this feature request.

I hope that there will be a small patch that will resolve the issue. 

**Additional context**

Ive tried to define the os and dist vars beforehand to force the parameters. No resolve. Error code 404.

**Comment by blotus** [comment]
Hello,

This script is provided by https://packagecloud.io/, so unfortunately we cannot modify it.

You can override the detected OS by running the script like this: `os=ubuntu dist=focal ./script.sh`
