### ISSUE TITLE
dial tcp http://ipcrowdsec:6060: connect: connection refused

### ISSUE THREAD

**Issue by brahmanggi** [crowdsecurity/crowdsec#1589]
always gave this error while trying to connect to grafana, is there any solution? thank you

here are the logs, 

`logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/status/buildinfo remote_addr=192.168.50.249 referer=http://192.168.50.152:3000/datasources/edit/bs-8rAC7k/ t=2022-06-13T19:25:08.68+0700 lvl=eror msg="Proxy request failed" err="dial tcp ipcrowdsecserver:6060: connect: connection refused"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-13T19:25:08.68+0700 lvl=eror msg="Request Completed" method=GET path=/api/datasources/proxy/1/api/v1/status/buildinfo status=502 remote_addr=192.168.50.249 time_ms=265 duration=265.47729ms size=0 referer=http://192.168.50.152:3000/datasources/edit/bs-8rAC7k/ traceID=00000000000000000000000000000000
logger=tsdb.prometheus t=2022-06-13T19:25:08.89+0700 lvl=eror msg="Instant query failed" query=1+1 err="Post \"http://ipcrowdsecserver:6060/metrics/api/v1/query\": dial tcp ipcrowdsec:6060: connect: connection refused"`

**Comment by blotus** [comment]
Hello,

By default, the prometheus endpoint will listen on 127.0.0.1, you need to edit the parameter `prometheus.listen_addr` in `/etc/crowdsec/config.yaml` to expose it to another host (see [here](https://docs.crowdsec.net/docs/next/configuration/crowdsec_configuration/#prometheus)).

Also, this endpoint is meant to be scrapped by prometheus, not to be queried directly with grafana.
