### ISSUE TITLE
Improvement/Add a `cscli support-dump` command

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#1604]
The goal of this command would be to simplify support for users: we often ask always the same questions (metrics, acquis.yaml, config, collections/parsers/scenarios, ...) and this can add a lot of back and forth.

We should add a new command in cscli to create a .tar.gz which would contains all required information.

We must take care to not include any sensitive data in the archive (like database credentials, CAPI creds, ....).

**Comment by buixor** [comment]
cf. https://github.com/crowdsecurity/crowdsec/pull/1634

**Comment by buixor** [comment]
good, merged
