### ISSUE TITLE
notifications: elasticsearch : datetime variables for index ?

### ISSUE THREAD

**Issue by aderumier** [crowdsecurity/crowdsec#1649]
### What would you like to be added?

Hi,

for elasticsearch notification, the documentation specify 1 unique index "crowdsec'
```
format: |-
 {{ range .}}
  {"index": { "_index": "crowdsec"} }
  {{.|toJson}}
 {{ end }}
```

is it possible to pass some datetime variables like  "crowdsec-%y%m%d"   ?

### Why is this needed?

to be able to delete old index / do rotation.

**Comment by buixor** [comment]
(closing as it should be fine, don't hesitate to re-open if more is needed!)
