### ISSUE TITLE
1.4.0-rc4 : on Windows, fatal errors are dropped and service doesn't appear as stopped

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1653]
### What happened?

Two issues on windows during 1.4.0-rc4 testing :
 - Giving an invalid config to crowdsec, the fatal error message is not visible in logs (and stderr goes to the void on windows)
 - When this very situation happens, windows is not notified that the service has crashed and thus still appears as running

### What did you expect to happen?

fatal error messages in the logs, and windows knowing the service died.

### How can we reproduce it (as minimally and precisely as possible)?

Craft an invalid profiles.yaml for example (with invalid yaml).

### Crowdsec version

1.4.0-rc4

### OS version

Windows

**Comment by sabban** [comment]
fixed
