### ISSUE TITLE
config.yaml file permissions on ubuntu 22

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#1660]
### What happened?

After installing crowdsec-1.4.0-rc4 on a fresh Ubuntu 22, the config.yaml permissions were `644` where as I think it should be `600`.

### What did you expect to happen?

The config.yaml permissions set to `600`.

### How can we reproduce it (as minimally and precisely as possible)?

Install crowdsec-1.4.0-rc4 on ubuntu 22 from the package cloud repository.

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by sabban** [comment]
I believe this is fixed
