### ISSUE TITLE
Improvement: Docker one shot error

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#1665]
### What would you like to be added?

Improve the error message here: https://github.com/crowdsecurity/crowdsec/blob/628d7be1d84fd90db10a4d2b7316ed275158b5de/pkg/acquisition/modules/docker/docker.go#L324

### Why is this needed?

Users may confuse this error with Crowdsec not being able to communicate with the docker socket. Something like "No running container named: %s, can't run one-shot acquisition"

**Comment by AlteredCoder** [comment]
Done in https://github.com/crowdsecurity/crowdsec/pull/1666
