### ISSUE TITLE
Unit tests do not make the CI fail

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1676]
### What happened?

unit tests failed on [this pr](https://github.com/crowdsecurity/crowdsec/runs/7464251524?check_suite_focus=true).
Logs show tests failed, but status of CI says ok.

### What did you expect to happen?

see that unit tests failed

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Crowdsec version

master

**Comment by blotus** [comment]
Fixed in #1677
