### ISSUE TITLE
No IPv6 adress for api.crowdsec.net

### ISSUE THREAD

**Issue by OcelotNat** [crowdsecurity/crowdsec#1692]
### What happened?

Hello,

When installing CrowdSec on a server without IPv4 : 
`FATA[29-07-2022 03:06:47 PM] api client register ('https://api.crowdsec.net/'): api register (https://api.crowdsec.net/) : Post "https://api.crowdsec.net/v2/watchers": dial tcp 79.125.69.239:44
3: connect: network is unreachable: Post "https://api.crowdsec.net/v2/watchers": dial tcp 79.125.69.239:443: connect: network is unreachable`

`ping -6 api.crowdsec.net`
`ping: api.crowdsec.net: Address family for hostname not supported`

### What did you expect to happen?

No fatal error on install

### How can we reproduce it (as minimally and precisely as possible)?

computer without IPv4, only IPv6
`curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash`
`apt install crowdsec`

### Crowdsec version

<details>
CrowdSec version :
version: v1.4.1-debian-pragmatic-e1954adc325baa9e3420c324caabd50b7074dd77

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian`

</details>


### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

**Comment by xRiesch** [comment]
host api.crowdsec.net
api.crowdsec.net has address 63.32.12.96
api.crowdsec.net has address 34.246.154.187
api.crowdsec.net has address 34.251.148.43

**Comment by LaurenceJJones** [comment]
Hi, thank you for opening this issue. We do know about this limitation of only ipv4 machines can connect, I will try to get an update to this. I will remove the "bug" tag as that is more for application issues rather than networking.

**Comment by LaurenceJJones** [comment]
```
host api.crowdsec.net
api.crowdsec.net has address 18.165.201.56
api.crowdsec.net has address 18.165.201.109
api.crowdsec.net has address 18.165.201.123
api.crowdsec.net has address 18.165.201.36
api.crowdsec.net has IPv6 address 2600:9000:23d3:de00:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:f800:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:3400:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:7e00:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:3800:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:2200:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:a00:12:19c9:7380:93a1
api.crowdsec.net has IPv6 address 2600:9000:23d3:9400:12:19c9:7380:93a1
```
