### ISSUE TITLE
Collection suricata cant autoinstall

### ISSUE THREAD

**Issue by AdzerKI** [crowdsecurity/crowdsec#1694]
### What happened?

cscli collections install crowdsecurity/suricata
FATA[31-07-2022 12:30:00 PM] Error while installing 'crowdsecurity/suricata': unable to retrieve item: crowdsecurity/suricata 

### What did you expect to happen?

normal install

### How can we reproduce it (as minimally and precisely as possible)?

cscli collections install crowdsecurity/suricata

### Crowdsec version

<details>

2022/07/31 12:31:26 version: v1.4.1-el8-rpm-e1954adc325baa9e3420c324caabd50b7074dd77
2022/07/31 12:31:26 Codename: alphaga
2022/07/31 12:31:26 BuildDate: 2022-07-25_09:53:23
2022/07/31 12:31:26 GoVersion: 1.17.5
2022/07/31 12:31:26 Platform: linux
2022/07/31 12:31:26 Constraint_parser: >= 1.0, <= 2.0
2022/07/31 12:31:26 Constraint_scenario: >= 1.0, < 3.0
2022/07/31 12:31:26 Constraint_api: v1
2022/07/31 12:31:26 Constraint_acquis: >= 1.0, < 2.0

</details>

### OS version

<details>

NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.6 (Sky Tiger)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.6"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Could you run
```
cscli hub update
cscli hub upgrade
cscli collections install crowdsecurity/suricata
```
You have to periodically update the hub to get the latest collections

**Comment by AdzerKI** [comment]
Thx! this work for me

**Comment by LaurenceJJones** [comment]
Great! feel free to close this issue, we are working to implement a automatic "update" feature for the hub so this shouldn't happen in the future!
