### ISSUE TITLE
Cannot install on new Rocky Linux 9 instance

### ISSUE THREAD

**Issue by JohRest** [crowdsecurity/crowdsec#1699]
### What happened?

Installed with:
curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh | sudo bash

Installing yum-utils...
crowdsec_crowdsec-source                                                                                                                                                    479  B/s | 951  B     00:01
Package yum-utils-4.0.24-4.el9_0.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Generating yum cache for crowdsec_crowdsec...
Generating yum cache for crowdsec_crowdsec-source...

The repository is setup! You can now install packages.

then I ran:
yum install crowdsec
Last metadata expiration check: 0:00:10 ago on Wed Aug  3 12:56:49 2022.
No match for argument: crowdsec
Error: Unable to find a match: crowdsec

### What did you expect to happen?

Successful installation via yum install command

### How can we reproduce it (as minimally and precisely as possible)?

redo the steps on a Rocky Linux 9 instance (see what happened)

### Anything else we need to know?

no

### Crowdsec version

current version available via package manager

### OS version

NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"

### Enabled collections and parsers

not applicable

### Acquisition config

not applicable

### Config show

not applicable

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

none

**Comment by pvogler** [comment]
I guess the repo on packagecloud is still empty for path el/9
That is why  I opened enhancement #1683 (https://github.com/crowdsecurity/crowdsec/issues/1683).
Hopefully the packages will be built soon.

**Comment by sabban** [comment]
Yes, providing packages for el/9 is still work in progress.
I hope to provide smth by the end of the week.

Regards,

**Comment by pvogler** [comment]
@sabban: Once you close this issue, issue #1683 can be closed as well. I requested packages for el/9 with that issue as enhancement.

**Comment by pabl-o-ce** [comment]
hey guys you just need to change this for make it work at your https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh file:

Line 96 =>
```
if [ "${dist}" = "8" || "${dist}" = "9" ]; then
    _skip_pygpgme=1
else
    _skip_pygpgme=0
fi
```
or I'm wrong?

**Comment by pabl-o-ce** [comment]
okay guys I made it work like this:

add  /etc/yum.repos.d/crowdsec_crowdsec.repo file: 
```repo
[crowdsec_crowdsec]
name=crowdsec_crowdsec
baseurl=https://packagecloud.io/crowdsec/crowdsec/el/8/$basearch
repo_gpgcheck=1
gpgcheck=1
enabled=1
gpgkey=https://packagecloud.io/crowdsec/crowdsec/gpgkey
       https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-B78D1222C9AD2D5D.pub.gpg
       https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[crowdsec_crowdsec-source]
name=crowdsec_crowdsec-source
baseurl=https://packagecloud.io/crowdsec/crowdsec/el/8/SRPMS
repo_gpgcheck=1
gpgcheck=1
enabled=1
gpgkey=https://packagecloud.io/crowdsec/crowdsec/gpgkey
       https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-B78D1222C9AD2D5D.pub.gpg
       https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

using the 8 configurations on rocky 9:
`baseurl=https://packagecloud.io/crowdsec/crowdsec/el/8/$basearch`
and
`baseurl=https://packagecloud.io/crowdsec/crowdsec/el/8/SRPMS`

because 9 don't exist? or its not working

**Comment by pvogler** [comment]
Packages are provided now.
Installation worked for the regular package and the firewall bouncers
