### ISSUE TITLE
Where I can find HTTPD_ERRORLOG  pattern?

### ISSUE THREAD

**Issue by AdzerKI** [crowdsecurity/crowdsec#1713]
### What would you like to be added?

Hi. 

Where I can find pattern HTTPD_ERRORLOG in my linux files
in dir /etc/crowdsec/patterns/ its absent

### Why is this needed?

I have a bug with detect correct client IP in PHP error, want to try change pattern

**Comment by LaurenceJJones** [comment]
All default patterns are documented on the docs here: https://doc.crowdsec.net/docs/next/parsers/patterns

**Comment by buixor** [comment]
Hello,

It's defined in https://github.com/crowdsecurity/grokky/blob/master/base.go#L150

You can overload existing expressions directly in your parsers if needed !

**Comment by AdzerKI** [comment]
but where is httpd? all other from logstash i see
