### ISSUE TITLE
Typo on the app.crowdsec.net console

### ISSUE THREAD

**Issue by shleeable** [crowdsecurity/crowdsec#1719]
### What happened?

![image](https://user-images.githubusercontent.com/17537000/186301530-909bd52a-73d8-4051-9dba-d60cf8f05cdc.png)

### What did you expect to happen?

"unknown"

### How can we reproduce it (as minimally and precisely as possible)?

Add a new agent. Because the version ID is updated, you'll see `unkown`.

### Crowdsec version

https://app.crowdsec.net/overview

### OS version

NA

### Enabled collections and parsers

NA

### Acquisition config

NA

### Config show

NA

### Prometheus metrics

NA

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

NA

**Comment by LaurenceJJones** [comment]
Hey! Thank you for spotting this grammatical error. I have forward this over to the web team.

**Comment by wojtekxtx** [comment]
Its super easy to correct this. Im seriously suprised its taking 3 months ( and counting )

**Comment by LaurenceJJones** [comment]
This repository isn't for the frontend of the console so closing this, have raised internally via our ticketing system.
