### ISSUE TITLE
When creating hubtest in v1.4.1 new parser doesn't get tested

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/crowdsec#1720]
### What happened?

In the (long) process of creating a video on how to do parsers and scenarios I started the process during v1.3.4 and did the last recording on v1.4.1. For some reason following the exact same process in v.1.4.1 compared to v1.3.4 resulted in my new parser not being tested when I ran the hubtest. 
After tracking down the error I found that in v1.4.1 when you create a hubtest this line gets added to the skeleton config.yaml as the very last line:
`override_statics: []`

When removing that, everything works. Here's the [PR](https://github.com/crowdsecurity/hub/pull/536) that I submitted in this process. Add that line to my config.yaml and it skips my custom parser.

If you have problems recreating the error I have the recording available. Just let me know if you need it.

### What did you expect to happen?

I expected the hubtest to actually test my parser.

### How can we reproduce it (as minimally and precisely as possible)?

Check out the code in this PR: https://github.com/crowdsecurity/hub/pull/536

Add the line `override_statics: []` to config.yaml and run csclie hubtest.

### Crowdsec version

<details>

```console
2022/08/25 11:25:20 version: v1.4.1-debian-pragmatic-e1954adc325baa9e3420c324caabd50b7074dd77
2022/08/25 11:25:20 Codename: alphaga
2022/08/25 11:25:20 BuildDate: 2022-07-25_09:20:06
2022/08/25 11:25:20 GoVersion: 1.17.5
2022/08/25 11:25:20 Platform: linux
2022/08/25 11:25:20 Constraint_parser: >= 1.0, <= 2.0
2022/08/25 11:25:20 Constraint_scenario: >= 1.0, < 3.0
2022/08/25 11:25:20 Constraint_api: v1
2022/08/25 11:25:20 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by buixor** [comment]
as seen  it was because the file wasn't save, user issue
