### ISSUE TITLE
issue in decision deletion

### ISSUE THREAD

**Issue by sabban** [crowdsecurity/crowdsec#1724]
### What happened?

`cscli decisions delete --id  . `

reported this

̀`INFO[30-08-2022 06:22:08 AM] 13603 decision(s) deleted`

### What did you expect to happen?

report an errur

### How can we reproduce it (as minimally and precisely as possible)?

`cscli decisions delete --id  . `

### Crowdsec version

2022/08/30 06:36:20 version: v1.4.1-rc1-debian-pragmatic-0eea20fa7c2fed02693eb0b30b4de9d1aebbf552
2022/08/30 06:36:20 Codename: alphaga
2022/08/30 06:36:20 BuildDate: 2022-07-22_09:41:15
2022/08/30 06:36:20 GoVersion: 1.17.5
2022/08/30 06:36:20 Platform: linux
2022/08/30 06:36:20 Constraint_parser: >= 1.0, <= 2.0
2022/08/30 06:36:20 Constraint_scenario: >= 1.0, < 3.0
2022/08/30 06:36:20 Constraint_api: v1
2022/08/30 06:36:20 Constraint_acquis: >= 1.0, < 2.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, 
</details>


### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
I thought this was fun to try to debug here what I found if it helps
```
Delete by decisions appends the ID to fmt.Sprintf("%s/decisions/%s", s.client.URLPrefix, decision_id)
Which will be HTTP://127.0.0.1/decisions/. However, in URL the . will be removed so it will trigger this route instead HTTP://127.0.0.1/decisions
# jwtAuth.DELETE("/decisions", c.HandlerV1.DeleteDecisions)
```

**Comment by sabban** [comment]
Yes, it's because the id flag got on the command line has just no sanitation. Before going further I want to ensure that there's no other joke of the same kind
