### ISSUE TITLE
Add specific banning time using CLI

### ISSUE THREAD

**Issue by jav-12** [crowdsecurity/crowdsec#1750]
### What would you like to be added?

I would like to have something like:

```
# cscli decision add -i 2.2.2.2 -ban_time 4hr
# cscli decision add -i 2.2.2.2 -ban_time 6hr
# cscli decision add -i 3.3.3.3 -ban_time 1hr
```

and so

So you can add a specific ban time to a specific IP and increase or decrease it as your will

### Why is this needed?

Nice to have. If we are getting attacked several times, each time we want the ban time to increase for that IP.

**Comment by he2ss** [comment]
Hi @jav-12,

You can already set a time using `duration` parameter : `cscli decisions add --ip 1.2.3.4 --duration 24h`
you can look at the [documentation](https://docs.crowdsec.net/docs/next/cscli/cscli_decisions_add/).
