### ISSUE TITLE
Seperate LAPI and Agent default metrics ports

### ISSUE THREAD

**Issue by Ornias1993** [crowdsecurity/crowdsec#1776]
### What would you like to be added?

It would be nice to have the LAPI and Agents either on seperate ports by default or have them configured by env var.

### Why is this needed?

When wanting to run Crowdsec LAPI and Agent in a single kubernetes pod with multiple containers, metrics cannot work "out of the box", because both containers use the same (default) port for metrics.

However this cannot be pre-configured by end var, requiring modifications to the configuration after installation, which makes things needlessly troublesome.

**Comment by mmetc** [comment]
Yes, we can have it configurable in the helm values.

But if an instance has both agent and lapi, we use the metrics port to see if both are ready, so I'd keep a single port.

**Comment by Ornias1993** [comment]
We require this ability to be reasonably able to include crowssec in our SCALE Apps.
It has basically been put on hold completely waiting for this, as we do not want to include needless complications to work around this mistake.

**Comment by mmetc** [comment]
Added METRICS_PORT in https://github.com/crowdsecurity/crowdsec/pull/1891

**Comment by Ornias1993** [comment]
> Added METRICS_PORT in #1891

Quick, Easy and Clean fix.
Thanks! :)
