### ISSUE TITLE
Schema not reachable

### ISSUE THREAD

**Issue by wojtekxtx** [crowdsecurity/crowdsec#1799]
https://github.com/crowdsecurity/crowdsec/blob/daae241ff9a13f8066c0f554d6a3bdb8d6958925/windows/installer/product.wxs#L13

Schema has been moved or deleted.

Going to the above web address gives:
![Zrzut ekranu 2022-10-8 o 13 03 45](https://user-images.githubusercontent.com/109670049/194704355-7d8f3388-e359-4951-9113-4582d3d4076f.png)

**Comment by blotus** [comment]
Hello,

XML uses a URI (i.e., an indicator), not an URL (i.e., a location) for namespacing, so there are no requirements for the URI to point to something that exists.

In addition, this namespace is part of the Wix spec: https://wixtoolset.org/documentation/manual/v3/xsd/wix/
