### ISSUE TITLE
Docker pipeline for -slim variant

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#1859]
### What would you like to be added?

When using containers you may want to use a slimmer image than the default one we provide as this include all notification binaries which take 10 - 15 mb each so in total we could save 40mb. As we include more notification options this would get bigger and bigger over time. Here is the uncompressed image so far.
```
crowdsecurity/crowdsec                       v1.4.1       064f5d85c9a9   3 months ago   199MB
```

### Why is this needed?

When running containers or orchestration environments you want the images to be as slim as possible. Offering a `-slim` option would allow users to make a choice to run a container without the notification binaries.

**Comment by LaurenceJJones** [comment]
Linked to #1862

**Comment by mmetc** [comment]
So, we should have this now

crowdsecurity/crowdsec:1.4.2
crowdsecurity/crowdsec:1.4.2-slim
crowdsecurity/crowdsec:latest
crowdsecurity/crowdsec:slim

the last one is latest of course, but I don't think I've ever seen "latest-slim"

The full image is 205 MB, slim is 86. I have removed the duplication of the geoip db when it's used, so it saves 78mb when using full.

There are two other possible targets for BUILD_ENV (with-plugins, 129MB and with-geoip, 166MB), but they are not pushed. 

When the geoip is missing, even if a scenario uses it, it won't be downloaded at start but requires a  "cscli hub upgrade".

**Comment by mmetc** [comment]
Done in https://github.com/crowdsecurity/crowdsec/pull/1862
