### ISSUE TITLE
db_config.use_wal

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#1860]
### What would you like to be added?

The new message about use_wal doesn't really describe how to enable it well. We should include a commented out line so user doesnt need to think about un commenting it.
```
time="07-11-2022 10:04:34" level=warning msg="you are using sqlite without WAL, this can have an impact of performance. If you do not store the database in a network share, set db_config.use_wal to true. Set explicitly to false to disable this warning." context=ent
```

### Why is this needed?

For ease for users to enable it without needing to think what key is.

**Comment by buixor** [comment]
I think the message itself is quite ok ? however it repeats too much at startup, so I can try to make it repeat only once
