### ISSUE TITLE
LAPI sync with websocket

### ISSUE THREAD

**Issue by suryadana** [crowdsecurity/crowdsec#1879]
### What would you like to be added?

I suggest LAPI sync with WebSocket method to make a real-time synchronization process.

### Why is this needed?

Because when we use API that make a delay in synchronization.

**Comment by LaurenceJJones** [comment]
Could you provide some metrics / logs where you are seeing this delay?

**Comment by suryadana** [comment]
> Could you provide some metrics / logs where you are seeing this delay?

I I mean on the sync process between crowdsec into bouncer right now using interval update I think we can use WebSocket protocol to broadcast the decisions into bouncer so that makes a real-time process. I am concerned if we use multiple-server that make delay or make the central server will crash because too many HTTP requests.

**Comment by LaurenceJJones** [comment]
> > Could you provide some metrics / logs where you are seeing this delay?
> 
> I I mean on the sync process between crowdsec into bouncer right now using interval update I think we can use WebSocket protocol to broadcast the decisions into bouncer so that makes a real-time process. I am concerned if we use multiple-server that make delay or make the central server will crash because too many HTTP requests.

Yes, I understand. However, it would mean we need to design a websocket endpoint and update the bouncers to support it.

Regarding your concerns, we have a hoster that currently has over 500 bouncers on a single lapi node (system resources is quite a lot 64 cores and 128gb ram), and they had a single issue which we resolved and is behind a feature flag in 1.5
