### ISSUE TITLE
Failed to start Crowdsec v1.4.2 on Centos 7

### ISSUE THREAD

**Issue by itspec-ru** [crowdsecurity/crowdsec#1881]
### What happened?

Required static build for working crowdsec-v1.4.2 on Centos 7. But it's not available for download. Available only crowdsec-release.tgz, but not crowdsec-release-static.tgz

$ systemctl status crowdsec

```
● crowdsec.service - Crowdsec agent
   Loaded: loaded (/etc/systemd/system/crowdsec.service; disabled; vendor preset: disabled)
      Active: failed (Result: exit-code) since Ср 2022-11-23 14:27:49 +04; 21s ago
        Process: 4900 ExecStart=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml (code=exited, status=0/SUCCESS)
          Process: 24648 ExecStartPre=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml -t (code=exited, status=1/FAILURE)
           Main PID: 4900 (code=exited, status=0/SUCCESS)
           
           nov 23 14:27:48 mx.porttlt.ru systemd[1]: Starting Crowdsec agent...
           nov 23 14:27:48 mx.porttlt.ru crowdsec[24648]: /usr/local/bin/crowdsec: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/crowdsec)
           nov 23 14:27:49 mx.porttlt.ru systemd[1]: crowdsec.service: control process exited, code=exited status=1
           nov 23 14:27:49 mx.porttlt.ru systemd[1]: Failed to start Crowdsec agent.
           nov 23 14:27:49 mx.porttlt.ru systemd[1]: Unit crowdsec.service entered failed state.
           nov 23 14:27:49 mx.porttlt.ru systemd[1]: crowdsec.service failed.

```

### What did you expect to happen?

Starting crowdsec without errors

### How can we reproduce it (as minimally and precisely as possible)?

Install and run crowdsec-v1.4.2 on Centos 7 linux

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux mx.porttlt.ru 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Hey

Could you provide the output of `tail -n 50 /var/log/crowdsec.log` will help us debug

**Comment by itspec-ru** [comment]
I have installed crowdsec by wizard.sh. I do upgrading by wizard.sh too. And I don't want change it to installing from rpm.

I downloaded https://github.com/crowdsecurity/crowdsec/releases/download/v1.4.2/crowdsec-release-static.tgz.
After unpacking, I get the crowdsec-v1.4.2-freebsd directory. Is it correct?

**Comment by mmetc** [comment]
Hi @itspec-ru , no problem with the wizard.sh script. Just be aware that you have to manually update the hub, and wizard.sh itself is not copied anywhere so you need it again when you want to uninstall.

The version number is not correct, it took the wrong tag because I built it by hand on a test machine, but no effect otherwise. I'm re-uploading asap, thanks again.

**Comment by mmetc** [comment]
I have uploaded the release package with the right version number. No other change.
