### ISSUE TITLE
Bouncer Init through Environmental Variables adds additional value to the

### ISSUE THREAD

**Issue by pewter77** [crowdsecurity/crowdsec#1912]
### What happened?

Based on https://github.com/crowdsecurity/crowdsec/pull/1341 I've added the following to my environment in docker-compose for crowdsec:
`- "BOUNCER_KEY_traefik=${CROWDSEC_API_TRAEFIK}"`

but when I run `cscli bouncers list` I get a bouncer with the name KEY_traefik

I believe the parser has a bug.

Not breaking or anthing.

### What did you expect to happen?

I expect the name of my bouncer to be "traefik"

### How can we reproduce it (as minimally and precisely as possible)?

1.  Add `- "BOUNCER_KEY_traefik=${CROWDSEC_API_TRAEFIK}"` to your docker-compose.yaml file
2.  use the cscli in the docker container `cscli bouncers list`
3.  View Incorrect Name

### Crowdsec version

<details>

```console
docker exec -t crowdsec cscli version      
2022/12/06 10:31:36 version: v1.4.2-3beb84bcfe05885fdd9a00f3124b4a949e45ce82
2022/12/06 10:31:36 Codename: alphaga
2022/12/06 10:31:36 BuildDate: 2022-11-15_12:52:20
2022/12/06 10:31:36 GoVersion: 1.19.3
2022/12/06 10:31:36 Platform: linux
2022/12/06 10:31:36 Constraint_parser: >= 1.0, <= 2.0
2022/12/06 10:31:36 Constraint_scenario: >= 1.0, < 3.0
2022/12/06 10:31:36 Constraint_api: v1
2022/12/06 10:31:36 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by mmetc** [comment]
Keeping this open until the next docker release. Thanks @pewter77 !

**Comment by LaurenceJJones** [comment]
@mmetc can we close?

**Comment by mmetc** [comment]
No stable release since the fix, but crowdsecurity/crowdsec:v1.4.4-rc1 has it

**Comment by LaurenceJJones** [comment]
Isn't latest tag on docker 1.4.4-rc1?

**Comment by mmetc** [comment]
no, latest always points to  a stable one atm
