### ISSUE TITLE
[Docker] Fails to start watcher login failed

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#1914]
after the latest update,
any changes in /etc/crowdsec/local_api_credentials.yaml file is being reverted back to default port of 8080 and crowdsec is crashing on startup due to 8080 being used by another process on my system...i am running crowdsec in docker in host network mode....

Edit: Nevermind,
for docker, we also need to add LOCAL_API_URL env variable to docker to change port, since env variable is picked up first before config file i think....
worked after adding that env variable and changing port using that....

Note: Also looks like in recent update, the local_api_credentials.yaml file is refreshed on every start of crowdsec...this caused my issue..

_Originally posted by @milindpatel63 in https://github.com/crowdsecurity/crowdsec/issues/552#issuecomment-1340340396_

**Comment by LaurenceJJones** [comment]
@mmetc Seems some issue may have come from the latest docker_start changes. I will investigate but seems user has found cause.

**Comment by mmetc** [comment]
Some change was necessary to work in k8s, and I didn't think of all the possible combinations especially with configuration in persistent or host-mounted volumes. I never used host network except for monitoring.

We suggest configuring via environment variables when possible, but I understand they have limits (for now).

**Comment by mmetc** [comment]
what you can do in these cases, is keep the persistent configuration but also set the envvars that differ from the defaults.
