### ISSUE TITLE
[DOCKER] fails to start X is tainted unless --force

### ISSUE THREAD

**Issue by mushuthecat** [crowdsecurity/crowdsec#1916]
### What happened?

HI,

Since the last update my crowdsec restart in loop.

After reading some other bug report i tried to edit the local_api_credantials.yaml by editing the port 8080 by 8082 because of one of my other container already use this port but it seems that it's not my issue....

### What did you expect to happen?

Starting crowdsec.

To by pass the issue i disabled crowdsec from my traefik config....

### How can we reproduce it (as minimally and precisely as possible)?

Extract from Docker logs

PM" level=fatal msg="Error while installing 'crowdsecurity/traefik': while enabling crowdsecurity/traefik: while installing crowdsecurity/base-http-scenarios: crowdsecurity/base-http-scenarios is tainted, won't enable unless --force"

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/83928911/206463794-863f0bb0-0deb-4f39-a553-340f8e7a4049.png)

### Crowdsec version

<details>

crowdsecurity/crowdsec               latest        30b889b850d0   2 days ago      206MB

</details>

### OS version

<details>

```console
# On Linux:
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux DOCKER-I7 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux



</details>


### Enabled collections and parsers

<details>

crowdsecurity/crowdsec               latest        30b889b850d0   2 days ago      206MB

</details>


### Acquisition config

<details>
```console
filenames:
  - /var/log/crowdsec/traefik.log
#this is not a syslog log, indicate which kind of logs it is
labels:
  type: traefik
---
filenames:
 - /var/log/auth.log
labels:
  type: syslog
---
filenames:
  - /var/log/crowdsec/authelia.log
labels:
  type: authelia


</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
/triage accepted

To workaround issue you need to remove the `COLLECTIONS` environment variable from crowdsec section in your compose. Since you edited the files locally it tries to update them and it cant since they been edited. We are working on a patch here #1915 but in the meantime follow the workaround above.

**Comment by mushuthecat** [comment]
> /triage accepted
> 
> To workaround issue you need to remove the `COLLECTIONS` environment variable from crowdsec section in your compose. Since you edited the files locally it tries to update them and it cant since they been edited. We are working on a patch here #1915 but in the meantime follow the workaround above.

One Shot Thanks
