### ISSUE TITLE
Installation fail on Ubuntu bionic

### ISSUE THREAD

**Issue by reinerj** [crowdsecurity/crowdsec#1918]
### What happened?

crowdsec_wizard: acquisition file path: /etc/crowdsec/acquis.yaml
/usr/local/bin/cscli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/cscli)
ERR[11/12/22:10:45:05] crowdsec_wizard: fail to install collection crowdsec/whitelists

### What did you expect to happen?

Install on OS

### How can we reproduce it (as minimally and precisely as possible)?

Try to install or update an existing crowdsec

### Crowdsec version

1.4.3

### OS version

4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu bionic

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Going to need some context: as `Try to install or update an existing crowdsec` isnt enough to reproduce....
So guess you are not using our package repository? and installing from source? are you building on the same machine you are planning to install on?

**Comment by mmetc** [comment]
@LaurenceJJones given the path to cscli and the conflict with glibc, it's certainly not installed from .deb, nor built from sources. Binary tarball?

**Comment by reinerj** [comment]
Hi,

after reinstall the package from repo, same error.

apt install crowdsec
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed
  crowdsec
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/30.5 MB of archives.
After this operation, 109 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package crowdsec.
(Reading database ... 140221 files and directories currently installed.)
Preparing to unpack .../crowdsec_1.4.3_amd64.deb ...
You can always run the configuration again interactively by using '/usr/share/crowdsec/wizard.sh -c
Unpacking crowdsec (1.4.3) ...
Setting up crowdsec (1.4.3) ...
Creating /etc/crowdsec/acquis.yaml
INFO[23/12/22:18:47:13] crowdsec_wizard: service 'sshd': /var/log/auth.log
INFO[23/12/22:18:47:13] crowdsec_wizard: service 'linux': /var/log/syslog /var/log/kern.log
cscli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by cscli)
dpkg: error processing package crowdsec (--configure):
 installed crowdsec package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 crowdsec
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by LaurenceJJones** [comment]
Is this the base bionic installation media you get from Ubuntu? Or are you running inside a container? I tested via digitalocean and can't replicate so needs specific details.

**Comment by reinerj** [comment]
Hi,

it is not running in a container. It is a server which we run on real hardware. No virtualization. What other details do you need?

**Comment by mmetc** [comment]
Hi @reinerj , I am not sure your apt source points to the right version of crowdsec.

I have deployed a bionic system, fully upgraded, and I can install the 1.4.3 package. It does not require GLIBC 2.28 and I have 2.27.

```
vagrant@ubuntu1804:~$ uname -a
Linux ubuntu1804.localdomain 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

vagrant@ubuntu1804:~$ grep bionic /etc/apt/sources.list.d/crowdsec_crowdsec.list 
deb [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ bionic main
deb-src [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ bionic main

vagrant@ubuntu1804:~$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

```

**Comment by reinerj** [comment]
Hi,

here are the settings of the server:

# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/crowdsec/crowdsec

deb [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ bionic main
deb-src [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ bionic main

Linux 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by mmetc** [comment]
The .deb packages install cscli in /usr/bin/, not in /usr/local/bin. You have some leftover from the previous installation.

**Comment by reinerj** [comment]
Hi,

thanks for the help, Indeed there was a leftover.  Installation did work now without an error

Regards
Reiner
