### ISSUE TITLE
Crowdsec Docker - CAPI community-blocklist - IPv6 Missing

### ISSUE THREAD

**Issue by ancker010** [crowdsecurity/crowdsec#1973]
### What happened?

Running latest crowdsec docker image.
The only special variable is below.
- DISABLE_AGENT="true"

When I run `cscli decisions list --origin CAPI` there are no IPv6 addresses listed.

### What did you expect to happen?

I expect that the list should contain both IPv4 and IPv6 addresses.

(I have other Crowdsec instances running (not in Docker) where both IPv4 and IPv6 addresses are present.)

### How can we reproduce it (as minimally and precisely as possible)?

See above. Nothing special.

### Anything else we need to know?

This docker instance does NOT currently have IPv6 enabled. Is it possible Crowdsec looks for working IPv6 before asking CAPI for IPv6 entries?

If so, this should be configurable as I'm using a bouncer to configure an upstream device using the community blocklists that is IPv6 enabled.

### Crowdsec version

<details>

```console
$ cscli version
2023/01/06 15:41:39 version: v1.4.4-8d0af73a4fb24ef8416e598d891c6e5e5501ede5
2023/01/06 15:41:39 Codename: alphaga
2023/01/06 15:41:39 BuildDate: 2023-01-05_10:41:00
2023/01/06 15:41:39 GoVersion: 1.19.4
2023/01/06 15:41:39 Platform: linux
2023/01/06 15:41:39 Constraint_parser: >= 1.0, <= 2.0
2023/01/06 15:41:39 Constraint_scenario: >= 1.0, < 3.0
2023/01/06 15:41:39 Constraint_api: v1
2023/01/06 15:41:39 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
$ uname -a
Linux <snip> 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
No your agent receives both ipv4 and ipv6 depending on the scenarios you have installed. There nothing you need to do this, I'll be open and say ipv6 does not have alot of ips compared to ipv4.

**Comment by ancker010** [comment]
@LaurenceJJones I'm not sure that's the case.

This instance is receiving 14k IPv4 entries, and 0 IPv6 entries.

Another instance of mine: 17k IPv4, 176 IPv6

So there SHOULD be IPv6 in the list.

As a test, I set `DISABLE_AGENT="false"` and am seeing the same behavior.

**Comment by ancker010** [comment]
As an aside, I'm also curious, since the total number from CAPI is only ~14k, if the REAL problem is that the initial download didn't complete or something.

I see this in the logs, is there a way to force a CAPI refresh?
`time="06-01-2023 16:10:55" level=info msg="last CAPI pull is newer than 1h30, skip."`

**Comment by LaurenceJJones** [comment]
The agent flag wont change things in that case.

While optimizing the decisions delivery steam we ran into a pagination limit (~15k) so your agent receives aggressive ips first hence 14k vs 17k.

**Comment by LaurenceJJones** [comment]
From our data 0.5% is ipv6 so its an extremely small figure so it could be correct that the initial pull didn't have any ipv6 addresses.

We cant presume or know what people networks setups are like so like stated we prioritise the most aggressive ips first and encourage people to send signals so they can benefit from the community list instead of the smaller list.

**Comment by ancker010** [comment]
I'm okay with getting the smaller list for this particular application.
The "most aggressive" is exactly what I'm looking to filter anyway.

I guess what I'm most concerned about at this point is making sure if an IPv6 address is listed as "most aggressive", it will be sent EVEN if there are ~3k IPv4.

State differently, is "aggressiveness" a separate metric than address type? If an IPv6 address is super aggressive, will it be sent ahead of other IPv4 addresses?

**Comment by LaurenceJJones** [comment]
Yes, so there is no difference in address type so if an ipv6 is classed as more aggressive than ipv4 it would be distributed as normal.

**Comment by LaurenceJJones** [comment]
Closing the issue, if you believe this is a mistake please reopen
