### ISSUE TITLE
Slim variant for v1.4.4 is missing

### ISSUE THREAD

**Issue by MrAlucardDante** [crowdsecurity/crowdsec#1974]
### What happened?

The slim variant for 1.4.4 hasn't been built/pushed to the docker hub

### What did you expect to happen?

Tag v1.4.4-slim to exist on the docker hub

### How can we reproduce it (as minimally and precisely as possible)?

Check on the docker hub or in the build pipeline

### Crowdsec version

<details>

```console
$ cscli version
irrelevant
```

</details>

### OS version

<details>

```console
irrelevant
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
irrelevant
```

</details>

### Acquisition config

<details>
```console
irrelevant
</details>


### Config show

<details>

```console
$ cscli config show
irrelevant
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
irrelevant
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
This is now resolved, slim variants have been released for 1.4.4 and 1.4.5
