### ISSUE TITLE
CrowdSec in a Kubernetes Cluster doesn't raise alerts

### ISSUE THREAD

**Issue by Aptul9** [crowdsecurity/crowdsec#1975]
Hi everyone,
I have recently tried to set up a Kubernetes cluster with Ingress-Nginx and CrowdSec.
I have followed this guide posted in CrowdSec: https://www.crowdsec.net/blog/kubernetes-crowdsec-integration
However, I think some parts are missing, such as the ingress file, which I set up by myself.
Everything seems to be working fine, CrowdSec has access to the logs produced by ingress-nginx, but when I try to use Nikto, no alerts get raised:
![image](https://user-images.githubusercontent.com/48324233/211274907-d83e95fa-bba4-4f44-b2ae-845157492f15.png)
I have tried everything, but I could not identify the issue.
The only change I made was that I am not using AWS, therefore I have omitted the file 

> ingress-nginx-values.yaml

**Comment by Aptul9** [comment]
I will open another issue with labels

**Comment by LaurenceJJones** [comment]
Closing due to duplication
