### ISSUE TITLE
error : non-positive interval for NewTicker

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1991]
### What happened?

Crash on startup, the random ticker generated in `apiserver.(*apic).Push` was negative (or non-positive) causing NewTicker to panic.

### What did you expect to happen?

n/a

### How can we reproduce it (as minimally and precisely as possible)?

be very unlucky

### Anything else we need to know?

we should ensure it's always positive

### Crowdsec version

branch : decisions_sync_with_capi

**Comment by mmetc** [comment]
I think there is a misunderstanding:

```
// randomDuration returns a duration value between d-delta and d+delta                  
func randomDuration(d time.Duration, delta time.Duration) time.Duration {
       return time.Duration(float64(d) + float64(delta)*(-1.0+2.0*rand.Float64()))
}                                                                   
```

The delay is between (pushIntervalDefault - pushIntervalDelta) and (pushIntervalDefault + pushIntervalDelta)
This translates to 15s < delay < 45s in the master branch, and -5s < delay < 25s in your branch.
pushIntervalDefault must be >= pushIntervalDelta

https://github.com/crowdsecurity/crowdsec/blob/decisions_sync_with_capi/pkg/apiserver/apic.go#L31

We can:
 - panic / fatal if default < delta
 - return 0 if the result is negative, but it would flatten the curve and it's not random anymore -> spikes

**Comment by buixor** [comment]
thx @mmetc , fixed on decisions_sync_with_capi
