### ISSUE TITLE
Debian 11 : apt error NO_PUBKEY on install

### ISSUE THREAD

**Issue by OcelotNat** [crowdsecurity/crowdsec#2002]
### What happened?

Installing Crowdsec on a new installed Debian 11 :
`curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash`
-> No error
`apt update`
`Réception de :5 https://packagecloud.io/crowdsec/crowdsec/debian bullseye InRelease [24,7 kB]                
Err :5 https://packagecloud.io/crowdsec/crowdsec/debian bullseye InRelease
  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 9EB2753BF09DFB77`

### What did you expect to happen?

An 'apt update' without error to be able to install crowdsec.

### How can we reproduce it (as minimally and precisely as possible)?

Install a fresh Debian 11(.6)
`curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash`
`apt update`

### Anything else we need to know?

solution :
`mv /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg /usr/share/keyrings/`

/etc/apt/sources.list.d/crowdsec_crowdsec.list : replace
`[signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg]`
with
`[signed-by=/usr/share/keyrings/crowdsec_crowdsec-archive-keyring.gpg]`

`apt update` -> work

### Crowdsec version

<details>
2023/01/18 17:45:42 version: v1.4.4-debian-pragmatic-8d0af73a4fb24ef8416e598d891c6e5e5501ede5
2023/01/18 17:45:42 Codename: alphaga
2023/01/18 17:45:42 BuildDate: 2023-01-05_10:38:38
2023/01/18 17:45:42 GoVersion: 1.19.2
2023/01/18 17:45:42 Platform: linux
2023/01/18 17:45:42 Constraint_parser: >= 1.0, <= 2.0
2023/01/18 17:45:42 Constraint_scenario: >= 1.0, < 3.0
2023/01/18 17:45:42 Constraint_api: v1
2023/01/18 17:45:42 Constraint_acquis: >= 1.0, < 2.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
$ uname -a
Linux [host] 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

</details>


### Enabled collections and parsers

_No response_

### Acquisition config

_No response_

### Config show

_No response_

### Prometheus metrics

_No response_

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

_No response_

**Comment by LaurenceJJones** [comment]
Tried to replicate via digital ocean debian 11
```
root@debian-s-1vcpu-1gb-intel-lon1-01:~# uname -a
Linux debian-s-1vcpu-1gb-intel-lon1-01 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
root@debian-s-1vcpu-1gb-intel-lon1-01:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
root@debian-s-1vcpu-1gb-intel-lon1-01:~# curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
Detected operating system as debian/bullseye.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.2.4
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing 
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/crowdsec_crowdsec.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
root@debian-s-1vcpu-1gb-intel-lon1-01:~# 
```
Might be proxmox image does not ship with a package the install script needs

**Comment by OcelotNat** [comment]
[LaurenceJJones](https://github.com/LaurenceJJones) really sorry for the waste of your time, i don't be able to reproduce the bug.
It wasn't on a Proxmox install, but well a Debian (+ Proxmox-backup-client).
I'll re-open the bug if I find how to reproduce the problem.
