### ISSUE TITLE
Can't update image with watchtower: manifest format

### ISSUE THREAD

**Issue by mhellmeier** [crowdsecurity/crowdsec#2013]
### What happened?

The external tool [watchtower](https://github.com/containrrr/watchtower) helps to update docker container images automatically. This doesn't work for crowdsec.

As shown [in this discussion](https://github.com/containrrr/watchtower/discussions/1529), the problem occurs due to a new manifest format when using `docker buildx`. Crowdsec is also mentioned as an image with an unsupported manifest.
Other problematic images like pi-hole already solved the issue: https://github.com/pi-hole/docker-pi-hole/issues/1289

### What did you expect to happen?

The head request shouldn't result in an 404 error.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start and run the crowdsec container
2. Start and run the watchtower container
3. The following error message occurs:
```
Could not do a head request for "crowdsecurity/crowdsec:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```

### Crowdsec version

<details>

```console
latest (v1.4.5)
```

</details>

### OS version

<details>

```console
Ubuntu 22.04 LTS
```

</details>

**Comment by LaurenceJJones** [comment]
Will speak to @mmetc tomorrow but this issue seems to effect more than just us https://github.com/containrrr/watchtower/issues/1514#issue-1513403555

**Comment by LaurenceJJones** [comment]
Seems the upstream issue has been resolved https://github.com/containrrr/watchtower/issues/1514#issuecomment-1407625089 we most likely won't push a fix ourside since we never recommend the use of watchertowerr with our image.
