### ISSUE TITLE
[Feature Request] Please add math or math.Pow to the expressions helpers for duration_expr

### ISSUE THREAD

**Issue by casesolved-co-uk** [crowdsecurity/crowdsec#2025]
For things like:

`Pow(4, GetDecisionsCount(Alert.GetValue()))`

https://docs.crowdsec.net/docs/next/profiles/format/#duration_expr

https://github.com/crowdsecurity/crowdsec/blob/e927717fa072430aaac3934d50ef3f6b8fe2f200/pkg/exprhelpers/exprlib.go#L44

/kind enhancement

**Comment by LaurenceJJones** [comment]
If you wish to do this now I believe some of the arithmetic provided by expr could help in the meantime https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md . Your right though an easier name to read make the statement more readable for user and better QOL.

**Comment by LaurenceJJones** [comment]
Link to #1964

**Comment by casesolved-co-uk** [comment]
> If you wish to do this now I believe some of the arithmetic provided by expr could help in the meantime https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md . Your right though an easier name to read make the statement more readable for user and better QOL.

Right, thanks. Could you make sure this link is added to the `duration_expr` documentation. It's difficult to find.

I'll close this because it's not required given `^` and `**` exist.

**Comment by casesolved-co-uk** [comment]
Link to original discussion
https://github.com/crowdsecurity/hub/issues/646

**Comment by casesolved-co-uk** [comment]
`^` gives an error in an Sprintf expression, starting a new bug
