### ISSUE TITLE
`^` expr operator giving error in Sprintf

### ISSUE THREAD

**Issue by casesolved-co-uk** [crowdsecurity/crowdsec#2026]
### What happened?

> Feb  1 12:23:48 host crowdsec[98482]: time="01-02-2023 12:23:48" level=fatal msg="api server init: unable to run local API: controller init: failed to compile profiles: error compiling duration_expr of default_ip_remediation: unrecognized character: U+005E '^' (1:19)\n | Sprintf('%dh', 4 ^ GetDecisionsCount(Alert.GetValue()) )\n | ..................^"
> Feb  1 12:23:48 host systemd[1]: crowdsec.service: Control process exited, code=exited, status=1/FAILURE
> Feb  1 12:23:48 host systemd[1]: crowdsec.service: Failed with result 'exit-code'.

### What did you expect to happen?

no error

### How can we reproduce it (as minimally and precisely as possible)?

Put this in your profiles.yaml and restart:
`duration_expr: Sprintf("%dh", 4 ^ GetDecisionsCount(Alert.GetValue()) )`

### Anything else we need to know?

Related history:
https://github.com/crowdsecurity/crowdsec/issues/2025

### Crowdsec version

<details>

```console
$ cscli version
2023/02/01 12:41:21 version: v1.4.5-debian-pragmatic-a9a2186a76af63551352aa3bc296bdbe80ca4893
2023/02/01 12:41:21 Codename: alphaga
2023/02/01 12:41:21 BuildDate: 2023-01-19_15:07:44
2023/02/01 12:41:21 GoVersion: 1.19.2
2023/02/01 12:41:21 Platform: linux
2023/02/01 12:41:21 Constraint_parser: >= 1.0, <= 2.0
2023/02/01 12:41:21 Constraint_scenario: >= 1.0, < 3.0
2023/02/01 12:41:21 Constraint_api: v1
2023/02/01 12:41:21 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ lsb_release
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
$ uname -a
5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux# paste output here

```

</details>

**Comment by LaurenceJJones** [comment]
Yes, can replicate easily. For now suggestion to use `**` as that is working as intended and not throwing any error.

**Comment by casesolved-co-uk** [comment]
Already done.
Thanks for all the help @LaurenceJJones !

**Comment by antonmedv** [comment]
The `^` operator was added in expr v1.11. 

https://github.com/antonmedv/expr/releases/tag/v1.11.0

I can help with upgrading.

**Comment by buixor** [comment]
thanks @antonmedv ! We opened an issue yesterday about something we encountered while upgrading to 1.11 (looking forward to it!) : https://github.com/antonmedv/expr/issues/346

**Comment by antonmedv** [comment]
Expr has a new cool feature: [expr.Function](https://expr.medv.io/docs/Getting-Started#functions).

The expr.Function interface defines the fastest function.
