### ISSUE TITLE
Crowdsec overlay 

### ISSUE THREAD

**Issue by necrose99** [crowdsecurity/crowdsec#2052]
### What would you like to be added?

For feature request please pick a kind label by removing `<!-- -->` that wrap the example lines below

 gentoo ebuild overlay
https://github.com/funtoo/skeleton-overlay or simular.. setup ebuild repo scripts
Github/crowdsec/crowdsec-overlay 

Add ebuild/s to build crowdsec for gentoo from src.. or debian deb extraction and setup.. @

 gentoo crowdsec provisioning..

### Why is this needed?

Would be useful

**Comment by necrose99** [comment]
/kind gentoo linux support.. 
/kind enhancement  gentoo overlay.. 
/kind packaging.. 

Of which i or other gentoo users might help in kind.

**Comment by LaurenceJJones** [comment]
Does this help at all? https://git.stargazer.at/vbauer/portage/src/branch/master/net-analyzer/crowdsec

**Comment by necrose99** [comment]
nano /etc/portage/repos.conf/stargazer.conf 

`[stargazer]
location = /var/db/repos/stargazer
sync-type = git
sync-uri = https://git.stargazer.at/vbauer/portage.git'

**Comment by ToeiRei** [comment]
I still prefer the pronoun 'she' or 'her' 

The ebuild is far from perfect as it circumvents network sandboxing.

I'd appreciate it if you'd copy the specific files - the ebuild, the manifest and the 'files' to your local repository as this is my private repo to service my gentoo machines and bump a few ebuilds to have them on all of my machines.

**Comment by necrose99** [comment]
I might add net-analyzer/crowdsec-bin also to just yank the binary as it builds or dosent 
zip up the whole mess github.com/crowdsecurity/crowdsec-overlay 
adding lines to ebuild to add operc > /etc/..... will take some trivial work latter on...

**Comment by ToeiRei** [comment]
The source ebuild adds a gentoo specific marking for the agent to identify as (same as the debian pragmatic build). Not sure how you'd get that with the raw binary.

For the ebuild itself, we'd have to look up what external rust libs we'd need and see if we can get those downloaded in the ebuild itself to making it clean build without breaking out of the sandbox network-wise.

**Comment by necrose99** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-p2p/resilio-sync/resilio-sync-9999.ebuild
some things can be swiped from this to apply much of the binaries unpacking etc. 
src_install()  from yours 
(src_unpack , can even graverob debian  debs for arm64/arm etc package cloud wont let you brows for uri...  so i'll have to go fishing.. )  rust or golang depends however is the thorniness bits if at all. 

From source is best , but -bin is a failsafe... option...

**Comment by ToeiRei** [comment]
I did a couple of ebuilds and created an overlay at https://github.com/ToeiRei/crowdsec-overlay

**Comment by necrose99** [comment]
https://github.com/Necrohol/crowdsec-overlay/blob/main/net-analyzer/crowdsec/files/ 
I haven't had a chance to update these templates,  of late..
Binary one was to build from debs ie useful on iot, or embedded..  i do have gentoo as well on a number or arm64 devices.. 

I have openrc.in files if you @Toeirei care to swipe them. 


https://github.com/goose121/initify ,  perl inittify.pl Something.service ... and most of the time an openrc file with very minimal if at all edits. 


```
# Notifications
	..... 

	systemd_dounit "${FILESDIR}/${PN}.service"
#append ebuild to add openrc runner...
	newinitd "${FILESDIR}"/${PN}.openrc.in crowdsec
```

**Comment by ToeiRei** [comment]
@necrose99 I'll add the openrc files. Thank you. If you want to, we can collaborate with those ebuilds and maybe some guys at crowdsec can make this an official repo? (@blotus  @LaurenceJJones )

**Comment by necrose99** [comment]
crowdsec-release-static.tgz as for using a binary variants on gentoo ebuild/s 
crowsdec atm... doesn't have embedded  variants  

https://goreleaser.com/customization/builds/   
crowsec-release-static-arm64..... etc... 

RISCV boards and  but give fail-safe -bin options for older low memory  hardware   if crowdsec improves their GOREALSER , i'd rather use official Binary tarballs on -bin ebuilds ...  
@blotus  @LaurenceJJones  
newer golang will build riscv with gox etc.  for sei managed IOT croudsec would be useful as most are not as watched over as they should be...  
(higher capacity ie 16 gig arm64 boards will likely negate the nastier compile times) but older iot/SBC's with less ram are most common ATM.... 


```
# swipe some logic from resilio-sync-9999.ebuild as template uri handler   rob debs  
`QA_PREBUILT="usr/bin/${PN}" # add any other prebuild bins hear too..... 
#http://ftp.us.debian.org/debian/pool/main/c/crowdsec/crowdsec_1.0.9-2+b4_arm64.deb
# http://ftp.us.debian.org/debian/pool/main/c/crowdsec/crowdsec_1.0.9-2+b4_amd64.deb 
# http://ftp.us.debian.org/debian/pool/main/c/crowdsec/crowdsec_1.0.9-2+b4_i386.deb
#http://ftp.us.debian.org/debian/pool/main/c/crowdsec/crowdsec_1.0.9-2+b4_armhf.deb
#
BASE_URI="#http://ftp.us.debian.org/debian/pool/main/c/$PN/$PN_@$PV@arch@.deb
###  test  case URI handeler 
#
#BASE_URI="https://download-cdn.resilio.com/stable/linux-@arch@/${PN}_@arch@.tar.gz"
inherit upacker 
# unpack/unzip deb > @ /  
# add any fixes chmod 755 +X as /where needed 
## ensure depends are installed walla 
SRC_URI="amd64? ( ${BASE_URI//@arch@/+b4_amd64} )
	arm? ( ${BASE_URI//@arch@/+b4_armhf} )
	arm64? ( ${BASE_URI//@arch@/+b4_arm64} )
	x86? ( ${BASE_URI//@arch@/+b4_i386} )"`

```
https://github.com/Necrohol/crowdsec-overlay/blob/main/net-analyzer/crowdsec-bin/crowdsec-bin-1.4.6.ebuild_  
i as of yet haven't finished "massaging the src ebuild " etc over to do bins but was based on @ToeiRei  prior ebuild 

anyways if i get a chance to meddle with bin templates i will... 

building from sources is preferred but on some embedded hardware .... it can be a challenge..  but offer the choice,,

**Comment by ToeiRei** [comment]
My ebuilds now have the go vendor files split into their own archive to stay in the sandbox. No need for network breaches anymore.
