### ISSUE TITLE
Upgrading from 1.0.9 to 1.4.x loses CAPI decisions temporarily

### ISSUE THREAD

**Issue by CyrilBrulebois** [crowdsecurity/crowdsec#2128]
### What happened?

When upgrading from 1.0.9 to 1.4.x, using the Debian packages, the decisions fetched from the Central API seem to disappear for several hours. While they are still shown in `cscli decisions list -a`'s output, they are not returned via the API, meaning bouncers see no IPs to block.

The SQLite storage was in doubt initially, so I've performed another test with PostgreSQL, which led to similar results.

Testing with SQLite again, comparing the `decisions` table before/after, this caught my eye (scroll to the end of each line):

- before:
```
500|2023-03-17 18:46:28.397291569+01:00|2023-03-17 18:46:28.397292058+01:00|2023-03-24 18:46:28.397288609+01:00|crowdsecurity/ssh-bf|ban|-9223372036122623615|-9223372036122623615|-9223372036854775807|-9223372036854775807|4|ip|ANO.NYM.IZ.ED|CAPI|0|1
```

- after:
```
15486|2023-03-17 17:20:31.461238707+00:00|2023-03-17 17:20:31.461238773+00:00|2023-03-24 07:20:31+00:00|crowdsecurity/ssh-slow-bf|ban|-9223372036153557171|-9223372036153557171|-9223372036854775807|-9223372036854775807|4|Ip|AL.SO.HID.DEN|CAPI|0|6
```

so I've tried my luck running an `UPDATE` query in SQLite:

```
update decisions set scope = 'Ip' where scope = 'ip';
```

and all of a sudden crowdsec 1.4.6 is reporting decisions fetched from CAPI in version 1.0.9.

Looking around, I haven't been able to spot an obvious change regarding the case, but I reckon that at least 1.2.x introduced batched additions via `UpdateCommunityBlocklist()`, and maybe the change is hidden somewhere in there.

In any case, I'm filing this ticket for two reasons:

1. As a reference for the workaround I'm about to use in the next `crowdsec` upload to Debian: see “Anything else we need to know?” for details, and below for sample logs (close to 4 hours without CAPI decisions).
2. As a gentle reminder to developers regarding on-disk (or rather in-database) storage: while I can understand the “it's going to fix itself after a few hours” stance, I'm reluctant to considering that OK for admins that would rely on `crowdsec` to keep them safe. While I could probably could have lived with that during the Debian 11 life cycle, that's not the case for Debian 12: we're now shipping `crowdsec` itself but also two bouncers (`firewall` and `custom`), so I'd like to get a rock-solid user experience.

Sample logs, from the upgraded daemon:

```
time="17-03-2023 03:34:45" level=info msg="Starting processing data"
time="17-03-2023 03:34:46" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 04:01:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 04:31:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 05:01:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 05:30:11" level=info msg="last CAPI pull is newer than 1h30, skip."
time="17-03-2023 05:31:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 06:01:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 06:31:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 07:01:37" level=info msg="capi metrics: metrics sent successfully"
time="17-03-2023 07:30:11" level=info msg="Starting community-blocklist update"
time="17-03-2023 07:30:13" level=info msg="capi/community-blocklist : 2 explicit deletions"
time="17-03-2023 07:30:13" level=info msg="crowdsecurity/community-blocklist : added 14964 entries, deleted 498 entries (alert:2)"
```

(The “last CAPI pull” line in the middle seems doubtful, in passing.)

### What did you expect to happen?

I'd expect crowdsec not to lose decisions during an upgrade. Even if that might not be easy to achieve, keeping track of how data gets stored in the database, and thinking about some kind of migration mechanism would be best.

### How can we reproduce it (as minimally and precisely as possible)?

Install 1.0.9, get decisions from CAPI, upgrade to 1.4.x, notice that decisions aren't returned when querying the API (e.g. like bouncers do). Amusingly, they still appear in `cscli decisions list -a`'s output and in the database, which makes for a confusing debugging session.

### Anything else we need to know?

The initial debugging step was deleting all alerts then restarting the daemon:

```
cscli alerts delete -a
systemctl restart crowdsec
```

but as mentioned by @blotus, that's a heavy hammer: that'd drop any other decisions, manually inserted/imported.

Since the old version doesn't support deleting alerts by ID (so as to remove only the “Community blocklist” one), my current plan is to let the upgraded daemon start, query alerts, spot the “Community blocklist” one, and delete that one, finally restarting the daemon:

```sh
if [ "$refresh_capi" = 1 ]; then
  ids=$(cscli alerts list -a -o raw|awk -F',' '$2 == "Community blocklist" { print $1}')
  n=0
  for id in $ids; do
    cscli alerts delete --id $id
    n=$((n+1))
  done
  if [ "$n" -gt 0 ]; then
    echo "I: Restarting crowdsec after deleting CAPI decisions to force a refresh"
    deb-systemd-invoke restart 'crowdsec.service' >/dev/null || true
  fi
fi
```

(The `refresh_capi` variable is set earlier, when the need for another workaround is spotted, see [Debian#1031326](https://bugs.debian.org/1031326).)

### Crowdsec version

1.4.x

### OS version

Debian testing/unstable (soon to be Debian 12)

**Comment by buixor** [comment]
Hello,

As discussed, corner case with an existing workaround. It is not something we plan to work on.
