### ISSUE TITLE
Include vendor files in sources for offline building

### ISSUE THREAD

**Issue by ToeiRei** [crowdsecurity/crowdsec#2146]
I'm working on the [Gentoo Overlay](https://github.com/crowdsecurity/crowdsec/issues/2052) and the go dependencies are loaded in on compile time.

The problem I see here is, that we cannot build crowdsec completely offline just having the source tarball - which leads to me having to provide a separate tarball  with those vendor files or break out of the gentoo sandbox basically putting additional work in maintaining the repository.

Is it possible to include the vendor files in the future? As a bonus it would give us more consistent builds.

Same issue btw on the blocklist mirror as well as the firewall bouncer.

**Comment by mmetc** [comment]
We have the same issue with the FreeBSD version. The build system does not allow access to the net during the build phase, and the system of macros does not play well with our use of gmake.
The current solution, which is far from optimal but served us well so far, is to provide an alternate tag for stable releases that includes vendored dependencies.

So if, for example, you need a tarball with dependencies for v1.4.6, you can use v1.4.6-freebsd. We can name the next tag 1.5.0-vendor for example, to make the intent clearer.
It would in theory be possible to always include them, but it has not been discussed in a while. Are stable tags enough for you?

**Comment by ToeiRei** [comment]
@mmetc I can offer you my vendor files for 1.4.6 as a workaround 

I've been in touch with the team and talked to a few guys on discord as well and they are now aware of the issue.

**Comment by mmetc** [comment]
@ToeiRei sorry if I didn't explain well enough, I work at packaging for crowdsec and we also do the freebsd version. If you download your tarball from 1.4.6-freebsd instead of 1.4.6, the vendor files are included.

**Comment by ToeiRei** [comment]
Sorry, I was pretty decaf 10 hours ago. So what you're saying is that I should try the freebsd version?

**Comment by ToeiRei** [comment]
alright. Stuff done in a805ee836f5371785363f016b639c1acb3a42b2f, 02d0062ef26903ebd638073e9a10e6bb35933ec9 and 2858b3f69c02ad46bd785e0244949b062d0e6585
