### ISSUE TITLE
lapi fatal error if container is restarted after first init

### ISSUE THREAD

**Issue by pmffromspace** [crowdsecurity/crowdsec#2196]
### What happened?

I installed the crowdsec helm chart on my microk8s (v1.27.1) cluster several times using longhorn as storage provider.
When the lapi pod got recreated for example when scaling replica count to 0 and back to 1, the lapi would break.
I noticed the lapi container would end in a restart loop with the fatal error that the security engine is already enrolled.

Im using the` image.tag: "v1.4.6"` in the crowdsec-helm-values.yaml

It appears like I solved the issue, by removing the enroll key env variable after first install, and running `helm3 upgrade --install`

```
lapi:
  env:
    # - name: ENROLL_KEY
    #   value: "myEnrollKey"
```

### What did you expect to happen?

The lapi should not break when the pod is beeing recreated / restarted.

### How can we reproduce it (as minimally and precisely as possible)?

microk8s version v1.27.1
longhorn version v1.4.1

helm-values added to default ones: 
- image.tag: "v1.4.6"

1. Install crowdsec helm chart, delete pod crowdsec-lapi-* so the pod will be recreated
2. watch pod beeing in restart loop and logs saying "fatal error, security engine already enrolled"

(to fix:)
3. comment out in helm values like so:
```
lapi:
  env:
    # - name: ENROLL_KEY
    #   value: "myEnrollKey"
```
4. upgrade helm installation `helm3 upgrade --install .......`

### Crowdsec version

<details>

```cscli version:


2023/05/13 07:16:24 version: v1.4.5-a9a2186a76af63551352aa3bc296bdbe80ca4893
2023/05/13 07:16:24 Codename: alphaga
2023/05/13 07:16:24 BuildDate: 2023-01-25_08:57:05
2023/05/13 07:16:24 GoVersion: 1.19.5
2023/05/13 07:16:24 Platform: linux
2023/05/13 07:16:24 Constraint_parser: >= 1.0, <= 2.0
2023/05/13 07:16:24 Constraint_scenario: >= 1.0, < 3.0
2023/05/13 07:16:24 Constraint_api: v1
2023/05/13 07:16:24 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```
Linux n0 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by wolkenschieber** [comment]
Since today I get a similar message and the crowdsec container isn't starting anymore:
```
crowdsec      | Regenerate local agent credentials
crowdsec      | time="14-05-2023 09:36:32" level=info msg="Machine 'HOST' successfully added to the local API"
crowdsec      | time="14-05-2023 09:36:32" level=info msg="API credentials dumped to '/etc/crowdsec/local_api_credentials.yaml'"
crowdsec      | Check if lapi needs to register an additional agent
crowdsec      | time="14-05-2023 09:36:33" level=fatal msg="Could not enroll instance: API error: the security engine is already enrolled, force enroll is required to overwrite the current configuration"
crowdsec exited with code 1
```

The image `crowdsecurity/crowdsec:v1.4.6`. No configuration changes have been applied. Only the host machine has been restarted.

**Comment by wolkenschieber** [comment]
I can confirm that removing environment variable `ENROLL_KEY` allows the container to start again.

**Comment by blotus** [comment]
Hello,

This error was caused by a server side change in CAPI, we've fixed the issue on our end.
