### ISSUE TITLE
Crowdsec.service error on Ubuntu 20.04, possible bug

### ISSUE THREAD

**Issue by FullStackIndie** [crowdsecurity/crowdsec#2203]
I am using crowdesc on Ubuntu 22.04. It was working fine for months but today after updating I keep getting the error below. I noticed the error when trying to update the Crowdsec-firewall-bouncer that kept failing to install properly. 

I finally looked and nginx and crowdsec and nginx was running fine but crowdsec kept erroring and was shutdown. I tried restarting it, purging/removing it, reinstalling it (same with Crowdsec-firewall-bouncer) and It still doesnt work. Not sure if it's a crowdsec issue or a system issue.

Any Help is greatly appreciated. Thanks!!!

here is the the error 

Murph@homeserver: ~$ sudo systemctl restart crowdsec. Service
job for crowdsec. Service failed because the control process exited with error code.
See "systemctl status crowdsec. Service" and "journalctl -xeu crowdsec. Service" for details.
Murph@homeserver: ~$ sudo journalctl -xeu crowdsec. Service
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 an execstart= process belonging to unit crowdsec. Service has exited.

 The process' exit code is 'exited' and its exit status is 1.
May 16 19:54:51 homeserver systemd[1]: crowdsec. Service: failed with result 'exit-code'.
 Subject: unit failed
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 the unit crowdsec. Service has entered the 'failed' state with result 'exit-code'.
May 16 19:54:51 homeserver systemd[1]: failed to start crowdsec agent.
 Subject: a start job for unit crowdsec. Service has failed
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 a start job for unit crowdsec. Service has finished with a failure.

 The job identifier is 4707 and the job result is failed.
May 16 19:54:51 homeserver systemd[1]: crowdsec. Service: consumed 1.730s cpu time.
 Subject: resources consumed by unit runtime
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 the unit crowdsec. Service completed and consumed the indicated resources.
Lines 2263-2286/2286 (end)

 an execstart= process belonging to unit crowdsec. Service has exited.

 The process' exit code is 'exited' and its exit status is 1.
May 16 19:54:51 homeserver systemd[1]: crowdsec. Service: failed with result 'exit-code'.
 Subject: unit failed
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 the unit crowdsec. Service has entered the 'failed' state with result 'exit-code'.
May 16 19:54:51 homeserver systemd[1]: failed to start crowdsec agent.
 Subject: a start job for unit crowdsec. Service has failed
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 a start job for unit crowdsec. Service has finished with a failure.

 The job identifier is 4707 and the job result is failed.
May 16 19:54:51 homeserver systemd[1]: crowdsec. Service: consumed 1.730s cpu time.
 Subject: resources consumed by unit runtime
 defined-by: systemd
 support: http: //www. Ubuntu. Com/support

 the unit crowdsec. Service completed and consumed the indicated resources.

**Comment by LaurenceJJones** [comment]
Check `/var/log/crowdsec.log` and `/var/log/crowdsec-firewall-bouncer.log` for any `fatal` or `error` messages as the logs provided don't show much for us to debug

**Comment by LaurenceJJones** [comment]
Closing due to no response from OP, please reopen once you have relevant logs and we can help you with the issue.
