### ISSUE TITLE
Question: Can Crowdsec block outgoing connections? /kind feature

### ISSUE THREAD

**Issue by RasheedAZ** [crowdsecurity/crowdsec#2211]
### What would you like to be added?

Hi. Just wanted to ask if Crowdsec can be used to block outgoing connections to bad ips as well as incoming ones?

### Why is this needed?

Use case on a desktop Linux machine - would it make sense or improve security?

Thanks.

**Comment by LaurenceJJones** [comment]
For detection the most common use case would be route all traffic through a squid proxy then you can detect stuff that you deem a violation of rules.

For blocking you can use our firewall bouncer but change the chains to support `OUTPUT` within configuration. Please note that the community blocklist is focused on ingress traffic so most likely C2's wouldn't use the same IP as a bad reputation. However, you can do whatever you want 😆
