### ISSUE TITLE
File acq defaults in 1.5 issues

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2223]
Just to make it clearer file systems that are network shared or NFS do not work with inotify by default unless you have installed an optional package for the operating system. **NOTE** this does not resolve in all instances and following the workaround below is the most optimal solution.

This issue is intended to explore whether CrowdSec can detect the filesystem and change the default behaviour accordingly.

### What would you like to be added?

By default on 1.5 file acquisition uses inotify instead of polling ( < 1.5 defaults). Many users are reporting that upgrading to 1.5 causes there to be no logs parsed since inotify does not work it does not inform the tailing acquisition to parse the lines.

Workaround:

User can enable the old defaults by adding `poll_without_inotify: true` to the file acquisition within `acquis.yaml` example below.

```
poll_without_inotify: true
source: file
filenames:
 - /tmp/foo/*.log
 - /var/log/syslog
labels:
 type: syslog
 ```

/kind enhancement

### Why is this needed?

If crowdsec can detect that inotify failed to bind or there was some sort of error the system could auto heal from this instead of the user finding the option to turn back to manual polling

**Comment by LaurenceJJones** [comment]
I have asked affected user to post there current workarounds or suggestions here

**Comment by GNU-Plus-Windows-User** [comment]
at least for me ionotify is working fine, yet disabling it only mostly fixes the issue.
```
Establishing watches...
Total of 1 watches.
Finished establishing watches, now collecting statistics.
Will listen for events for 30 seconds.
total  access  modify  close_write  close_nowrite  open  filename
48     6       14      7            7              14    t
```

**Comment by yuphing-ong** [comment]
1. definitely should highlight this in documentation
2. perhaps as part of agent startup, you can do some testing e.g. create a temp file, start inotify on it, modify said file, then after 1 second check inotify, and if no events generate a warning.

**Comment by LaurenceJJones** [comment]
#2241

**Comment by mateuszdrab** [comment]
> #2241

Don't think this PR would make any difference for me, my log files are on the local filesystem.

**Comment by LaurenceJJones** [comment]
Classing issue as resolved, there is documentation and the implementation of auto detecting the disk type has improved this. Please open a new issue if you are struggling to resolve this or the auto detecting is not working as intended.
