### ISSUE TITLE
Warn user if plugin name already exists

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2239]
If a user has two plugins with the same name, they may find it hard to debug why a config is not working, and its because it could have  been overriden at runtime since 2 yaml filed have same name property.

 pb.pluginConfigByName[pluginConfig.Name] = pluginConfig

/kind enhancement

**Comment by mmetc** [comment]
You currently have a warning only for the notifications enabled in profiles.yaml.

`WARN[27-05-2023 23:50:07] several configs for notification slack_default found`

So you are asking for a warning even if slack_default is not used, right?
