### ISSUE TITLE
Alert without decisions are not displayed by `cscli alerts list`

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#2242]
### What happened?

I'm testing the new auditd collection, and when a scenario get triggered, I can see the alert in the Console but not with the `cscli alerts list`. I can only see it with `cscli alerts list -a`.

### What did you expect to happen?

I would like to be able to see alerts that don't contains decisions with `cscli alerts list`

### How can we reproduce it (as minimally and precisely as possible)?

trigger a scenario with a `remediation: false` and run `cscli alerts list`.

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by buixor** [comment]
fixed by https://github.com/crowdsecurity/crowdsec/pull/2435
