### ISSUE TITLE
Should be lower than warning?

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2367]
https://github.com/crowdsecurity/crowdsec/blob/9ac5aeda79287fb206ff87d6790436ad7a104234/pkg/leakybucket/manager_load.go#L271

I dont see why this should be a warning unless they load > 100 and it might cause longer processing times.

**Comment by mmetc** [comment]
+1

**Comment by mmetc** [comment]
As it's trivial, I added it to my PR here

https://github.com/crowdsecurity/crowdsec/pull/2361
