### ISSUE TITLE
crowdsec smb share block about

### ISSUE THREAD

**Issue by torefloo** [crowdsecurity/crowdsec#2372]
After installing crowdsec on windows server, smb share blocks the complete connection, I don't want it, just ban that ip when wrong attempts are made, isn't it possible?

**Comment by LaurenceJJones** [comment]
That's the way the bouncer works. If you stop the service do you regain access?

**Comment by LaurenceJJones** [comment]
My opinion it is not our bouncer unless you are getting false positive alerts, however, we only detect failed credentials so unless everyone is failing SMB auth that would be the reason.

Please remember to close your issue if you managed to solve it.

**Comment by torefloo** [comment]
> Is it the same server that had the firewall turned off?

yes I regain access once the bouncer is turned off.
no alert list.
I probably turned off the firewall by mistake.

**Comment by LaurenceJJones** [comment]
So is the firewall still turned on and the bouncer is turned off?

**Comment by torefloo** [comment]
yes, windows firewall is on, when you turn off the bouncer service, smb share comes.

**Comment by LaurenceJJones** [comment]
Can you provide output of `cscli alerts list` and `cscli decisions list` ?

**Comment by LaurenceJJones** [comment]
closing till op returns. You will be able to have better support experience on [discord](https://discord.gg/crowdsec)
