### ISSUE TITLE
[1.5.3] Cscli {parsers,collections,sceanarios} install

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2376]
### What happened?

When using `cscli hub update` if the version is not parsed correctly we default back to `master` branch. The same logic should be applied to `cscli` sub commands that interact with the hub index or else we can never download anything.

```
[vagrant@centos8s ~]$ sudo cscli hub update
WARN[25-07-2023 12:25:16] Crowdsec is not the latest version. Current version is '1.5.3' and the latest stable version is 'v1.5.2'. Please update it!
WARN[25-07-2023 12:25:16] As a result, you will not be able to use parsers/scenarios/collections added toCrowdsec Hub after CrowdSec v1.5.2
WARN[25-07-2023 12:25:16] Could not find index file for branch '1.5.3', using 'master'
INFO[25-07-2023 12:25:17] hub index is up to date
INFO[25-07-2023 12:25:17] Wrote new 794403 bytes index to /etc/crowdsec/hub/.index.json
[vagrant@centos8s ~]$ sudo cscli collections install crowdsecurity/linux
WARN[25-07-2023 12:25:18] Crowdsec is not the latest version. Current version is '1.5.3' and the latest stable version is 'v1.5.2'. Please update it!
WARN[25-07-2023 12:25:18] As a result, you will not be able to use parsers/scenarios/collections added toCrowdsec Hub after CrowdSec v1.5.2
FATA[25-07-2023 12:25:19] Error while installing 'crowdsecurity/linux': while downloading crowdsecurity/linux: while downloading crowdsecurity/syslog-logs: bad http code 404 for https://hub-cdn.crowdsec.net/1.5.3/parsers/s00-raw/crowdsecurity/syslog-logs.yam
```

### What did you expect to happen?

`cscli` parsers,scenarios,collections should attempt to parse version if it fails to default back to `master` as per `cscli hub` behaviour.

### How can we reproduce it (as minimally and precisely as possible)?

Install any `1.5.3~RC2` for RPM based distros then run

```
cscli hub update
cscli collections install crowdsecurity/linux
```

### Anything else we need to know?
Setting the branch to `master` within `config.yaml` makes it works

```yaml
cscli:
   hub_branch: "master"
```

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
2023/07/25 12:34:48 version: 1.5.3~rc2-rpm-pragmatic-f9ca14f01037169422375c8a6f5ca15e00fd9a54
2023/07/25 12:34:48 Codename: alphaga
2023/07/25 12:34:48 BuildDate: 2023-07-10_15:31:04
2023/07/25 12:34:48 GoVersion: 1.20.5
2023/07/25 12:34:48 Platform: linux
2023/07/25 12:34:48 libre2: C++
2023/07/25 12:34:48 Constraint_parser: >= 1.0, <= 2.0
2023/07/25 12:34:48 Constraint_scenario: >= 1.0, < 3.0
2023/07/25 12:34:48 Constraint_api: v1
2023/07/25 12:34:48 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by mmetc** [comment]
The current version (1.5.6-rc2) should do what you want, but if the version number cannot be parsed or compared it will fail on both commands (hub update & collections install).
Should be ok in most cases, and provide a useful message in some edge cases with a message like

failed to update hub: index not found at https://hub-cdn.crowdsec.net/vmeh/.index.json, branch 'vmeh'. Please check the .cscli.hub_branch value if you specified it in config.yaml, or use 'master' if not sure
