### ISSUE TITLE
Allow to set proxy from config.yaml

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#2400]
We currently only support setting a proxy for crowdsec (or cscli) through the `http_proxy` or `https_proxy` environment variable.

While easy to set on linux, it's a bit more cumbersome on windows and requires a registry edit.

We should add a new option in config.yaml to allow windows users to easily set a proxy for crowdsec to use.

**Comment by LaurenceJJones** [comment]
duplicated off #1232
