### ISSUE TITLE
Bug/Ubuntu repo for lunar is missing Release file 

### ISSUE THREAD

**Issue by Xyaren** [crowdsecurity/crowdsec#2433]
### What happened?

Pretty much the same as in #1073.
Release file for Ubuntu `lunar` is missing since months.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo

$ uname -a
Linux lx0001 6.2.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Yes, this is known and we have started steps to generalise the releases so moving forward it will support all version not matter if they are day 0 release. You can, however, fix this currently by setting the OS and DIST flags

```
https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | os=ubuntu dist=jammy bash
```

**Comment by Xyaren** [comment]
I recommend publishing under "stable" then like other products do.
That way there is no need to do any of those workarounds.

**Comment by LaurenceJJones** [comment]
>That way there is no need to do any of those workarounds.

Like I stated these workarounds wont be needed once the new packaging is in place.

**Comment by sabban** [comment]
Hi,

Can you try this `curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh?any=true | sudo bash`

Regards,

**Comment by LaurenceJJones** [comment]
> 

Does the machine has internet access without a proxy? if so try `cscli capi register` then `systemctl restart crowdsec`

**Comment by Xyaren** [comment]
Can confirm this works :) Thank you !
