### ISSUE TITLE
Example for `expr` testing

### ISSUE THREAD

**Issue by antonmedv** [crowdsecurity/crowdsec#2436]
### What would you like to be added?

Hello!

I'm working on improving testing for https://github.com/antonmedv/expr and would like to add Crowdsec expressions as testdata. 

I was able to collect some examples from https://github.com/crowdsecurity/hub and created this:
- [testdata/crowdsec.json](https://github.com/antonmedv/expr/blob/master/testdata/crowdsec.json)
- [test/crowdsec/crowdsec.go](https://github.com/antonmedv/expr/blob/master/test/crowdsec/crowdsec.go)

Where I can find more examples? Thanks

### Why is this needed?

This will help to detect incompatible changes and prevent bugs in future versions of Expr.

**Comment by LaurenceJJones** [comment]
Hey these are the majority, the others are the `parser.assert` or `scenario.assert` within `.tests` folder in the hub. However, up to you if you wish to use those.
