### ISSUE TITLE
404 reported by apt on Ubuntu lunar when trying install

### ISSUE THREAD

**Issue by scegg** [crowdsecurity/crowdsec#2448]
### What happened?

When following the steps provided [here](https://github.com/crowdsecurity/crowdsec#from-package-debian), apt reports 404.

```
~# sudo apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu lunar InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu lunar-updates InRelease                                                                             
Get:3 http://azure.archive.ubuntu.com/ubuntu lunar-backports InRelease [99.8 kB]                                                                 
Hit:4 http://download.zerotier.com/debian/jammy jammy InRelease                                                                                  
Get:5 http://security.ubuntu.com/ubuntu lunar-security InRelease [109 kB]                                                                                 
Ign:6 https://packagecloud.io/crowdsec/crowdsec/ubuntu lunar InRelease                                                              
Err:7 https://packagecloud.io/crowdsec/crowdsec/ubuntu lunar Release           
  404  Not Found [IP: 13.56.62.181 443]
Get:8 https://pkgs.tailscale.com/stable/ubuntu lunar InRelease                 
Reading package lists... Done                           
E: The repository 'https://packagecloud.io/crowdsec/crowdsec/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### What did you expect to happen?

Install

### How can we reproduce it (as minimally and precisely as possible)?

In Ubuntu Lunar,
curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
sudo apt-get update

### Crowdsec version

N/A

### OS version

PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo

Linux HK-V2-1 6.2.0-1010-azure #10-Ubuntu SMP Wed Aug 16 20:06:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LaurenceJJones** [comment]
Duplicate of #2433
