### ISSUE TITLE
Bug/cscli: metrics shown are wrong

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#246]
**Describe the bug**
When i run `cscli metrics` , in parser metrics, a child of a parser has more `hits` and `unparsed` than his parent.

**To Reproduce**
1. install crowdsec with sshd parser and produce some ssh traffic
2. run `cscli metrics`
3. you will see that `child-crowdsecurity/sshd-logs` `hits` and `unparsed` are higher than `crowdsecurity/sshd-logs`

**Expected behavior**
The parent parser should have more hits and unparsed than his son.

**Screenshots**
```
INFO[0000] Parser Metrics:
+--------------------------------+---------+---------+----------+
|            PARSERS             |  HITS   | PARSED  | UNPARSED |
+--------------------------------+---------+---------+----------+
| child-crowdsecurity/sshd-logs  | 4934170 |  695324 |  4238846 |
| crowdsecurity/dateparse-enrich |  695324 |  695324 | -        |
| crowdsecurity/geoip-enrich     |  695324 |  695324 | -        |
| crowdsecurity/sshd-logs        | 1418462 |  695324 |   723138 |
| crowdsecurity/syslog-logs      | 1468600 | 1468600 | -        |
| crowdsecurity/whitelists       |  695324 |  695324 | -        |
+--------------------------------+---------+---------+----------+

```

**Technical Information (please complete the following information):**
 - Crowdsec version:

```
2020/09/23 13:56:12 version: v0.3.1-5ac430093f878cb16ddc46f6fc35fb8694f19083
2020/09/23 13:56:12 Codename: beta
2020/09/23 13:56:12 BuildDate: 2020-08-31_13:13:20
2020/09/23 13:56:12 GoVersion: 1.13.3
2020/09/23 13:56:12 Constraint_parser: >= 1.0, < 2.0
2020/09/23 13:56:12 Constraint_scenario: >= 1.0, < 3.0
2020/09/23 13:56:12 Constraint_api: v1
2020/09/23 13:56:12 Constraint_acquis: >= 1.0, < 2.0

```

**Comment by sbs2001** [comment]
@AlteredCoder  where can I find this `child-crowdsecurity/sshd-logs  ` ? It doesn't exist at the hub atm.

**Comment by AlteredCoder** [comment]
This is not a bug but a normal behavior. If a subnode of a parser doesn't have a name (which is the case for mostly all subnode of all parsers), its name fallback to `child-crowdsecurity/<parser_name>`
