### ISSUE TITLE
CrowdSec not showing updated Nginx bouncer version

### ISSUE THREAD

**Issue by slimshizn** [crowdsecurity/crowdsec#2491]
`cscli bouncer list` shows:

`crowdsec-nginx-bouncer v1.0.4`

Swag docker logs:

`**** Successfully configured CrowdSec nginx Bouncer v1.0.5 ****`

**Comment by LaurenceJJones** [comment]
https://github.com/crowdsecurity/cs-nginx-bouncer/blob/main/nginx/crowdsec_nginx.conf#L6

We haven't bumped the string within the base conf file so it's not an issue but all we need to do is edit the string that is passed
