### ISSUE TITLE
Crowdsec block page can be bypassed by navigating to a subdirectory

### ISSUE THREAD

**Issue by tltglitch** [crowdsecurity/crowdsec#2519]
### What happened?

I am using crowdsec with Nginx proxy manager and it works as expected, however on my testing and running some scans to make sure all my rules and collections are working as expected i noticed when i get banned to access a site for example:

cloud.example.com

if i navigate to cloud.example.com/share/test.text i am able to access to that resource. The ban only applies to the / root of the website. 

Is there a way to fix this ? or this is how crowdsec ban/blocking is suppose to work?

### What did you expect to happen?

I expected to be blocked from all pages of the website cloud.example.com

### How can we reproduce it (as minimally and precisely as possible)?

ban an ip from accessing a website test.com and try to access the ip test.com you get blocked but test.com/new lets you through

### Crowdsec version

<details>
2023/10/04 16:57:27 version: v1.5.4-debian-pragmatic-amd64-e4dcdd25728b914823525f1efabf18d5c454902b
2023/10/04 16:57:27 Codename: alphaga
2023/10/04 16:57:27 BuildDate: 2023-09-20_12:17:53
2023/10/04 16:57:27 GoVersion: 1.20.5
2023/10/04 16:57:27 Platform: linux
2023/10/04 16:57:27 libre2: C++
2023/10/04 16:57:27 Constraint_parser: >= 1.0, <= 2.0
2023/10/04 16:57:27 Constraint_scenario: >= 1.0, < 3.0
2023/10/04 16:57:27 Constraint_api: v1
2023/10/04 16:57:27 Constraint_acquis: >= 1.0, < 2.0

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux/ubuntu - docker 
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Do you have any sort of caching provided by a CDN like cloudflare or by nginx itself?

**Comment by tltglitch** [comment]
That was my first thought after turning off cloudflare caching and putting my account on dev mode to bypass cache waited a few days and tested again still behaves thesame way

**Comment by LaurenceJJones** [comment]
> Thank you @LaurenceJJones for your response. That was my first thought after turning off cloudflare caching and putting my account on dev mode to bypass cache waited a few days and tested again still behaves thesame way

Okay, I will attempt to setup a docker environment with openresty bouncer (Same lua code that npm uses) and see if I can replicate

**Comment by tltglitch** [comment]
Thank you @LaurenceJJones  for your speedy response. I figured it out. I had some misconfiguration my cloudflare side. 

I appreciate it. i will close the thread
