### ISSUE TITLE
KNS BROADBAND NETWORK ISP 

### ISSUE THREAD

**Issue by knsnetwork** [crowdsecurity/crowdsec#2528]
![instasquare.photoeditor.effect.cutout_202392651933450~3.png](https://github.com/crowdsecurity/crowdsec/assets/124529831/494aa749-ef00-46a6-8cfd-e0c6cddfcc97)

**Comment by knsnetwork** [comment]
Hi

**Comment by LaurenceJJones** [comment]
What is this?
