### ISSUE TITLE
Support Nginx non-standard 444 responses

### ISSUE THREAD

**Issue by marcocajon** [crowdsecurity/crowdsec#2553]
### What would you like to be added?

/kind enhancement 
Feature is available but this extends or adds extra functionality

### Why is this needed?

Hey Folks,

I have Crowdsec running on an Ubuntu machine, the daemon is parsing plain text nginx log files, and it works like a charm. However, looking at Grafana I’m getting hundreds of hits from sometimes the same IP address, of course since my web server is set to deflect by returning 444 so these stop quickly, but I am concerned because I expected the nginx-logs parser to be trained to block IP’s with the behavior below (aggressive scanning, I got more than 1000 requests from a group of 7 IPs that were running an endpoint scan). However, this did not happen.

https://app.crowdsec.net/hub/author/crowdsecurity/configurations/nginx-logs

Can the parser YAML be modified to detect and take action against his behavior? Looking at the crowdsec.log file, no actions are action against these IPs, I ran a thorough review of the logs to confirm this. 

**A portion of the large log from nginx, note that Crowdsec has access to this file and is on its acquisitions.** 

97.79.236.49 - - [16/Oct/2023:21:26:49 -0600] “GET /wp-login.php HTTP/1.1” **444** 0 “http://Site.example.comwp-login.php” “Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/95.0”
35.89.141.221 - - [16/Oct/2023:22:28:13 -0600] “GET / HTTP/1.1” **444** 0 “-” “Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36”
107.170.238.43 - - [16/Oct/2023:22:31:44 -0600] “GET /autodiscover/autodiscover.json?@zdi/Powershell HTTP/1.1” **444** 0 “-” “Mozilla/5.0 zgrab/0.x”
107.170.234.6 - - [16/Oct/2023:22:37:21 -0600] “GET /autodiscover/autodiscover.json?@zdi/Powershell HTTP/1.1” **444** 0 “-” “Mozilla/5.0 zgrab/0.x”

http://Site.example.comwp-login.php is just me changing the original site to protect privacy. 

Thanks!

**Comment by LaurenceJJones** [comment]
444 response code has no meaning https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

So we wouldn't create a hub scenario as it would only be useful to you. You can create your own local scenario file to handle these

```
# 404 scan

type: leaky

#debug: true

name: me/444-scans

description: "Detect 444 scanning/probing from a single ip"

filter: "evt.Meta.service == 'http' && evt.Meta.http_status == '444' && evt.Parsed.static_ressource == 'false'"

groupby: "evt.Meta.source_ip + '/' + evt.Parsed.target_fqdn"

capacity: 10

reprocess: true

leakspeed: "10s"

blackhole: 5m

labels:

  remediation: true

  classification:

    - attack.T1595.003

  behavior: "http:scan"

  label: "HTTP Probing"

  spoofable: 0

  service: http

  confidence: 1
```

**Comment by marcocajon** [comment]
Thanks a bunch @LaurenceJJones, I’ll try your custom scenario on my instance, this should be as simple as creating http-probing-444.yml and saving it at the /scenarios directory of my installation and then reloading the service, am I right?

**Comment by LaurenceJJones** [comment]
> Thanks a bunch @LaurenceJJones, I’ll try your custom scenario on my instance, this should be as simple as creating http-probing-444.yml and saving it at the /scenarios directory of my installation and then reloading the service, am I right?
> 
> 

Yes as simple as that. You can see if it works by running a log line through explain and it will show your scenario at the bottom

**Comment by marcocajon** [comment]
Almost there!

time=”18-10-2023 16:50:35” level=fatal msg=”crowdsec init: Failed to load scenarios: scenario loading failed: bad yaml in /etc/crowdsec/scenarios/http-probing-444.yaml : yaml: unmarshal errors:\n  line 13: cannot unmarshal !!seq into string”

**Comment by LaurenceJJones** [comment]
Are you on latest crowdsec version?

**Comment by LaurenceJJones** [comment]
> One last thing, I just noticed that crowdsecurity/http-crawl-non_statics matched in this and other tests, however no actions were taken by it before, I’m new to the logic of the scenarios but is a leakspeed of 0.5s or capacity of 40 enough to trap the bad IPs? Or should I use it a bucket trigger?

It is purely up to you if response code 444 is only likely because its 100% an attacker. Then, yeah, if you would like a fallback, give 1-2 tries before the ban, then lower the capacity of the example I gave you.

**Comment by marcocajon** [comment]
Awesome, you rock @LaurenceJJones, thanks a lot for the custom scenario, just saw this on the daemon log. 

time=”18-10-2023 20:42:50” level=info msg=”Ip 68.183.86.228 performed ‘marcocajon/444-scans’ (6 events over 3.009024536s) at 2023-10-18 20:42:50.785607571 +0000 UTC”
time=”18-10-2023 20:42:50” level=info msg=”(2671d820499445a4b2d2723a9534ad9cprSCcuvLiB11IecE/crowdsec) marcocajon/444-scans by ip 68.183.86.228 (IN/14061) : 4h ban on Ip 68.183.86.228”

I went down from hundreds (in average) to just a few before they get banned. 

![image](https://github.com/crowdsecurity/crowdsec/assets/120045398/dd079651-da29-45f5-baa3-1c54a99c184e)

**Comment by ackphill** [comment]
> 444 response code has no meaning https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses
> 
> So we wouldn't create a hub scenario as it would only be useful to you. You can create your own local scenario file to handle these

@LaurenceJJones 
Since HTTP status code 444, while not standard, is a Nginx-specific response code that indicates an 'explicit' connection termination without sending packets, it may not be suitable for inclusion in a general HTTP parser, but I believe it would be appropriate to include it in a Nginx-specific parser.

And thank you for the custom script. I will put it to good use.

**Comment by LaurenceJJones** [comment]
> it may not be suitable for inclusion in a general HTTP parser, but I believe it would be appropriate to include it in a Nginx-specific parser.

We already parse the information so the scenario should be a drop in, however, I dont know under what setting where nginx would offer this code as for my own production system I used `429` for rate limting. So if we can understand some additional context of when this would occur then it could be something we publish to the hub.

**Comment by ackphill** [comment]
@LaurenceJJones 
As far as I know, there aren't specific situations where 444 naturally occurs. The 444 status code is typically used when you explicitly want to deny a response and send nothing back to the client.

Personally, I use 444 for suspected hacking attempts to avoid providing additional information (such as specific error details) and to prevent wasting resources on further responses.

Since 444 is more of a user preference or need-based implementation, while having scenarios to handle 444 might be convenient, I don't consider it absolutely necessary.
Therefore, as you mentioned, publishing it to the official hub might not be essential.
