### ISSUE TITLE
[AppSec] Status code modsec override

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2700]
### What would you like to be added?

Currently status code only comes from the configuration:

https://github.com/crowdsecurity/crowdsec/blob/da746f77d542d2f594926c9e8b1cee37b88ada67/pkg/acquisition/modules/appsec/appsec_runner.go#L229

However, the user can define within modsec what status code to return, user may get confused if they use own custom rules why this is not respected

/kind enhancement

Coraza has a implementation here:

https://github.com/corazawaf/coraza/blob/b887a580da2c8d76e0abbf8f5e029735d0f89313/http/middleware.go#L166-L177

### Why is this needed?

User custom modsec rules may defined different status codes than just a static `403` and you may want to return different status codes depending on the situation

**Comment by blotus** [comment]
Closed by #2742
