### ISSUE TITLE
[cscli] cscli hang forever when i try to delete a decision

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#2733]
### What happened?

cscli hang forever when i try to delete the decision. 

When checking with pprof, this issue is caused by this line : https://github.com/crowdsecurity/crowdsec/blob/48f011dc1c24d6c31ee47741ab6c4b20e0cf0f16/pkg/apiserver/controllers/v1/decisions.go#L126 . 

Indeed, my instance is enrolled in the console but I don't have PAPI enabled. We can see here: https://github.com/crowdsecurity/crowdsec/blob/48f011dc1c24d6c31ee47741ab6c4b20e0cf0f16/pkg/apiserver/apiserver.go#L247 that we create the channel if the instance is enrolled.

But we consume this channel only if PAPI is enabled: https://github.com/crowdsecurity/crowdsec/blob/48f011dc1c24d6c31ee47741ab6c4b20e0cf0f16/pkg/apiserver/papi.go#L311

### What did you expect to happen?

cscli to return when i delete an IP, even if my instance is enrolled but i have no PAPI enabled

### How can we reproduce it (as minimally and precisely as possible)?

Enroll an instance and try to delete a decisions with cscli decisions delete

### Crowdsec version

<details>

```console
2024/01/12 18:59:30 version: v1.5.6-rc9-14-g3549ed9b
2024/01/12 18:59:30 Codename: alphaga
2024/01/12 18:59:30 BuildDate: 2024-01-11_18:03:44
2024/01/12 18:59:30 GoVersion: 1.21.3
2024/01/12 18:59:30 Platform: linux
2024/01/12 18:59:30 libre2: C++
2024/01/12 18:59:30 Constraint_parser: >= 1.0, <= 3.0
2024/01/12 18:59:30 Constraint_scenario: >= 1.0, <= 3.0
2024/01/12 18:59:30 Constraint_api: v1
2024/01/12 18:59:30 Constraint_acquis: >= 1.0, < 2.0

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by mmetc** [comment]
edit: changed links to permalinks because the code is under refactor
