### ISSUE TITLE
[Docker] Cannot build container from FORK due to no arguments

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2735]
### What happened?

When building crowdsec from a fork you must define the version you are aiming for by default the Makefile tries to get this from GIT, however, within forks there is no version.

### What did you expect to happen?

The Dockerfile should allow build arguments to be passed to the context for example

```
  crowdsec:
    build:
      context: crowdsec
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=v1.5.6
        - BUILD_STATIC=1
 ```

### How can we reproduce it (as minimally and precisely as possible)?

Fork CrowdSec repository and run the following podman or docker command

```
podman build -f crowdsec/Dockerfile -t appsec-dev_crowdsec --build-arg BUILD_VERSION=v1.5.6 --build-arg BUILD_STATIC=1 crowdsec
```

You will get the Makefile error about the version not starting with `v`

### Anything else we need to know?

To fix this it is as easy as defining it as a build argument within the Dockerfile EG:

```
diff --git a/Dockerfile b/Dockerfile
index 3b95ca3c..9bf02a80 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,6 +8,8 @@ WORKDIR /go/src/crowdsec
# We like to choose the release of re2 to use, and Alpine does not ship a static version anyway.
ENV RE2_VERSION=2023-03-01

+ARG BUILD_VERSION
+
```

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by mmetc** [comment]
Why not, I'll do a PR.
Fetching the tags from the original repository works as well.
