### ISSUE TITLE
[AppSec / Api] Dont update bouncer IP on HEAD requests

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2738]
### What happened?

Since the AppSec component uses the same API key as the bouncer itself, when the appsec component sends a HEAD request to check validity it will update the bouncer ip to `127.0.0.1` instead of the bouncer actual IP address

### What did you expect to happen?

HEAD requests should not update the IP address or something must be made so the IP address is the actual bouncer not appsec checking validity 

### How can we reproduce it (as minimally and precisely as possible)?

Implement Appsec and bouncer on a different IP to crowdsecc (I did mine within podman)
```
time="2024-01-14T20:03:23Z" level=info msg="10.89.4.7 - [Sun, 14 Jan 2024 20:03:23 UTC] \"GET /v1/decisions?ip=10.89.4.7 HTTP/1.1 200 8.124925ms \"crowdsec-openresty-bouncer/v1.0.1\" \""
time="2024-01-14T20:03:23Z" level=warning msg="new IP address detected for bouncer 'OR': 127.0.0.1 (old: 10.89.4.7)"
time="2024-01-14T20:03:23Z" level=info msg="127.0.0.1 - [Sun, 14 Jan 2024 20:03:23 UTC] \"HEAD /v1/decisions/stream HTTP/1.1 200 6.872021ms \"Go-http-client/1.1\" \""
```

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by blotus** [comment]
Closed by #2742
