### ISSUE TITLE
http code 405, invalid body: unexpected end of JSON input

### ISSUE THREAD

**Issue by cronyakatsuki** [crowdsecurity/crowdsec#2768]
### What happened?

 I have installed crowdsec on my debian server, after that I added it to my engines using the cscli command and restarted the service.

After that crowdsec doesn't want to launch anymore throwing this error.

```log
time="22-01-2024 10:31:29" level=fatal msg="starting outputs error : authenticate watcher (REDACTED): http code 405, invalid body: unexpected end of JSON input"
``` 

### What did you expect to happen?

Authenticate without issues.

### How can we reproduce it (as minimally and precisely as possible)?

 1. Install on debian with official repo
 2. Create crowdsec account
 3. authenticate
 4. Restart

### Crowdsec version

<details>

```console
$ cscli version
2024/01/22 11:01:59 version: v1.5.5-debian-pragmatic-amd64-d2d788c5dc0a9e387635276623c6781774a9dfd4
2024/01/22 11:01:59 Codename: alphaga
2024/01/22 11:01:59 BuildDate: 2023-10-24_08:03:17
2024/01/22 11:01:59 GoVersion: 1.21.3
2024/01/22 11:01:59 Platform: linux
2024/01/22 11:01:59 libre2: C++
2024/01/22 11:01:59 Constraint_parser: >= 1.0, <= 2.0
2024/01/22 11:01:59 Constraint_scenario: >= 1.0, < 3.0
2024/01/22 11:01:59 Constraint_api: v1
2024/01/22 11:01:59 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux cronyakatsuki.xyz 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
> 1. Install on debian with official repo

The official repository which is maintained by Debian is out of date, to which we have reported multiple times. We suggest using our own repositories [documentation here](https://docs.crowdsec.net/docs/next/getting_started/install_crowdsec) which should resolve your issue.

**Comment by LaurenceJJones** [comment]
Do you have anything else running on the default port of `8080`?

**Comment by cronyakatsuki** [comment]
> > 1. Install on debian with official repo
> 
> The official repository which is maintained by Debian is out of date, to which we have reported multiple times. We suggest using our own repositories [documentation here](https://docs.crowdsec.net/docs/next/getting_started/install_crowdsec) which should resolve your issue.

 I used your documentation to install, didn't use the debian package.

**Comment by LaurenceJJones** [comment]
> > > 1. Install on debian with official repo
> > 
> > 
> > The official repository which is maintained by Debian is out of date, to which we have reported multiple times. We suggest using our own repositories [documentation here](https://docs.crowdsec.net/docs/next/getting_started/install_crowdsec) which should resolve your issue.
> 
> I used your documentation to install, didn't use the debian package.

Yes I read it wrong and updated my comment

**Comment by cronyakatsuki** [comment]
> Do you have anything running on the default port of `8080`?
> 
> ```shell
> sudo ss -lntp
> ```
> 
> Could you expand what you mean by `I have installed crowdsec on my debian server, after that I added it to my engines using the cscli command and restarted the service.`?
> 
> So is it a multi server and this server is talking to another?

I explained it incorrectly, I mean't that I installed it on my dedicated hetzner server, and then enrolled it to the crowdsec console with the provided command in the console.

At first I had a minuflux server on port 8080 so I changed the crowdsec's port to a different one, which then showed me this error.

I have now moved miniflux on different port and moved crowdsec back to 8080, which did start it correctly, now I'm trying to restart it again and see if that fixes it completely or it was a lucky start.

**Comment by cronyakatsuki** [comment]
Yes moving miniflux to different port and getting crowdsec to listen on port `8080` again fixed this issue.

Should this be added to the documentation so that it's explicit that port 8080 is needed for crowdsec to work or is this a different issue?

**Comment by LaurenceJJones** [comment]
> I have now moved miniflux on different port and moved crowdsec back to 8080, which did start it correctly, now I'm trying to restart it again and see if that fixes it completely or it was a lucky start.

You can change CrowdSec port it just there two files to change

```
/etc/crowdsec/config.yaml
/etc/crowdssec/local_api_credentials.yaml
```

The error about 405 was because miniflux was responding to the http call

**Comment by cronyakatsuki** [comment]
Thanks, everything clear now I have only changed the port in `/etc/crowdsec/config.yaml`.

Thanks for the explanation.
