### ISSUE TITLE
[cscli] Machines add stdout example

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2774]
https://github.com/crowdsecurity/crowdsec/blob/84606eb2073f12009ef019926936e4d7263ac052/cmd/crowdsec-cli/machines.go#L209-L213

There is no example of how to write to stdout `cscli machines add -f- --auto` and user didn't know this was a feature.

Something like `cscli machines add -f- --auto > /tmp/mycreds.yaml`

**Comment by mmetc** [comment]
Thanks! I'm updating cscli machines, will add it to that branch

**Comment by mmetc** [comment]
well, it's the latest commit of this PR

https://github.com/crowdsecurity/crowdsec/pull/2777/commits/814f1e8b9f5fce1f08ba176146a44c65c63e66a1

I wanted to merge bouncers first, then machines... but we can also merge all at once
