### ISSUE TITLE
[deb] Package should depend on cron

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [crowdsecurity/crowdsec#2796]
### What happened?

I think the crowdsec package for debian/ubuntu should (optionally?) depend on cron

### What did you expect to happen?

I can remove cron without apt notifying me that it might prevent crowdsec from working properly

### How can we reproduce it (as minimally and precisely as possible)?

`sudo apt install crowdsec; sudo apt remove cron`

### Crowdsec version

<details>

```console
2024/01/30 14:33:12 version: v1.6.0-debian-pragmatic-amd64-4b8e6cd7
2024/01/30 14:33:12 Codename: alphaga
2024/01/30 14:33:12 BuildDate: 2024-01-24_11:01:12
2024/01/30 14:33:12 GoVersion: 1.21.3
2024/01/30 14:33:12 Platform: linux
2024/01/30 14:33:12 libre2: C++
2024/01/30 14:33:12 Constraint_parser: >= 1.0, <= 3.0
2024/01/30 14:33:12 Constraint_scenario: >= 1.0, <= 3.0
2024/01/30 14:33:12 Constraint_api: v1
2024/01/30 14:33:12 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux XXXXXXXX.stratoserver.net 5.4.0 #1 SMP Wed Jul 12 12:00:44 MSK 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**Comment by blotus** [comment]
Hello,

Crowdsec itself does not use cron directly: we do install a cron to make sure the hub stays up-to-date, but if cron is not installed I wouldn't expect it to break anything (ie, your crowdsec installation will keep working as normal, you just won't have access  to the latest parsers/scenarios automatically).

Did you encounter an actual error with crowdsec after uninstalling cron ?

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
I get that. But from my understanding, it would get outdated quickly and degrade the quality of the detections. Is it actually feasible to run crowdsec without the update cron job?

**Comment by blotus** [comment]
Yes, crowdsec itself will work just fine, you just won't have the latest scenarios/appsec-rules or fixes in parsers.
Whether this is actually important or not will vary depending on which collections you use (some are rarely updated, other are updated more regularly).

Anyway, we'll have a look to add `cron` as a suggested package (I don't want to have a very strong dependency, as it's not strictly necessary for crowdsec to work, but it should let apt know that the packages are somehow related)
