### ISSUE TITLE
Missing RPM packages for Fedora 39

### ISSUE THREAD

**Issue by pschiffe** [crowdsecurity/crowdsec#2818]
### What happened?

Fedora 38:
```bash
$ dnf search crowdsec
Last metadata expiration check: 1:13:31 ago on Wed 07 Feb 2024 09:52:34 PM UTC.
============================================================================== Name & Summary Matched: crowdsec ===============================================================================
crowdsec.aarch64 : Crowdsec - An open-source, lightweight agent to detect and respond to bad behaviors. It also automatically benefits from our global community-wide IP reputation database
crowdsec-aws-waf-bouncer.aarch64 : AWS WAF bouncer for Crowdsec
crowdsec-blocklist-mirror.aarch64 : CrowdSec blocklist mirror
crowdsec-cloudflare-bouncer.aarch64 : cloudflare bouncer for Crowdsec
crowdsec-cloudflare-worker-bouncer.aarch64 : cloudflare-worker bouncer for Crowdsec
crowdsec-custom-bouncer.aarch64 : Custom bouncer for Crowdsec
crowdsec-firewall-bouncer-iptables.aarch64 : Firewall bouncer for Crowdsec (iptables+ipset configuration)
crowdsec-firewall-bouncer-nftables.aarch64 : Firewall bouncer for Crowdsec (nftables configuration)
crowdsec-openresty-bouncer.aarch64 : OpenResty bouncer for Crowdsec
```

Fedora 39:
```bash
$ dnf search crowdsec
Last metadata expiration check: 0:09:42 ago on Wed 07 Feb 2024 11:56:58 PM CET.
============================================================================== Name & Summary Matched: crowdsec ===============================================================================
crowdsec.x86_64 : Crowdsec - An open-source, lightweight agent to detect and respond to bad behaviors. It also automatically benefits from our global community-wide IP reputation database
crowdsec-custom-bouncer.x86_64 : Custom bouncer for Crowdsec
crowdsec-openresty-bouncer.x86_64 : OpenResty bouncer for Crowdsec
```

From the official repo on packagecloud.io.

### What did you expect to happen?

The same packages should be offered for F38 and F39.

### How can we reproduce it (as minimally and precisely as possible)?

https://doc.crowdsec.net/docs/next/getting_started/install_crowdsec/

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by pschiffe** [comment]
Fedora 39 is still missing packages and there are no packages for Fedora 40
https://packagecloud.io/app/crowdsec/crowdsec/search?q=&filter=rpms&dist=fedora

**Comment by LaurenceJJones** [comment]
> Fedora 39 is still missing packages and there are no packages for Fedora 40 https://packagecloud.io/app/crowdsec/crowdsec/search?q=&filter=rpms&dist=fedora

Currently we are transitioning over to an `any/any` model which allows us to support all distros and versions. We have got this working for deb based systems, and @sabban is currently working on RPM side. Once this is added I believe he will let you know.

**Comment by kalaklanar** [comment]
This is still an issue with whatever the latest Fedora Release is. Now, Fedora 41 is missing packages.
https://packagecloud.io/app/crowdsec/crowdsec/search?q=&filter=all&dist=fedora%2F41&arch= shows no results.
I posted this in the Discord as a yum packaging issue, but it seems like this issue is the root cause:
```
root@f41server:/etc/yum.repos.d# dnf install crowdsec
Updating and loading repositories:
 Fedora 41 openh264 (From Cisco) - x86_ 100% |   5.4 KiB/s |   6.0 KiB |  00m01s
 Fedora 41 - x86_64 - Updates           100% |   1.8 MiB/s |   4.3 MiB |  00m02s
 Fedora 41 - x86_64                     100% |   3.6 MiB/s |  35.4 MiB |  00m10s
 crowdsec_crowdsec                      100% |   1.0 KiB/s |   1.9 KiB |  00m02s
 crowdsec_crowdsec-source               100% |   1.2 KiB/s |   1.9 KiB |  00m02s
Repositories loaded.
Failed to resolve the transaction:
No match for argument: crowdsec
You can try to add to command line:
  --skip-unavailable to skip unavailable packages```

**Comment by LaurenceJJones** [comment]
> This is still an issue with whatever the latest Fedora Release is. Now, Fedora 41 is missing packages. https://packagecloud.io/app/crowdsec/crowdsec/search?q=&filter=all&dist=fedora%2F41&arch= shows no results. I posted this in the Discord as a yum packaging issue, but it seems like this issue is the root cause:
> 
> ```
> root@f41server:/etc/yum.repos.d# dnf install crowdsec
> Updating and loading repositories:
>  Fedora 41 openh264 (From Cisco) - x86_ 100% |   5.4 KiB/s |   6.0 KiB |  00m01s
>  Fedora 41 - x86_64 - Updates           100% |   1.8 MiB/s |   4.3 MiB |  00m02s
>  Fedora 41 - x86_64                     100% |   3.6 MiB/s |  35.4 MiB |  00m10s
>  crowdsec_crowdsec                      100% |   1.0 KiB/s |   1.9 KiB |  00m02s
>  crowdsec_crowdsec-source               100% |   1.2 KiB/s |   1.9 KiB |  00m02s
> Repositories loaded.
> Failed to resolve the transaction:
> No match for argument: crowdsec
> You can try to add to command line:
>   --skip-unavailable to skip unavailable packages
> ```

Yes we are currently working on this, hopefully should be released this week.

I will update this thread once it is available and working, you will have to re run the installation script again once it is live though.

**Comment by LaurenceJJones** [comment]
Classing as resolved, however, if you used the older installation method you must re run the following command:

```
curl -s https://install.crowdsec.net | sudo sh
```

This will force the new naming schemas on the rpm `any:any` install

**Comment by pschiffe** [comment]
Thank you for the issue fix! Looking at https://packagecloud.io/app/crowdsec/crowdsec/search?dist=any it seems that we will have to wait for next releases before the packages will be available there? Deb seems to be OK, but most RPM packages are missing, so for example, I'm not able to install firewall bouncer on Fedora now.

**Comment by LaurenceJJones** [comment]
> Thank you for the issue fix! Looking at https://packagecloud.io/app/crowdsec/crowdsec/search?dist=any it seems that we will have to wait for next releases before the packages will be available there? Deb seems to be OK, but most RPM packages are missing, so for example, I'm not able to install firewall bouncer on Fedora now.

Thank you for notifying us, it was there pre new year 😅 we will look into it!

**Comment by Typhora** [comment]
Can you explain to me why this issue is closed when this is a recurrent issue over every single fedora release? There is a realease every 6 months you should be able to anticipate that by now...

**Comment by blotus** [comment]
We have been providing generic packages for all RPM based distribution for quite a while now.

If you don't see recent packages, you need to run `curl -s https://install.crowdsec.net | sudo sh` to switch to the generic repo, or follow the [manual instructions](https://docs.crowdsec.net/u/getting_started/installation/linux/#manual-repository-installation).

**Comment by Typhora** [comment]
then explain this :```
 >>> Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://packagecloud.io/crowdsec/crowdsec/rpm_any/rpm_any/SRPMS/repodata/repomd.xml [error adding trust anchors from file: /etc/pki/tls/certs/ca-bundle.crt] - https://packagecloud.io/crowdsec/crowdsec/rpm_any/rpm_any/SRPMS/repodata/repomd.xml
>>> An Curl handle error
```
Before to assume something maybe test your own system first...

**Comment by blotus** [comment]
I personally don't use fedora, and don't have access to a fedora machine at the moment, but just using curl on the file seems to work for me:
```
~ ᐅ curl https://packagecloud.io/crowdsec/crowdsec/rpm_any/rpm_any/SRPMS/repodata/repomd.xml   -L
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo">
  <data type="other">
....
```

It looks like you are the only one reporting this at the moment, so it might be an issue on your end.

PS: Try to be kinder when people are trying to help you, it will go a long way.

**Comment by Typhora** [comment]
there are no issue on my end because there is no manual modification on this VM about this. So it is a simple VM transitioning from 43 to 44. 
If migration procedure are not handled correctly by the maintainers that's what happens usually.
And I am just cold. Not rude. not antagonistic. But do you know how many packages I need to report because of badly transitioning from one fedora version to another ? And usually it is always the same. Tor, crowdsec, suricata.
There is obviously a problem with your SSL certificate.
For the moment crowdsec version is provided by the main fedora repository, not by the one it is supposed to be providing.

**Comment by Typhora** [comment]
proof that there is a problem with the SSL transitionning: 
after having changed to no check : 
```
 https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-EDE2C695 100% |   4.0 KiB/s |   2.4 KiB |  00m01s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey                            100% |   6.2 KiB/s |   3.9 KiB |  00m01s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-C822EDD6 100% |   3.8 KiB/s |   2.4 KiB |  00m01s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314 100% |  11.4 KiB/s |   2.4 KiB |  00m00s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey                            100% |  18.2 KiB/s |   3.9 KiB |  00m00s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-EDE2C695 100% |  11.0 KiB/s |   2.4 KiB |  00m00s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-C822EDD6 100% |  11.1 KiB/s |   2.4 KiB |  00m00s
 https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314 100% |  11.2 KiB/s |   2.4 KiB |  00m00s
Importing OpenPGP key 0x6E93CD0C:
 UserID     : "https://packagecloud.io/crowdsec/crowdsec (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 6A89E3C2303A901A889971D3376ED5326E93CD0C
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0xEA83274E:
 UserID     : "Crowdsec Rpm Archive <support@crowdsec.net>"
 Fingerprint: 781AD9A69D9EAB7C6B4773ED02DA1539EA83274E
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-EDE2C695EC9A5A5C.pub.gpg
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0x145CE2F2:
 UserID     : "Crowdsec Team <debian@crowdsec.net>"
 Fingerprint: 79B8CC3F94472AC862A8AD8DB06F1981145CE2F2
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-C822EDD6B39954A1.pub.gpg
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0x3CDF0DB4:
 UserID     : "Crowdsec Rpm Archive <support@crowdsec.net>"
 Fingerprint: 9082D8CACBBEB0DAB218BAB04C3D386C3CDF0DB4
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0x6E93CD0C:
 UserID     : "https://packagecloud.io/crowdsec/crowdsec (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 6A89E3C2303A901A889971D3376ED5326E93CD0C
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0xEA83274E:
 UserID     : "Crowdsec Rpm Archive <support@crowdsec.net>"
 Fingerprint: 781AD9A69D9EAB7C6B4773ED02DA1539EA83274E
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-EDE2C695EC9A5A5C.pub.gpg
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0x145CE2F2:
 UserID     : "Crowdsec Team <debian@crowdsec.net>"
 Fingerprint: 79B8CC3F94472AC862A8AD8DB06F1981145CE2F2
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-C822EDD6B39954A1.pub.gpg
Is this ok [y/N]: y
The key was successfully imported.
Importing OpenPGP key 0x3CDF0DB4:
 UserID     : "Crowdsec Rpm Archive <support@crowdsec.net>"
 Fingerprint: 9082D8CACBBEB0DAB218BAB04C3D386C3CDF0DB4
 From       : https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
Is this ok [y/N]: y
The key was successfully imported.
```
so the migration clearly has done be handled well at the code level for the hosting provider of the packages of crowdsec. So please contact them if you can.

**Comment by jmaliska** [comment]
> then explain this :```
> 
> > > > Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://packagecloud.io/crowdsec/crowdsec/rpm_any/rpm_any/SRPMS/repodata/repomd.xml [error adding trust anchors from file: /etc/pki/tls/certs/ca-bundle.crt] - https://packagecloud.io/crowdsec/crowdsec/rpm_any/rpm_any/SRPMS/repodata/repomd.xml
> > > > An Curl handle error
> 
> ```
> Before to assume something maybe test your own system first...
> ```

https://jeer.fr/fr/blog/fedora-44-fixing-the-crowdsec-repo-after-upgrade

**Comment by Typhora** [comment]
as I said, migration not handled carefully in the code itself as the blog states and shows. 
Thanks @jmaliska
