### ISSUE TITLE
/etc/crowdsec/acquis.yaml is a directory inside the docker container, keeps restarting.

### ISSUE THREAD

**Issue by it9exm** [crowdsecurity/crowdsec#2823]
### What happened?

As from the title.
crowdsecurity/crowdsec:latest on docker hub is having this hiccup.
Can you please take care of it?

### What did you expect to happen?

I think that is supposed to be a file path.

### How can we reproduce it (as minimally and precisely as possible)?

Just spin up the container.

### Anything else we need to know?

Here's the relevant log excerpt:

time="2024-02-08T18:06:37Z" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"
time="2024-02-08T18:06:37Z" level=fatal msg="crowdsec init: while loading acquisition config: failed to yaml decode /etc/crowdsec/acquis.yaml: yaml: input error: read /etc/crowdsec/acquis.yaml: is a directory"

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by blotus** [comment]
Hello,

How do you start the container ? Do you mount any volume/files in it (a custom acquisition configuration for example) ?
Just running `docker run  crowdsecurity/crowdsec:latest` looks ok on my end.

Can you also run `docker pull crowdsecurity/crowdsec:latest` to make sure you are actually using the latest version of the `latest` tag ?

**Comment by it9exm** [comment]
Image is up to date.
I'm using docker-compose with the following boilerplate:
https://github.com/JamesTurland/JimsGarage/blob/main/Crowdsec/docker-compose.yml
But if I start only the container with docker run the file is in its place. Sorry for this report

**Comment by blotus** [comment]
The error is probably because you are trying to mount a non-existing file in the container, for example:
```
$ ls /tmp/sakdhlalskdg/acquis.yaml
ls: cannot access '/tmp/sakdhlalskdg/acquis.yaml': No such file or directory
$ docker run --rm -v /tmp/sakdhlalskdg/acquis.yaml:/etc/crowdsec/acquis.yaml crowd security/crowdsec:latest
.....
time="2024-02-08T18:49:40Z" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"
time="2024-02-08T18:49:40Z" level=fatal msg="crowdsec init: while loading acquisition config: failed to yaml decode /etc/crowdsec/acquis.yaml: yaml: input error: read /etc/crowdsec/acquis.yaml: is a directory"
```

The dockerfile you linked wants the file to be in `/home/ubuntu/docker/crowdsec/acquis.yaml` (https://github.com/JamesTurland/JimsGarage/blob/main/Crowdsec/docker-compose.yml#L10).

Make sure the file is in the proper place or update the path in the Dockerfile (note that docker will have created the directory `/home/ubuntu/docker/crowdsec/acquis.yaml` on the host when you first ran the container, so you may want to remove it)

**Comment by ToXinE** [comment]
same problem here with, the `docker-compose.yml` file create an `acquis.yaml` DIRECTORY in the crowdsec path. I've setup some files in the `/etc/crowdsec/acquis.d` directory and none for acquis.yaml.

**Comment by LaurenceJJones** [comment]
> same problem here with, the `docker-compose.yml` file create an `acquis.yaml` DIRECTORY in the crowdsec path. I've setup some files in the `/etc/crowdsec/acquis.d` directory and none for acquis.yaml.

It is because by default, docker creates directories. If the file doesn't exist, we have no control over this behaviour

**Comment by MadJalapeno** [comment]
Just had the same problem - the docker-compose file was looking for acquis.yaml, and I had acquis.yml.

yaml is not the same as yml
