### ISSUE TITLE
Validate configuration before reloading crowdsec in the cron

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#2831]
The cron installed by default will reload crowdsec automatically if the hub was updated, but it won't check if the configuration is valid first.
This can lead to an outage if any part of the configuration is invalid.

**Comment by mmetc** [comment]
This should be done in systemd (ExecReload) so we're sure there is a trace in the logs, no? cron output often goes to /dev/null

**Comment by mmetc** [comment]
Having read https://github.com/systemd/systemd/issues/2175

I see the solution would be

`ExecReload=sh -c '/usr/local/bin/crowdsec -t /etc/crowdsec/config.yaml && /bin/kill -HUP $MAINPID'`

*but* from what I see in the above issue, shouldn't we also notify systemd of reload, stop etcetera?

https://github.com/coreos/go-systemd/blob/main/daemon/sdnotify.go
