### ISSUE TITLE
Postoverflow country whitelist is ignored

### ISSUE THREAD

**Issue by pschiffe** [crowdsecurity/crowdsec#2849]
### What happened?

I have a postoverflow country whitelist:
```yaml
name: ws/country_whitelist
description: country whitelist
whitelist:
  reason: whitelist based on country
  expression:
    - evt.Enriched.IsoCode == 'SK'
    - evt.Enriched.IsoCode == 'CZ'
```

```
$ docker exec -it crowdsec cscli postoverflows list

POSTOVERFLOWS
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name                               📦 Status          Version   Local Path                                                          
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 crowdsecurity/cdn-whitelist        ✔️ enabled          0.4       /etc/crowdsec/postoverflows/s01-whitelist/cdn-whitelist.yaml        
 crowdsecurity/rdns                 ✔️ enabled          0.3       /etc/crowdsec/postoverflows/s00-enrich/rdns.yaml                    
 crowdsecurity/seo-bots-whitelist   ✔️ enabled          0.4       /etc/crowdsec/postoverflows/s01-whitelist/seo-bots-whitelist.yaml   
 ws/country_whitelist        🏠 enabled,local             /etc/crowdsec/postoverflows/s01-whitelist/ws_country_whitelist.yaml 
 ws/rdns_whitelist           🏠 enabled,local             /etc/crowdsec/postoverflows/s01-whitelist/ws_rdns_whitelist.yaml    
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

```
$ docker exec -it crowdsec cscli postoverflows inspect ws/country_whitelist
type: postoverflows
stage: s01-whitelist
name: ws/country_whitelist
file_name: ws_country_whitelist.yaml
local_path: /etc/crowdsec/postoverflows/s01-whitelist/ws_country_whitelist.yaml
installed: true
downloaded: false
uptodate: true
tainted: false
local: true

Current metrics:
```

It's loaded based on the logs:
```
time="2024-02-18T22:24:03Z" level=info msg="Loading postoverflow parsers"
time="2024-02-18T22:24:03Z" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/postoverflows/s00-enrich/rdns.yaml stage=s00-enrich
time="2024-02-18T22:24:03Z" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/postoverflows/s01-whitelist/cdn-whitelist.yaml stage=s01-whitelist
time="2024-02-18T22:24:03Z" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/postoverflows/s01-whitelist/seo-bots-whitelist.yaml stage=s01-whitelist
time="2024-02-18T22:24:03Z" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/postoverflows/s01-whitelist/ws_country_whitelist.yaml stage=s01-whitelist
time="2024-02-18T22:24:03Z" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/postoverflows/s01-whitelist/ws_rdns_whitelist.yaml stage=s01-whitelist
time="2024-02-18T22:24:03Z" level=info msg="Loaded 5 nodes from 2 stages"
```

But even after that:
```
time="2024-02-18T22:57:10Z" level=info msg="Ip 90..38 performed 'crowdsecurity/postfix-spam' (6 events over 1.206752701s) at 2024-02-18 22:57:10.533036756 +0000 UTC"
time="2024-02-18T22:57:11Z" level=info msg="(localhost/crowdsec) crowdsecurity/postfix-spam by ip 90..38 (SK/15962) : 168h ban on Ip 90..38"
time="2024-02-18T22:57:16Z" level=info msg="Signal push: 1 signals to push"
```

### What did you expect to happen?

To not get ban on IP from whitelisted country.

### How can we reproduce it (as minimally and precisely as possible)?

Described above.

### Crowdsec version

<details>

```console
$ cscli version
2024/02/18 23:48:36 version: v1.6.0-4192af30
2024/02/18 23:48:36 Codename: alphaga
2024/02/18 23:48:36 BuildDate: 2024-01-31_13:41:30
2024/02/18 23:48:36 GoVersion: 1.21.6
2024/02/18 23:48:36 Platform: docker
2024/02/18 23:48:36 libre2: C++
2024/02/18 23:48:36 Constraint_parser: >= 1.0, <= 3.0
2024/02/18 23:48:36 Constraint_scenario: >= 1.0, <= 3.0
2024/02/18 23:48:36 Constraint_api: v1
2024/02/18 23:48:36 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Hey 👋 

`evt.Enriched` does not exist on postoverflow overflow object due to it switching to an Alert.

You should be able to access it via `evt.Overflow.Alert.Source.Cn` 


https://docs.crowdsec.net/docs/next/whitelist/intro

**Comment by pschiffe** [comment]
Hi @LaurenceJJones, thank you. OK, so the issue here is that I was reading the docs for 1.5, which is still the default when you open the docs. However, on the [next docs](https://docs.crowdsec.net/docs/next/whitelist/create_postoverflow), it still shows to use `evt.Enriched` and the note only says that `evt.Parsed` is not available (and to use `evt.Overflow`).

**Comment by LaurenceJJones** [comment]
> Hi @LaurenceJJones, thank you. OK, so the issue here is that I was reading the docs for 1.5, which is still the default when you open the docs. However, on the [next docs](https://docs.crowdsec.net/docs/next/whitelist/create_postoverflow), it still shows to use `evt.Enriched` and the note only says that `evt.Parsed` is not available (and to use `evt.Overflow`).

My bad that an error on my behalf, I will rectify it

**Comment by LaurenceJJones** [comment]
Okay I investigated it more "technically" it not an error since the example shown is the enrichment provided by the post overflows

You just cant access previous past enrichment

**Comment by pschiffe** [comment]
I mean, I understand and I leave it up to you, but maybe you could add at least one more example to that postoverflow whitelist page with the `evt.Overflow` field, as it now indicates that using `evt.Enriched` is fine and should work in all cases. Just my suggestion. Have a nice day!

**Comment by LaurenceJJones** [comment]
> I mean, I understand and I leave it up to you, but maybe you could add at least one more example to that postoverflow whitelist page with the `evt.Overflow` field, as it now indicates that using `evt.Enriched` is fine and should work in all cases. Just my suggestion. Have a nice day!

Yeah, its my plan to add some more examples of common use cases EG overflow source country
