### ISSUE TITLE
[CrowdSec CTI] Use custom useragent

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2864]
### What would you like to be added?

For CTI analytics we should send a custom useragent since we cannot distinguish usage 

https://github.com/crowdsecurity/crowdsec/blob/8e9e091656f2a72a37e21c173ed0c2015e97e726/pkg/cticlient/client.go#L34-L69

/kind enhancement

### Why is this needed?

To improve our analytics so we can improve the service for Security Engine if errors are detected

**Comment by mmetc** [comment]
When doing this we might as well define the useragents in a single place instead of building "crowdsec/" + csversion.String() every time.
