### ISSUE TITLE
[enhancement] cscli support dump collect pprofs

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2937]
In many cases pprofs can be useful to see cpu/memory/goroutines which is an endpoint which is enabled on the LAPI side. When a user runs `cscli support dump` we should collect this information and store it within the zipped output.

/kind enhancement

**Comment by mmetc** [comment]
done in https://github.com/crowdsecurity/crowdsec/pull/2987 which includes logs and a refactoring
