### ISSUE TITLE
crowdsecurity/crowdsec docker image is outdated: latest == 1.6.0

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [crowdsecurity/crowdsec#2944]
### What happened?

Docker image is outdated. Latest available stable version is 1.6.0

### What did you expect to happen?

Please update docker image to version 1.6.1

### How can we reproduce it (as minimally and precisely as possible)?

https://hub.docker.com/r/crowdsecurity/crowdsec/tags

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Yes, this is on purpose by the team to ensure a gradual rollout

**Comment by Sad-Soul-Eater** [comment]
The docker image was updated, thank you :+1:
