### ISSUE TITLE
Log processor `last_push` / `created_at` are always updated.

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#2980]
In the DB schema, the `last_push` and `created_at` fields have an `UpdateDefault` value, which means that they will get updated each time we write to a LP row (for example, when we receive a heartbeat).

`last_push` should only be updated when LAPI actually receives a signal, and `created_at` should never be touched after the creation.

**Comment by mmetc** [comment]
done in https://github.com/crowdsecurity/crowdsec/pull/2981
