### ISSUE TITLE
deb package for ubuntu noble (24.04 LTS)

### ISSUE THREAD

**Issue by dionysius** [crowdsecurity/crowdsec#3030]
### What would you like to be added?

According to the list on [packagecloud](https://packagecloud.io/crowdsec/crowdsec) there are no packages yet for ubuntu noble [which has been out for a month now](https://canonical.com/blog/canonical-releases-ubuntu-24-04-noble-numbat).

### Why is this needed?

noble is the next ubuntu LTS release

**Comment by LaurenceJJones** [comment]
We already support `any/any` packaging type. Please use the following script to install an upgraded repository

```
curl -s https://install.crowdsec.net | sudo sh
```

if not you can see manual instructions here https://docs.crowdsec.net/u/getting_started/installation/linux

**Comment by LaurenceJJones** [comment]
but we tested it and it already installable using the new script

**Comment by LaurenceJJones** [comment]
If you normally download the deb directly from packagecloud there search is not upgraded to find `any/any` so here a direct link

https://packagecloud.io/crowdsec/crowdsec/packages/any/any/crowdsec_1.6.1_amd64.deb

**Comment by dionysius** [comment]
Indeed it does use `any`:

```
root@noble-test:~# curl -s https://install.crowdsec.net | sudo sh
Detected operating system as ubuntu/24.
Detected apt version as 2.7.14
Checking for gpg...
Detected gpg...
Checking for curl...
Detected curl...
Scanning processes...

Importing packagecloud gpg key...

Packagecloud gpg key imported to /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg

Installing /etc/apt/sources.list.d/crowdsec_crowdsec.list...

root@noble-test:~# cat /etc/apt/sources.list.d/crowdsec_crowdsec.list
deb [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/any/ any main
deb-src [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/any/ any main
```

---

Be prepared that in August (when the first dot release happens and the lts upgrade path is open) people might open issues when they try to upgrade from jammy to xenial with `do-release-upgrade`, since it will replace `jammy` with `noble` in all apt sources files. My current jammy system apt repo was:
```
# lxc exec proxy -- cat /etc/apt/sources.list.d/crowdsec_crowdsec.list
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/crowdsec/crowdsec

deb [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ jammy main
deb-src [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ jammy main
```
