### ISSUE TITLE
consider adding crowdsec to extrepo

### ISSUE THREAD

**Issue by dionysius** [crowdsecurity/crowdsec#3031]
### What would you like to be added?

[extrepo manpage]()

> The extrepo tool is used to manage external repositories in Debian. Before extrepo, users who wished to use software not packaged for Debian had to manually write the apt configuration files, run an unsigned script as root, or install an unsigned .deb package that contained all the configuration on their system. None of these methods were very secure.
> 
> Extrepo remedies this by way of a metadata repository for external package repositories. The user can search the list of metadata repositories by way of "extrepo search", and manage them through "extrepo enable", "extrepo disable", or "extrepo update".

The extrepo-metadata archive can be found in [extrepo-data](https://salsa.debian.org/extrepo-team/extrepo-data/)

/kind package

### Why is this needed?

So users don't have to execute a potentially untrusted script from the internet as root to just install a repository

**Comment by LaurenceJJones** [comment]
We love this idea, but don't want to maintain it ourselves since we already put a lot of effort into having various platforms supported.

So I will class this as not planned for now but if we have capacity in the future then we can take a look.
