### ISSUE TITLE
wizard.sh dependencies

### ISSUE THREAD

**Issue by ghost** [crowdsecurity/crowdsec#31]
In order to be able to port crowdsec and `wizard.sh` we should document properly the exact dependencies we rely on. So far I noticed:
* bash (obviously, the script is executed by bash)
* gettext (gettext-base in debian based distribution to be able to use envsubst)
* systemd. Wizard can't install anything on a sysvinit based system

**Comment by ThomasLohner** [comment]
In my case i also needed to install `whiptail` on Ubuntu 18.04 inside a docker container.

**Comment by erenJag** [comment]
Hi,

Thanks for your feedback guys !
This was fixed in the [README](https://github.com/crowdsecurity/crowdsec/blob/master/README.md#arrow_down-install-it-).

You can close the issue if it's ok for you.
