### ISSUE TITLE
Dashboard Setup fails - EOF

### ISSUE THREAD

**Issue by Tragyn** [crowdsecurity/crowdsec#3142]
### What happened?

When trying to start dashboard, the command prompts for Y/n but fails before input can be given, with EOF and a string of characters are displayed on the next prompt

### What did you expect to happen?

Dashboard setup to proceed

### How can we reproduce it (as minimally and precisely as possible)?

```
root@wu:~# sudo docker exec crowdsec cscli dashboard setup --listen 0.0.0.0 --port 8091
level=warning msg="You are potentially exposing your metabase port to the internet (addr: 0.0.0.0), please consider using a reverse proxy"
? CrowdSec takes no responsibility for the security of your metabase instance. Do you accept these responsibilities ? (Y/n) level=fatal msg="unable to ask to question: EOF"
root@wu:~# 0;83R42R
```

### Crowdsec version

<details>
version: v1.6.2-16bfab86
Codename: alphaga
BuildDate: 2024-06-05_14:25:55
GoVersion: 1.22.3
Platform: docker
libre2: C++
User-Agent: crowdsec/v1.6.2-16bfab86-docker
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0
</details>

### OS version

<details>
unRAID 7
```console
# On Linux:
$ cat /etc/os-release
NAME=Slackware
VERSION="15.0"
ID=slackware
VERSION_ID=15.0
PRETTY_NAME="Slackware 15.0 x86_64 (post 15.0 -current)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:15.0"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=current

$ uname -a
Linux wu 6.8.12-Unraid #3 SMP PREEMPT_DYNAMIC Tue Jun 18 07:52:57 PDT 2024 x86_64 12th Gen Intel(R) Core(TM) i5-12400 GenuineIntel GNU/Linux
</details>


### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
Global:
   - Configuration Folder   : /etc/crowdsec
   - Data Folder            : /var/lib/crowdsec/data
   - Hub Folder             : /etc/crowdsec/hub
   - Simulation File        : /etc/crowdsec/simulation.yaml
   - Log Folder             : /var/log
   - Log level              : info
   - Log Media              : stdout
Crowdsec:
  - Acquisition File        : /etc/crowdsec/acquis.yaml
  - Parsers routines        : 1
  - Acquisition Folder      : /etc/crowdsec/acquis.d
cscli:
  - Output                  : human
  - Hub Branch              : 
API Client:
  - URL                     : http://0.0.0.0:8080/
  - Login                   : localhost
  - Credentials File        : /etc/crowdsec/local_api_credentials.yaml
Local API Server:
  - Listen URL              : 0.0.0.0:8080
  - Listen Socket           : 
  - Profile File            : /etc/crowdsec/profiles.yaml

  - Trusted IPs:
      - 127.0.0.1
      - ::1
  - Database:
      - Type                : sqlite
      - Path                : /var/lib/crowdsec/data/crowdsec.db
      - Flush age           : 7d
      - Flush size          : 5000
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by blotus** [comment]
Hello,

This occurs because this command is interactive, you need to pass `-it` to the docker command to enable a TTY and keep stdin open.

Note that running `cscli dashboard setup` inside a container will not work, as it creates a container to run the metabase instance.
If you want to run it, we have an example docker compose [here](https://github.com/crowdsecurity/example-docker-compose/tree/main/basic).

Also, we are in the process of deprecating `cscli dashboard`, you can see the reasons [here](https://docs.crowdsec.net/blog/cscli_dashboard_deprecation/) (we will still provide a way to have local visualization, but it will be outside of crowdsec itself).

If you want data visualization, I'd recommend using https://app.crowdsec.net instead.
