### ISSUE TITLE
[hubtest] cscli hubtest explain verbose

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#3160]
### What would you like to be added?

In cscli explain we have a verbose flag that shows the details, but hubtest does not have the same flag which contains useful details when creating parsers/scenarios

/kind enhancement

### Why is this needed?

Already stated

**Comment by mmetc** [comment]
After https://github.com/crowdsecurity/crowdsec/pull/3174

**Comment by mmetc** [comment]
Can we merge?

https://github.com/crowdsecurity/crowdsec/pull/3162
