### ISSUE TITLE
After pull i get hash mismatch error

### ISSUE THREAD

**Issue by mourningsun75** [crowdsecurity/crowdsec#3186]
### What happened?

I always update by calling the following steps:

docker compose stop
docker compose pull
docker compose up -d

Since today i got the following error

level=fatal msg="error while installing 'crowdsecurity/traefik': while downloading crowdsecurity/http-cve: while downloading crowdsecurity/http-cve to https://hub-cdn.crowdsec.net/master/collections/crowdsecurity/http-cve.yaml: hash mismatch: expected dd2e8debbba19d19646b9a8010baf9bd901a4eec84a53a0cb62294b8da3e91ef, got b974f20dc2cf23c292eede422c1c6e0008297f8b3397e3851bb6a988866f3e34"

### What did you expect to happen?

No error. An updated environment.

### How can we reproduce it (as minimally and precisely as possible)?

docker compose stop
docker compose pull
docker compose up -d

if necessarry i will post the docker compose yaml

I am not so deep in technical details

### Crowdsec version

<details>
In the cocker compose file there "latest"
```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

We pushed an update to the collection, but if your compose has recently been brought up with mounted volumes you may experience this.

The best way is to run a temporary container to update the index and then quit.

```bash
docker run --rm -it --entrypoint cscli -v $MountPath:/etc/crowdsec/ -v $MountPath:/var/lib/crowdsec/data/ crowdsecurity/crowdsec:latest hub update
```

In the example above I have used `$MountPath` as place holders for you to update where the mounts are if they are relative via your compose then launch the run within the compose directory, if they are named volumes then replace with the named volumes. The names are volumes may have a prefix so check via `docker volume ls` for the actual names.

**Comment by mourningsun75** [comment]
Thank you so much, this fixed the problem.

**Comment by AlexMelnykov** [comment]
I have the same problem and proposed solution fixed it. @LaurenceJJones please consider to add it to troubleshooting documentation.

**Comment by LaurenceJJones** [comment]
> I have the same problem and proposed solution fixed it. @LaurenceJJones please consider to add it to troubleshooting documentation.

Already on it 👍🏻
