### ISSUE TITLE
Telegram Thread id

### ISSUE THREAD

**Issue by Tresillo2017** [crowdsecurity/crowdsec#3193]
### What would you like to be added?

Add the ability for the telegram notifier to specify a thread id for those who use a group with threads to keep things organized.

### Why is this needed?

It will be such a small feature but really cool for those who use it

**Comment by blotus** [comment]
Hello,

The telegram notification template is not distributed with crowdsec itself, so you can edit it as you see fit.

From what I'm seeing in the telegram documentation, you just need to add a `message_thread_id` key to the request.
You can edit your telegram notification configuration file to add it in the `format` parameter:
```
format: |
  {
   "chat_id": "-XXXXXXXXX", 
   "message_thread_id": 12345,
   ....
  }
```
