### ISSUE TITLE
Improvement/portcheck

### ISSUE THREAD

**Issue by Ludvigden6th** [crowdsecurity/crowdsec#321]
Please, start your issue name (after `improvement`) with the component name impacted by this feature request and a small description of the FR. Example: `Improvement/cscli: add this feature ....` and remove this line :)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered** (Optional) 

**Example of what you imagine**
If applicable, add an example of what you would expect from this feature request.

**Additional context**

**Comment by Ludvigden6th** [comment]
1month with appel and understanding a lit more of how you let Apps build themeselvs after your commitment!

**Comment by buixor** [comment]
Yes
