### ISSUE TITLE
Bug reading traefik.log

### ISSUE THREAD

**Issue by zenkraker** [crowdsecurity/crowdsec#3279]
### What happened?

I have added the collection crowdsec/traefik to monitor traefik.log file but I receive such errors all the time
2024-10-06T11:45:31.403475780Z time="2024-10-06T13:45:31+02:00" level=error msg="UnmarshalJSON : invalid character '-' after top-level value" line="2024-10-06T13:45:31+02:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:84 > Accepting IP 192.168.40.65 middlewareName=ip-whitelist@file middlewareType=IPAllowLister"

### What did you expect to happen?

Crowdsec should read successfully my logs

### How can we reproduce it (as minimally and precisely as possible)?

These lines were not parsed correctly by crowdsec parser

2024-10-06T13:45:31+02:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:84 > Accepting IP 192.168.40.65 middlewareName=ip-whitelist@file middlewareType=IPAllowLister
2024-10-06T13:45:31+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 36680c615607cae0

### Crowdsec version

latest version of: 2024-09-12T08:19:58Z
--

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
This is expected as the log lines are not access logs, CrowdSec only parses access log lines so if anything else is wrote to the file then it will produce this error.

**Comment by zenkraker** [comment]
@LaurenceJJones Do you mean, should I pass the access.log instead of traefik.log? Or does crowdsec need traefik.log but only "access specific" log lines?

**Comment by LaurenceJJones** [comment]
> @LaurenceJJones Do you mean, should I pass the access.log instead of traefik.log? Or does crowdsec need traefik.log but only "access specific" log lines?

It depends on your configuration for traefik, but CrowdSec only cares about access logs, so if you output to a seperate file then you only need to specify that one. On the other hand if you combine them into the traefik log then your going to keep getting those logs as it mixing traefik and access logs.
