### ISSUE TITLE
Generic HTTP datasource 

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#3289]
Add a new datasource that will expose a generic HTTP server to receive JSON formatted logs.

The datasource will be agnostic regarding the exact content of the logs, and if "complex" objects are received (for example an array of items), it will rely on the [transform](https://docs.crowdsec.net/docs/next/data_sources/intro/#transform) features to split the items.

Requirements:
 -  Authentication: Support basic auth and custom headers name/values (in the case of header, it should probably allow an `AND` between multiples headers as some services seem to send multiple auth-related headers). In P2, mTLS support.
 - TLS Support

Optional:
 - Source IP filtering

Questions:
 - Input format: At the beginning, only support JSON data. Should we only support "one-shot" requests (ie, every items in an array) or NDJSON (one item per line).
 - Maximum body size: should the user be able to configure a max body size to avoid potential memory issues when dealing with a lot of logs ?
 - Chunk size configuration ?(mostly for streaming purpose)
 - Compression support ? Rely on the Content-type provided by the client ?
 - Stream support for decoding ? (ie, client open a persistent connection and stream data to crowdsec).
 - Configuration of HTTP response code on success and success headers.
 - Timeout configuration (should we kill the connection if no data is transmitted after some time)
 - How to support client that perform a health-check ? Have a configuration with a custom route + return code ?

**Comment by LaurenceJJones** [comment]
Mark as solved due to #3294 ??
