### ISSUE TITLE
Improvement/Dashboard - unified dashboard for multiple installs

### ISSUE THREAD

**Issue by jackmac92** [crowdsecurity/crowdsec#330]
**Describe the solution you'd like**
I'd like to be able to see a dashboard for multiple servers with crowdsec installed

**Example of what you imagine**
Configuration option to provide metabase host/credentials (ideally after generating the metabase dashboard on one server via cscli)

**Comment by buixor** [comment]
Hello @jackmac92 !

Thanks for the issue and the suggestion.
I'm going to let this one on standby, but the next major release of crowdsec should make this possible :)

Stay tuned and I'll keep you posted!

**Comment by buixor** [comment]
Hello @jackmac92 

If you played with the last release, I guess you might have found what you were looking for.
Don't hesitate to re-open an issue if you're facing any issues

**Comment by jackmac92** [comment]
Hey thanks @buixor I just re-reviewed docs and I'm actually still not clear on how to setup a unified dashboard. 

Would I set this up through the config file? It appears that `cscli dashboard setup` always just creates/updates a metabase instance on the current server.
