### ISSUE TITLE
Improvement/Makefile Build process should check for a minimum of Go 1.13

### ISSUE THREAD

**Issue by zathras777** [crowdsecurity/crowdsec#333]
When building using make build, the version of Go should be checked.

My initial attempt at building was on an older system with Go 1.10 installed which led to a failed build. As a minimum of Go 1.13 appears to be required it would have been far better to have this highlighted by a simple check in the makefile.

Also, I totally missed the 1.13 requirement in the docs prior to building, so maybe it should be clearer?

**Comment by buixor** [comment]
Thanks for the report, 110% agreed :)

**Comment by buixor** [comment]
Hello,

Out of curiosity, what `Makefile` command did you use to build? Was going to fix it and I thought that a lot of the targets already check for golang version (ie. https://github.com/crowdsecurity/crowdsec/blob/master/Makefile#L62)

Thanks!

**Comment by zathras777** [comment]
I followed the instructions and did

$ make build
rm -f crowdsec
CURRENT_GOVERSION="1.15.2"
RESPECT_VERSION=" 1.13"

While this is good and makes sense, when the version was lower it should
probably have stopped? With the older version it simply carried on and
promptly failed.

**Comment by buixor** [comment]
fixed on master, thanks !
