### ISSUE TITLE
Latest version (tag v1.6.4) is missing from Docker Hub

### ISSUE THREAD

**Issue by kenayagi** [crowdsecurity/crowdsec#3339]
### What happened?

Can't pull latest version from Docker Hub

### What did you expect to happen?

Download latest version from https://hub.docker.com/r/crowdsecurity/crowdsec/tags

### How can we reproduce it (as minimally and precisely as possible)?

```
~# docker pull crowdsecurity/crowdsec:v1.6.4

Error response from daemon: manifest for crowdsecurity/crowdsec:v1.6.4 not found: manifest unknown: manifest unknown
```

### Crowdsec version

<details>

Not relevant

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux REDACTED.com 6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux
```

</details>

**Comment by LaurenceJJones** [comment]
Yes this is known, we impose a rollout procedure so this will be completed today.

**Comment by kenayagi** [comment]
Okay, thank you.
Sorry to bother you.
