### ISSUE TITLE
Wrong Github issue file on the install script

### ISSUE THREAD

**Issue by rickythewoof** [crowdsecurity/crowdsec#3358]
### What happened?

The install script, in the case of unsupported operating system, pops out a message with the wrong github link to file issues.
message returned is 

> Detected operating system as pop/22.
Error This system is not supported (yet) by this script.
Please have a look at documentation https://docs.crowdsec.net/ or
file an issue at https://github.com/crowsecurity/crowdsec if you think
the behavior is not intended

### What did you expect to happen?

i expect the link to be [https://github.com/crowdsecurity/crowdsec](url), not the erroneous one reported as an error.

### How can we reproduce it (as minimally and precisely as possible)?

Running the install script with `curl -s https://install.crowdsec.net | sudo sh` on unsupported OS returns the wrong github link.

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
pop/22
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by sabban** [comment]
Hi,

Thanks for reporting this issue. This should now be fixed.

Regards,
Manuel Sabban
