### ISSUE TITLE
Improvement/hub add support for traefik

### ISSUE THREAD

**Issue by ovizii** [crowdsecurity/crowdsec#343]
I am running a couple of services using docker using traefik as a reverse proxy. I would like to enable an access log for traefik and have crowdsec check those whic hwould help secure all services behind the reverse proxy. 

afaik traefik can write the access logs in json or in CLF format.

**Comment by buixor** [comment]
Hello @ovizii,

Great idea, never had the chance to play with it, but heard great things about it :)
I'm opening the issue in the [hub](https://github.com/crowdsecurity/hub/issues/41) for tracking (that's more like where we want to track issues regarding parsers and scenarios).

Would you happen to have some logs to share with us, and/or some scenarios specific to the service that might make sense?

Thanks,

**Comment by ovizii** [comment]
thanks for moving the issue to the right place, lets close things on here and of course I can supply a couple of sample log files.
