### ISSUE TITLE
Improvement/Documentation - how often should we do cscli api pull ?

### ISSUE THREAD

**Issue by bunkerity** [crowdsecurity/crowdsec#377]
Hello crowdsecurity team,

I'm integrating CrowdSec into [bunkerized-nginx](https://github.com/bunkerity/bunkerized-nginx) and would like to know how often we should do a *cscli api pull* ? Every hour ? Every day ? Can't find anything about it on the documentation.

**Comment by erenJag** [comment]
Hi @bunkerity, 

Good news, thanks for your trust and your feedback.
Indeed, we forgot to be more specific about the pull process on the documentation, we use [cronjob](https://github.com/crowdsecurity/crowdsec/blob/master/config/crowdsec_pull) config that is installed by the [wizard](https://github.com/crowdsecurity/crowdsec/blob/master/wizard.sh#L38).

**Comment by buixor** [comment]
Since v1, crowdsec (local api) itself does the reputation pull every 2 hours
