### ISSUE TITLE
Improvement/wizard : do not overwrite profiles.yaml on `wizard --upgrade`

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#397]
**Is your feature request related to a problem? Please describe.**
When you upgrade crowdsec with the wizard, it's going to overwrite the `profiles.yaml`.
It would be nice it the wizard would check if it was touched before wanting to overwrite it.

**Comment by AlteredCoder** [comment]
The `./wizard.sh --upgrade` don't override the profiles.yaml file anymore.
