### ISSUE TITLE
Improvement/Automatically extend ipv6 IP to range when taking decision (ie. /56 /64 etc.)

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#402]
We should automatically extend decisions on a given IPV6 to the range it might be part of :
 - It will prevent attackers constantly switching IPs within the block to avoid getting blocked
 - It will as well prevent attackers from trying to pollute the ban base

**Comment by registergoofy** [comment]
Some ISPs do not provide /48 or /56 as they should. Somehow these should get an exemption and only get to ban /64 ....

**Comment by buixor** [comment]
:partying_face: https://github.com/crowdsecurity/crowdsec/pull/1540 has been merged and solves this for 1.4

**Comment by buixor** [comment]
and this is the associated post-overflow to automate the process : https://github.com/crowdsecurity/hub/pull/475
