### ISSUE TITLE
Bug/ Wizard no dialog fallback if whiptail isn't avaible

### ISSUE THREAD

**Issue by guiguid** [crowdsecurity/crowdsec#413]
**Describe the bug**
whiptail is not available on all distrib. (archlinux yes, yes).
dialog is massively available and replace whiptial.  

**To Reproduce**
try sudo ./wizard.sh -i on archbased dsitrib

**Expected behavior**
dialog fallback
works well with : ln -s /usr/bin/dialog /usr/local/bin/whiptail
and add dialog as pre-requierd

**Technical Information (please complete the following information):**
 - OS: archlinux
 - Version latest

**Comment by AlteredCoder** [comment]
Hello @guiguid , thanks for testing crowdsec!

As you can see [here](https://github.com/crowdsecurity/crowdsec/pull/417), we tried to add `dialog` as fallback when whiptail is not installed. As we can think, everythink work perfectly, but in fact no.
When i ran the `wizard.sh` with dialog, i had no error, but the `acquis.yaml` file generated by the wizard contained the errors from `dialog` as you can see below:

```
#Generated acquisition file - wizard.sh (service: apache2) / files : Error: Expected at least 6 tokens for --checklist, have 4. Use --help to list options.
filenames:
  - Error:
  - Expected
  - at
  - least
  - 6
  - tokens
  - for
  - --checklist,
  - have
  - 4.
  - Use
  - --help
  - to
  - list
  - options.
labels:
  type: apache2
---
#Generated acquisition file - wizard.sh (service: nginx) / files : Error: Expected at least 6 tokens for --checklist, have 4. Use --help to list options.
filenames:
  - Error:
  - Expected
  - at
  - least
  - 6
  - tokens
  - for
  - --checklist,
  - have
  - 4.
  - Use
  - --help
  - to
  - list
  - options.
labels:
  type: nginx
```

We will continue to work on this after our next release that is coming soon :)

**Comment by buixor** [comment]
wizard detects if whiptail is present and has an unattended mode now (1.1.0)
