### ISSUE TITLE
Bug/dashboard: stuck at INFO[0002] Waiting for metabase API to be up (can take up to a minute)

### ISSUE THREAD

**Issue by vlebourl** [crowdsecurity/crowdsec#416]
**Describe the bug**

I've run the command `sudo cscli dashboard setup` several times (cleaning the container and such between each attempt), and every time, I get stuck at the same step. I've tried waiting for more than an hour, but still nothing... 
Any help is most welcome!

**Technical Information (please complete the following information):**
 - Ubuntu 20.04

**Comment by AlteredCoder** [comment]
Hello @vlebourl , thanks for using crowdsec!

Can you please clean everything about the dashboard ?
 - `docker stop crowdsec-metabase`
- `docker rm crowdsec-metabase`
- `sudo rm -rf /var/lib/crowdsec/data/metabase.db`

rerun : `cscli dashboard setup --debug` and paste the output please ? 

If it still hang, can you try to run: `docker run -p 3000:3000 -v /var/lib/crowdsec/data:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db"  --name metabase metabase/metabase` to see if the container can be launched with `docker` ?

thanks :)

**Comment by vlebourl** [comment]
Your procedure worked. Thanks a lot!
Dunno what was going wrong.
