### ISSUE TITLE
Bug/ Install wizard fails with Unable to read downloaded index

### ISSUE THREAD

**Issue by ririsoft** [crowdsecurity/crowdsec#421]
Hello,

**Describe the bug**
I am running Debian Buster with SSH and Apache2.
I downloaded the latest release tarball (after advert on LinuxFr ;-) ) and run ./wizard.sh -i.

At the end of the process I got the following error message:
```
INFO[0000] api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-api.eu-west-1.amazonaws.com/v1/)
FATA[0000] Unable to read downloaded index : open /etc/crowdsec/config/cscli/.index.json: no such file or directory. Please run update
```

running `cscli update` a first time returns the error:
```
ERRO[0000] failed request Do : Get https://raw.githubusercontent.com/crowdsecurity/hub/master/.index.json: dial tcp: lookup raw.githubusercontent.com on 192.168.1.1:53: server misbehaving
FATA[0000] Unable to download index : Get https://raw.githubusercontent.com/crowdsecurity/hub/master/.index.json: dial tcp: lookup raw.githubusercontent.com on 192.168.1.1:53: server misbehaving.

```
I run it another time and it returns:

```
INFO[0000] Wrote new 73826 bytes index to /etc/crowdsec/config/cscli/.index.json
```

I restarted the crowdsec systemd service it fails with following errors in the logs:
```
time="11-11-2020 21:45:39" level=info msg="Opening file '/var/log/apache2/error.log' (pattern:/var/log/apache2/error.log)"
time="11-11-2020 21:45:39" level=info msg="Opening file '/var/log/apache2/access.log' (pattern:/var/log/apache2/access.log)"
time="11-11-2020 21:45:39" level=info msg="No filename or filenames, skipping empty item {Type:file Mode:tail Filename: Filenames:[] tail:<nil> Labels:map[] Profiling:false}"
time="11-11-2020 21:45:39" level=fatal msg="no parser(s) loaded, abort."
```

**Expected behavior**
crowdsec working out of the box after running the wizard.

**Technical Information (please complete the following information):**
 - Debian
 - Buster

Thanks in advance for your helps here,
do not hesitate to ask for more info.

Cheers,
Riri.

**Comment by buixor** [comment]
Hello @ririsoft !


It seems that you had a network issue (`dial tcp: lookup ... on 192.168.1.1:53: server misbehaving`) during the first install as your logs pointed out :

```
ERRO[0000] failed request Do : Get https://raw.githubusercontent.com/crowdsecurity/hub/master/.index.json: dial tcp: lookup raw.githubusercontent.com on 192.168.1.1:53: server misbehaving
```
(just in case it's unclear: the githubusercontent.com is part of github and not our scope ^^)

As the wizard failed to contact github (cf. error above), it failed to see available collections and thus failed to propose you the relevant ones :disappointed: 

This is why the startup then failed, as crowdsec will refuse to start if there is not parsers nor scenarios enabled (avoiding to give a false sense of "things are working" when they're obviously not).

Three questions :
 - do you know what might have caused the network error at the first attempt ?
 - were you able to reproduce the behaviour ?
 - did you try starting the wizard again and see what happened ?


Please let me know,

Thanks !

**Comment by ririsoft** [comment]
> * do you know what might have caused the network error at the first attempt ?

I have strictly no idea, and I am not sure at all that there was a network issue: I was connected in ssh, and my server monitoring dashboard (netdata) does not show any issue at that time.

 The error message `dial tcp: lookup ... on 192.168.1.1:53: server misbehaving` is vague and does not necessarily evoke a network down issue. Maybe there is room for improvement here.

> * were you able to reproduce the behaviour ?

I was not able to reproduce the behavior, sorry.

> * did you try starting the wizard again and see what happened ?

I did a `cscli update` followed up by `cscli install ...` to put things back on track.
However my apache2 logs are not parsed (according to metrics, line read = lines unparsed), but this might be related to my local configuration I will investigate that separately., Or you advise to relaunch the wizard ?


Cheers !

**Comment by buixor** [comment]
> The error message dial tcp: lookup ... on 192.168.1.1:53: server misbehaving is vague and does not necessarily evoke a network down issue. Maybe there is room for improvement here.

Yep agreed ^^ (the message is not ours btw, but seems to be from your local resolver)

> However my apache2 logs are not parsed (according to metrics, line read = lines unparsed), but this might be related to my local configuration I will investigate that separately., Or you advise to relaunch the wizard ?

It seems that this failure kinda messed up the initial setup I'm afraid. Relaunch the wizard will be our last resort, can you show me the list of installed collections & scenarios as well as your metrics ? (`cscli list` and `cscli metrics`)

If you have no parsers & scenarios, there will be two solutions :
 - restart the wizard (either the bug happens again and I will be happy with a reproducible bug, or it won't and you will be happy because it will work :p)
 - manually install the needed collections (ie `cscli install collection crowdsecurity/apache2`)


PS: feel free to drop by on [gitter](https://gitter.im/crowdsec-project/community) for a live debug session

**Comment by ririsoft** [comment]
I did a wizard re-install, and updated apache log parser configuration to match my LogFormat.
Things seem to be working now:

```
cscli list
INFO[0000] dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainted.
INFO[0000] Loaded 13 collecs, 17 parsers, 20 scenarios, 3 post-overflow parsers
INFO[0000] unmanaged items : 20 local, 2 tainted
INFO[0000] PARSERS:
-----------------------------------------------------------------------------------------------------------------------------
 NAME                            📦 STATUS            VERSION  LOCAL PATH
-----------------------------------------------------------------------------------------------------------------------------
 crowdsecurity/sshd-logs         ✔️  enabled          0.1      /etc/crowdsec/config/parsers/s01-parse/sshd-logs.yaml
 crowdsecurity/geoip-enrich      ✔️  enabled          0.2      /etc/crowdsec/config/parsers/s02-enrich/geoip-enrich.yaml
 crowdsecurity/syslog-logs       ✔️  enabled          0.1      /etc/crowdsec/config/parsers/s00-raw/syslog-logs.yaml
 crowdsecurity/dateparse-enrich  ✔️  enabled          0.1      /etc/crowdsec/config/parsers/s02-enrich/dateparse-enrich.yaml
 crowdsecurity/http-logs         ✔️  enabled          0.2      /etc/crowdsec/config/parsers/s02-enrich/http-logs.yaml
 crowdsecurity/apache2-logs      ⚠️  enabled,tainted  ?        /etc/crowdsec/config/parsers/s01-parse/apache2-logs.yaml
 crowdsecurity/whitelists        ✔️  enabled          0.1      /etc/crowdsec/config/parsers/s02-enrich/whitelists.yaml
-----------------------------------------------------------------------------------------------------------------------------
INFO[0000] SCENARIOS:
----------------------------------------------------------------------------------------------------------------------------------
 NAME                                       📦 STATUS    VERSION  LOCAL PATH
----------------------------------------------------------------------------------------------------------------------------------
 crowdsecurity/http-sensitive-files         ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-sensitive-files.yaml
 crowdsecurity/http-probing                 ✔️  enabled  0.1      /etc/crowdsec/config/scenarios/http-probing.yaml
 crowdsecurity/http-crawl-non_statics       ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-crawl-non_statics.yaml
 crowdsecurity/http-sqli-probing            ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-sqli-probing.yaml
 crowdsecurity/http-backdoors-attempts      ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-backdoors-attempts.yaml
 crowdsecurity/http-bad-user-agent          ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-bad-user-agent.yaml
 crowdsecurity/http-path-traversal-probing  ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-path-traversal-probing.yaml
 crowdsecurity/http-xss-probing             ✔️  enabled  0.2      /etc/crowdsec/config/scenarios/http-xss-probing.yaml
 crowdsecurity/ssh-bf                       ✔️  enabled  0.1      /etc/crowdsec/config/scenarios/ssh-bf.yaml
----------------------------------------------------------------------------------------------------------------------------------
INFO[0000] COLLECTIONS:
----------------------------------------------------------------------------------------------------------------------------
 NAME                               📦 STATUS            VERSION  LOCAL PATH
----------------------------------------------------------------------------------------------------------------------------
 crowdsecurity/linux                ✔️  enabled          0.2      /etc/crowdsec/config/collections/linux.yaml
 crowdsecurity/sshd                 ✔️  enabled          0.1      /etc/crowdsec/config/collections/sshd.yaml
 crowdsecurity/apache2              ⚠️  enabled,tainted  0.1      /etc/crowdsec/config/collections/apache2.yaml
 crowdsecurity/base-http-scenarios  ✔️  enabled          0.1      /etc/crowdsec/config/collections/base-http-scenarios.yaml
----------------------------------------------------------------------------------------------------------------------------
INFO[0000] POSTOVERFLOWS:
--------------------------------------
 NAME  📦 STATUS  VERSION  LOCAL PATH
--------------------------------------
--------------------------------------
```

```
cscli metrics
INFO[0000] Buckets Metrics:
+--------------------------------------+---------------+-----------+--------------+--------+---------+
|                BUCKET                | CURRENT COUNT | OVERFLOWS | INSTANCIATED | POURED | EXPIRED |
+--------------------------------------+---------------+-----------+--------------+--------+---------+
| crowdsecurity/http-crawl-non_statics | -             | -         |            5 |      8 |       5 |
| crowdsecurity/http-probing           | -             | -         |            4 |      7 |       4 |
+--------------------------------------+---------------+-----------+--------------+--------+---------+
INFO[0000] Acquisition Metrics:
+-----------------------------+------------+--------------+----------------+------------------------+
|           SOURCE            | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+-----------------------------+------------+--------------+----------------+------------------------+
| /var/log/apache2/access.log |         73 |           73 | -              |                     15 |
| /var/log/apache2/error.log  |         25 | -            |             25 | -                      |
+-----------------------------+------------+--------------+----------------+------------------------+
INFO[0000] Parser Metrics:
+--------------------------------+------+--------+----------+
|            PARSERS             | HITS | PARSED | UNPARSED |
+--------------------------------+------+--------+----------+
| child-crowdsecurity/http-logs  |  219 |    147 |       72 |
| crowdsecurity/apache2-logs     |   98 |     73 |       25 |
| crowdsecurity/dateparse-enrich |   73 |     73 | -        |
| crowdsecurity/geoip-enrich     |   73 |     73 | -        |
| crowdsecurity/http-logs        |   73 |     51 |       22 |
| crowdsecurity/non-syslog       |   98 |     98 | -        |
| crowdsecurity/whitelists       |   73 |     73 | -        |
+--------------------------------+------+--------+----------+
```

This is frustrating that I cannot reproduce.
I guess you can close and re-open if this reoccurres.

Thanks for your time and support.

**Comment by buixor** [comment]
glad to know at least it's working :)
Out of curiosity, what change did you need to do to the apache2 parser ?

**Comment by ririsoft** [comment]
> Out of curiosity, what change did you need to do to the apache2 parser ?

- My apache conf:
`LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O %I %D \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined`
I have added the %I and %D to monitor input bytes and response times

- My`s01-parse/apache2-logs.yaml` "tainted" parser conf:
`pattern: '(%{URIHOST:target_fqdn} )?%{COMMONAPACHELOG} %{POSINT} %{POSINT} %{QS:referrer} %{QS:agent}'`
I inserted `%{POSINT} %{POSINT}` to parse %I and %D.

However I still do not have my apache error.log parsed, I do not understand (yet) how to have them parsed too.

**Comment by buixor** [comment]
Thanks :+1:

**Comment by ririsoft** [comment]
@buixor : I forgot to mention that I had to replace `%{IPORHOST:target_fqdn}` by `%{URIHOST:target_fqdn}`: This one looks more a bug from crowdsec to me since logging with `%v:%p` sounds pretty standard isn't it ?
