### ISSUE TITLE
Improvement/journald support

### ISSUE THREAD

**Issue by alexpovel** [crowdsecurity/crowdsec#423]
**Is your feature request related to a problem? Please describe.**

This is not really a problem per-se, but when running multiple containerized applications on one host, it is kind on inconvenient to pull (via volumes) all the log files out of the containers and onto the host.

**Describe the solution you'd like**

In the case of Docker and specifically `docker-compose` at least, there is the [journald logging driver](https://docs.docker.com/config/containers/logging/journald/).
Using a very simple instruction, this allows us to send logs to `journald`, without having to deal with or even know where the log files are located inside the container.

From `journald`, `fail2ban` can read using `backend = systemd` in a jail config, with a `journalmatch` field in a filter config. The match can be as simple as `CONTAINER_NAME=<name>`, which Docker provides automatically when using the journald logging driver. It also allows to run, on the host:

```bash
journalctl CONTAINER_NAME=<name>
```

This is very sleek and simple.

**Describe alternatives you've considered** (Optional) 

See the described solution above.

**Example of what you imagine**

An option to not only specify log files, but also a solution maybe somewhat similar to how fail2ban handles it:

instead of a logfile, provide a `journalmatch` string, and specify somewhere else that systemd/journald should be used.

I am just getting started with crowdsec, but these would go into the [configurations](https://hub.crowdsec.net/browse/#configurations) as far as I can see?

This is extremely simple and requires minimal setting up and fiddling with volumes, log files etc.

**Additional context**

**Comment by ririsoft** [comment]
Hello,

I have a similar use case: I am not using docker but use journald for centralizing my logs.
I am running Debian Buster, shutdown rsyslog and activated permanent journald storage: all syslog logs go to journald, auth logs (sshd, pam ...) in particular. Crowdsec is thus a no-go to me to parse sshd logs, while fail2ban does that very well.

Filtering journald logs can be done through several ways but the best ones for our use case are SYSLOG_FACILITY and SYSLOG_IDENTIFIER. To follow sshd logs for the AUTH facility one would run: `journalctl SYSLOG_FACILITY=4 SYSLOG_IDENTIFIER=sshd`.

core-os provides journald API bindings, but this require cgo and might not be the best for crowdsec deployment. One can also use a[ journald http gateway](https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html), but the easiest migth be to simply parse `journalctl` (json output, taking care of cursors for instance). fail2ban uses python and C systemd bindings provided by systemd project. This need to be further explored.

Thanks in advance for your time on this.

**Comment by buixor** [comment]
Thank you both for your inputs, we're starting to look into it!


So far we saw three options (as listed by @ririsoft ) :

 - **using cgo bindings**: this doesn't seem a viable option, as it will make the portability harder, and add extra complexity
 - **piping `journalctl` output**: while it's not technically elegant, it seems so far the best option, as it will as well be a mechanism we can re-use for future data-sources
 - **using a journald http gateway** : this is a viable option, but as it doesn't seem to be a default setup, we'll keep this one for later when we know better what we want to do with http gateways

Do you have any extra thoughts regarding this?

**Comment by buixor** [comment]
Merged into coming release: https://github.com/crowdsecurity/crowdsec/pull/456 !

**Comment by alexpovel** [comment]
Impressive speed, thanks!

**Comment by buixor** [comment]
Feel free to provide feedback on the integration and the documentation, closing the issue for now :)

**Comment by ririsoft** [comment]
> 
> 
> Feel free to provide feedback on the integration and the documentation, closing the issue for now :)

I am currently running v0.3 and this does not seem to have landed in v1.0.0 release candidates yet.
Do you have a tag to recommend for testing all this as well as new 1.0.0 version (I am interested in the firewall bouncer on the hub in particular).
