### ISSUE TITLE
Improvement/docker

### ISSUE THREAD

**Issue by Antoine-Sevec** [crowdsecurity/crowdsec#429]
I would like to have the option of using an official docker with the project.
In order to enable us, to automate, industrialize, to do scaling, etc...

I'm not sure what to add more to the demand ...

**Comment by erenJag** [comment]
Hi @Antoine-Sevec,

Could you please be more specific on an usecase example. We're working on the docker support and we need usecases to create a suitable docker image.

**Comment by erenJag** [comment]
Hi @Antoine-Sevec,

There is now an [official docker image](https://hub.docker.com/r/crowdsecurity/crowdsec).
