### ISSUE TITLE
Bug/ api pull cron job fails

### ISSUE THREAD

**Issue by ririsoft** [crowdsecurity/crowdsec#437]
**Describe the bug**

Doing a `cscli ban list` this morning I noticed that the IP ban from the api list
was empty. Running `cscli api pull` manually works without issue. I believe the cron job is not working correctly.
According to the cscli logs it works one day out of 3: 
```
time="2020-11-12T08:00:01+01:00" level=info msg="api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-
api.eu-west-1.amazonaws.com/v1/)"
time="2020-11-12T08:00:04+01:00" level=fatal msg="api signin: return bad HTTP code (500): Something went wrong."
time="2020-11-13T08:00:01+01:00" level=info msg="api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-
api.eu-west-1.amazonaws.com/v1/)"
time="2020-11-13T08:00:01+01:00" level=info msg="dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainte
d."
time="2020-11-13T08:00:02+01:00" level=info msg="api signin: signed in successfuly"
time="2020-11-13T08:00:04+01:00" level=warning msg="api pull returned 100 entries"
time="2020-11-13T08:00:06+01:00" level=info msg="Wrote 100 bans from api to database."
time="2020-11-14T08:00:02+01:00" level=info msg="api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-
api.eu-west-1.amazonaws.com/v1/)"
time="2020-11-14T08:00:02+01:00" level=info msg="dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainte
d."
time="2020-11-14T08:00:04+01:00" level=fatal msg="api signin: return bad HTTP code (500): Something went wrong."
```

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version 10 (Buster)

**Comment by ririsoft** [comment]
Issue persist and funnily one day it works and the day after it does not with same error 500. I cannot reproduce with `cscli api pull` which always work.

**Comment by buixor** [comment]
Hello,

The problem has been identified on our side in the AWS architecture, we have a pending ticket with AWS, I'll keep you posted !

Thanks,

**Comment by ririsoft** [comment]
> The problem has been identified on our side in the AWS architecture, we have a pending ticket with AWS, I'll keep you posted !

I believe there is also an issue on crowdsec side, if I may: the previous data pulled are removed when the connection to AWS fails. I think that the previous data should be removed only when the call to AWS succeed, so that a failing AWS service (this can always happen) does not put at risk the security of a system based on crowdsec, which should be able to run with data previously pulled until new pull finally succeed.

**Comment by buixor** [comment]
@ririsoft oh thanks, I might have missed something, but I think the fact that your "previous data" is removed is simply because it expired. By default, the decisions shared are only valid 24h.

**Comment by ririsoft** [comment]
I was not aware of the 24h validity period. The question is then what is the best: having outdated shared list or an empty one when the pull fails ? I do not understand well the impact of having an outdated shared list, I would say it is better than an empty one, but there might be side effects ...

**Comment by registergoofy** [comment]
The main issue should be now fixed.

We assume that at least some of the IP that we share, are from compromised server, or rent by hour. When legit actors do take over we do want not to be blocked. That's why we make the data expire.

Now your point makes sense, I'll have this issue open until we have a decision.

**Comment by ririsoft** [comment]
> We assume that at least some of the IP that we share, are from compromised server, or rent by hour. When legit actors do take over we do want not to be blocked. That's why we make the data expire.

Thank you for the clarification, this makes sense too.

I understand that: local ban expires after 4h (by default), community shared bad IPs expire after 24h. This expiration process is independent from the cron job which just fetch new shared bad IPs, so expiration occurs what ever the result of the cron job. Is that correct ?

Do you have weighted bad IPs ? I mean some bad IPs are bad for a long time and should have expiration date longer than others that have not been reported bad for a given period of time. This would allow to have distinct expiration dates and would lower the impact of a failing pull job.

**Comment by ririsoft** [comment]
The connection issue is solved but I still have 0 IPs coming from the cron job :

```
# /var/log/cscli.log
time="2020-11-17T08:00:01+01:00" level=info msg="api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-api.eu-west-1.amazonaws.com/v1/)"
time="2020-11-17T08:00:01+01:00" level=info msg="dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainted."
time="2020-11-17T08:00:03+01:00" level=fatal msg="api signin: return bad HTTP code (500): Something went wrong."
time="2020-11-18T08:00:01+01:00" level=info msg="api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-api.eu-west-1.amazonaws.com/v1/)"
time="2020-11-18T08:00:01+01:00" level=info msg="dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainted."
time="2020-11-18T08:00:01+01:00" level=info msg="dependency issue crowdsecurity/base-http-scenarios : missing scenarios crowdsecurity/http-crawl-non_statics, tainted."
time="2020-11-18T08:00:04+01:00" level=info msg="api signin: signed in successfuly"
time="2020-11-18T08:00:11+01:00" level=warning msg="api pull returned 0 entries"
time="2020-11-18T08:00:11+01:00" level=info msg="Wrote 0 bans from api to database."
time="2020-11-19T08:00:01+01:00" level=info msg="api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-api.eu-west-1.amazonaws.com/v1/)"
time="2020-11-19T08:00:01+01:00" level=info msg="dependency issue crowdsecurity/base-http-scenarios : missing scenarios crowdsecurity/http-crawl-non_statics, tainted."
time="2020-11-19T08:00:01+01:00" level=info msg="dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainted."
time="2020-11-19T08:00:03+01:00" level=info msg="api signin: signed in successfuly"
time="2020-11-19T08:00:10+01:00" level=warning msg="api pull returned 0 entries"
time="2020-11-19T08:00:10+01:00" level=info msg="Wrote 0 bans from api to database."
```

```shell
~$ cscli ban list
No local decisions
And 0 records from API, 0 distinct AS, 0 distinct countries
```

```shell
~$ sudo cscli api pull
INFO[0000] api load configuration: configuration loaded successfully (base:https://tmsov6x2n9.execute-api.eu-west-1.amazonaws.com/v1/)
INFO[0000] dependency issue crowdsecurity/base-http-scenarios : missing scenarios crowdsecurity/http-crawl-non_statics, tainted.
INFO[0000] dependency issue crowdsecurity/apache2 : tainted parsers crowdsecurity/apache2-logs, tainted.
INFO[0000] api signin: signed in successfuly
WARN[0001] api pull returned 100 entries
INFO[0002] Wrote 100 bans from api to database.
chicha@horous:~$ cscli ban list
No local decisions
And 100 records from API, 33 distinct AS, 17 distinct countries
```

**Comment by erenJag** [comment]
Hi @ririsoft,

After troubleshooting, we found out it's partially because all the users were pulling at the same time (because of the cron), and it triggered a limit in some service. We managed to limit the impact with a workaround (you should not see it but it might still happen).
We are working on release 1.0, that will improve pulling and sending signals.

Closing for now if it's ok for you !

**Comment by ririsoft** [comment]
> After troubleshooting, we found out it's partially because all the users were pulling at the same time (because of the cron), and it triggered a limit in some service.

This can of issue can be limited with the usage of systemd timers instead of a cron job, but this is limited to Linux platforms only, which might be an issue for you.

> We managed to limit the impact with a workaround (you should not see it but it might still happen).
This is totally fine until v1.0 is out. I did not encounter the issue lately, workaround is working for me. Thanks a lot !
