### ISSUE TITLE
Bug/Reports of the service not starting automatically at boot time

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#446]
[As reported on discourse](https://discourse.crowdsec.net/t/systemd-service-doesnt-auto-start-at-boot-time/61/2) it seems that the service doesn't restart after reboot.

**Describe the bug**
Service doesn't start automatically after reboot.

**Additional context**
User provided suggested fixes :

```bash
sudo chmod +x /etc/systemd/system/crowdsec.service
sudo systemctl enable crowdsec
```

**Comment by registergoofy** [comment]
This will be fixed is next upcoming 1.0.0 release.
