### ISSUE TITLE
Improvement/services: target caddy and haproxy logs

### ISSUE THREAD

**Issue by c-nv-s** [crowdsecurity/crowdsec#470]
**Describe the solution you'd like**

It would be nice to be able to have crowdsec recognize haproxy or caddy reverse proxies as services that have been installed.
I think it would complement both tools if crowdsec could parse their log files and be able to apply e.g. the netfilter/iptables bouncer when malicious activity is detected.

**Comment by buixor** [comment]
moved to https://github.com/crowdsecurity/hub/issues/69
