### ISSUE TITLE
Failed to start metabase container

### ISSUE THREAD

**Issue by dlevequeIT** [crowdsecurity/crowdsec#497]
Hello,
I begin with crowdsec on my uybuntu server and have some difficulties to start dashboard.
Command describes in the Howto is the following :  cscli dashboard setup --listen 0.0.0.0
But after execute that I have the following issue :
`INFO[0000] /var/lib/crowdsec/data/metabase.db exists, skip.
INFO[0000] Downloaded metabase DB
INFO[0000] Pulling docker image metabase/metabase
FATA[0000] Failed to start metabase container : failed to pull docker image : Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I do not used Docker on my system (I know, I should). Could you help me please ?

**Comment by buixor** [comment]
Hello,

Sorry for the delay, created the doc after your issue but we forgot to answer :sweat_smile: 

You will find some documentation here : https://doc.crowdsec.net/faq/#how-to-have-a-dashboard-without-docker

**Comment by dlevequeIT** [comment]
Thanks about that.
My setup with metabase is done on MySQL and I access to http://localhost:3000
So I changed the /etc/crowdsec/config.yaml and /etc/crowdsec/user.yaml files with my MySQL settings and replace port 8080 by 8085 in /config.yaml, local_api_credentials.yaml and user.yaml because 8080 is already used.

Now, when I try to launch, it's failed again and I have, in crowdsec logfile, the following information :
`time="15-12-2020 16:00:44" level=warning msg="while configuring datasource : empty filename(s) and journalctl filter, malformed datasource"
time="15-12-2020 16:00:44" level=warning msg="Starting processing data"
time="15-12-2020 16:00:44" level=info msg="Error machine login for f6ffd395775f43ba8f3e116eff6ce273 : ent: machine not found "
time="15-12-2020 16:00:44" level=fatal msg="starting outputs error : authenticate watcher (f6ffd395775f43ba8f3e116eff6ce273): Post http://127.0.0.1:8085/v1/watchers/login: received response status \"401 Unauthorized\" when fetching http://127.0.0.1:8085/v1/watchers/login"`

In addition I have tried <cscli dashboard setup> but I see the following error :
`FATA[0000] metabase setup init: 'mysql' is not supported yet for cscli dashboard`

Could you help me please ?

**Comment by dlevequeIT** [comment]
Hello I answer to myself but as I upgraded in same time from 1.0.0 to 1.0.2, I forgot to tegister crowdsec to local & central API with command : `sudo cscli machines add -a`

Now crowdsec, capi and lapi are in running successful but no dashboard :(
How I can check if crowdsec is working without that ?

**Comment by AlteredCoder** [comment]
Hello @dlevequeIT , sorry for the delay, the issue was closed so we didn't saw your answer.

You can use `cscli metrics` to see if you're logs are correctly parsed.
