### ISSUE TITLE
Improvement/ Provide arm64 builds

### ISSUE THREAD

**Issue by panos** [crowdsecurity/crowdsec#500]
**Is your feature request related to a problem? Please describe.**

My homelab's infrastructure heavily consists of ARM devices. 

**Describe the solution you'd like**
I'd like for the installation wizard to detect and install arm64 binaries.

**Additional context**
The platform that I tried CrowdSec on was a Raspberry Pi 4B+.

**Comment by buixor** [comment]
closing as a duplicate of #324 it's in progress, don't hesitate to comment over there
