### ISSUE TITLE
Bug/Upgrade wizard delete everything in crowdsec config directory

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/crowdsec#525]
When you upgrade the crowdsec agent with the ./wizard --upgrade everything in /etc/crowdsec is deleted.
Including the cs-custom-bouncer folder and other custom config files.

Custom config files should be left untouched, or place in a backup directory.
The cs-custom-bouncer should not be touched at all.

**Comment by AlteredCoder** [comment]
Hello @LtSich,

This issue has been fixed in #522. We are going to release a new patch soon to avoid this bug in the future :)
