### ISSUE TITLE
Bug/Local agent need to be restarted if the LAPI is restarted

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/crowdsec#526]
On my setup I have a central LAPI and multiple servers who connect to the LAPI on a central server.
If I restart the LAPI on the central server I have to restart all local agent on all server.

When you restart the LAPI, and a "slave" agent try to send report you got this in the logfile : 
time="10-12-2020 07:38:00" level=error msg="while pushing to api : failed sending alert to LAPI: API error: signature is invalid"

The only way to fix that is to restart the local agent to reauth on the LAPI.
Maybe on that error the local agent should try to reauth after waiting a little time. (in the case the server have to reboot).

**Comment by buixor** [comment]
oh indeed this is quite unfortunate. I have a wip MR for this : https://github.com/crowdsecurity/crowdsec/pull/527

**Comment by buixor** [comment]
https://github.com/crowdsecurity/crowdsec/pull/527 has been merged, it will be in next release (in the coming days), thanks !
