### ISSUE TITLE
Improvement/Do not use `localhost` for configurations

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#529]
**Is your feature request related to a problem? Please describe.**
Default crowdsec configuration use "localhost" a lot (ie. for local api). However, it can resolve either to ipv4 or ipv6. Using loopback address instead would avoid any confusion/mistakes.

**Describe the solution you'd like**
Use loopback (127.0.0.1 or ::1) instead

**Comment by erenJag** [comment]
Fixed here : https://github.com/crowdsecurity/crowdsec/pull/522
