### ISSUE TITLE
Improvement/Use of Tor to push or pull crowdsource API data

### ISSUE THREAD

**Issue by jorong1** [crowdsecurity/crowdsec#531]
**Is your feature request related to a problem? Please describe.**
No, this is just an improvement

**Describe the solution you'd like**
I think it would be a good idea to either offer the use of Tor, or have instructions on how a user could setup proxying API calls through Tor. This is intended to provide improved anonymity for end users, so that even their own IPs are not provided when sharing data.

Even if end user IPs are not stored/logged/parsed, it would still be a good idea to have this.

**Example of what you imagine**
I am sure there is a way to do this, I just do not know how. You could run the daemon behind proxychains, but then that also proxies local servers when running for metabase.
So maybe if there's a way to only have API push/pull code communicate over a SOCKS5 proxy, perhaps you can toggle this through the setup wizard.

**Additional context**
None. Thanks

**Comment by buixor** [comment]
that's a great idea, we're going to look into it !

**Comment by buixor** [comment]
Hello,

Following the MR #546 , we added documentation on how to use tor with crowdsec (wizard, cscli and crowdsec itself) in the faq.
I didn't test it exhaustively, but it seems to work. I'm keeping this open awaiting your feedback or further testing from us.

The documentation is available here : https://doc.crowdsec.net/faq/#how-to-configure-crowdseccscli-to-use-tor

**Comment by jorong1** [comment]
This is fantastic, thanks!
It will be tested soon but this looks very easy to use, great work!
