### ISSUE TITLE
Improvement/cscli hub upgrade

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#533]
Please, start your issue name (after `improvement`) with the component name impacted by this feature request and a small description of the FR. Example: `Improvement/cscli: add this feature ....` and remove this line :)

**Is your feature request related to a problem? Please describe.**
It seems that the hub upgrade feature was forgotten in the 1.0

**Describe the solution you'd like**
The ability to upgrade all configuration at once, would be very nice.

**Example of what you imagine**
```
cscli hub upgrade 
```
For upgrading all configuration items

**Comment by AlteredCoder** [comment]
Fixed in #534
