### ISSUE TITLE
Bug/Documentation

### ISSUE THREAD

**Issue by Taubin** [crowdsecurity/crowdsec#539]
**Describe the bug**
Documentation for local/custom configuration is missing

**To Reproduce**
1. Go to the documentation User Guide > Configurations and Management > Managing local/custom configuration 

**Expected behavior**
Documentation for custom configurations to be there.

**Screenshots**
N/A

**Technical Information (please complete the following information):**
N/A

**Additional context**
Documentation link is also missing from [github](https://github.com/crowdsecurity/crowdsec/edit/master/docs/Crowdsec/v1/user_guide/configurations_management/local-configurations.md)

**Comment by buixor** [comment]
thanks, I deleted the leftover empty pages
