### ISSUE TITLE
Bug/Update from v1.0.0 to v1.0.1 leaves crowdsec half installed, half removed

### ISSUE THREAD

**Issue by ririsoft** [crowdsecurity/crowdsec#540]
**Describe the bug**
Upgrade from v1.0.0 to v1.0.1 failed: some local settings where removed, others were kept.

**To Reproduce**
1. sudo ./wizard.sh --upgrade (from v 1.0.1 downloaded directory)
2. System is broken: the crowdsecurity/apache2 collection was entirely removed. Note: I "tainted" some configuration files, just updating the pattern to match apache logs and deactivating scenario http-crawl-non_statics. My custom acquisition file was left untouched.

**Expected behavior**
Same upgrade experience, production grade, as I have with Debian Stable packages: nothing to do on minor upgrade such v1.0.0 to v1.0.1, no breakage and files in /etc are left untouched, unless I explicitly merge them with the new version provided by the package.

Maybe #525 did not fixed the issue entirely ?
Also #334 would have helped a lot here.

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version: 10 (Buster)

**Comment by buixor** [comment]
Hello,

Sorry for the poor upgrade experience.

It seems that `cscli config backup` generates wrong filenames for the tainted items, I'm looking for a fix.
Did you had other issues with the upgrade ?

Thanks,

**Comment by ririsoft** [comment]
> Sorry for the poor upgrade experience.

The project is young, but the fundamental concepts are good which is why I am not giving up ;-)

> Did you had other issues with the upgrade ?

I do not think so: I reinstalled the apache2 collection, "tainted" again the apache logs PATTERN to match my configuration, deactivated again the crawl_non_statics scenario and things seem back to normal. Note: I have no bouncer installed for the moment (I plan to install one soon). `cscli alerts list`, `cscli metrics` and logs do not show any issue.

**Comment by buixor** [comment]
Made a new release to fix this, but waiting for items before closing the issue :
 - [ ] Functional tests of wizard upgrade feature
 - [ ] Improved documentation on how to upgrade (ie. patch upgrade should be done with `--binupgrade` to limit impact)
 - [ ] Improve wizard.sh to limit user's confusion

**Comment by ririsoft** [comment]
I will test again with upgrade to 1.0.2 once the bug is closed (and above items done). I will thus be a good guinea pig, following the documentation for upgrade path.

I saw on LinuxFR that you are working on a Debian package. I cannot be more happy !

**Comment by ririsoft** [comment]
@buixor actually I noticed that cron job /etc/cron.d/crowdsec_pull was not removed when upgrading from v0.3 to v1 

```
# /etc/cron.d/crowdsec_pull: crontab to pull crowdsec API
# bad IP in ban DB.

# Run everyday at 08:00 A.M

0 8 * * * root /usr/local/bin/cscli api pull >> /var/log/cscli.log 2>&1
```

Should I open a distinct issue for this ?

**Comment by buixor** [comment]
This has been dealt with :)
