### ISSUE TITLE
Bug/crowdsec uninstall does not remove iptables entries

### ISSUE THREAD

**Issue by readall** [crowdsecurity/crowdsec#548]
**Describe the bug**
The `wizard.sh --uninstall` does not remove the chains created by crowdsec from iptables.

**To Reproduce**
1. Install crowdsec with default options
2. Install the firewall and ssh boucers
3. List iptable rules to see that crowdsec chain is created for ssh
4. now execute wizard.sh --uninstall
     This step stops the service but does not clean the iptables

**Expected behavior**
Cleanup after yourself, post uninstall, the tool must remove any chains, targets and rules it created

**Screenshots**
I have now removed it and do not have the screen shots as of now

**Technical Information (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Version: crowdsec-v1.0.0

**Additional context**
No errors reported. Uninstall is successful, just not clean which think is inappropriate behavior of the application.

**Comment by buixor** [comment]
Hello,

Thanks for the issue!
It makes sense that crowdsec would clean up any existing bans before exiting.
However, it is a bit more tricky, as crowdsec/wizard :
 - crowdsec/wizard isn't necessarily aware of existing bouncers (however, it could "guess" it from `cscli bouncers list`)
 - bouncers aren't necessarily on the same machine, so we can't "cleanup" firewall state

What we might do is : during `wizard.sh --uninstall`, we can list existing bouncers and cancel/bailout of the uninstall process while warning the user ?


(Please not however that if you remove the firewall bouncer, it will cleanup existing chains etc.)

**Comment by readall** [comment]
Hi,

Yes tricky, in that case it may be better to make the guesses and present/print manual command (even if direct iptables commands) to clean up. This way the user gets an indication about what needs cleaning and how to achieve it. 
 
Thanks

**Comment by buixor** [comment]
Late update: For now what we can reasonably do is to check for the user if there is any registered bouncers, and remind to uninstall them before moving further.

https://github.com/crowdsecurity/crowdsec/pull/579

```
WARNING : You have at least one bouncer registered (cscli bouncers list).
WARNING : Uninstalling crowdsec with a running bouncer will let it in an unpredictable state.
WARNING : If you want to uninstall crowdsec, you should first uninstall the bouncers.
Specify --force to bypass this restriction.
```
