### ISSUE TITLE
Improvement/bouncer Add capability to enable bouncer in docker container

### ISSUE THREAD

**Issue by thelittlefireman** [crowdsecurity/crowdsec#549]
**Is your feature request related to a problem? Please describe.**
Is not possible to enable bouncer on crowdsec container.

**Describe the solution you'd like**
Due to the impossibility of docker container to handle systemd/systemctl, it's not possible to add bouncer on crowdsec container.
Could it be possible to add a feature to lunch bouncer at start with the container ? (nohup ?) 

**Describe alternatives you've considered** (Optional) 
Set bouncer in a separate dockerfile and launch directly by exec the binary without systemd

**Example of what you imagine**
If applicable, add an example of what you would expect from this feature request.

**Additional context**

Thanks

**Comment by buixor** [comment]
Hello !

I think what you might want is the [firewall bouncer](https://github.com/crowdsecurity/cs-firewall-bouncer/) : the firewall bouncer allows you to manage firewall rules, including the DOCKER related user-chains  !

see https://github.com/crowdsecurity/cs-firewall-bouncer/issues/19

**Comment by thelittlefireman** [comment]
HI,
Not exactly. I'm on Synology NAS and I have no options  to install cs-firewall-bouncer as standalone. So, I would like to launch cs-firewall-bouncer or cs-custom-bouncer as a Docker container with a custom script to interface with the custom Synology firewall.

I'm looking for a bouncer container (ie : docker run --name=bouncer crowdsecurity/cs-custom-bouncer ...)
Thanks

**Comment by moritzj29** [comment]
@thelittlefireman did you manage to get it working on your NAS? I'm currently looking for the same but all the documentation requires cs-firewall-bouncer to be installed on the host... this somehow breaks the advantages of containers...
It must be possible somehow, since fail2ban is also modifying the `DOCKER-USER` chain from within the container.
