### ISSUE TITLE
Change 8080 port

### ISSUE THREAD

**Issue by bartounet16** [crowdsecurity/crowdsec#552]
Hello
i cannot start crowdsec 8080 is already in use.
There is nothing in documentation to change it

If i change port in config.yaml
Le daemon start but i cannot lauche cscli

# cscli metrics
FATA[0000] failed to fetch prometheus metrics : executing GET request for URL "http://127.0.0.1:6060/metrics" failed: Get http://127.0.0.1:6060/metrics: dial tcp 127.0.0.1:6060: connect: connection refused

**Comment by registergoofy** [comment]
you are mixing the prometheus url and the local api server url. 
prometheus url is for scraping metrics and local api server url is for communicating with bouncers. By default, local api server use port 8080 and prometheus scraping server use 6060. You can change either port in /etc/crowdsec/config.yaml`:

* *local api server port*:
this is defined under the api->server->listen_uri directive in the config.yaml. Please keep in mind, that modifying this will requires that you modifiy bouncer ports accordingly in /etc/crowdsec/cs-<boucner_name>-bouncer

* *prometheus port*
after changing this port, you can allow `cscli metrics` to access the new url by using `cscli metrics -u http://localhost:new_port`

**Comment by bartounet16** [comment]
Thank you for answer !
When i change local api port in config.yaml
i have this error after daemon restart

time="21-12-2020 17:00:58" level=fatal msg="starting outputs error : authenticate watcher (46ff6c98803f480d82d7317116e6655a): Post http://127.0.0.1:8080/v1/watchers/login: received response status \"404 \" when fetching http://127.0.0.1:8080/v1/watchers/login"

**Comment by bartounet16** [comment]
it works after changing port /etc/crowdsec/local_api_credentials.yaml

**Comment by bartounet16** [comment]
it works after changing port /etc/crowdsec/local_api_credentials.yaml

**Comment by hugo4711** [comment]
A bit more clearly: One needs to change the port in config.yaml *and* set the port in local_api_credentials.yaml so that they match.

**Comment by magnums** [comment]
Here, This is the method works for me.
i want to changed the port 8080 to 9090

then edit 8080 to 9090 in files below.

/etc/crowdsec/config.yaml
/etc/crowdsec/local_api_credentials.yaml

then ,   
systemctl restart crowdsec

that's it.!!!

**Comment by milindpatel63** [comment]
after the latest update,
any changes in /etc/crowdsec/local_api_credentials.yaml file is being reverted back to default port of 8080 and crowdsec is crashing on startup due to 8080 being used by another process on my system...i am running crowdsec in docker in host network mode....

**Comment by Ammar-UT** [comment]
even when changing the port in the two files it's not work!

**Comment by securegh** [comment]
Same issue here, port 8080 is often used and there is no doc on crowdsec to effectively change the default port, please advice on the procedure, thank you very much!

**Comment by freaky-m0** [comment]
If you use the crowdsec-firewall-bouncer you need to change the port for the local-api in that config too:

/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
"api_url"

Just want to help others find there way here..

**Comment by mvnixon** [comment]
couldn't find the file
/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml

Where is this located?
