### ISSUE TITLE
Cannot install Crowdsec on RPI

### ISSUE THREAD

**Issue by bartounet16** [crowdsecurity/crowdsec#553]
Hello
is it normal that i can not install crowdsec on a RPI ?
No compatibility with ARM ?

**Comment by buixor** [comment]
Hello,

In the meanwhile, I'll refer you to this issue : https://github.com/crowdsecurity/crowdsec/issues/324
Crowdsec runs on ARM, but we don't provide a binary release yet : https://doc.crowdsec.net/faq/#how-to-use-crowdsec-on-raspberry-pi-os-formerly-known-as-rasbian


It should be here in january (for next release I hope)
