### ISSUE TITLE
Improvement/Support OpenRC

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#556]
Please, start your issue name (after `improvement`) with the component name impacted by this feature request and a small description of the FR. Example: `Improvement/cscli: add this feature ....` and remove this line :)

**Is your feature request related to a problem? Please describe.**
We should support OpenrRC (gentoo, alpine,

**Describe the solution you'd like**
wizard should detect if the system is systemd-based or openrc-based and install crowdsec accordingly.

**Comment by buixor** [comment]
cf. #555

**Comment by sabban** [comment]
Main distributions that supports openrc are gentoo and alpine. 
* https://git.alpinelinux.org/aports/tree/testing/crowdsec/ 
* https://github.com/ToeiRei/crowdsec-overlay/
Each of this repository comes with a openrc init file.
