### ISSUE TITLE
Improvement/update github.com/docker/docker

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#562]
Please, start your issue name (after `improvement`) with the component name impacted by this feature request and a small 
debian packaging require that github.com/docker/docker be updated at 20.10.1

**Is your feature request related to a problem? Please describe.**
This is a showstopper for creating a debian package.

**Describe the solution you'd like**
github.com/docker/docker being updated at 20.10.1

**Comment by AlteredCoder** [comment]
Fix in https://github.com/crowdsecurity/crowdsec/pull/563
