### ISSUE TITLE
Improvement/ulog2 as log source iptables

### ISSUE THREAD

**Issue by clopnis** [crowdsecurity/crowdsec#571]
**Is your feature request related to a problem? Please describe.**
there is a iptables log source based on syslog / journald. [ulog2](https://www.netfilter.org/projects/ulogd/index.html) is able to store iptables log in several database model 

**Describe the solution you'd like**
I have already node pushing log into ulog2, I would like to use this as source log.

**Describe alternatives you've considered** (Optional) 
this is a more proper / scalable solution

**Comment by sabban** [comment]
Hi, 
We are sorry for not getting back to you sooner. This repository is not the place for this kind feature request. The hub (repository)[https://github.com/crowdsecurity/hub] is more the place for this. 

Please keep in mind that we welcome third-party contributions there, but if you want to seek help from our team to have your log format supported, we need some log excerpts with some lines that would lead to the suspicious activity that you want to see blocked, and some lines that are normal activities.
