### ISSUE TITLE
Improvement/crowdsec: support environment variables in configuration

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#600]
**Is your feature request related to a problem? Please describe.**
Currently, configuration values can only be 'hardcoded' in the configuration file, which is for problematic for values intended to be secret (such as the database password).

**Describe the solution you'd like**
Being able to set a configuration value based on environment variables, ie:
```yaml
db_config:
  password: ${DB_PASSWORD}
```

A very simple solution could be to use `os.ExpandEnv` before unmarshaling the configuration.

**Comment by AlteredCoder** [comment]
Hello @blotus, thanks for opening this issue. Indeed it's a good idea, here is the PR that allows this: https://github.com/crowdsecurity/crowdsec/pull/601

**Comment by AlteredCoder** [comment]
Hello @blotus, for information the v1.0.6 release contains this change

**Comment by blotus** [comment]
Awesome, thanks !
