### ISSUE TITLE
Bug/ backup option in wizard.sh tool is broken

### ISSUE THREAD

**Issue by gerbier** [crowdsecurity/crowdsec#611]
**Describe the bug**
I am using crowdsec-v1.0.6
and the the wizard.sh help displays a "-b|--backup" option
but running this option does not work :
./wizard.sh -b
./wizard.sh: ligne 495: backup_to_dir : commande introuvable

the function backup_to_dir is not defined in wizard.sh, and is not an unix/linux command

**To Reproduce**
1. ./wizard.sh -b

**Expected behavior**
show only working options 

**Screenshots**

**Technical Information (please complete the following information):**
 - OS:  ubuntu 20.10
 - Version :  crowdsec-v1.0.6

**Additional context**

**Comment by AlteredCoder** [comment]
Hello @gerbier, thanks for opening this issue.
This options is old and is not possible via the wizard, only the help message was not removed (i'm going to remove it and it will be remove from the next release.

If you can to backup/restore your crowdsec configuration you can use `cscli config backup <path_to_backup_folder>` and `cscli config restore <path_to_backup_folder>` .

**Comment by gerbier** [comment]
thank you
you will have to remove the ./wizard.sh -r|--restore too

**Comment by buixor** [comment]
thanks, it has been removed as well in : https://github.com/crowdsecurity/crowdsec/pull/612
