### ISSUE TITLE
Bug/ipset list crowdsec6-blacklists is empty

### ISSUE THREAD

**Issue by gerbier** [crowdsecurity/crowdsec#613]
**Describe the bug**
I am using crowdsec with cs-firewall-bouncer on a linux ubuntu with iptables.
the commands "iptables -L" and "ip6tables -L" show me that a rule was inserted in INPUT Chain , which will use ipset lists.
# ip6tables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       all      anywhere             anywhere             match-set crowdsec6-blacklists src

the crowdsec-blacklists list is filled with 63 entries today
but the crowdsec6-blacklists list is empty :

#  ipset list crowdsec6-blacklists
Name: crowdsec6-blacklists
Type: hash:net
Revision: 6
Header: family inet6 hashsize 1024 maxelem 65536 timeout 300
Size in memory: 1232
References: 1
Number of entries: 0
Members:

**To Reproduce**
1. ipset list crowdsec6-blacklists

**Expected behavior**
a filled ipset list

**Screenshots**

**Technical Information (please complete the following information):**
 - OS: ubuntu 20.10
 - Version crowdsec 1.0.6

**Additional context**
Add any other context about the problem here, for example `/var/log/crowdsec.log` or error messages.

**Comment by buixor** [comment]
Hello,

if you trigger an scenario on ipv6 or if you manually add a ban `cscli decisions add -i ... ` on ipv6, does the set stays empty ?
it might as well be because the consensus didn't redistributed you yet lists on ipv6.

**Comment by gerbier** [comment]
$ sudo cscli decisions add -i 2001:db8::
$ sudo ipset  list crowdsec6-blacklists
Name: crowdsec6-blacklists
Type: hash:net
Revision: 6
Header: family inet6 hashsize 1024 maxelem 65536 timeout 300
Size in memory: 1392
References: 1
Number of entries: 1
Members:
2001:db8:: timeout 14326

seems ok
and my computer is using ipv6 
$ sudo ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:24:e8:c6:e4:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.11/24 brd 192.168.0.255 scope global dynamic noprefixroute enp0s25
       valid_lft 862894sec preferred_lft 862894sec
    inet6 fe80::c9d6:7e20:24c3:22ba/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

and IP are received on my computer
$ sudo cscli alerts list
+----+---------------------+------------------------------------+---------+----+-----------+--------------------------------+
| ID |        VALUE        |               REASON               | COUNTRY | AS | DECISIONS |           CREATED AT           |
+----+---------------------+------------------------------------+---------+----+-----------+--------------------------------+
| 27 | Ip:2001:db8::       | manual 'ban' from                  |         |    | ban:1     | 2021-02-12 14:06:13 +0100      |
|    |                     | '88cecf923c7f4189963bf9fb2a06da08' |         |    |           | +0100                          |
| 26 | Community blocklist | update : +81/-0 IPs                |         |    | ban:81    | 2021-02-12 14:00:07.667787959  |
|    |                     |                                    |         |    |           | +0100 +0100                    |
| 25 | Community blocklist | update : +81/-0 IPs                |         |    | ban:81    | 2021-02-12 13:58:28.699546984  |
|    |                     |                                    |         |    |           | +0100 +0100                    |
| 24 | Community blocklist | update : +81/-0 IPs                |         |    | ban:81    | 2021-02-12 13:48:36.002034654  |
|    |                     |                                    |         |    |           | +0100 +0100                    |
| 23 | Comunity blocklist  | update : +81/-0 IPs                |         |    | ban:81    | 2021-02-09 13:27:18.318960926  |
|    |                     |                                    |         |    |           | +0100 +0100                    |
| 22 | Comunity blocklist  | update : +81/-0 IPs                |         |    | ban:81    | 2021-02-07 16:49:57.002804703  |
|    |                     |                                    |         |    |           | +0100 +0100                    |
+----+---------------------+------------------------------------+---------+----+-----------+--------------------------------+

**Comment by AlteredCoder** [comment]
Hello @gerbier, i will close this issue since it seems to be resolved. You can re opened it at any moment if you feel that the issue is not resolved.
