### ISSUE TITLE
Allow multiple acquis config files

### ISSUE THREAD

**Issue by dani** [crowdsecurity/crowdsec#618]
From reading the doc, it looks like acquisition can only be defined in a single file (crowdsec_service.acquisition_path, with default value of /etc/crowdsec/acquis.yml)
To simplify deploiement, it'd be great if we could define a directory instead, and all the .yml files inside would be parsed. The reason for me is that I'm planing to add crowdsec support to my ansible roles. So, I would have a main crowdsec role which setup the agent, and then, any other roles can add their own acquis/parser config. So, my zimbra role for example could just drop /etc/crowdsec/config/acquis/zimbra.yml  which would listen to /opt/zimbra/log/mailbox.log

If this is already possible (I'm just starting to look at crowdsec), then I couldn't find it in the doc

**Comment by buixor** [comment]
Hello,

It's currently the only way to specify acquisition configuration.
You request makes sense and it was a needed change :+1: 

There is a wip for this on #619

**Comment by dani** [comment]
Oh, I didn't saw it was already on track. What would be even better is for the agent to monitor this dir ans reload the config automatically if something changed (same for parsers). This is what filebeat does for example ans it's really conveniant for this kind of deployement
