### ISSUE TITLE
Improvement/Network inputs for acquisition

### ISSUE THREAD

**Issue by dani** [crowdsecurity/crowdsec#621]
**Is your feature request related to a problem? Please describe.**
Having crowdsec able to listen on network sockets for various protocols would make it really nice for enterprise deployement. Eg, crowdsec could listen for various protocols like syslog, beats, gelf.

**Describe the solution you'd like**
Network listeners to receive either raw, or structured logs. Most important IMHO would be
- syslog
- gelf
- beats
- journald

**Example of what you imagine**

The idea behind this is to make it easier to deploy in enterprises, and reduce log parsing overlaps. Eg : I use Graylog to centralize my logs. Graylog already parses most of my logs. And it could forward those already structured logs to a central crowdsec, which would just have to apply scenarios (or maybe trivial parsing when required).

Then, I'd only have to deploy the bouncers on the servers I want to protect.

**Comment by buixor** [comment]
Hello,

Yes this is something that we want and plan to work on rather soon.

We need to refactor the "acquisition" mechanism beforehand (and decide how we deal with modules), so that we can make this modular and easy to extend.

**Comment by buixor** [comment]
We have currently syslogd and journald. There is currently no will to add gelf or beats as a network source. Please let us know if it's still needed :)

**Comment by dch** [comment]
belated +1 for GELF source, for example.
