### ISSUE TITLE
Bug/wizard randomness generation

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#628]
**Describe the bug**
On some VPS the random generation hangs. It is done by `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`. man page of urandom, tells us that random is delivered by 256 bytes blocks. So cat is expecting a lot of random blocks. It seems that `dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev` expects only one block of random. This should be enough for security, and it is confirmed not to hang on those VPS boxes/

**To Reproduce**
`./wizard.sh -i` on some weird VPS boxes.

**Expected behavior**
Wizard should'nt hang.

**Technical Information (please complete the following information):**
- debian 9/10 on OVH VPS

see https://discourse.crowdsec.net/t/wizard-stalled-line-594-dev-urandom-tr-dc-a-za-z0-9/122

**Comment by buixor** [comment]
`cscli machines add` knows how to generate random secure password. We should simply use the `-a` option in the wizard rather than try to generate password with black magic.

**Comment by buixor** [comment]
closed with https://github.com/crowdsecurity/crowdsec/pull/696
