### ISSUE TITLE
Bug/Empty line in rdns_whitelists lead to misbehavior

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#630]
**Describe the bug**
If an empty line is added to `rdns_seo_bots.txt` (or similar whitelists), it will lead to any event being whitelisted, as the `crowdsecurity/seo-bots-whitelist` has :

```
"any(File('rdns_seo_bots.txt'), { evt.Enriched.reverse_dns endsWith #})"
```

so, if the line is '', any reverse dns will end with it.

**Comment by erenJag** [comment]
To avoid this behavior, we need to improve the expr helper `File`, so the empty lines will not be loaded.
