### ISSUE TITLE
Bug/prometheus default port

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#632]
**Describe the bug**
It seems that the default port for prometheus scraping is 9090. We should stick with nice defaults. So we should change prometheus default port from 6060 to 9090

**Comment by he2ss** [comment]
Add our exporter default port to the [default port allocation prometheus official list](https://github.com/prometheus/prometheus/wiki/Default-port-allocations#exporters-outside-of-the-standard-port-ranges). No need to change our default port because it's the exporter not the server.
