### ISSUE TITLE
Improvement/FAQ question "Why are some logs unparsed"

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#640]
**Is your feature request related to a problem? Please describe.**
At the moment it's hard to understand that crowdsec is working correctly even if some logs are unparsed.

**Describe the solution you'd like**
A question should be added in the documentation. "Why are some logs unparsed"

**Comment by liberodark** [comment]
Hi have same question i dont understand for why is not parsing all log access.
Is only parse /var/log/nginx/access.log but have many other application on nignx with access too is not parsed.
crowdsec no see if you have attack or bad connection on the other application.
Have possibility to define manually the source ?

```
+---------------------------+------------+--------------+----------------+------------------------+
|          SOURCE           | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+---------------------------+------------+--------------+----------------+------------------------+
| /var/log/auth.log         |        356 | -            |            356 | -                      |
| /var/log/messages         |          4 |            4 | -              | -                      |
| /var/log/nginx/access.log |          2 |            2 | -              |                      2 |
| /var/log/nginx/error.log  |          4 |            4 | -              |                      4 |
| /var/log/syslog           |       1500 |            8 |           1492 | -                      |
+---------------------------+------------+--------------+----------------+------------------------+
```

Best Regards
