### ISSUE TITLE
Question/Need to add new logs manually ?

### ISSUE THREAD

**Issue by liberodark** [crowdsecurity/crowdsec#646]
Hi,

You confirm need to adding log manually in :  `/etc/crowdsec/acquis.yaml`
if im adding new apps in nginx for example : 
crowdsec read my_app.com-access.log my_app.com-error.log
But if im adding my_app-two.com need to add on this file : `/etc/crowdsec/acquis.yaml`
my_app-two.com-access.log my_app-two.com-error.log

Best Regards

**Comment by buixor** [comment]
Hello @liberodark :)

Yes, you will want to add the files if they were not detected by the wizard.
Keep in mind that you can as well use regular expressions :

```yaml
filename: /var/log/apache2/*.log
labels:
  type: apache2
```
