### ISSUE TITLE
Question/How to run Dashboard without Docker ?

### ISSUE THREAD

**Issue by liberodark** [crowdsecurity/crowdsec#648]
Hi,

Have read doc + readme but you only explain how to deploy dashboard with docker.
https://doc.crowdsec.net/Crowdsec/v1/observability/dashboard/
But im not docker fan and i want to install dashboard without docker.

Best Regards

**Comment by AlteredCoder** [comment]
Hello @liberodark,

You can find the documentation in the FAQ: https://doc.crowdsec.net/faq/#how-to-have-a-dashboard-without-docker

**Comment by liberodark** [comment]
Thank you @AlteredCoder have no read FAQ but only Documentation.

**Comment by AlteredCoder** [comment]
@liberodark yes, we are going to add this link to the dashboard documentation :)
