### ISSUE TITLE
Improvement/Have make dashboard install without docker

### ISSUE THREAD

**Issue by liberodark** [crowdsecurity/crowdsec#650]
Hi,

Have using your FAQ for make installer and db preinstalled with metadata.
https://github.com/liberodark/crowdsec-dashboard
And is working with systemd.
I share my work with you, hoping that it can help some.

Best Regards

**Comment by buixor** [comment]
oh great, do you mind if I link it into the existing documentation ?

**Comment by buixor** [comment]
I have linked your repository in the FAQ : https://github.com/crowdsecurity/crowdsec/pull/654

Thanks !
