### ISSUE TITLE
Improvement/: how to install and config crowdsec with kubernetes ingress-nginx

### ISSUE THREAD

**Issue by Rom888** [crowdsecurity/crowdsec#653]
It would be nice to see any tutorial on how to install and configure CrowdSec in kubernetes cluster with ingress-nginx, and with or without ModSecurity Web Application Firewall addon enabled:
https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/

**Comment by AlteredCoder** [comment]
Hello @Rom888,

We are currently working on how to integrate Crowdsec in a kubernetes cluster with nginx as ingress-controller. 
An example of this integration and a tutorial about how to do it will be published soon :)

**Comment by flo-mic** [comment]
@AlteredCoder any updates on this? I know we can inject the logs with an agent (nice article by the way ;) ). But how can be block such requests on the ingress?

**Comment by buixor** [comment]
Hello,

Here it is : https://docs.crowdsec.net/docs/bouncers/ingress-nginx/

Please open an issue if you're facing any problems !
