### ISSUE TITLE
Bug/closed database

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#656]
**Describe the bug**

With the sqlite configuration.

Sometimes when crowdsec is reloaded via systemd, we can get 
`unable to fetch scenarios from db: while listing machines: setting machine status: unable to update` 

One can get this error after registering to CAPI and following the instructions
```
one@home:~/work/clients/crowdsec/git/salsa$ sudo cscli capi register
INFO[01-03-2021 04:08:13 PM] Successfully registered to Central API (CAPI) 
INFO[01-03-2021 04:08:13 PM] Central API credentials dumped to '/etc/crowdsec/online_api_credentials.yaml' 
WARN[01-03-2021 04:08:13 PM] Run 'sudo systemctl reload crowdsec' for the new configuration to be effective 
```

tl;dr

On some old debian 9 system system:
`cscli capi register`followed by `systemctl reload crowsec` lead to `unable to fetch scenarios from db: while listing machines: setting machine status: unable to update`

**Comment by buixor** [comment]
unable to reproduce, keeping for the record

**Comment by CyrilBrulebois** [comment]
The Debian package has a patch to prefer `restart` over `reload` due to this bug, up to version 1.0.9; I'll double check what happens with 1.4.2 release candidates, and update this report accordingly.

**Comment by LaurenceJJones** [comment]
Classing as close as not planned. If you believe this is an error and can provide us reproducible steps please reopen.
