### ISSUE TITLE
Community blocklist update is different on 2 server

### ISSUE THREAD

**Issue by reinerj** [crowdsecurity/crowdsec#663]
There are 2 servers where we are trying crowdsec. The community blocklist differs on booth.

**Describe the bug**
The older test system, running current crowdsec 1.0.9 does show the list since days as:

 Community blocklist | update : +50/-0 IPs            |         |                                | ban:50

the new test system, installed today does show

Community blocklist | update : +81/-0 IPs |         |    | ban:81

**To Reproduce**

**Expected behavior**
Booth lists should have the same amount of IP

**Screenshots**

**Technical Information (please complete the following information):**
Ubuntu 18.03 (older system) 
Ubuntu 20.04 (new test system)

**Additional context**
Add any other context about the problem here, for example `/var/log/crowdsec.log` or error messages.

**Comment by buixor** [comment]
Hello @reinerj 

Two machines can have different blocklist especially if they don't have the same scenarios enabled. The blocklist you receive are based on the scenarios that you enabled (so that we feed you only relevant ips). Can you check that ?

Please let me know :+1:

**Comment by reinerj** [comment]
Hi,

this does make sense now ... Maybe I missed in the readme that different scenarios pull different sets. 

Thanks for the fast answer
