### ISSUE TITLE
Systemd cs-firewall bouncer does have // 

### ISSUE THREAD

**Issue by reinerj** [crowdsecurity/crowdsec#664]
The cs-firewall-bouncer does have a double //

**Describe the bug**
/usr/local/bin/cs-firewall-bouncer -c /etc/crowdsec/cs-firewall-bouncer//cs-firewall-bouncer.yaml

**To Reproduce**
We installed the binary available for download

**Expected behavior**
/usr/local/bin/cs-firewall-bouncer -c /etc/crowdsec/cs-firewall-bouncer/cs-firewall-bouncer.yaml

**Screenshots**

**Technical Information (please complete the following information):**
Ubuntu with crowdsec-release.tgz

**Additional context**

**Comment by he2ss** [comment]
Closing this issue, moved to the concerned repo : https://github.com/crowdsecurity/cs-firewall-bouncer/issues/30
