### ISSUE TITLE
Improvement/debian packages

### ISSUE THREAD

**Issue by jamiew0w** [crowdsecurity/crowdsec#669]
Hello!

I was wondering if there is plans to add debian packages or maybe your own repository?

>**Is your feature request related to a problem? Please describe.**

I can't speak for others but my experiences with upgrading is awkward and frequently buggy, using debian packages should make things much more stable.

> **Describe the solution you'd like**

Ideally, being in the official debian/ubuntu repositories would be amazing but I imagine that'd be quite a lot of work.

> **Describe alternatives you've considered** (Optional) 

with regards to updates, i've wrote a few bash scripts to automate updating but it's not ideal.

>**Example of what you to expect if this was implemented**

streamlined update process mainly. 

Thanks in advance for your time!

**Comment by sabban** [comment]
The answer has to be in two parts.
* crowdec is making its path into the upcoming debian stable as of 1.0.9 (not yet released as of now)
* We have released our own debian package that are still in beta state (By the way it's time to officially release them, but you can have a look at https://discourse.crowdsec.net/t/debian-package-availability/116/10 in the meantime)

I'll have this ticket closed when the official release is done.

**Comment by buixor** [comment]
Hello,

It's now documented [here](https://doc.crowdsec.net/Crowdsec/v1/getting_started/installation/) (cf. https://github.com/crowdsecurity/crowdsec/pull/678)

please let us know :slightly_smiling_face:
