### ISSUE TITLE
Bug/cscli decisions delete --id - removes the decision, but then a new one is created for the same IP

### ISSUE THREAD

**Issue by gdudas** [crowdsecurity/crowdsec#670]
**Describe the bug**
cscli decisions delete --id - removes the decision, but then a new one is created for the same IP

`root@crowdsec:~# cscli decisions list`
`+-----+----------+------------------+-----------------------------------+--------+---------+--------------------------------+--------+--------------------+----------+`
`| ID  |  SOURCE  |   SCOPE:VALUE    |              REASON               | ACTION | COUNTRY |               AS               | EVENTS |     EXPIRATION     | ALERT ID |`
`+-----+----------+------------------+-----------------------------------+--------+---------+--------------------------------+--------+--------------------+----------+`
`| 141 | crowdsec | Ip:***.131.*.110 | crowdsecurity/http-bad-user-agent | ban    | HU      |                                |      2 | 3h58m14.456221898s |        3 |`
`|     |          |                  |                                   |        |         |                                |        |                    |          |`
`+-----+----------+------------------+-----------------------------------+--------+---------+--------------------------------+--------+--------------------+----------+`
`root@crowdsec:~# cscli decisions delete --id 141`
`INFO[0000] 1 decision(s) deleted`
`root@crowdsec:~# cscli decisions list`
`+-----+----------+------------------+----------------------------+--------+---------+--------------------------------+--------+-------------------+----------+`
`| ID  |  SOURCE  |   SCOPE:VALUE    |           REASON           | ACTION | COUNTRY |               AS               | EVENTS |    EXPIRATION     | ALERT ID |`
`+-----+----------+------------------+----------------------------+--------+---------+--------------------------------+--------+-------------------+----------+`
`| 142 | crowdsec | Ip:***.131.*.110 | crowdsecurity/http-probing | ban    | HU      |                                |     11 | 3h58m6.444066164s |        4 |`
`|     |          |                  |                            |        |         |                                |        |                   |          |`
`+-----+----------+------------------+----------------------------+--------+---------+--------------------------------+--------+-------------------+----------+`

**To Reproduce**
- Install crowdsec-v1.0.7 and cs-firewall-bouncer-v0.0.10
- Start a test scan with nikto
- After the first ban, stop nikto
- Delete the decision
- Then list again

**Expected behavior**
After "cscli decisions delete --id 141" it should remove the ban.

**Technical Information (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Crowdsec: crowdsec-v1.0.7 + cs-firewall-bouncer-v0.0.10

**Comment by AlteredCoder** [comment]
Hello @gdudas,

The behavior is normal but we didn't documented it enough.
When you launched nikto, multiple alerts (and their associated decisions) were generated, but when you run `cscli decisions list` only the decisions with the highest expiration is printed. So when deleting a decision by id, it will delete the decision with the provided id, but there is still some decision concerning the same IP address. (as you can see in the result  of `cscli decisions list`, the decisions ID is not the same).

I would suggest you to delete a decision by its ip instead of the id by running: `cscli decisions delete -i <ip_addr>`.

I hope this helped you, and we are going to improve the documentation :)

**Comment by gdudas** [comment]
Hi,

I can confirm, when I delete by IP it works well. Thanks for your reply!
