### ISSUE TITLE
Bug/crowdsec.service

### ISSUE THREAD

**Issue by skyser93** [crowdsecurity/crowdsec#680]
**Describe the bug**
Аfter parsed the logs, the crowdsec.service agent failed
<pre>
● crowdsec.service - Crowdsec agent
   Loaded: loaded (/etc/systemd/system/crowdsec.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-02-11 16:30:34 MSK; 9h ago
  Process: 25188 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 18160 ExecStart=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml (code=exited, status=1/FAILURE)
  Process: 18035 ExecStartPre=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml -t (code=exited, status=0/SUCCESS)
 Main PID: 18160 (code=exited, status=1/FAILURE)
</pre>
**To Reproduce**
We simulated scanning web applications on nginx via wapiti from an external IP address.

**Expected behavior**
Logs are parsed (at least partially), after which, crowdsec.service failed

**Technical Information (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 
 - Version v1.0.7

**Additional context**
Output of cscli `parsers list`:
<pre>
-------------------------------------------------------------------------------------------------------------
 NAME                            📦 STATUS   VERSION  LOCAL PATH
-------------------------------------------------------------------------------------------------------------
 crowdsecurity/postfix-logs      ✔️  enabled  0.3      /etc/crowdsec/parsers/s01-parse/postfix-logs.yaml
 crowdsecurity/postscreen-logs   ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/postscreen-logs.yaml
 crowdsecurity/geoip-enrich      ✔️  enabled  0.2      /etc/crowdsec/parsers/s02-enrich/geoip-enrich.yaml
 crowdsecurity/http-logs         ✔️  enabled  0.5      /etc/crowdsec/parsers/s02-enrich/http-logs.yaml
 crowdsecurity/iptables-logs     ✔️  enabled  0.2      /etc/crowdsec/parsers/s01-parse/iptables-logs.yaml
 crowdsecurity/cowrie-logs       ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/cowrie-logs.yaml
 crowdsecurity/nginx-logs        ✔️  enabled  0.3      /etc/crowdsec/parsers/s01-parse/nginx-logs.yaml
 crowdsecurity/smb-logs          ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/smb-logs.yaml
 crowdsecurity/naxsi-logs        ✔️  enabled  0.1      /etc/crowdsec/parsers/s02-enrich/naxsi-logs.yaml
 crowdsecurity/syslog-logs       ✔️  enabled  0.1      /etc/crowdsec/parsers/s00-raw/syslog-logs.yaml
 crowdsecurity/tcpdump-logs      ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/tcpdump-logs.yaml
 crowdsecurity/whitelists        ✔️  enabled  0.1      /etc/crowdsec/parsers/s02-enrich/whitelists.yaml
 firewallservices/zimbra-logs    ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/zimbra-logs.yaml
 crowdsecurity/apache2-logs      ✔️  enabled  0.5      /etc/crowdsec/parsers/s01-parse/apache2-logs.yaml
 crowdsecurity/dateparse-enrich  ✔️  enabled  0.1      /etc/crowdsec/parsers/s02-enrich/dateparse-enrich.yaml
 crowdsecurity/modsecurity       ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/modsecurity.yaml
 crowdsecurity/vsftpd-logs       ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/vsftpd-logs.yaml
 crowdsecurity/dovecot-logs      ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/dovecot-logs.yaml
 crowdsecurity/mysql-logs        ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/mysql-logs.yaml
 crowdsecurity/sshd-logs         ✔️  enabled  0.1      /etc/crowdsec/parsers/s01-parse/sshd-logs.yaml
-------------------------------------------------------------------------------------------------------------
</pre>

Output of `systemctl status crowdsec.service` after restart of service:
<pre>
● crowdsec.service - Crowdsec agent
   Loaded: loaded (/etc/systemd/system/crowdsec.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-02-12 02:10:32 MSK; 1h 39min ago
  Process: 5695 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 4226 ExecStartPre=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml -t (code=exited, status=0/SUCCESS)
 Main PID: 4474 (crowdsec)
   CGroup: /system.slice/crowdsec.service
           └─4474 /usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml

Feb 12 03:15:03 localhost.localdomain crowdsec[4474]: 2021/02/12 03:15:03 Successfully reopened /var/log/httpd/error_log
Feb 12 03:37:51 localhost.localdomain systemd[1]: Reloading Crowdsec agent.
Feb 12 03:37:51 localhost.localdomain systemd[1]: Can't open PID file /var/run/crowdsec.pid (yet?) after reload: No such file or directory
Feb 12 03:37:51 localhost.localdomain systemd[1]: Reloaded Crowdsec agent.
Feb 12 03:37:54 localhost.localdomain crowdsec[4474]: 127.0.0.1 - [Fri, 12 Feb 2021 03:37:54 MSK] "POST /v1/watchers/login HTTP/1.1 200 395.659638ms "crowdsec/v1.0.7-18ff3a3a306d1eca786038fb343250e43784a900" "
Feb 12 03:37:54 localhost.localdomain crowdsec[4474]: 127.0.0.1 - [Fri, 12 Feb 2021 03:37:54 MSK] "POST /v1/watchers/login HTTP/1.1 200 133.926435ms "crowdsec/v1.0.7-18ff3a3a306d1eca786038fb343250e43784a900" "
Feb 12 03:38:24 localhost.localdomain crowdsec[4474]: 127.0.0.1 - [Fri, 12 Feb 2021 03:38:24 MSK] "POST /v1/watchers/login HTTP/1.1 200 122.977008ms "crowdsec/v1.0.7-18ff3a3a306d1eca786038fb343250e43784a900" "
Feb 12 03:38:24 localhost.localdomain crowdsec[4474]: 127.0.0.1 - [Fri, 12 Feb 2021 03:38:24 MSK] "GET /v1/alerts?has_active_decision=true&include_capi=false HTTP/1.1 200 3.390082ms "crowdsec/v1.0.7-18ff3a3a306d1eca786...250e43784a900" "
Feb 12 03:43:51 localhost.localdomain crowdsec[4474]: 127.0.0.1 - [Fri, 12 Feb 2021 03:43:51 MSK] "POST /v1/watchers/login HTTP/1.1 200 122.666592ms "crowdsec/v1.0.7-18ff3a3a306d1eca786038fb343250e43784a900" "
Feb 12 03:43:51 localhost.localdomain crowdsec[4474]: 127.0.0.1 - [Fri, 12 Feb 2021 03:43:51 MSK] "GET /v1/alerts?has_active_decision=true&include_capi=false HTTP/1.1 200 1.769338ms "crowdsec/v1.0.7-18ff3a3a306d1eca786...250e43784a900" "
Hint: Some lines were ellipsized, use -l to show in full.
</pre>
Output of `cscli metrics` shows:
<pre>
INFO[0000] Acquisition Metrics:
+---------------------------+------------+--------------+----------------+------------------------+
|          SOURCE           | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+---------------------------+------------+--------------+----------------+------------------------+
| /var/log/httpd/access_log |          7 |            7 | -              | -                      |
| /var/log/messages         |        710 | -            |            710 | -                      |
| /var/log/nginx/access.log |          7 | -            |              7 | -                      |
| /var/log/secure           |         24 | -            |             24 | -                      |
+---------------------------+------------+--------------+----------------+------------------------+
INFO[0000] Parser Metrics:
+----------------------------------+------+--------+----------+
|             PARSERS              | HITS | PARSED | UNPARSED |
+----------------------------------+------+--------+----------+
| child-crowdsecurity/apache2-logs |    7 |      7 | -        |
| child-crowdsecurity/http-logs    |   21 |     11 |       10 |
| child-crowdsecurity/nginx-logs   |   14 | -      |       14 |
| child-crowdsecurity/sshd-logs    |   60 | -      |       60 |
| crowdsecurity/apache2-logs       |    7 |      7 | -        |
| crowdsecurity/dateparse-enrich   |    7 |      7 | -        |
| crowdsecurity/geoip-enrich       |    7 |      7 | -        |
| crowdsecurity/http-logs          |    7 |      3 |        4 |
| crowdsecurity/nginx-logs         |    7 | -      |        7 |
| crowdsecurity/non-syslog         |   14 |     14 | -        |
| crowdsecurity/sshd-logs          |   12 | -      |       12 |
| crowdsecurity/syslog-logs        |  734 |    734 | -        |
| crowdsecurity/whitelists         |    7 |      7 | -        |
+----------------------------------+------+--------+----------+
INFO[0000] Local Api Metrics:
+--------------------+--------+------+
|       ROUTE        | METHOD | HITS |
+--------------------+--------+------+
| /v1/alerts         | GET    |    4 |
| /v1/watchers/login | POST   |    8 |
+--------------------+--------+------+
INFO[0000] Local Api Machines Metrics:
+----------------------------------+------------+--------+------+
|             MACHINE              |   ROUTE    | METHOD | HITS |
+----------------------------------+------------+--------+------+
| 87894ea7f2a54c7da86841f02addf27f | /v1/alerts | GET    |    4 |
+----------------------------------+------------+--------+------+
</pre>

**Comment by buixor** [comment]
Hello !

Can you share the `/var/log/crowdsec.log` error log please ?

Thanks !

**Comment by skyser93** [comment]
[crowdsec.log](https://github.com/crowdsecurity/crowdsec/files/6128821/crowdsec.log)

**Comment by buixor** [comment]
Hello, I might have spotted the issue.
Can you please try to remove the `crowdsecurity/ban-reports-ssh_bf_report` scenario and see if it happens ?

(I'm going to try and reproduce on my side in the meanwhile)

**Comment by buixor** [comment]
Hello,

Confirmed that the scenario `crowdsecurity/ban-reports-ssh_bf_report` is broken and leads to the error.
I'm going to remove it from the hub.

**Comment by buixor** [comment]
Hello, the above MR fixed the issue (it's because you seem to have installed a old/broken scenario that has been removed).

Please remove `crowdsecurity/ban-reports-ssh_bf_report` locally !

and thanks for the report !
