### ISSUE TITLE
Bug/API error

### ISSUE THREAD

**Issue by skyser93** [crowdsecurity/crowdsec#682]
**Describe the bug**
level=error msg="capi metrics: sending metrics failed: API error: The incoming token has expired"
After restarting crowdsec, this error disappears.
<pre>
[root@localhost]# cscli --debug capi status
DEBU[0000] Using /etc/crowdsec/config.yaml as configuration file
DEBU[0000] loading hub idx /etc/crowdsec/hub/.index.json
DEBU[0000] 4 item types in hub index
DEBU[0000] scanning /etc/crowdsec
DEBU[0000] scanning /etc/crowdsec/hub
INFO[0000] Loaded credentials from /etc/crowdsec/online_api_credentials.yaml
INFO[0000] Trying to authenticate with username 87894ea7f2a54c7da86841f02addf27fTTktFWQf5mcW3LMU on https://api.crowdsec.net/
INFO[0001] You can successfully interact with Central API (CAPI)
DEBU[0001] [headers] X-Amzn-Trace-Id : [Root=1-604b0ef1-113e6135776c191f6d326c89]
DEBU[0001] [headers] Date : [Fri, 12 Mar 2021 06:49:21 GMT]
DEBU[0001] [headers] Content-Type : [application/json]
DEBU[0001] [headers] Content-Length : [963]
DEBU[0001] [headers] X-Amzn-Requestid : [07646449-04df-4bf9-906c-c11aae02f221]
DEBU[0001] [headers] X-Amz-Apigw-Id : [cD9FxEefjoEFtgQ=]
DEBU[0001] Response: HTTP/2.0 200 OK
Content-Length: 963
Content-Type: application/json
Date: Fri, 12 Mar 2021 06:49:21 GMT
X-Amz-Apigw-Id: cD9FxEefjoEFtgQ=
X-Amzn-Requestid: 07646449-04df-4bf9-906c-c11aae02f221
X-Amzn-Trace-Id: Root=1-604b0ef1-113e6135776c191f6d326c89

</pre>

**Technical Information (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009
 - Version Version v1.0.7

**Additional context**
Output of `cscli machines list`:
<pre>
----------------------------------------------------------------------------------------------------------------------------------
 NAME                              IP ADDRESS  LAST UPDATE                STATUS  VERSION
----------------------------------------------------------------------------------------------------------------------------------
 87894ea7f2a54c7da86841f02addf27f  127.0.0.1   2021-02-12T04:54:14+03:00  ✔️       v1.0.7-18ff3a3a306d1eca786038fb343250e43784a900
----------------------------------------------------------------------------------------------------------------------------------
</pre>

**Comment by buixor** [comment]
Hello,

Would you mind sharing some of your `/var/log/crowdsec.log` around when this happened if you had other errors ?

If I'm not mistaken, `level=error msg="capi metrics: sending metrics failed: API error: The incoming token has expired"` might happen when crowdsec tries to push to the central API while its token is expired, but it should re-authenticate and won't lead to undesirable side effect. Did you just notice this error in the logs, or did you see crowdsec misbehave as well ?

Thanks,

**Comment by skyser93** [comment]
Thanks for the help!
