### ISSUE TITLE
Improvement/blocklist

### ISSUE THREAD

**Issue by reinerj** [crowdsecurity/crowdsec#683]
**Is your feature request related to a problem? Please describe.**
There should be an easy option to add to the blocklist automatically the IP list as example from shodan.io and other similar services. Also several bad IP list are available for free to use.  

**Describe the solution you'd like**
There should be an option that services as example like Shodan will be installed with crowdsec to stop them inspecting your server. There are also several public IP lists available which could be used from know attacher sites or spammer sites. For sure you can also stop as example known spammers on your mailserver but it would be much better to stop them before they reach it.  

**Describe alternatives you've considered** (Optional) 
You can write your own handmade scripts to download and add this IP addresses to iptables as example with ipset but when there is already a solution in place like crowdsec it would be much easier to combine this and update regular 

**Example of what you imagine**
Crowdsec will pull from different sources where there should be to possibility to exclude or include what you want use. Some lists are huge when to be used on a small system, it would possible run out of memory  

**Additional context**

**Comment by buixor** [comment]
Stay tuned, we didn't forget this one :smile:

**Comment by buixor** [comment]
https://doc.crowdsec.net/docs/next/cscli/cscli_decisions_import/ was merged a few releases ago and I forgot to close this one.
We are as well adding support for proper "subscriptions" to 3rd party lists in https://app.crowdsec.net (but this is a bit out of scope for the open-source part itself!)
