### ISSUE TITLE
Bug/enabling use_forwarded_for_headers yields yaml unmarshal errors when using cscli

### ISSUE THREAD

**Issue by jamiew0w** [crowdsecurity/crowdsec#695]
**Describe the bug**
setting `use_forwarded_for_headers: true` in the config _DOES_ work, however when using cscli afterwards, it complains of an unmarshal error and doesn't proceed.

```
FATA[0000] failed unmarshaling config: yaml: unmarshal errors:
  line 39: field use_forwarded_for_headers not found in type csconfig.LocalApiServerCfg
```

If I then comment out the `use_forwarded_for_headers` entry in the config and use cscli again, it works (and shows the correct forwarded IP addresses).

**To Reproduce**
1. be using a reverse proxy and be forwarding addresses to crowdsec properly
2. create new machine from outside your LAN, register and validate it
3. using `cscli machines list` it should show the IP address of your reverse proxy
4. set `use_forwarded_for_headers: true` in the server config
5. `cscli machines list` will now show the error mentioned above
6. restart the crowdsec instance on the remote client and wait a minute
7. comment out `use_forwarded_for_headers: true`, cscli will work again. `cscli machines list` and it will show the remote IP correctly.

**Expected behavior**
`use_forwarded_for_headers: true` shouldn't complain of an unmarshal error, rendering cscli unusable when activated.

**Technical Information (please complete the following information):**
 - OS: ubuntu 20.04
 - Version 1.0.9-1-debian-pragmatic-a8b16a66b110ebe03bb330cda2600226a3a862d7

**Additional context**
(my apologies if the steps are a bit unwieldy - please let me know if anything needs clarifying)

**Comment by AlteredCoder** [comment]
Hello @jamiew0w ,

I didn't managed to reproduce the bug.
What is the version of your `cscli` ? it seems that you use an older version than your crowdsec one.

**Comment by jamiew0w** [comment]
Hi @AlteredCoder 

You're correct. There was two versions of cscli, one in /usr/bin and one in /usr/local/bin. I guess the old installer (i'm using the debian packages) used /usr/local/bin and it never got removed.
Deleting the old one will likely fix this, testing it now.

```
root@backup:~# whereis cscli
cscli: /usr/bin/cscli /usr/local/bin/cscli
root@backup:~# cscli version
2021/03/17 12:34:51 version: v1.0.2-b79c897d99cf18c031846398d01bbec7f7d79c3d
```

On a newer machine:

```
root@zabbix:~# whereis cscli
cscli: /usr/bin/cscli
root@zabbix:~# cscli version
2021/03/17 12:37:23 version: 1.0.9-1-debian-pragmatic-a8b16a66b110ebe03bb330cda2600226a3a862d7
```

**Comment by jamiew0w** [comment]
yep, that fixed it. nice!

Thanks again for your help!
