### ISSUE TITLE
Bug/crowdsec - goroutine crowdsec/runParse crashed : interface conversion: interface {} is nil, not parser.GeoIpEnricherCtx

### ISSUE THREAD

**Issue by rafipiccolo** [crowdsecurity/crowdsec#716]
process crashes after some seconds

**To Reproduce**
run this
```
touch ./crowdsec/data/crowdsec.db
touch ./crowdsec/config/local_api_credentials.yaml
```

create this docker compose file
```
crowdsec:
        container_name: crowdsec
        restart: always
        image: crowdsecurity/crowdsec:latest
        ports:
            - "8080:8080"
        volumes:
            - ./crowdsec/config/acquis.yaml:/etc/crowdsec/acquis.yaml
            - ./crowdsec/config/local_api_credentials.yaml:/etc/crowdsec/local_api_credentials.yaml
            - ./crowdsec/data:/var/lib/crowdsec/data
            - /var/log/auth.log:/logs/auth.log:ro
            - /var/log/syslog:/logs/syslog:ro
        environment:
            - "COLLECTIONS=crowdsecurity/sshd"
```

run it :
```
docker-compose up -d
```

**Expected behavior**
just running and working

**Technical Information (please complete the following information):**
ubuntu 20.04
 - crowdsec Version v1.0.9-docker-a8b16a66b110ebe03bb330cda2600226a3a862d7 

**Additional context**

docker logs -f crowdsec
time="22-03-2021 11:32:55 PM" level=info msg="push and pull to crowdsec API disabled"
 0a10039f069d45e6b9fc4426a6bba1beyCi5ANeAGAP5OM6k  127.0.0.1   2021-03-22T23:30:18Z  ✔️       v1.0.9-docker-a8b16a66b110ebe03bb330cda2600226a3a862d7 
time="22-03-2021 11:32:56 PM" level=info msg="push and pull to crowdsec API disabled"
time="22-03-2021 11:32:58 PM" level=info msg="Successfully registered to Central API (CAPI)"
time="22-03-2021 11:32:58 PM" level=info msg="Central API credentials dumped to '/etc/crowdsec/online_api_credentials.yaml'"
time="22-03-2021 11:32:58 PM" level=warning msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective"
time="22-03-2021 11:32:59 PM" level=info msg="Wrote new 103344 bytes index to /etc/crowdsec/hub/.index.json"
time="22-03-2021 11:32:59 PM" level=info msg="crowdsecurity/linux : up-to-date"
time="22-03-2021 11:32:59 PM" level=info msg="Item 'crowdsecurity/linux' is up-to-date"
time="22-03-2021 11:32:59 PM" level=info msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
time="22-03-2021 11:32:59 PM" level=info msg="/etc/crowdsec/collections/sshd.yaml already exists."
time="22-03-2021 11:32:59 PM" level=info msg="Enabled crowdsecurity/sshd"
time="22-03-2021 11:32:59 PM" level=info msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
time="22-03-2021 23:32:59" level=info msg="Crowdsec v1.0.9-docker-a8b16a66b110ebe03bb330cda2600226a3a862d7"
time="22-03-2021 23:32:59" level=info msg="Loading prometheus collectors"
time="22-03-2021 23:32:59" level=info msg="Loading CAPI pusher"
time="22-03-2021 23:32:59" level=info msg="start crowdsec api push (interval: 30s)"
time="22-03-2021 23:32:59" level=info msg="start crowdsec api pull (interval: 2h)"
time="22-03-2021 23:32:59" level=info msg="start crowdsec api send metrics (interval: 30m)"
time="22-03-2021 23:32:59" level=info msg="Loading grok library /etc/crowdsec//patterns/"
time="22-03-2021 23:33:00" level=info msg="Loading enrich plugins"
time="22-03-2021 23:33:00" level=warning msg="load (fake) plugin load : open /var/lib/crowdsec/data//GeoLite2-City.mmdb: no such file or directory"
time="22-03-2021 23:33:00" level=info msg="Loading parsers 4 stages"
time="22-03-2021 23:33:00" level=info msg="Node in /etc/crowdsec/parsers/s00-raw/syslog-logs.yaml has no name,author or description. Skipping."
time="22-03-2021 23:33:00" level=info msg="Loaded 2 parser nodes" file=/etc/crowdsec/parsers/s00-raw/syslog-logs.yaml
time="22-03-2021 23:33:00" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/parsers/s01-parse/sshd-logs.yaml
time="22-03-2021 23:33:00" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/parsers/s02-enrich/dateparse-enrich.yaml
time="22-03-2021 23:33:00" level=error msg="open /var/lib/crowdsec/data/GeoLite2-City.mmdb: no such file or directory"
time="22-03-2021 23:33:00" level=error msg="open /var/lib/crowdsec/data/GeoLite2-ASN.mmdb: no such file or directory"
time="22-03-2021 23:33:00" level=info msg="Loaded 1 parser nodes" file=/etc/crowdsec/parsers/s02-enrich/geoip-enrich.yaml
time="22-03-2021 23:33:00" level=info msg="Loaded 5 nodes, 3 stages"
time="22-03-2021 23:33:00" level=info msg="Loading postoverflow Parsers"
time="22-03-2021 23:33:00" level=info msg="Loaded 0 nodes, 0 stages"
time="22-03-2021 23:33:00" level=info msg="Loading 1 scenario files"
time="22-03-2021 23:33:00" level=info msg="Adding leaky bucket" cfg=black-sea file=/etc/crowdsec/scenarios/ssh-bf.yaml name=crowdsecurity/ssh-bf
time="22-03-2021 23:33:00" level=info msg="Adding leaky bucket" cfg=frosty-water file=/etc/crowdsec/scenarios/ssh-bf.yaml name=crowdsecurity/ssh-bf_user-enum
time="22-03-2021 23:33:00" level=warning msg="Loaded 2 scenarios"
time="22-03-2021 23:33:00" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"
time="22-03-2021 23:33:00" level=info msg="[file datasource] opening file '/logs/auth.log'"
time="22-03-2021 23:33:00" level=info msg="[file datasource] opening file '/logs/syslog'"
time="22-03-2021 23:33:00" level=warning msg="Starting processing data"
time="22-03-2021 23:33:42" level=info msg="pull top: added 100 entries"
127.0.0.1 - [Mon, 22 Mar 2021 23:33:42 UTC] "POST /v1/watchers/login HTTP/1.1 200 42.67325549s "crowdsec/v1.0.9-docker-a8b16a66b110ebe03bb330cda2600226a3a862d7" "
127.0.0.1 - [Mon, 22 Mar 2021 23:33:43 UTC] "POST /v1/watchers/login HTTP/1.1 200 259.329469ms "crowdsec/v1.0.9-docker-a8b16a66b110ebe03bb330cda2600226a3a862d7" "
time="22-03-2021 23:34:08" level=error msg="crowdsec - goroutine crowdsec/runParse crashed : interface conversion: interface {} is nil, not parser.GeoIpEnricherCtx"
time="22-03-2021 23:34:08" level=error msg="please report this error to https://github.com/crowdsecurity/crowdsec/"
time="22-03-2021 23:34:08" level=error msg="stacktrace/report is written to /tmp/crowdsec-crash.224995139.txt : please join it to your issue"
time="22-03-2021 23:34:08" level=fatal msg="crowdsec stopped"

**Comment by rafipiccolo** [comment]
if i remove theses lines in acquis.yml it stops crashing, but ofc the project becomes useless :)
- /logs/auth.log
- /logs/syslog

**Comment by rafipiccolo** [comment]
Also i was able to stop crashing by removing this file (but feels like a huge hack :))

docker exec -ti crowdsec rm /etc/crowdsec/parsers/s02-enrich/geoip-enrich.yam

**Comment by buixor** [comment]
Hello @rafipiccolo !

It seems to crash because the `geoip-enrich` is enabled but cannot file its associated `.mmdb` file.
You just fetch the crowdsec image from docker hub ?

**Comment by rafipiccolo** [comment]
yes. where should be the mmdb file ?
i could try to find it in the container.
let me know if i can help.

**Comment by buixor** [comment]
Hello, I was able to reproduce, the issue is on our end. We'll keep you posted !

**Comment by rafipiccolo** [comment]
thk u rock

**Comment by Masgalor** [comment]
I have the exact same problem but with the debian package.

After installing crowdsec from the repo everything worked as expected until I did:
```
cscli hub update
cscli hub upgrade
```

Now it is crashing the same way as described above.

`/var/lib/crowdsec/data` is not empty but has no `.mmdb` files.

**Comment by Masgalor** [comment]
I downloaded the missing files manually, now it is working again.
```
cd /var/lib/crowdsec/data
wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/GeoLite2-City.mmdb
wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/GeoLite2-ASN.mmdb
```
