### ISSUE TITLE
Bug/crowdsec: Error loglevel includes all requests to the API

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#726]
**Describe the bug**
Setting the API loglevel to `error` doesn't prevent it from logging every single request made to it. This causes a lot of logs to be emitted.

**Expected behavior**
I'd expect the "error" level to only show important messages, which the request logs aren't.

Fixing this would be a small improvement for #502.

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version: 1.0.7 (latest at time of writing on your Debian repo)

**Comment by buixor** [comment]
Hello @ThinkChaos ,

Thanks for the issue, I'm opening an MR to fix it :+1:
