### ISSUE TITLE
Bug/crowdsec: Debian package duplicates logs by default

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#727]
**Describe the bug**
Installing the debian package from your repo (see [here](https://discourse.crowdsec.net/t/debian-package-availability/116/9)) causes logs to be duplicated.
They are both sent to stdout/stderr (which ends up in syslog: `/var/log/daemon.log`) and to `/var/log/crowdsec_api.log`.

Combined with #726 this causes crowdsec to spam logs.

**Expected behavior**
I'd a single source of truth for the logs. I think only having them in `crowdsec_api.log` would be best so that `daemon.log` can be used as an log source in crowdsec.
Of course stderr should still show fatal errors for easy service debugging with `systemctl status crowdsec`.

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version: 1.0.7 (latest at time of writing on your Debian repo)

**Comment by buixor** [comment]
Hello, 

If I'm not mistaken, this was fixed by https://github.com/crowdsecurity/crowdsec/pull/707 and should only concern local api logs.
It will ship with 1.0.11 once it leaves pre-release.

(keeping this issue open for tracking)
