### ISSUE TITLE
Bug/crowdsec: pid file should be in /run

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#728]
**Describe the bug**
systemd complains about the pid file being in `/var/run` and overrides it with `/run`.

**Expected behavior**
Both crodwsec's config and the service file should be updated to use `/run`.

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version: 1.0.7 (latest at time of writing on your Debian repo)

**Additional context**
```
systemd[1]: /etc/systemd/system/crowdsec.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/crowdsec.pid → /run/crowdsec.pid; please update the unit file accordingly.
```

**Comment by he2ss** [comment]
It's fixed, it will be available in the next package release :)
