### ISSUE TITLE
Bug/crowdsec: pid file missing

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#729]
**Describe the bug**
Crowdsec pid file doesn't get created.

**Expected behavior**
The file should be created in the configured directory.

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version: 1.0.7 (latest at time of writing on your Debian repo)

**Comment by he2ss** [comment]
Hi @ThinkChaos,

We just forgot to remove the `pid_dir` directive, because it's no longer supported by crowdsec, only with systemd.
We are thinking about adding the pid_file creation by crowdsec if enabled in config or give hand to systemd to do it. What do you think about that ?

**Comment by ThinkChaos** [comment]
I think letting systemd handle it is fine, it should make it simpler on crowdsec's side :)

**Comment by FinweVI** [comment]
Hello,

on your systemd service file you guys are using the `PIDFile` directive while it's not really recommended anymore (https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=)

It can lead to errors such as: `systemd[1]: crowdsec.service: Can't open PID file /run/crowdsec.pid (yet?) after reload: No such file or directory`

When reloading the agent.

Also the `pid_dir` configuration option seems to still be there OOTB on a fresh install (Ubuntu) and default to `/var/run`
