### ISSUE TITLE
cscli from crowdsec 1.0.11 does not work on Centos 7

### ISSUE THREAD

**Issue by SignFinder** [crowdsecurity/crowdsec#733]
I have an error on Centos 7.9 x64 when install crowdsec via binaries (crowdsec 1.0.11)
"cscli: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by cscli)"
Version 1.0.9 installed correct. There is differences benween cscli 1.0.11 and 1.0.9 
![csclierror](https://user-images.githubusercontent.com/299814/113471684-b473e000-9466-11eb-81f5-35f3946be070.png)
on attached screenshot
Might the good idea to compile releases binaries statically.
csclierror

**Comment by sabban** [comment]
I do confirm this issue. We'll investigate.

**Comment by registergoofy** [comment]
Fixed in 1.0.12. Please use the crowdsec-release-static.tgz, this shouldn't depend on libc version.
