### ISSUE TITLE
Bug/crowdsec: reload doesn't release logs file descriptors

### ISSUE THREAD

**Issue by svesve** [crowdsecurity/crowdsec#744]
**Describe the bug**
Crowdsec reloading, doesn't release file descriptors on centos 7
first run corwdsec
```
lsof |grep crowdsec | wc -l
7832
```
reload
```
lsof |grep crowdsec | wc -l
15320
```

**To Reproduce**
1. Run crowdesc on centos 7
2. count opened files via lsof |grep crowdsec | wc -l
3. reload crowdsec service
4. count opened files via lsof |grep crowdsec | wc -l

**Expected behavior**
opened files before reload and after must be same +-

**Technical Information (please complete the following information):**
 - OS: Centos 7
 - kernel 3.10.0-1127.19.1.el7.x86_64

**Comment by buixor** [comment]
Thanks for the issue, looking into it !

**Comment by buixor** [comment]
@svesve : which version of crowdsec are you using btw ?

**Comment by svesve** [comment]
> @svesve : which version of crowdsec are you using btw ?

1.0.9

**Comment by buixor** [comment]
@svesve thanks, I opened an MR to fix this, bug confirmed.

It will be in the new release that should be pretty imminent :+1:
