### ISSUE TITLE
Improvement/ Could we see the "version" option in the cscli help / options output

### ISSUE THREAD

**Issue by philippecrowdsec** [crowdsecurity/crowdsec#751]
Please, start your issue name (after `improvement`) with the component name impacted by this feature request and a small description of the FR. Example: `Improvement/cscli: add this feature ....` and remove this line :)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered** (Optional) 

**Example of what you imagine**
If applicable, add an example of what you would expect from this feature request.

**Additional context**

**Comment by AlteredCoder** [comment]
Fixed in v1.0.9
