### ISSUE TITLE
Bug/crowdsec for slave installation in multi-server setup

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#752]
When setting up a crowdsec agent in a multi-machine setup. This issue is for the apiless server.

**Describe the bug**

`cscli machines list` gives a misleading error besides `cscli alerts list` works.

`cscli mahcines list` gives FATA[15-04-2021 03:38:27 PM] unable to create new database client: DB config is empty.

On top of that, when starting an apiless agent, a warning is displayed "crowdsec local API is disabled"

**Expected behavior**
cscli machines list should at least give a meaningful error or add an API endpoint for giving the list of machines. The warning message should be removed or made info message.

**Comment by buixor** [comment]
dup #753
