### ISSUE TITLE
Bug/deb-repo: Package out of date

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#755]
Your official Debian repo is out of date.
Can you setup continuous delivery for it/update your release method to make sure it gets updated at the same time as the rest?

**Comment by buixor** [comment]
Hello,

What make you think so ? Latest public release is 1.0.9, latest package is `1.0.9-4` ?

Cheers,

**Comment by ThinkChaos** [comment]
Sorry I got confused, I didn't notice 1.0.11/12 were pre-releases when I got the notifications.
