### ISSUE TITLE
Bug/lapi: some `events` has the `alert_events` to NULL

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#778]
**Describe the bug**
For some users, we have the `alert_events` and the `alert_decisions` set to NULL in DB.
This lead to crowdsec not flushing them and the database size growing.

**To Reproduce**
Still didn't manage to reproduce

**Technical Information (please complete the following information):**
 - crowdsec v1.0.13

I think we should at least remove all `alert_events` and the `alert_decisions` that are set to NULL when flushing the database.

**Comment by buixor** [comment]
After investigation, the most plausible (so far) explanation is :
 -those events were all created during daylight saving hour, with agent on a machine without DST and LAPI on a machine with DST *using mysql*
 - currently the bulk insertion is as follows : insert events, insert decisions, insert alerts

Thus, as the time inserted is illegal for a machine with DST (`2021-03-28 02:53:24.059753`), the events are inserted but the alerts and decisions fail to, leading to orphan `events` entries without a parent `alert` entry.

We keep this open for the record, but it seems to be considered a corner case.
