### ISSUE TITLE
Improvement/cscli: Add domain or at least the source log file to the event

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/crowdsec#780]
**Is your feature request related to a problem? Please describe.**
I host multiple websites on the same apache server. When Crowdsec raises an alarm, I see why it is banned, but not for which domain. I can't say website XY is under attack without digging deeper into log files.

**Describe the solution you'd like**
Best would be that I can see in `cscli decisions list` the domain it attacked. Or with the command `cscli alerts list`.
Another approach is to include the full path to the source log file in the alert. With that I can see which domain is actually under attack using `cscli alerts inspect 158`.

**Comment by Lamera** [comment]
Hi @AlteredCoder :smile: 
Thanks for the tip. Didn't know that switch for inspect.
But it doesn't solve my issue, because I don't see the domain name in the alert. With `-d` I can see the http path of the alert, but not the domain.

**Comment by AlteredCoder** [comment]
erf ok, i think we need to improve our parser to give you this information

**Comment by buixor** [comment]
Hello !

Logging the full meta in the alert log might be a bit too noisy (think http with long URLs and user-agents), however :
 - we're about to merge [a change in the syslog parser that would include the logfile in the metas](https://github.com/crowdsecurity/hub/pull/234)
 -  if you `cscli alerts inspect -d <alert_id>` you're going to see the whole metas of the alerts :

```
# cscli  alerts inspect -d 759

################################################################################################

 - ID         : 759
 - Date       : 2021-08-31T08:40:52+02:00
 - Machine    : x
 - Simulation : false
 - Reason     : crowdsecurity/http-probing
 - Events Count : 11
 - Scope:Value: Ip:xxx.xxx.184.237
 - Country    : 
 - AS         : 


 - Events  :

- Date: 2021-08-31 08:40:51 +0200 +0200
+-----------------+--------------------------------+
|       KEY       |             VALUE              |
+-----------------+--------------------------------+
| ASNNumber       |                              0 |
| IsInEU          | false                          |
| http_args_len   |                              0 |
| http_path       | /wp-includes/wlwmanifest.xml   |
| http_status     |                            404 |
| http_user_agent | Mozilla/5.0 (Windows NT 10.0;  |
|                 | Win64; x64) AppleWebKit/537.36 |
|                 | (KHTML, like Gecko)            |
|                 | Chrome/88.0.4240.193           |
|                 | Safari/537.36                  |
| http_verb       | GET                            |
| log_type        | http_access-log                |
| service         | http                           |
| source_ip       | xxx.xxx.184.237                |
| target_fqdn     | xxxxx.ro                       |
+-----------------+--------------------------------+

```
