### ISSUE TITLE
Bug/crash

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/crowdsec#785]
Get that crash today

cs log :
time="07-05-2021 14:43:59" level=error msg="crowdsec - goroutine crowdsec/middlewaresV1/api_key/MiddlewareFunc crashed : write tcp 10.1.0.2:8080->10.1.158.111:21182: write: broken pipe"
time="07-05-2021 14:43:59" level=error msg="please report this error to https://github.com/crowdsecurity/crowdsec/"
time="07-05-2021 14:43:59" level=error msg="stacktrace/report is written to /tmp/crowdsec-crash.630421472.txt : please join it to your issue"
time="07-05-2021 14:43:59" level=fatal msg="crowdsec stopped"

crash dump :
error : write tcp 10.1.0.2:8080->10.1.158.111:21182: write: broken pipe
version: v1.0.13-3-debian-pragmatic-a19f13ab45a18024ad7ddbf38ef2ff4aadeaaaf5
Codename: alphaga
BuildDate: 2021-04-28_08:48:24
GoVersion: 1.15.8
Platform: linux
goroutine 5869 [running]:
runtime/debug.Stack(0xc00137e080, 0xc0010d83c0, 0xa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/crowdsecurity/crowdsec/pkg/types.WriteStackTrace(0x13b8400, 0xc0011ce230, 0x14df79f, 0x46)
	/crowdsec/pkg/types/utils.go:88 +0x2ce
github.com/crowdsecurity/crowdsec/pkg/types.CatchPanic(0x14d2210, 0x2d)
	/crowdsec/pkg/types/utils.go:103 +0x14e
panic(0x13b8400, 0xc0011ce230)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gin-gonic/gin/render.JSON.Render(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:59
github.com/gin-gonic/gin.(*Context).Render(0xc000638c30, 0xc8, 0x15eeaa0, 0xc000ce5f80)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 +0x149
github.com/gin-gonic/gin.(*Context).JSON(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884
github.com/crowdsecurity/crowdsec/pkg/apiserver/controllers/v1.(*Controller).StreamDecision(0xc0002fdea0, 0xc000638c30)
	/crowdsec/pkg/apiserver/controllers/v1/decisions.go:169 +0x1d58
github.com/gin-gonic/gin.(*Context).Next(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/crowdsecurity/crowdsec/pkg/apiserver/controllers/v1.PrometheusBouncersMiddleware.func1(0xc000638c30)
	/crowdsec/pkg/apiserver/controllers/v1/metrics.go:96 +0x65
github.com/gin-gonic/gin.(*Context).Next(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/crowdsecurity/crowdsec/pkg/apiserver/middlewares/v1.(*APIKey).MiddlewareFunc.func1(0xc000638c30)
	/crowdsec/pkg/apiserver/middlewares/v1/api_key.go:112 +0x73b
github.com/gin-gonic/gin.(*Context).Next(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/crowdsecurity/crowdsec/pkg/apiserver/controllers/v1.PrometheusMiddleware.func1(0xc000638c30)
	/crowdsec/pkg/apiserver/controllers/v1/metrics.go:105 +0x145
github.com/gin-gonic/gin.(*Context).Next(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/crowdsecurity/crowdsec/pkg/apiserver.CustomRecoveryWithWriter.func1(0xc000638c30)
	/crowdsec/pkg/apiserver/apiserver.go:86 +0x4e
github.com/gin-gonic/gin.(*Context).Next(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe5
github.com/gin-gonic/gin.(*Context).Next(0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000461180, 0xc000638c30)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x67a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000461180, 0x15fa760, 0xc001f12d20, 0xc0005a8700)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0000e60e0, 0x15fa760, 0xc001f12d20, 0xc0005a8700)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000eea780, 0x15fd660, 0xc001484640)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

**Comment by LtSich** [comment]
To give more information the crash happen when I was upgrading some bouncers (cs-fw 0.0.10 to 0.0.12).
Probably when I do the systemctl restart cs-firewall-bouncer after the upgrade.

**Comment by AlteredCoder** [comment]
thanks @LtSich , i will try to reproduce this!

**Comment by buixor** [comment]
Nice catch, while the `CustomRecoveryWithWriter` will handle this gently (ie. broken pipe shouldn't lead to a `fatal`), two middlewares still have their own panic handler that lead to this behavior : at least JWT and API auth middlewares.

**Comment by buixor** [comment]
dealt with in https://github.com/crowdsecurity/crowdsec/pull/788 
will ship in next release
