### ISSUE TITLE
Bug/lapi: LAPI fatal when agent fatal

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#786]
**Describe the bug**
When LAPI and crowdsec agent run together in the same daemon, if crowdsec agent has an error (level fatal), LAPI fatal also.
This behavior can impact other crowdsec agent pushing to this LAPI. 

**To Reproduce**
1. change the listen_uri of your API server
2. restart crowdsec
3. LAPI will fatal also because the agent cannot connect to the LAPI

**Expected behavior**
the LAPI not to crash

**Technical Information (please complete the following information):**
 - crowdsec v1.0.13

**Comment by he2ss** [comment]
Following a discussion about this subject. We finally don't want to let fail only the agent.
Because users will often let the agent in fatal mode without detecting it. We want to let both fatal so the user will need to fix and then be able to rerun LAPI.
