### ISSUE TITLE
Bug/simulation: simulation mode seems to not be supported anymore

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#787]
**Describe the bug**
The simulation mode doesn't seems to work anymore :(

**To Reproduce**
1. enable the simulation mode globally
2. attack your server
3. inspect the alert to check if the alert is in simulation

**Expected behavior**
The alert to be simulated

**Technical Information (please complete the following information):**
 - crowdsec v1.0.13

**Comment by buixor** [comment]
After a quick look, it *seems* to have been broken in 1.0.13 with the configuration load revamp. (crowdsec doesn't load simulation at startup, only a reload)
