### ISSUE TITLE
Bug/ Correction of the documentation

### ISSUE THREAD

**Issue by Geoffrey-lvg** [crowdsecurity/crowdsec#796]
In this tutorial we are asked to create a folder "s01-parser" but it does not work, just put our parser in "s01-parse"

```
mkdir -p config/parsers/s01-parser
cp myparser.yaml config/parsers/s01-parser/ 
```

https://docs.crowdsec.net/Crowdsec/v1/write_configurations/parsers/

**Comment by AlteredCoder** [comment]
Hello, thanks for the issue!

Fixed in https://github.com/crowdsecurity/crowdsec/pull/800
