### ISSUE TITLE
Bug/ Correction of the documentation

### ISSUE THREAD

**Issue by Geoffrey-lvg** [crowdsecurity/crowdsec#797]
In this tutorial we will learn how to upgrade the installed packages
The package "sshd-bf" does not exist it is in fact "ssh-bf"

`$ sudo cscli scenarios upgrade crowdsecurity/sshd-bf`

https://docs.crowdsec.net/Crowdsec/v1/user_guide/configurations_management/scenarios/#upgrading-installed-scenarios

**Comment by AlteredCoder** [comment]
Hello! Thanks for the issue.

Fixed in https://github.com/crowdsecurity/crowdsec/pull/798
