### ISSUE TITLE
Bug/installer Cant Install : cannot stat './cmd/crowdsec/crowdsec': No such file or directory

### ISSUE THREAD

**Issue by ScarVite** [crowdsecurity/crowdsec#809]
**Describe the bug**
Doing the Initial Installation, the setup fails

**To Reproduce**
git clone https://github.com/crowdsecurity/crowdsec.git
cd crowdsec && ./wizard.sh -i

**Expected behavior**
The Firewall should be installed and i should be able to configure and even use it

**Screenshots**
![firefox_DkEIYBpVJC](https://user-images.githubusercontent.com/43887376/119693313-7387be80-be4c-11eb-8b19-69e2e35f30de.png)

**Technical Information (please complete the following information):**
 Debian GNU/Linux 10 (buster) x86_64

**Additional context** (same as screenshot)
INFO[05/26/21:18:00:52] crowdsec_wizard: checking if crowdsec is installed
INFO[05/26/21:18:00:52] crowdsec_wizard: installing crowdsec
install: cannot stat './cmd/crowdsec/crowdsec': No such file or directory

**Comment by AlteredCoder** [comment]
Hello @ScarVite,

You are trying to install crowdsec from the source folder directly, which is not possible without building crowdsec.
You can find [here](https://docs.crowdsec.net/Crowdsec/v1/getting_started/installation/) several method to install crowdsec.

Please let us know if it went good :)

**Comment by ScarVite** [comment]
I've just followed the steps mentioned in Readme

Shouldn't it be updated it the mentioned method isn't even possible?

**Comment by AlteredCoder** [comment]
Oh yes nice catch! I'm sorry about, its an error from our side. I'm going to update the README right now.

**Comment by ScarVite** [comment]
Thank you for your quick help.
Appreciate it
