### ISSUE TITLE
Bug/acquisition Cleanup test data after running tests

### ISSUE THREAD

**Issue by sbs2001** [crowdsecurity/crowdsec#818]
**Describe the bug**
The tests for pkg/acquisition write data to test data files. When the tests are again ran they fail due to previously written data. Tests should have no side effects.

**To Reproduce**
```bash
cd pkg/acquisition/
go test .
go clean -testcache
go test .
```

This is caused because some test is writting to https://github.com/crowdsecurity/crowdsec/blob/master/pkg/acquisition/tests/test.log
```
➜  acquisition git:(master) ✗ cat tests/test.log
one log line
atata0
ratata1
ratata2
ratata3
ratata4
ratata0
ratata1
ratata2
ratata3
ratata4
```

**Expected behavior**
Tests should not succeed no matter how many times they are ran.

**Comment by blotus** [comment]
Fixed by the acquisition revamp & new tests.
