### ISSUE TITLE
Improvement/ Please support armel platform

### ISSUE THREAD

**Issue by jeanbruder** [crowdsecurity/crowdsec#819]
Dear crowdsecurity Team,

Can you please provide .deb package to install on the armel platform ?

Here's the error (in french, sorry) : N: Le fichier configuré « main/binary-armel/Packages » ne sera pas pris en compte car le dépôt « https://s3-eu-west-1.amazonaws.com/crowdsec.debian.pragmatic/buster buster InRelease » ne prend pas en charge l'architecture « armel ».

Regards,
Jean

**Comment by sabban** [comment]
Hi,

We have now have armhf packages for debian and raspbian, but we don't have armel. 

Nevertheless, a debian package exist in official debian https://packages.debian.org/bullseye/armel/crowdsec/download, or you can even compile it for armel. Feel free to ask support for this in our support channels (https://gitter.im/crowdsec-project/community, https://discourse.crowdsec.net/).

Regards,
