### ISSUE TITLE
Improvement/`cscli dashboard setup` : check available resources and warn user 

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#826]
**Is your feature request related to a problem? Please describe.**
When the user is running `cscli dashboard setup` and the available resources are obviously lacking (people tend to think that the dashboard might not require more resources than crowdsec itself), we should warn the user.

**Describe the solution you'd like**
Warn the user and/or ask for a confirmation if the available resources aren't enough to run metabase

**Comment by buixor** [comment]
I think we should use something like https://github.com/pbnjay/memory and check that > 1Gb of ram is present (as per metabase req's).

**Comment by nanikjava** [comment]
@buixor Interested to work on this. 

So what we need to check is only memory ? like in free memory ? anything else we want to check ?

**Comment by buixor** [comment]
Yes, I think RAM is enough !

**Comment by LaurenceJJones** [comment]
Hey I want to get involved in a "good first issue", this still a feature you want to implement?

**Comment by LaurenceJJones** [comment]
@buixor  Just to let you know I started working on implementing this however in the docs it states 1-2GB of ram [here](https://doc.crowdsec.net/docs/getting_started/crowdsec_tour/#deploy-dashboard=)? we should stay consistent

**Comment by buixor** [comment]
solved and shipped in 1.4 !
