### ISSUE TITLE
Improvement/make `cscli <item> upgrade` re-download the datasource(s)

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#835]
**Is your feature request related to a problem? Please describe.**
For scenarios that are using `data: source_url: http://...` there is no simple way to upgrade data source.
Currently to achieve this, you have to force scenario re-installation.

**Describe the solution you'd like**
`cscli scenario upgrade foobar` should do this, regardless of the scenario itself being up to date.

**Comment by AlteredCoder** [comment]
Currently, running  `cscli scenario upgrade foobar --force` does the job
