### ISSUE TITLE
BUG: issue with `cscli --branch`

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#84]
**Describe the bug**
When i pushed an updated scenario on a branch on the hub and wanted to install it with `cscli --branch` , i had an error.

**To Reproduce**
1. Update an existing parser and push it on a branch :
2. Run the following commands
```
./cscli -c dev.yaml update --branch add_source_for_geoip
INFO[0000] Wrote new 68522 bytes index to config/crowdsec-cli/.index.json 
```

```
./cscli -c dev.yaml install parser crowdsecurity/geoip-enrich --branch add_source_for_geoip
ERRO[0000] Downloaded version doesn't match index, please 'hub update' 
FATA[0000] error while downloading crowdsecurity/geoip-enrich : invalid download hash 
```

**Expected behavior**
I would like to install a parser from a different branch.

**Information**
 -  Linux Mint
 -  v0.2.0

**Additional context**
Note: I was doing this test with the test environment provided by crowdsec package.
Note2: I also pushed the updated parser and the `.index.json` file on the branch i created (`add_source_for_geoip` for this case)

**Comment by buixor** [comment]
The high council has decided it was github fault! (more seriously there is a delay when accessing "raw" file)
