### ISSUE TITLE
Bug/wizard.sh

### ISSUE THREAD

**Issue by sabban** [crowdsecurity/crowdsec#840]
wizard fail with some weird error because of missing whiptail
**Describe the bug**

**To Reproduce**
Try to use wizard.sh without whiptail.

Whiptail presence should be checked when wizard is launched with SILENT=false (whiptail is not needed when SILENT is true)

**Comment by buixor** [comment]
https://github.com/crowdsecurity/crowdsec/pull/new/fix_840
