### ISSUE TITLE
Bug/cscli completion

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#841]
On some setups, `cscli completion` instruction will fail if you don't source `/etc/profile` :

```
cscli decisio-bash: _get_comp_words_by_ref: command not found
```

We need to document it in the help

**Comment by he2ss** [comment]
Had to install `sudo yum install bash-completion` to fix the issue.

```
sudo yum install bash-completion
source /etc/profile
source <(cscli completion bash)
```

OS: Centos8
