### ISSUE TITLE
Improvment/cscli: install multiple configuration at the same time

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#85]
**Is your feature request related to a problem? Please describe.**
It is frustrating when you want to install multiple configuration but you have to run the command for each configuration.

**Describe the solution you'd like**
It would be great if we can install multiple configuration with the same command

**Example of what you imagine**
```
cscli install collection crowdsecurity/http-backdoors-attempts crowdsecurity/http-probing ...
```

**Comment by buixor** [comment]
done
