### ISSUE TITLE
Bug/ not able to get bouncers for raspbian

### ISSUE THREAD

**Issue by microcreators** [crowdsecurity/crowdsec#860]
**Describe the bug**
After successfully compiling it myself for rpi (armv7l), I'm trying to get bouncers from the repo. However it fails with
```
https://packagecloud.io/crowdsec/crowdsec/raspbian buster Release
  404  Not Found [IP: 54.193.9.65 443]
E: The repository 'https://packagecloud.io/crowdsec/crowdsec/raspbian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
... and apparently no crowdsec components are available. That's also a reason why I compiled the agent myself.

**To Reproduce**
1. Use the installation script from https://crowdsec.net/ --> Get Started
2. Install the repos, then "apt update". The update fails as described above
3. The line for installing bouncers will also fail as repos aren't responding

**Technical Information (please complete the following information):**
v 1.1.1
Linux  5.10.17-v7 armv7l GNU/Linux

**Comment by microcreators** [comment]
Forget it... Compiled everything from scratch ;)

**Comment by sabban** [comment]
Hi microcreators,

There's no build on our side for raspbian/raspberry pi os but there's a package in official raspberry os repository: http://raspbian.raspberrypi.org/raspbian/pool/main/c/crowdsec/
