### ISSUE TITLE
Improvement/iis

### ISSUE THREAD

**Issue by itpropaul** [crowdsecurity/crowdsec#861]
Have there ever been considerations of building this tool to work on Windows with IIS?

**Comment by sabban** [comment]
It is definitevely on the roadmap ! Please stay tuned !

**Comment by itpropaul** [comment]
Any updates?

**Comment by blotus** [comment]
Hello,

We have released an alpha version of crowdsec for windows which supports IIS and other windows services (a proper release will come soon-ish) and a bouncer for the windows firewall.

You can find the documentation on how to install everything [here](https://docs.crowdsec.net/docs/next/getting_started/install_windows).
