### ISSUE TITLE
Improvement/LAPI : Add healthcheck endpoint 

### ISSUE THREAD

**Issue by he2ss** [crowdsecurity/crowdsec#869]
Add healthcheck endpoint `/health` to the LAPI that return 200 if the service is ok. 
It's standardized way to validate the status of a service.

**Comment by buixor** [comment]
https://github.com/alexliesenfeld/health

**Comment by nanikjava** [comment]
@buixor Interested to work on this. 

So pretty much what we need is `lapiserver/health` endpoint right ?

**Comment by borisjacquot** [comment]
@nanikjava  Yes that's the idea. It has to return `200` only if the LAPI is alive. A use case could be with HAProxy, with something lilke that :
```
   option httpchk GET /health
   http-check expect status 200
```
(https://www.haproxy.com/blog/using-haproxy-as-an-api-gateway-part-3-health-checks/)

That's better than a TCP check ^^

**Comment by nanikjava** [comment]
@borisjacquot thanks

@buixor will take a look https://github.com/alexliesenfeld/health and get WIP PR up.
