### ISSUE TITLE
Bug/cscli: cscli backup save add useless parameter in configuration

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#87]
**Describe the bug**
When i ran `cscli backup save` , some weird parameters appeared in the configuration file.

**To Reproduce**
1. `sudo cscli backup save my_dir`
2. Here is the content of the api.yaml file
```
version: v1
pull_path: pull
push_path: signals
signin_path: signin
register_path: register
reset_pwd_path: resetpassword
enroll_path: enroll
url: https://tmsov6x2n9.execute-api.eu-west-1.amazonaws.com
machine_id: ""
password: ""
muted: false
debug_dump: false
pushertomb: {}

```

**Expected behavior**
I think the last 3 parameters shouldn't be writed in the configuration file.

**Technical Information (please complete the following information):**
-   Linux Mint
 -  v0.2.0

**Comment by buixor** [comment]
fixed in https://github.com/crowdsecurity/crowdsec/pull/103
