### ISSUE TITLE
Bug/Remote clients need crowdsec service restart

### ISSUE THREAD

**Issue by erdoukki** [crowdsecurity/crowdsec#883]
cscli machines list shows "old" dates of communication !

**Describe the bug**
Looks like that my debian servers need crowdsec service restart...

**To Reproduce**
I do not yet know why, if it is in case of main API lost, or network problems, or any other reasons...

**Expected behavior**
The remote Crowdsec clients might reconnect to the API/main Crowdsec server after a timeout or lost of connection ?

**Technical Information (please complete the following information):**
My main CrowdSec is an OpenWrt with firewall-bouncer (still in development phase)
My remotes CrowdSec are LXC Debian on OpenWrt host... (an NGINX and an APACHE/NextCloud)

**Additional context**
Add any other context about the problem here, for example `/var/log/crowdsec.log` or error messages.

**Comment by erdoukki** [comment]
I am testing this on V1.1.1 on OpenWrt 20.02-RC4 (MVEBU:ESPRESSOBIN-ULTRA)

**Comment by erdoukki** [comment]
If the "main" server (hosting local_api) is offline, the service crash and never start up again ;
```
time="13-08-2021 18:42:31" level=fatal msg="starting outputs error : authenticate watcher (5244e15d7908402192135ac72b4acb10yqGbFd9bcN233Mpf): Post \"http://10.4.2.1:8080/v1/watchers/login\": could not get jwt token: Post \"http://10.4.2.1:8080/v1/watchers/login\": dial tcp 10.4.2.1:8080: connect: no route to host"
```
I will prefer to have the service timeout and restart in endless loop, trying to connect again...

**Comment by erdoukki** [comment]
my error; not the problem, the service is keeping to trying to connect to the main server...
And when the server is back again, the connection is made !
So I still try to see what is the problem (may be it is a misconfiguration on my side)

**Comment by erdoukki** [comment]
May be it is fault of : https://github.com/crowdsecurity/crowdsec/issues/887

**Comment by buixor** [comment]
@erdoukki can we close this one ?

**Comment by erdoukki** [comment]
@buixor, sure, yes, I do not get the problem back...
