### ISSUE TITLE
Bug/OpenWrt ARM packaging and uneeded plugin need binutils-gold

### ISSUE THREAD

**Issue by erdoukki** [crowdsecurity/crowdsec#885]
binutils-gold may not be needed with the tweak of disabling the plugin from https://github.com/openwrt/packages/issues/16193#issuecomment-897126602

https://github.com/openwrt/packages/pull/16244/files#diff-07d2f406c61e442f2748604cbba900d14403f28e6ff83ef8ee9fb71e7a23254d

May be it can be fixed upstream (here) ?

Thanks...

**Comment by erdoukki** [comment]
@jefferyto said:

> I found [one case](https://github.com/golang/go/blob/go1.16.7/src/cmd/link/internal/ld/lib.go#L1401) where the Go compiler will switch to the gold linker for arm, when it is building code for dynamic linking. The Go compiler will do dynamic linking if `-buildmode=shared` or `-buildmode=plugin` (or `-linkshared`) is specified on the command line, or if it thinks the program it is compiling will (dynamically) load plugins. And I believe it figures out if the program will load plugins by looking to see if the `plugin` package is used.
> 
> In crowdsec I found [one place](https://github.com/crowdsecurity/crowdsec/blob/v1.1.1/pkg/parser/enrich.go#L4) where the `plugin` package is used, but from the code (and code comments) it appears that it is not doing real plugin loading. I believe if you patch that code to remove references to the `plugin` package, then the Go compiler will not switch to the gold linker for arm.

And I confirm that this works on OpenWrt 21.02-RC4 with a MVEBU EspressoBinBoard-ULTRA...
I have tested the v1.1.1, cross compiled, installed and tested with success !

Réf : https://github.com/openwrt/packages/issues/16193#issuecomment-897390376

**Comment by buixor** [comment]
Hello @erdoukki !

should be fixed upstream now, please let us know :smile:
