### ISSUE TITLE
Request/Debian package source (information request)

### ISSUE THREAD

**Issue by erdoukki** [crowdsecurity/crowdsec#886]
I do not find the Debian packages source (rules, control, ...) for Crowdsec.
Is it available, please ?
I need it to check and optimize the OpenWrt Packages.
I am sure to find in it some useful tweaks. ;-)

**Comment by erdoukki** [comment]
Found it : https://packagecloud.io/crowdsec/crowdsec/packages/debian/stretch/crowdsec_1.1.1.dsc
Thanks... (closing this issue)

**Comment by erdoukki** [comment]
Is there a Git for the Debian packages sources ?

**Comment by blotus** [comment]
Hello @erdoukki,

We've just merged the source for the debian and RPM packages here: https://github.com/crowdsecurity/crowdsec/pull/898.

There are a few caveats, as the sources are designed to be used in our internal CI, so while building with them will work, the resulting package will not probably be what you expect.
If you want to build a package yourself, you will need to set the following env vars:
 - VERSION: the crowdsec version
 - PACKAGE_NUMBER: for RPM build, the release of the package
 - RELEASEVER: for RPM build, the shortname of the OS you are targeting (el7, el8, fc34, ....)
 - If you are building for older debian based OS, you will need to downgrade the dh_compat value
