### ISSUE TITLE
Bug/Error logged : Failed to notify(sent: false): <nil>

### ISSUE THREAD

**Issue by erdoukki** [crowdsecurity/crowdsec#887]
```
# tail /var/log/crowdsec.log
```
```
level=error msg="Failed to notify(sent: false): <nil>"
```

**Comment by blotus** [comment]
This is an error message related to `sd_notify`, which allows to notify the init process that we are up.
The error can be safely ignored (it might happen if your init system does not support notifications, or if you are starting crowdsec directly).
