### ISSUE TITLE
Bug/wizard fails with ./wizard.sh: line 378: cd: config: No such file or directory - Centos and RHEL7

### ISSUE THREAD

**Issue by dldewey** [crowdsecurity/crowdsec#899]
installed from the repo using 'yum install crowdsec' on 2 machines, centos and RHEL.

then 'cd /usr/share/crowdsec'
./wizard.sh -i
INFO[08/19/2021:10:25:40 AM] crowdsec_wizard: checking if crowdsec is installed
INFO[08/19/2021:10:25:40 AM] crowdsec_wizard: installing crowdsec
./wizard.sh: line 378: cd: config: No such file or directory

Reproducible on both machines.
Line in question (378) causing the failure is:
(cd config && find patterns -type f -exec install -Dm 644 "{}" "${CROWDSEC_CONFIG_PATH}/{}" \; && cd ../) || exit

Fails on both centos 7.9.2009 and RHEL 7.9.

**Comment by blotus** [comment]
Hello,

If you have installed crowdsec from our repository, you don't need to run `wizard.sh -i`, this flag is intended for manual installation (from the github repo or from a release tarball).

Everything should be autoconfigured after installing the package, do you have any missing configuration ?

**Comment by dldewey** [comment]
ah, ok, then maybe it's the documentation that's unclear, at least to me... I was using the install guide at https://doc.crowdsec.net/Crowdsec/v1/getting_started/installation/#install-on-redhatcentos-using-crowdsec-repository 

and following down from the top, it appears to have package installation instructions, then leads into a large block about using the wizard. I see how a different reading is possible, where the wizard instructions follow along with the tarball install. thanks for the prompt response!
