### ISSUE TITLE
Bug/Failed to start the firewall bouncer for CrowdSec (Fatal error due to deny_log: true)

### ISSUE THREAD

**Issue by lol-deb** [crowdsecurity/crowdsec#906]
**Describe the bug**
On Debian 10, after installing crowdsec-firewall-bouncer-iptables, and enabling deny_log: true in /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml unable to restart service due to option problem in the iptables command: 

**To Reproduce**
1. install crowdsec crowdsec-firewall-bouncer and crowdsec-firewall-bouncer-iptables
2. Activate deny_log: true in crowdsec-firewall-bouncer.yaml
3. restart crowdsec-firewall-bouncer
4. crowdsec-firewall-bouncer failed on restart

**Expected behavior**
crowdsec-firewall-bouncer-iptables should restart without issue...

**Technical Information (please complete the following information):**
 - OS: Debian 10 - 4.19.0-17-amd64
 - Version crowdsec: *** 1.1.1 (https://packagecloud.io/crowdsec/crowdsec/debian buster/main amd64 Packages)
 - Version crowdsec-firewall-bouncer-iptables: *** 0.0.13 (https://packagecloud.io/crowdsec/crowdsec/debian buster/main amd64 Packages)

**Additional context**
Logs when it failed to restart
/var/log/crowdsec-firewall-bouncer.log
```
time="24-08-2021 07:25:25" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="24-08-2021 07:25:25" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec6-blacklists"
time="24-08-2021 07:25:25" level=info msg="Shutting down firewall-bouncer service"
time="24-08-2021 07:25:25" level=info msg="backend type : iptables"
time="24-08-2021 07:25:25" level=info msg="iptables for ipv4 initiated"
time="24-08-2021 07:25:25" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src --log-prefix CrowdSec DROP:  -j LOG"
time="24-08-2021 07:25:25" level=info msg="ipset 'crowdsec-blacklists' doesn't exist, skip"
time="24-08-2021 07:25:25" level=info msg="iptables clean-up : /usr/sbin/iptables -D INPUT -m set --match-set crowdsec-blacklists src -j DROP"
time="24-08-2021 07:25:25" level=info msg="ipset 'crowdsec-blacklists' doesn't exist, skip"
time="24-08-2021 07:25:25" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="24-08-2021 07:25:26" level=info msg="ipset 'crowdsec-blacklists' doesn't exist, skip"
time="24-08-2021 07:25:26" level=info msg="Checking existing set"
time="24-08-2021 07:25:26" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec-blacklists nethash timeout 300"
time="24-08-2021 07:25:27" level=warning msg="iptables check command (/usr/sbin/iptables -C INPUT -m set --match-set crowdsec-blacklists src --log-prefix CrowdSec DROP:  -j LOG) failed : exit status 2"
time="24-08-2021 07:25:27" level=info msg="Rule doesn't exist (/usr/sbin/iptables -C INPUT -m set --match-set crowdsec-blacklists src -j DROP)"
time="24-08-2021 07:25:27" level=info msg="iptables set-up : /usr/sbin/iptables -I INPUT -m set --match-set crowdsec-blacklists src --log-prefix CrowdSec DROP:  -j LOG"
time="24-08-2021 07:25:27" level=warning msg="Error inserting set in iptables (/usr/sbin/iptables -I INPUT -m set --match-set crowdsec-blacklists src --log-prefix CrowdSec DROP:  -j LOG): exit status 2 : iptables v1.8.2 (nf_tables): unknown option \"--log-prefix\"\nTry `iptables -h' or 'iptables --help' for more information.\n"
time="24-08-2021 07:25:27" level=fatal msg="iptables init failed: while inserting set in iptables: exit status 2"
```

Content of  /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml making restart failed:
```
mode: iptables
pid_dir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
api_url: http://localhost:8080/
api_key: 7c862f327f0205c2382e872dba60cfd4
disable_ipv6: false
deny_action: DROP
deny_log: true
#to change log prefix
deny_log_prefix: "CrowdSec DROP: "
#if present, insert rule in those chains
iptables_chains:
  - INPUT
#  - FORWARD
#  - DOCKER-USER
```

Of course if I don't activate the "deny_log_prefix, all is working as expected:

```
~ # iptables -S | grep crowdsec
-A INPUT -m set --match-set crowdsec-blacklists src -j DROP
~ # ip6tables -S | grep crowdsec
-A INPUT -m set --match-set crowdsec6-blacklists src -j DROP
```

Thank you for this nice software, for all the work, and for your help on this issue.
Regards,

**Comment by buixor** [comment]
Hello,

It seems that in debian 10, iptables is a wrapper to nftables (cf. `iptables v1.8.2 (nf_tables): unknown option \"--log-prefix\"`) and doesn't support `--log-prefix` :disappointed:

**Comment by lol-deb** [comment]
Hello,
Thank you for your answer.
I don't think iptables is a wrapper to nftables in Debian 10 (since Debian 9 nftables is a full-fledged package)

nftable exist as a packet in Debian 10:
```
 # apt-cache policy nftables
nftables:
  Installé : (aucun)
  Candidat : 0.9.0-2
 Table de version :
     0.9.0-2 900
        900 http://mirror.hetzner.de/debian/packages buster/main amd64 Packages
        900 http://deb.debian.org/debian buster/main amd64 Packages
```

And above all I already use the --log-prefix option in my iptables instructions: 

```
# iptables -S | grep "\-\-log\-prefix"
-A LOGGING -m limit --limit 2/min -j LOG --log-prefix "IPTables-Dropped: "
```

**Comment by blotus** [comment]
Hello @lol-deb ,

This is indeed a bug :) 
I've opened an issue in the correct repository: https://github.com/crowdsecurity/cs-firewall-bouncer/issues/69

On a side-note, I'd recommend you to switch the bouncer to the nftables mode:
 - By default, iptables on buster is just a wrapper on nftables (see https://wiki.debian.org/iptables)
 - The iptables mode makes use of ipset, and I don't think it will play nicely with nftables
 - This would also fix your issue, as we are using a pure Go package to interact with nftables which should not be subject to the same issue.

(i'm closing this issue, but feel free to add more information if you want in the issue I linked above).

**Comment by lol-deb** [comment]
Hello and thank you for you answer and time.

Sorry for the misplaced ticket. I saw the new one, good job! :-)

You are right, it was buried far in my memory, iptables-nft is the default framework since Buster. My bad
I'll think about switching, as soon as I'll move to bulleseye.

But that has nothing to do with the bug I reported! :-) 

Thanks.
