### ISSUE TITLE
Bug/Parse error extracting sshd_client_ip

### ISSUE THREAD

**Issue by lleddewk** [crowdsecurity/crowdsec#936]
**Describe the bug**
The ip address extracted by child-crowdsecurity/sshd-logs is one digit shorter than the address shown in /var/log/auth.log entries. As a result, the wrong ip address is banned leaving the attacher to continue brute force attempts.

**To Reproduce**
1. Enable ssh-bf scenario.
2. Get attacked by brute force attempts
3. View resulting alerts and decisions with cscli. 

**Expected behavior**
The parsed ip address should match that captured in logs.

**Screenshots**

**Technical Information (please complete the following information):**
 - OS: Debian
 - Version: Bullseye

**Additional context**
Debug log extract attached.
[auth.log](https://github.com/crowdsecurity/crowdsec/files/7110108/auth.log)
[crowdsec.log](https://github.com/crowdsecurity/crowdsec/files/7110109/crowdsec.log)

**Comment by blotus** [comment]
Hello,

This looks like the same issue as https://github.com/crowdsecurity/hub/issues/195.

Can you try to update your SSH parser ( `cscli hub update && cscli parsers upgrade crowdsecurity/sshd-logs && systemctl reload crowdsec.service`) and confirm this fixes it for you ?

**Comment by lleddewk** [comment]
Aah sorry I don't  know how I missed that issue.  I've updated and will report back when I get attacked again.  Thanks for the swift advice.

Keith

**Comment by lleddewk** [comment]
Unfortunately this has not fixed it, although it does seem to be exactly the same issue as #195.

Keith

**Comment by buixor** [comment]
Hello,

Can you please share the version of the parser (ie `cscli parsers  inspect crowdsecurity/sshd-logs`) and the version of crowdsec you are running ?

Thanks,

**Comment by lleddewk** [comment]
Hi,

The outputs are:

cscli version:
2021/09/05 09:18:19 version: v1.1.1-debian-pragmatic-73e0bbaf93070f4a640eb5a22212b5dcf26699de

cscli parsers inspect crowdsecurity/sshd-logs:
type: parsers
stage: s01-parse
name: crowdsecurity/sshd-logs
filename: sshd-logs.yaml
description: Parse openSSH logs
author: crowdsecurity
belongs_to_collections:
- crowdsecurity/sshd
remote_path: parsers/s01-parse/crowdsecurity/sshd-logs.yaml
version: "0.7"
local_path: /etc/crowdsec/parsers/s01-parse/sshd-logs.yaml
localversion: "0.7"
localhash: ad96d89f89e69fe3b9a0c70b7d643d4965cb893f719722d09957c38e89c31a8d
installed: true
downloaded: true
uptodate: true
tainted: false
local: false

Current metrics :

 - (Parser) crowdsecurity/sshd-logs:
+------------------------+------+--------+----------+
|        PARSERS         | HITS | PARSED | UNPARSED |
+------------------------+------+--------+----------+
| file:/var/log/auth.log | 6212 |   1384 |     4828 |
+------------------------+------+--------+----------+

Keith

**Comment by buixor** [comment]
@lleddewk : we have now forked [grokky](https://github.com/logrusorgru/grokky) to fix [the faulty pattern](https://github.com/crowdsecurity/grokky/pull/1/files).

New release is on its way (hopefully monday) and will fix this for future versions.
In the meanwhile, [it's being fixed in the hub for older versions](https://github.com/crowdsecurity/hub/pull/238)

Please let us know if you face any more issues :+1:
