### ISSUE TITLE
Bug/cwapi: machine_id is sometime empty when registering in a docker

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/crowdsec#94]
**Describe the bug**
When trying to register to crowdsec API in a docker, it returns the following error:

```
FATA[0000] api register machine: return bad HTTP code (400): {"message": "Invalid request body"}
```

**To Reproduce**
1. Run a docker 
2. Install crowdsec and try to register to the API

**Expected behavior**
Being able to register to crowdsec API

**Comment by AlteredCoder** [comment]
In docker files `/etc/machine-id` and `/var/lib/dbus/machine-id` are not present. So the library we use can't get the machine_id, return an empty string for the `machine_id` to send to crowdsec API

**Comment by ThomasLohner** [comment]
For future reference: You can get the docker container id from `/proc/self/cgroup` within the container. Maybe this is more reliable than a random id.
