### ISSUE TITLE
Bug/non-libc issue

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#97]
**Describe the bug**

When installing on alpine, several issues were faced :
 1. Alpine doesn't use libc but musl libc, thus :

```bash
bash-4.4# cscli 
bash: /usr/local/bin/cscli: No such file or directory
...
FATA[0000] While executing root command : plugin.Open("/usr/local/lib/crowdsec/plugins/backend/sqlite.so"): Error relocating /usr/local/lib/crowdsec/plugins/backend/sqlite.so: __vfprintf_chk: symbol not found
```

**possible solution** : build in static (`CGO_ENABLED=0`)

 2. wizard.sh requires `envsubst` which might be missing (package gettext)

**possible solution** : migrate the wizard to native golang as planed :)

**To Reproduce**

Run crowdsec's `wizard --bininstall` in a alpine Linux docker image :

```bash
docker run --name alpine-test -v /tmp/crowdsec/crowdsec-v0.2.1/:/home/ -it alpine:3.7
apk add bash libc6-compat gettext
/bin/bash
cd /home/
./wizard.sh --bininstall
```

**Technical Information (please complete the following information):**
 - OS: alpine Linux docker image
 - Version: v0.2.1

**Additional context**
The main question is : should we provide statically builder binaries to avoid this ?

**Comment by FaricaUnknown** [comment]
IMHO We want a specific build for alpine and not a static binary. Thus this is more a feature request than a bug.
