### ISSUE TITLE
Bug/crowdsec - goroutine crowdsec/runOutput crashed : runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thrynir** [crowdsecurity/crowdsec#992]
**Describe the bug**
I try to add to whitelist an url. But each time it should be trigger, crowdsec crash

**To Reproduce**
I had this to /etc/crowdsec/postoverflows/s01-whitelists/nextcloud.yaml
name: whitelist_nextcloud
description: whitelist nextcloud
filter: "evt.Parsed.request contains 'preview'"
whitelist:
  reason: "do not ban nextcloud users"
  expression:
    - "evt.Parsed.request contains '/preview?'"

Then, I provoke multiple 404 error on nextcloud (Probably an issue with it, I also open an issue at nextcloud for it)

note : I try to change the string check for evt.Parsed.request without success

**Expected behavior**
Should ignore this url.

**Technical Information (please complete the following information):**
 - OS: Debian 11
 - Version v1.2.0-debian-pragmatic-linux-0ecfe7568790a15791011da27eb24e96e7d4a39f

**Additional context**
time="28-09-2021 12:15:16" level=warning msg="Starting processing data"
time="28-09-2021 12:15:48" level=error msg="crowdsec - goroutine crowdsec/runOutput crashed : runtime error: invalid memory address or nil pointer dereference"
time="28-09-2021 12:15:48" level=error msg="please report this error to https://github.com/crowdsecurity/crowdsec/"
time="28-09-2021 12:15:48" level=error msg="stacktrace/report is written to /tmp/crowdsec-crash.067816395.txt : please join it to your issue"
time="28-09-2021 12:15:48" level=fatal msg="crowdsec stopped"

crowdsec-crash.669163194.txt
error : runtime error: invalid memory address or nil pointer dereference
version: v1.2.0-debian-pragmatic-0ecfe7568790a15791011da27eb24e96e7d4a39f
Codename: alphaga
BuildDate: 2021-09-14_15:16:59
GoVersion: 1.16.7
Platform: linux
goroutine 116 [running]:
runtime/debug.Stack(0x40001400d0, 0x400076b5e0, 0x9d)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/crowdsecurity/crowdsec/pkg/types.WriteStackTrace(0x10f9f40, 0x1bfba00, 0x12c3783, 0x46)
        /codebuild/output/src791/src/s3/01/pkg/types/utils.go:87 +0x214
github.com/crowdsecurity/crowdsec/pkg/types.CatchPanic(0x1282047, 0x12)
        /codebuild/output/src791/src/s3/01/pkg/types/utils.go:102 +0x120
panic(0x10f9f40, 0x1bfba00)
        /usr/local/go/src/runtime/panic.go:965 +0x154
main.runOutput(0x40004cb500, 0x4000096d80, 0x400000f5f0, 0x4000592ba0, 0x400015cd80, 0x3, 0x4, 0x1, 0x4000417ba8, 0x16, ...)
        /codebuild/output/src791/src/s3/01/cmd/crowdsec/output.go:147 +0xc48
main.runCrowdsec.func3.1(0x0, 0x0)
        /codebuild/output/src791/src/s3/01/cmd/crowdsec/crowdsec.go:100 +0x14c
gopkg.in/tomb%2ev2.(*Tomb).run(0x1c7e0e0, 0x4000040aa0)
        /codebuild/output/src791/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x34
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /codebuild/output/src791/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xcc

**Comment by AlteredCoder** [comment]
Hello @thrynir ,

I'm going to investigate this and i will come back to you when i have fix or found a solution for the bug.

**Comment by AlteredCoder** [comment]
Hello @thrynir , 

I don't manage to reproduce this bug.

Furthermore, i would suggest to add this whitelist in `/etc/crowdsec/parsers/s02-whitelist/` instead of putting it in postoverflows. Postoverflows mainly works with the `Overflow` object which contains all the logs that lead to this overflow. That's why `evt.Parsed` is empty for an overflow.

**Comment by thrynir** [comment]
Hi,

I read again the online documentation, and you are right, I need to put this in /etc/crowdsec/parsers/s02-whitelist/. Then it works fine.

Sorry for the inconvenience and many thanks,
